Repository owncloud/docs, pull requests merged in 2018-10, with the labels that each got.

#110 Updated the installation and build documentation
  docs/build-the-docs.md
  docs/install-antora.md
Labels: enhancement, help wanted, technical review

#131 Update the GitHub New Issue Template
  .github/issue_template.md
Labels: enhancement, review required

#117 Add PDF Theme Support
  README.md
  resources/themes/custom-theme.yml
  resources/themes/owncloud-theme.yml
Labels: enhancement, p2-high, review required

#138 Minor changes to the developer manual to help with PDF generation
  modules/developer_manual/pages/commun/help_and_communication.adoc
  modules/developer_manual/pages/core/introduction.adoc
Labels: bug

#139 Do not track PDF and TTF files
  .gitignore
Labels: enhancement

#136 Use Custom Font in the Custom ownCloud PDF Theme
  README.md
  fonts/.gitkeep
  resources/themes/owncloud-theme.yml
Labels: enhancement, p2-high

#142 Fix build issues
  modules/ROOT/pages/configuration/user/user_provisioning_api.adoc
  modules/developer_manual/pages/app/fundamentals/controllers.adoc
  modules/developer_manual/pages/app/fundamentals/info.adoc
  modules/developer_manual/pages/app/fundamentals/routes.adoc
Labels: bug, review required

#143 Fix up table styling to match the documentation style guide
  antora-ui-default/docs/modules/ROOT/pages/list-styles.adoc
  modules/ROOT/pages/configuration/files/encryption_configuration.adoc
  modules/ROOT/pages/configuration/mimetypes/index.adoc
  modules/ROOT/pages/configuration/server/antivirus_configuration.adoc
  modules/ROOT/pages/configuration/server/automatic_configuration.adoc
  modules/ROOT/pages/configuration/server/caching_configuration.adoc
  modules/ROOT/pages/configuration/server/email_configuration.adoc
  modules/ROOT/pages/configuration/server/occ_app_command.adoc
  modules/ROOT/pages/configuration/server/occ_command.adoc
  modules/ROOT/pages/configuration/server/security/oauth2.adoc
  modules/ROOT/pages/configuration/user/encryption_configuration_quick_guide.adoc
  modules/ROOT/pages/configuration/user/user_auth_ftp_smb_imap.adoc
  modules/ROOT/pages/configuration/user/user_provisioning_api.adoc
  modules/ROOT/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
  modules/ROOT/pages/enterprise/installation/oracle_db_configuration.adoc
  modules/ROOT/pages/enterprise/ransomware-protection/index.adoc
  modules/ROOT/pages/installation/configuration_notes_and_tips.adoc
  modules/ROOT/pages/installation/deployment_recommendations.adoc
  modules/ROOT/pages/installation/docker/index.adoc
  modules/ROOT/pages/installation/manual_installation.adoc
  modules/ROOT/pages/installation/system_requirements.adoc
  modules/developer_manual/pages/app/advanced/custom-cache-backend.adoc
  modules/developer_manual/pages/app/advanced/custom-storage-backend.adoc
  modules/developer_manual/pages/app/advanced/extstorage.adoc
  modules/developer_manual/pages/app/advanced/storage-backend.adoc
  modules/developer_manual/pages/app/fundamentals/css.adoc
  modules/developer_manual/pages/app/fundamentals/info.adoc
  modules/developer_manual/pages/app/fundamentals/publishing.adoc
  modules/developer_manual/pages/core/ocs-capabilities.adoc
  modules/developer_manual/pages/core/ocs-recipient-api.adoc
  modules/developer_manual/pages/core/ocs-share-api.adoc
  modules/developer_manual/pages/core/theming.adoc
  modules/developer_manual/pages/general/codingguidelines.adoc
  modules/developer_manual/pages/general/devenv.adoc
  modules/developer_manual/pages/index.adoc
  modules/developer_manual/pages/webdav_api/comments.adoc
  modules/developer_manual/pages/webdav_api/files_versions.adoc
  modules/developer_manual/pages/webdav_api/tags.adoc
  modules/user_manual/pages/files/public_link_shares.adoc
  modules/user_manual/pages/files/webgui/navigating.adoc
  modules/user_manual/pages/files/webgui/overview.adoc
  modules/user_manual/pages/files/webgui/sharing.adoc
  modules/user_manual/pages/files/webgui/tagging.adoc
  modules/user_manual/pages/troubleshooting.adoc
Labels: bug, review required

#137 Finish implementing pdf manual generation
  Makefile
  README.md
  book.adoc
  book.dev.adoc
  book.user.adoc
Labels: command-line, deployment, enhancement, p2-high, technical review, waiting on PR merge, work in progress

#150 Update makefile to build all manuals and be less verbose
  Makefile
  book.admin.adoc
  book.adoc
  build/.gitkeep
Labels: command-line, deployment, review required, technical review

#154 Update PDF Configuration File
  .gitignore
  docs/build-the-docs.md
  fonts/dejavu-sans-bold.ttf
  fonts/dejavu-sans-boldoblique.ttf
  fonts/dejavu-sans-condensed.ttf
  fonts/dejavu-sans-condensedbold.ttf
  fonts/dejavu-sans-condensedboldoblique.ttf
  fonts/dejavu-sans-condensedoblique.ttf
  fonts/dejavu-sans-extralight.ttf
  fonts/dejavu-sans-mono-bold.ttf
  fonts/dejavu-sans-mono.ttf
  fonts/dejavu-sans-monoboldoblique.ttf
  fonts/dejavu-sans-monooblique.ttf
  fonts/dejavu-sans-oblique.ttf
  fonts/dejavu-sans.ttf
  fonts/dejavuserif-bold.ttf
  fonts/dejavuserif-bolditalic.ttf
  fonts/dejavuserif-italic.ttf
  fonts/dejavuserif.ttf
  fonts/dejavuserifcondensed-bold.ttf
  fonts/dejavuserifcondensed-bolditalic.ttf
  fonts/dejavuserifcondensed-italic.ttf
  fonts/dejavuserifcondensed.ttf
  fonts/notoserif-bold.ttf
  fonts/notoserif-bolditalic.ttf
  fonts/notoserif-italic.ttf
  fonts/notoserif-regular.ttf
  fonts/opensans-bold.ttf
  fonts/opensans-bolditalic.ttf
  fonts/opensans-extrabold.ttf
  fonts/opensans-extrabolditalic.ttf
  fonts/opensans-italic.ttf
  fonts/opensans-light.ttf
  fonts/opensans-lightitalic.ttf
  fonts/opensans-regular.ttf
  fonts/opensans-semibold.ttf
  fonts/opensans-semibolditalic.ttf
  resources/themes/owncloud-theme.yml
Labels: enhancement, review required

#73 Minimum client versions
  modules/administration_manual/pages/installation/system_requirements.adoc
Labels: enhancement, help wanted, work in progress

#144 Backport owncloud/documentation#4405 to the new docs
  modules/administration_manual/pages/configuration/server/occ_command.adoc
Labels: enhancement, review required

#158 Add prose linting support
  Makefile
Labels: command-line, enhancement, review required

#161 minor occ system command update
  modules/administration_manual/pages/configuration/server/occ_command.adoc
Labels: command-line

#160 Add Document Classification and Policy Enforcement section
  modules/administration_manual/nav.adoc
  modules/administration_manual/pages/enterprise/classification_and_policy_enforcement.adoc
Labels: enhancement, review required, work in progress

#164 Document the send-email and output-link options to user:resetpassword
  modules/administration_manual/pages/configuration/server/occ_command.adoc
Labels: command-line, enhancement

#165 fix unterminated listing block
  modules/administration_manual/pages/configuration/files/external_storage/dropbox.adoc
Labels: bug

#166 Minor corrections to acceptance tests documentation
  modules/developer_manual/pages/core/acceptance-tests.adoc
Labels: bug, enhancement, review required

#177 Typo test-acceptance-cli
  modules/developer_manual/pages/core/acceptance-tests.adoc
Labels: review required

#135 post installation script update
  modules/administration_manual/examples/installation/post-installation-steps.sh
Labels: command-line, enhancement

#184 Fixing the image names from Office.adoc
  modules/administration_manual/pages/appliance/Office.adoc
Labels: bug, enhancement

#181 Fixes encryption_configuration.adoc: occ commands and other stuff
  modules/administration_manual/pages/configuration/files/encryption_configuration.adoc
Labels: bug, command-line, enhancement

#186 Update documented ports in the docker documentation
  modules/administration_manual/pages/installation/docker/index.adoc
Labels: enhancement, review required, technical review

#187 Fix broken link labels in classification and enforcement policy docs
  modules/administration_manual/pages/enterprise/classification_and_policy_enforcement.adoc
Labels: bug, enhancement
