Repository owncloud/docs, pull requests merged in 2018-11, with the labels that each got.

#192 fix link to install antora
  docs/getting-started.md
  docs/install-antora.md
Labels: bug

#198 Correct header level for argument and options in occ (apps) command reference
  modules/administration_manual/pages/configuration/server/occ_app_command.adoc
  modules/administration_manual/pages/configuration/server/occ_command.adoc
Labels: bug, enhancement

#197 Improve getting-started.md
  docs/getting-started.md
Labels: enhancement

#202 Fix owncloud.org history and created a missing file
  antora-ui-default/src/partials/footer-content.hbs
  modules/ROOT/nav.adoc
  modules/ROOT/pages/release_notes.adoc
  ui-bundle.zip
Labels: bug

#201 Section Title out of Sequence
  modules/administration_manual/pages/configuration/server/occ_app_command.adoc
  modules/administration_manual/pages/configuration/server/occ_command.adoc
Labels: bug, enhancement

#194 Fix available image :alt: (alternative) text
  modules/administration_manual/pages/appliance/Clamav.adoc
  modules/administration_manual/pages/appliance/ucs/add-groups-and-users.adoc
  modules/administration_manual/pages/configuration/files/external_storage/auth_mechanisms.adoc
  modules/administration_manual/pages/configuration/files/external_storage/ftp.adoc
  modules/administration_manual/pages/configuration/files/external_storage/google.adoc
  modules/administration_manual/pages/configuration/files/external_storage/openstack.adoc
  modules/administration_manual/pages/configuration/files/external_storage/sftp.adoc
  modules/administration_manual/pages/configuration/files/external_storage/smb.adoc
  modules/administration_manual/pages/configuration/files/external_storage/webdav.adoc
  modules/administration_manual/pages/configuration/files/external_storage_configuration_gui.adoc
  modules/administration_manual/pages/configuration/files/previews_configuration.adoc
  modules/administration_manual/pages/configuration/mimetypes/index.adoc
  modules/administration_manual/pages/configuration/server/antivirus_configuration.adoc
  modules/administration_manual/pages/configuration/server/security/password_policy.adoc
  modules/administration_manual/pages/configuration/user/user_auth_ldap.adoc
  modules/administration_manual/pages/enterprise/clients/creating_branded_apps.adoc
  modules/administration_manual/pages/enterprise/external_storage/enterprise_only_auth.adoc
  modules/administration_manual/pages/enterprise/external_storage/onedrive.adoc
  modules/administration_manual/pages/enterprise/external_storage/sharepoint-integration_configuration.adoc
  modules/administration_manual/pages/enterprise/file_management/files_tagging.adoc
  modules/administration_manual/pages/enterprise/firewall/file_firewall.adoc
  modules/administration_manual/pages/enterprise/logging/enterprise_logging_apps.adoc
  modules/administration_manual/pages/enterprise/server_branding/enterprise_server_branding.adoc
  modules/administration_manual/pages/installation/apps_management_installation.adoc
  modules/administration_manual/pages/installation/deployment_recommendations.adoc
  modules/user_manual/pages/files/gallery_app.adoc
  modules/user_manual/pages/files/webgui/comments.adoc
  modules/user_manual/pages/files/webgui/navigating.adoc
  modules/user_manual/pages/files/webgui/overview.adoc
  modules/user_manual/pages/files/webgui/sharing.adoc
  modules/user_manual/pages/files/webgui/tagging.adoc
  modules/user_manual/pages/session_management.adoc
  modules/user_manual/pages/userpreferences.adoc
  modules/user_manual/pages/webinterface.adoc
Labels: bug, enhancement

#199 Ignore the cache directory
  .gitignore
Labels: deployment, enhancement

#175 Description for data_exporter app
  modules/administration_manual/nav.adoc
  modules/administration_manual/pages/configuration/server/occ_app_command.adoc
  modules/administration_manual/pages/maintenance/export_import_instance_data.adoc
Labels: command-line, enhancement, native language review, technical review

#206 update readme.md
  README.md
Labels: enhancement, question

#207 Document how to migrate from User Key Encryption to Master Key Encryption
  modules/administration_manual/nav.adoc
  modules/administration_manual/pages/_partials/configuration/server/disable-single-user-mode.adoc
  modules/administration_manual/pages/_partials/configuration/server/enable-single-user-mode.adoc
  modules/administration_manual/pages/maintenance/encryption/migrating-from-user-key-to-master-key.adoc
Labels: command-line, deployment, enhancement, technical review

#208 Add a sample playbook file
  site.sample.yml
Labels: enhancement, review required

#213 [Docker] Adapt missleading 'Logging In' Section
  modules/administration_manual/pages/installation/docker/index.adoc
Labels: bug, enhancement

#216 Add package.json and package-lock.json
  package-lock.json
  package.json
Labels: command-line, enhancement, review required, technical review, work in progress

#212 Add broken Xref checker
  docs/build-the-docs.md
  generator/xref-validator.js
Labels: command-line, deployment, enhancement, review required

#218 Update .gitignore
  .gitignore
  package.json
Labels: bug

#217 adding example outputs to broken link checkers
  docs/build-the-docs.md
  docs/checking-broken-links.md
  docs/getting-started.md
Labels: enhancement

#215 first shot fixing broken links
  modules/administration_manual/pages/appliance/Clamav.adoc
  modules/administration_manual/pages/appliance/howto-update-owncloud.adoc
  modules/administration_manual/pages/configuration/files/encryption_configuration.adoc
  modules/administration_manual/pages/configuration/server/antivirus_configuration.adoc
  modules/administration_manual/pages/configuration/server/background_jobs_configuration.adoc
  modules/administration_manual/pages/configuration/user/encryption_configuration_quick_guide.adoc
  modules/administration_manual/pages/configuration/user/user_auth_ftp_smb_imap.adoc
  modules/administration_manual/pages/enterprise/classification_and_policy_enforcement.adoc
  modules/administration_manual/pages/enterprise/external_storage/onedrive.adoc
  modules/administration_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
  modules/administration_manual/pages/enterprise/ransomware-protection/index.adoc
  modules/administration_manual/pages/enterprise/user_management/saml_2.0_sso.adoc
  modules/administration_manual/pages/installation/command_line_installation.adoc
  modules/administration_manual/pages/installation/letsencrypt/index.adoc
  modules/administration_manual/pages/installation/nginx_configuration.adoc
  modules/administration_manual/pages/issues/general_troubleshooting.adoc
  modules/administration_manual/pages/maintenance/backup.adoc
  modules/administration_manual/pages/maintenance/upgrade.adoc
  modules/administration_manual/pages/release_notes.adoc
  modules/developer_manual/pages/app/advanced/extstorage.adoc
  modules/developer_manual/pages/app/advanced/storage-backend.adoc
  modules/developer_manual/pages/app/tutorial/request.adoc
  modules/developer_manual/pages/core/ocs-share-api.adoc
  modules/developer_manual/pages/general/devenv.adoc
  modules/developer_manual/pages/webdav_api/comments.adoc
  modules/developer_manual/pages/webdav_api/files_versions.adoc
  modules/user_manual/pages/external_storage/external_storage.adoc
  modules/user_manual/pages/files/webgui/overview.adoc
  modules/user_manual/pages/files/webgui/sharing.adoc
  modules/user_manual/pages/pim/calendar.adoc
  modules/user_manual/pages/pim/contacts.adoc
Labels: bug

#221 Backport Updates to Classification and Policy Enforcement (4453)
  modules/administration_manual/pages/enterprise/classification_and_policy_enforcement.adoc
Labels: enhancement

#211 Update production playbook
  docs/build-the-docs.md
  site.prod.yml
Labels: command-line, enhancement, technical review

#225 Update .drone.yml
  .drone.yml
Labels: bug

#226 next step fixing broken links
  modules/administration_manual/pages/configuration/database/linux_database_configuration.adoc
  modules/administration_manual/pages/enterprise/user_management/saml_2.0_sso.adoc
  modules/administration_manual/pages/installation/deployment_recommendations.adoc
  modules/administration_manual/pages/installation/linux_installation.adoc
  modules/developer_manual/pages/app/advanced/extstorage.adoc
  modules/developer_manual/pages/app/fundamentals/css.adoc
  modules/developer_manual/pages/app/fundamentals/database.adoc
  modules/developer_manual/pages/bugtracker/triaging.adoc
  modules/developer_manual/pages/core/translation.adoc
  modules/developer_manual/pages/core/ui-testing.adoc
  modules/developer_manual/pages/core/unit-testing.adoc
  modules/developer_manual/pages/general/security.adoc
  modules/developer_manual/pages/mobile_development/ios_library/library_installation.adoc
Labels: bug, enhancement

#189 Implement site search
  .dockerignore
  Dockerfile
  docs/build-the-docs.md
  generate-site.js
  package-lock.json
  package.json
  site.prod.yml
Labels: command-line, deployment, enhancement, p2-high, technical review

#227 adding a note about false positives
  docs/checking-broken-links.md
Labels: enhancement

#230 Update supported distributions
  modules/administration_manual/pages/installation/system_requirements.adoc
Labels: oudated documentation

#229 Fixing more broken links
  modules/developer_manual/pages/app/advanced/code_signing.adoc
  modules/developer_manual/pages/core/ui-testing.adoc
  modules/developer_manual/pages/core/unit-testing.adoc
  modules/developer_manual/pages/general/devenv.adoc
  modules/developer_manual/pages/general/security.adoc
  modules/developer_manual/pages/testing/index.adoc
  modules/user_manual/pages/files/large_file_upload.adoc
  modules/user_manual/pages/files/webgui/custom_groups.adoc
Labels: bug, enhancement

#228 Remove environment-specific Antora playbook
  .drone.yml
  docs/build-the-docs.md
  site.yml
Labels: command-line, deployment, enhancement, review required

#219 Add a make target to install the Antora command-line tools
  Makefile
Labels: command-line, deployment, enhancement, review required

#220 Add a make target for running an Antora Xref validator
  Makefile
Labels: command-line, deployment, enhancement, review required, technical review

#236 Remove remnants of local ui bundle
  .drone.yml
  docs/build-the-docs.md
  docs/checking-broken-links.md
  site.sample.yml
  ui-bundle.zip
Labels: command-line, enhancement, technical review, waiting on PR merge

#224 Document WebDAV Search API
  modules/developer_manual/examples/core/webdav_api/search/request/filter_files/minimal_filter_files_report_request_body.xml
  modules/developer_manual/examples/core/webdav_api/search/request/filter_files/search_body_filtering_by_system_tag_ids.xml
  modules/developer_manual/examples/core/webdav_api/search/request/filter_files/search_body_requesting_all_properties.xml
  modules/developer_manual/examples/core/webdav_api/search/request/search_files/limit_number_of_results.xml
  modules/developer_manual/examples/core/webdav_api/search/request/search_files/minimal_request_body.xml
  modules/developer_manual/examples/core/webdav_api/search/request/search_files/search_body_with_properties.xml
  modules/developer_manual/examples/core/webdav_api/search/response/common/failure/incorrect_payload_or_parse_failure.xml
  modules/developer_manual/examples/core/webdav_api/search/response/common/failure/request_non_existent_property.xml
  modules/developer_manual/examples/core/webdav_api/search/response/filter_files/success.xml
  modules/developer_manual/examples/core/webdav_api/search/response/search_files/success/search_response.xml
  modules/developer_manual/nav.adoc
  modules/developer_manual/pages/_partials/webdav_api/core_request_details.adoc
  modules/developer_manual/pages/_partials/webdav_api/search/common_error_responses.adoc
  modules/developer_manual/pages/_partials/webdav_api/search/file_properties.adoc
  modules/developer_manual/pages/webdav_api/search.adoc
  modules/developer_manual/pages/webdav_api/search/filter_files.adoc
  modules/developer_manual/pages/webdav_api/search/search_files.adoc
Labels: command-line, enhancement, work in progress

#238 Simplify the XSS link in the developer security documentation
  modules/developer_manual/pages/general/security.adoc
Labels: enhancement

#191 Restructured the encryption documentation
  modules/administration_manual/nav.adoc
  modules/administration_manual/pages/configuration/files/encryption/disabling-encryption.adoc
  modules/administration_manual/pages/configuration/files/encryption/enable-encryption.adoc
  modules/administration_manual/pages/configuration/files/encryption/enabling-user-key-encryption.adoc
  modules/administration_manual/pages/configuration/files/encryption/encryption-types.adoc
  modules/administration_manual/pages/configuration/files/encryption/encryption_configuration_quick_guide.adoc
  modules/administration_manual/pages/configuration/files/encryption/external-backends.adoc
  modules/administration_manual/pages/configuration/files/encryption/index.adoc
  modules/administration_manual/pages/configuration/files/encryption/master-key-encryption.adoc
  modules/administration_manual/pages/configuration/files/encryption/moving-key-locations.adoc
  modules/administration_manual/pages/configuration/files/encryption/sharing-encrypted-files.adoc
Labels: deployment, enhancement, review required, technical review

#401 Fix: only book doctypes can contain level 0 sections
  modules/administration_manual/pages/configuration/files/encryption/index.adoc
Labels: bug

#398 Document how we write acceptance tests
  modules/developer_manual/pages/core/acceptance-tests.adoc
Labels: work in progress

#399 Convert rST inline code blocks to AsciiDoc format
  modules/administration_manual/pages/appliance/Index.php-less_URLs.adoc
  modules/administration_manual/pages/appliance/howto-update-owncloud.adoc
  modules/administration_manual/pages/configuration/database/db_conversion.adoc
  modules/administration_manual/pages/configuration/database/linux_database_configuration.adoc
  modules/administration_manual/pages/configuration/files/encryption_configuration.adoc
  modules/administration_manual/pages/configuration/files/external_storage/dropbox.adoc
  modules/administration_manual/pages/configuration/files/external_storage_configuration_gui.adoc
  modules/administration_manual/pages/configuration/files/file_sharing_configuration.adoc
  modules/administration_manual/pages/configuration/server/antivirus_configuration.adoc
  modules/administration_manual/pages/configuration/server/caching_configuration.adoc
  modules/administration_manual/pages/configuration/server/config_sample_php_parameters.adoc
  modules/administration_manual/pages/configuration/server/legal_settings_configuration.adoc
  modules/administration_manual/pages/configuration/server/logging_configuration.adoc
  modules/administration_manual/pages/configuration/server/occ_command.adoc
  modules/administration_manual/pages/configuration/server/reverse_proxy_configuration.adoc
  modules/administration_manual/pages/configuration/server/security/password_policy.adoc
  modules/administration_manual/pages/configuration/server/security_setup_warnings.adoc
  modules/administration_manual/pages/configuration/user/user_auth_ldap.adoc
  modules/administration_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
  modules/administration_manual/pages/enterprise/ransomware-protection/index.adoc
  modules/administration_manual/pages/enterprise/server_branding/enterprise_server_branding.adoc
  modules/administration_manual/pages/installation/deployment_recommendations.adoc
  modules/administration_manual/pages/installation/nginx_configuration.adoc
  modules/administration_manual/pages/installation/system_requirements.adoc
  modules/administration_manual/pages/issues/code_signing.adoc
  modules/administration_manual/pages/maintenance/restore.adoc
  modules/developer_manual/pages/app/advanced/code_signing.adoc
  modules/developer_manual/pages/app/advanced/custom-cache-backend.adoc
  modules/developer_manual/pages/app/fundamentals/publishing.adoc
  modules/developer_manual/pages/app/tutorial/wiring_it_up.adoc
  modules/developer_manual/pages/bugtracker/codereviews.adoc
  modules/developer_manual/pages/bugtracker/triaging.adoc
  modules/developer_manual/pages/core/theming.adoc
  modules/developer_manual/pages/core/ui-testing.adoc
  modules/developer_manual/pages/general/devenv.adoc
  modules/developer_manual/pages/general/security.adoc
  modules/developer_manual/pages/mobile_development/android_library/examples.adoc
  modules/developer_manual/pages/mobile_development/ios_library/examples.adoc
  modules/developer_manual/pages/mobile_development/ios_library/library_installation.adoc
  modules/user_manual/pages/files/encrypting_files.adoc
  modules/user_manual/pages/files/gallery_app.adoc
  modules/user_manual/pages/troubleshooting.adoc
Labels: enhancement

#403 Improve readme
  README.md
  docs/test-ui-bundle.md
Labels: enhancement

#410 occ upgrade new option
  modules/administration_manual/pages/configuration/server/occ_command.adoc
Labels: command-line

#412 Add the branded_clients antora build to the docs
  site.yml
Labels: deployment, enhancement

#415 fixing failed to parse formatted text (image alt text)
  modules/administration_manual/pages/configuration/server/antivirus_configuration.adoc
  modules/administration_manual/pages/enterprise/firewall/file_firewall.adoc
Labels: bug

#405 Best practices
  README.md
  docs/best-practices.md
Labels: encryption, enhancement
