Repository owncloud/docs, pull requests merged in 2018-12, with the labels that each got.

#421 New option in occ command files_external:list `--short`
  modules/administration_manual/pages/configuration/server/occ_command.adoc
Labels: command-line, core

#418 General Fixes
  modules/administration_manual/pages/appliance/Clamav.adoc
  modules/administration_manual/pages/configuration/server/caching_configuration.adoc
  modules/administration_manual/pages/configuration/server/oc_server_tuning.adoc
  modules/administration_manual/pages/configuration/user/user_auth_ldap.adoc
  modules/administration_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
  modules/administration_manual/pages/installation/configuration_notes_and_tips.adoc
  modules/administration_manual/pages/installation/docker/index.adoc
  modules/administration_manual/pages/installation/nginx_configuration.adoc
  modules/administration_manual/pages/release_notes.adoc
  modules/developer_manual/pages/app/fundamentals/backgroundjobs.adoc
  modules/developer_manual/pages/app/fundamentals/classloader.adoc
  modules/developer_manual/pages/app/tutorial/database_connectivity.adoc
  modules/developer_manual/pages/bugtracker/codereviews.adoc
  modules/developer_manual/pages/bugtracker/triaging.adoc
  modules/developer_manual/pages/core/theming.adoc
  modules/developer_manual/pages/core/unit-testing.adoc
  modules/developer_manual/pages/general/devenv.adoc
  modules/developer_manual/pages/general/security.adoc
  modules/developer_manual/pages/mobile_development/ios_library/examples.adoc
  modules/developer_manual/pages/mobile_development/ios_library/library_installation.adoc
  modules/user_manual/pages/files/access_webdav.adoc
  modules/user_manual/pages/files/gallery_app.adoc
  modules/user_manual/pages/session_management.adoc
Labels: bug, enhancement

#323 Add netlify headers file
  .drone.yml
  netlify.toml
Labels: deployment, waiting on feedback

#424 Small text fixes / improvements for Best Practices
  docs/best-practices.md
Labels: enhancement

#427 Update links to root pages of ios and android manuals
  modules/ROOT/pages/index.adoc
Labels: waiting on PR merge

#234 Redirect the existing documentation to the new documentation
  modules/administration_manual/nav.adoc
  modules/administration_manual/pages/configuration/database/index.adoc
  modules/administration_manual/pages/configuration/files/index.adoc
  modules/administration_manual/pages/configuration/user/index.adoc
  modules/administration_manual/pages/installation/index.adoc
  modules/administration_manual/pages/issues/index.adoc
  modules/administration_manual/pages/maintenance/index.adoc
  modules/administration_manual/pages/upgrading/index.adoc
  modules/developer_manual/nav.adoc
  modules/developer_manual/pages/app/advanced/index.adoc
  modules/developer_manual/pages/app/fundamentals/index.adoc
  modules/developer_manual/pages/core/index.adoc
  modules/developer_manual/pages/general/index.adoc
  modules/developer_manual/pages/mobile_development/index.adoc
  modules/user_manual/nav.adoc
  modules/user_manual/pages/files/index.adoc
Labels: deployment, enhancement, technical review, waiting on feedback

#435 Customise the way that auto-generated anchors are created
  site.yml
Labels: deployment, enhancement, review required

#433 Fixes and updates to
  README.md
  docs/best-practices.md
  docs/build-the-docs.md
  docs/checking-broken-links.md
  docs/getting-started.md
  docs/install-antora.md
Labels: bug

#438 update occ user setting command
  modules/administration_manual/pages/configuration/server/occ_command.adoc
Labels: bug

#434 Deprecate OpenStack Swift support
  modules/administration_manual/pages/enterprise/external_storage/s3_swift_as_primary_object_store_configuration.adoc
Labels: enhancement, review required

#440 Fixes around makefile
  Makefile
  docs/build-the-docs.md
  docs/checking-broken-links.md
  docs/getting-started.md
  docs/install-antora.md
  generators/xref-validator.js
  package.json
  yarn.lock
Labels: enhancement

#448 Updated config sample files from core
  modules/administration_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
  modules/administration_manual/pages/configuration/server/config_sample_php_parameters.adoc
Labels: command-line, core

#455 xss link reference broken
  modules/developer_manual/pages/general/security.adoc
Labels: bug

#457 occ-files_transfer-ownership-link broken
  modules/administration_manual/pages/enterprise/external_storage/s3_swift_as_primary_object_store_configuration.adoc
Labels: bug

#456 config sample fixes
  modules/administration_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
  modules/administration_manual/pages/configuration/server/config_sample_php_parameters.adoc
Labels: bug

#454 Update best-practices.md
  docs/best-practices.md
Labels: bug

#463 Fix xref-validator copied from antora master
  generators/xref-validator.js
Labels: command-line, deployment

#461 navigation improvement
  modules/administration_manual/nav.adoc
  modules/developer_manual/nav.adoc
  modules/user_manual/nav.adoc
Labels: bug, enhancement

#460 improve best practices: admonition and tables
  docs/best-practices.md
Labels: enhancement

#459 Admonition and text fixes
  modules/administration_manual/pages/appliance/Office.adoc
  modules/administration_manual/pages/configuration/database/db_conversion.adoc
  modules/administration_manual/pages/configuration/files/encryption/enable-encryption.adoc
  modules/administration_manual/pages/configuration/files/encryption/enabling-user-key-encryption.adoc
  modules/administration_manual/pages/configuration/files/encryption/master-key-encryption.adoc
  modules/administration_manual/pages/configuration/files/encryption_configuration.adoc
  modules/administration_manual/pages/configuration/files/external_storage/auth_mechanisms.adoc
  modules/administration_manual/pages/configuration/files/external_storage_configuration_gui.adoc
  modules/administration_manual/pages/configuration/server/background_jobs_configuration.adoc
  modules/administration_manual/pages/configuration/server/caching_configuration.adoc
  modules/administration_manual/pages/configuration/server/harden_server.adoc
  modules/administration_manual/pages/configuration/server/legal_settings_configuration.adoc
  modules/administration_manual/pages/configuration/server/occ_app_command.adoc
  modules/administration_manual/pages/configuration/server/occ_command.adoc
  modules/administration_manual/pages/configuration/server/security/password_policy.adoc
  modules/administration_manual/pages/configuration/user/user_auth_ldap.adoc
  modules/administration_manual/pages/enterprise/classification_and_policy_enforcement.adoc
  modules/administration_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
  modules/administration_manual/pages/enterprise/firewall/file_firewall.adoc
  modules/administration_manual/pages/enterprise/user_management/saml_2.0_sso.adoc
  modules/administration_manual/pages/enterprise/user_management/user_auth_shibboleth.adoc
  modules/administration_manual/pages/installation/deployment_recommendations.adoc
  modules/administration_manual/pages/installation/letsencrypt/nginx.adoc
  modules/administration_manual/pages/maintenance/backup.adoc
  modules/administration_manual/pages/maintenance/encryption/migrating-from-user-key-to-master-key.adoc
  modules/administration_manual/pages/maintenance/migrating.adoc
  modules/developer_manual/pages/core/theming.adoc
  modules/user_manual/pages/files/encrypting_files.adoc
  modules/user_manual/pages/files/webgui/custom_groups.adoc
Labels: bug, enhancement

#453 New image and text fixes for files-sharing
  modules/administration_manual/assets/images/configuration/files/sharing-files-settings.png
  modules/administration_manual/pages/configuration/files/file_sharing_configuration.adoc
Labels: admin docs

#464 Remove duplicate enterprise links in non-enterprise nav section
  modules/administration_manual/nav.adoc
Labels: bug

#450 market app update
  modules/administration_manual/pages/configuration/server/occ_app_command.adoc
Labels: command-line

#471 fix "I think"
  modules/administration_manual/pages/configuration/files/file_sharing_configuration.adoc
Labels: admin docs, bug

#474 Better naming for migration to a different server
  modules/administration_manual/nav.adoc
Labels: enhancement

#473 Missing config apps navigation entry
  modules/administration_manual/nav.adoc
Labels: bug, deployment

#465 Document the WebDAV Custom Groups Management API
  modules/developer_manual/examples/core/webdav_api/group/report-customgroups.xml
  modules/developer_manual/examples/core/webdav_api/group/request/list-custom-group-members.xml
  modules/developer_manual/examples/core/webdav_api/group/request/list-custom-groups.xml
  modules/developer_manual/examples/core/webdav_api/group/request/rename-custom-group.xml
  modules/developer_manual/examples/core/webdav_api/group/response-success.xml
  modules/developer_manual/examples/core/webdav_api/group/response/list-group-members-successful-response.xml
  modules/developer_manual/examples/core/webdav_api/group/response/list-group-memberships-of-a-given-user-successful-response.xml
  modules/developer_manual/examples/core/webdav_api/group/response/list-groups-missing-group-response.xml
  modules/developer_manual/examples/core/webdav_api/group/response/list-groups-no-results-response.xml
  modules/developer_manual/examples/core/webdav_api/group/response/list-groups-successful-response.xml
  modules/developer_manual/nav.adoc
  modules/developer_manual/pages/_partials/webdav_api/core_curl_request.adoc
  modules/developer_manual/pages/_partials/webdav_api/responses/insufficient-privileges-overview.adoc
  modules/developer_manual/pages/_partials/webdav_api/uri_request_table.adoc
  modules/developer_manual/pages/webdav_api/groups.adoc
  modules/developer_manual/pages/webdav_api/groups/custom_groups_endpoints.adoc
  modules/developer_manual/pages/webdav_api/groups/group_membership_endpoints.adoc
Labels: review required

#478 Fixed broken link to ISO 27001
  modules/administration_manual/pages/enterprise/classification_and_policy_enforcement.adoc
Labels: admin docs, bug

#476 Document the Semantic Versioning guidelines
  modules/developer_manual/pages/core/semantic-versioning-guidelines.adoc
Labels: developer docs, enhancement, waiting on feedback

#482 Fix incorrect site.yml configuration
  site.yml
Labels: bug
