Repository owncloud/docs, pull requests merged in 2018-09, with the labels that each got.

#67 transactional file locking enabled by default
  modules/ROOT/pages/configuration/server/caching_configuration.adoc
Labels: enhancement

#68 Add second scenario to files:scan --repair
  modules/ROOT/pages/configuration/server/occ_command.adoc
Labels: enhancement

#71 database guidelines
  modules/developer_manual/pages/app/fundamentals/database.adoc
Labels: enhancement, work in progress

#90 Port occ_app_command.adoc and config_apps_sample_php_parameters from documentation
  modules/ROOT/pages/configuration/server/config_apps_sample_php_parameters.adoc
  modules/ROOT/pages/configuration/server/occ_app_command.adoc
Labels: review required

#87 added path for ransomware
  modules/ROOT/pages/appliance/login_information.adoc
Labels: enhancement, work in progress

#91 occ core/app command improvement including brute force protection
  modules/ROOT/pages/configuration/server/occ_app_command.adoc
  modules/ROOT/pages/configuration/server/occ_command.adoc
Labels: command-line

#70 limitations of encryption
  modules/ROOT/pages/configuration/files/encryption_configuration.adoc
Labels: enhancement, work in progress

#107 Adding json to the nginx location directive
  modules/ROOT/examples/installation/nginx/default-configuration.conf
  modules/ROOT/examples/installation/nginx/subdirectory-configuration.conf
Labels: enhancement, question

#120 Add a set of documentation links to the AsciiDoc guide
  docs/what-is-asciidoc.md
Labels: enhancement, review required

#113 more occ fixes
  modules/ROOT/pages/configuration/server/occ_app_command.adoc
  modules/ROOT/pages/configuration/server/occ_command.adoc
Labels: command-line, enhancement, work in progress

#122 Document occ app files_antivirus
  modules/ROOT/pages/configuration/server/occ_app_command.adoc
Labels: command-line
