Repository owncloud/docs, pull requests merged in 2019-02, with the labels that each got.

#570 Add a series of filetype-specific Markfile validation targets
  Makefile
Labels: command-line, deployment, enhancement, technical review

#559 Set the revision number and date correctly
  Makefile
  books/admin.adoc
  books/developer.adoc
  books/user.adoc
Labels: bug, command-line, deployment, p2-high, pdf generation, review required

#578 Update 10.0.10 branch component descriptor version
  antora.yml
Labels: bug

#584 Reorganise the maintenance section of the admin manual's navigation menu
  modules/administration_manual/nav.adoc
Labels: admin docs, enhancement, review required, waiting on feedback

#573 Document where to find the legal settings links in the ownCloud UI
  modules/administration_manual/assets/images/configuration/server/legal-settings/login-form-with-legal-settings-links.png
  modules/administration_manual/pages/configuration/server/legal_settings_configuration.adoc
Labels: admin docs, enhancement, review required

#588 Remove Piwik integration
  site.yml
Labels: admin docs, bug, deployment, developer docs, user docs

#581 Port Documentation PR #3889
  modules/developer_manual/examples/core/unit-testing/MyClass.php
  modules/developer_manual/examples/core/unit-testing/MyClassTest.php
  modules/developer_manual/pages/core/unit-testing.adoc
Labels: backport, developer docs, enhancement, review required

#590 updated sessions picture
  modules/user_manual/assets/images/session_management/app_passwords.png
  modules/user_manual/assets/images/session_management/sessions.png
  modules/user_manual/assets/images/session_management/settings_sessions.png
  modules/user_manual/assets/images/settings_sessions.png
  modules/user_manual/pages/session_management.adoc
Labels: enhancement, user docs, waiting on feedback

#595 Document how to enable images in asciidoc preview pane
  docs/images/what-is-asciidoc/setting-imagesdir-in-atom.png
  docs/images/what-is-asciidoc/setting-imagesdir-in-intellij.png
  docs/what-is-asciidoc.md
Labels: enhancement, waiting on feedback

#589 Update docs for version 10.1
  modules/ROOT/pages/index.adoc
Labels: admin docs, deployment, developer docs, enhancement, technical review, user docs

#587 Update playbook and component descriptor for version 10.0
  modules/ROOT/pages/index.adoc
  site.local.yml
  site.yml
Labels: admin docs, deployment, developer docs, enhancement, technical review, user docs

#601 WIP: Document the WOPI integration in oC enterprise
  modules/administration_manual/nav.adoc
  modules/administration_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
  site.yml
Labels: admin docs, enhancement, work in progress

#605 Clarify ownCloud server 9.1 is EOL
  modules/ROOT/pages/_partials/maintenance-release-schedule-link.adoc
  modules/ROOT/pages/index.adoc
Labels: enhancement

#608 Fix broken links on how to contribute page
  modules/ROOT/pages/how_to_contribute.adoc
Labels: bug

#616 fix shell used in makefile
  Makefile
Labels: bug, installation & configuration

#617 Fix minor wording in acceptance-tests.adoc
  modules/developer_manual/pages/core/acceptance-tests.adoc
Labels: developer docs

#623 Change system tag internal name to collaborative
  modules/user_manual/pages/files/webgui/tagging.adoc
Labels: enhancement

#624 Add section about tagging scenarios to acceptance-tests.adoc
  modules/developer_manual/pages/core/acceptance-tests.adoc
Labels: developer docs

#626 [10.1] Fix minor wording in acceptance-tests.adoc
  modules/developer_manual/pages/core/acceptance-tests.adoc
Labels: developer docs

#627 [10.0] Fix minor wording in acceptance-tests.adoc
  modules/developer_manual/pages/core/acceptance-tests.adoc
Labels: developer docs

#628 [10.0] Add section about tagging scenarios to acceptance-tests.adoc
  modules/developer_manual/pages/core/acceptance-tests.adoc
Labels: developer docs

#629 [10.1] Add section about tagging scenarios to acceptance-tests.adoc
  modules/developer_manual/pages/core/acceptance-tests.adoc
Labels: developer docs

#612 Document the build pipeline in the contributor docs
  docs/getting-started.md
  docs/the-build-pipeline.md
Labels: deployment, enhancement, review required

#633 Writing Scenarios For Bugs
  modules/developer_manual/pages/core/acceptance-tests.adoc
Labels: developer docs

#634 [10.1] Writing Scenarios For Bugs
  modules/developer_manual/pages/core/acceptance-tests.adoc
Labels: developer docs

#635 [10.0] Writing Scenarios For Bugs
  modules/developer_manual/pages/core/acceptance-tests.adoc
Labels: developer docs

#630 Document the documentation branching workflow
  docs/getting-started.md
  docs/images/the-branching-workflow.key
  docs/images/the-branching-workflow.png
  docs/the-branching-workflow.md
Labels: enhancement, review required

#644 Correct files:scan --all documentation
  modules/admin_manual/pages/configuration/server/occ_command.adoc
Labels: backport, review required

#645 [10.1] Correct files:scan --all documentation
  modules/admin_manual/pages/configuration/server/occ_command.adoc
Labels: review required

#646 [10.0] Correct files:scan --all documentation
  modules/admin_manual/pages/configuration/server/occ_command.adoc
Labels: review required

#642 [OC11] Issue 284 document files:scan --group
  modules/admin_manual/pages/configuration/server/occ_command.adoc
Labels: no backport, review required

#650 How to add new acceptance test steps
  modules/developer_manual/examples/core/acceptance-tests/given-step.php
  modules/developer_manual/examples/core/acceptance-tests/then-step-with-actions.php
  modules/developer_manual/examples/core/acceptance-tests/then-step.php
  modules/developer_manual/examples/core/acceptance-tests/when-step.php
  modules/developer_manual/pages/core/acceptance-tests.adoc
Labels: backport, review required

#651 Doc how to add new test steps 10.1
  modules/developer_manual/examples/core/acceptance-tests/given-step.php
  modules/developer_manual/examples/core/acceptance-tests/then-step-with-actions.php
  modules/developer_manual/examples/core/acceptance-tests/then-step.php
  modules/developer_manual/examples/core/acceptance-tests/when-step.php
  modules/developer_manual/pages/core/acceptance-tests.adoc
Labels: review required

#652 Doc how to add new test steps 10.0
  modules/developer_manual/examples/core/acceptance-tests/given-step.php
  modules/developer_manual/examples/core/acceptance-tests/then-step-with-actions.php
  modules/developer_manual/examples/core/acceptance-tests/then-step.php
  modules/developer_manual/examples/core/acceptance-tests/when-step.php
  modules/developer_manual/pages/core/acceptance-tests.adoc
Labels: review required

#653 fix Available APIs navigation link
  modules/developer_manual/nav.adoc
Labels: APIs, developer docs

#656 Fix some of the build errors
  modules/admin_manual/pages/configuration/files/encryption/enable-encryption.adoc
  modules/developer_manual/pages/app/fundamentals/filesystem.adoc
  modules/developer_manual/pages/webdav_api/groups/group_membership_endpoints.adoc
Labels: backport, bug, clean up, deployment, review required

#661 Rename make test-php to test-php-unit
  modules/developer_manual/pages/core/unit-testing.adoc
Labels: developer docs
