Repository owncloud/docs, pull requests merged in 2019-07, with the labels that each got.

#1364 Added YAML file and registry instructions
  modules/admin_manual/examples/installation/docker/docker-compose.yml
  modules/admin_manual/pages/installation/docker/index.adoc
Labels: admin docs, enhancement, p3-medium

#1371 Link to the new iOS Mobile App on the docs root page
  modules/ROOT/pages/index.adoc
Labels: enhancement, ios, p2-high, review required

#1379 Fix PDF generation process in 10.0
  .drone.yml
  Makefile
  bin/cli
  books/ownCloud_Admin_Manual.adoc
  books/ownCloud_Developer_Manual.adoc
  books/ownCloud_User_Manual.adoc
  modules/admin_manual/nav.adoc
  modules/admin_manual/pages/appliance/configuration/index.adoc
  modules/admin_manual/pages/appliance/maintenance/index.adoc
  modules/admin_manual/pages/configuration/files/encryption/root.adoc
  modules/admin_manual/pages/configuration/files/external_storage/index.adoc
  modules/admin_manual/pages/configuration/ldap/index.adoc
  modules/admin_manual/pages/configuration/ldap/ldap_proxy_cache_server_setup.adoc
  modules/admin_manual/pages/configuration/server/antivirus_configuration.adoc
  modules/admin_manual/pages/configuration/server/index.adoc
  modules/admin_manual/pages/configuration/server/security/index.adoc
  modules/admin_manual/pages/enterprise/clients/index.adoc
  modules/admin_manual/pages/enterprise/collaboration/index.adoc
  modules/admin_manual/pages/enterprise/external_storage/index.adoc
  modules/admin_manual/pages/enterprise/file_management/index.adoc
  modules/admin_manual/pages/enterprise/firewall/index.adoc
  modules/admin_manual/pages/enterprise/logging/index.adoc
  modules/admin_manual/pages/enterprise/security/index.adoc
  modules/admin_manual/pages/enterprise/server_branding/index.adoc
  modules/admin_manual/pages/enterprise/user_management/index.adoc
  modules/admin_manual/pages/enterprise/user_management/user_auth_shibboleth.adoc
  modules/admin_manual/pages/installation/apps_management_installation.adoc
  modules/admin_manual/pages/installation/docker/index.adoc
  modules/admin_manual/pages/installation/installation_wizard.adoc
  modules/admin_manual/pages/installation/letsencrypt/index.adoc
  modules/admin_manual/pages/installation/letsencrypt/using_letsencrypt.adoc
  modules/admin_manual/pages/installation/manual_installation.adoc
  modules/admin_manual/pages/installation/nginx_configuration.adoc
  modules/admin_manual/pages/installation/ubuntu_18_04.adoc
  modules/admin_manual/pages/maintenance/encryption/index.adoc
  modules/admin_manual/pages/maintenance/manual_upgrade.adoc
  modules/admin_manual/pages/troubleshooting/index.adoc
  modules/developer_manual/pages/_partials/webdav_api/search/common_error_responses.adoc
  modules/developer_manual/pages/app/advanced/extstorage.adoc
  modules/developer_manual/pages/app/fundamentals/backgroundjobs.adoc
  modules/developer_manual/pages/app/fundamentals/filesystem.adoc
  modules/developer_manual/pages/core/apis/index.adoc
  modules/developer_manual/pages/core/apis/ocs-capabilities.adoc
  modules/developer_manual/pages/core/apis/ocs-share-api.adoc
  modules/developer_manual/pages/core/theming.adoc
  modules/developer_manual/pages/general/backporting.adoc
  modules/developer_manual/pages/testing/acceptance-tests.adoc
  modules/developer_manual/pages/testing/index.adoc
  modules/developer_manual/pages/testing/unit-testing.adoc
  modules/developer_manual/pages/webdav_api/groups/custom_groups_endpoints.adoc
  modules/developer_manual/pages/webdav_api/groups/group_membership_endpoints.adoc
  modules/developer_manual/pages/webdav_api/index.adoc
  modules/developer_manual/pages/webdav_api/search/filter_files.adoc
  modules/developer_manual/pages/webdav_api/search/search_files.adoc
  modules/user_manual/pages/apps/index.adoc
  site.yml
Labels: bug, clean up, deployment, enhancement, p2-high, review required

#1378 Fix PDF generation process in 10.1
  .drone.yml
  Makefile
  bin/cli
  books/ownCloud_Admin_Manual.adoc
  books/ownCloud_Developer_Manual.adoc
  books/ownCloud_User_Manual.adoc
  modules/admin_manual/pages/appliance/configuration/index.adoc
  modules/admin_manual/pages/appliance/maintenance/index.adoc
  modules/admin_manual/pages/configuration/files/encryption/root.adoc
  modules/admin_manual/pages/configuration/files/external_storage/index.adoc
  modules/admin_manual/pages/configuration/ldap/index.adoc
  modules/admin_manual/pages/configuration/ldap/ldap_proxy_cache_server_setup.adoc
  modules/admin_manual/pages/configuration/server/antivirus_configuration.adoc
  modules/admin_manual/pages/configuration/server/index.adoc
  modules/admin_manual/pages/configuration/server/security/index.adoc
  modules/admin_manual/pages/enterprise/clients/index.adoc
  modules/admin_manual/pages/enterprise/collaboration/index.adoc
  modules/admin_manual/pages/enterprise/external_storage/index.adoc
  modules/admin_manual/pages/enterprise/file_management/index.adoc
  modules/admin_manual/pages/enterprise/firewall/index.adoc
  modules/admin_manual/pages/enterprise/logging/index.adoc
  modules/admin_manual/pages/enterprise/security/index.adoc
  modules/admin_manual/pages/enterprise/server_branding/index.adoc
  modules/admin_manual/pages/enterprise/user_management/index.adoc
  modules/admin_manual/pages/enterprise/user_management/user_auth_shibboleth.adoc
  modules/admin_manual/pages/installation/apps_management_installation.adoc
  modules/admin_manual/pages/installation/docker/index.adoc
  modules/admin_manual/pages/installation/installation_wizard.adoc
  modules/admin_manual/pages/installation/letsencrypt/index.adoc
  modules/admin_manual/pages/installation/letsencrypt/using_letsencrypt.adoc
  modules/admin_manual/pages/installation/manual_installation.adoc
  modules/admin_manual/pages/installation/nginx_configuration.adoc
  modules/admin_manual/pages/installation/ubuntu_18_04.adoc
  modules/admin_manual/pages/maintenance/encryption/index.adoc
  modules/admin_manual/pages/maintenance/manual_upgrade.adoc
  modules/admin_manual/pages/troubleshooting/index.adoc
  modules/developer_manual/pages/_partials/webdav_api/search/common_error_responses.adoc
  modules/developer_manual/pages/app/advanced/extstorage.adoc
  modules/developer_manual/pages/app/fundamentals/backgroundjobs.adoc
  modules/developer_manual/pages/app/fundamentals/filesystem.adoc
  modules/developer_manual/pages/core/apis/index.adoc
  modules/developer_manual/pages/core/apis/ocs-capabilities.adoc
  modules/developer_manual/pages/core/apis/ocs-share-api.adoc
  modules/developer_manual/pages/core/theming.adoc
  modules/developer_manual/pages/general/backporting.adoc
  modules/developer_manual/pages/testing/acceptance-tests.adoc
  modules/developer_manual/pages/testing/index.adoc
  modules/developer_manual/pages/testing/unit-testing.adoc
  modules/developer_manual/pages/webdav_api/groups/custom_groups_endpoints.adoc
  modules/developer_manual/pages/webdav_api/groups/group_membership_endpoints.adoc
  modules/developer_manual/pages/webdav_api/index.adoc
  modules/developer_manual/pages/webdav_api/search/filter_files.adoc
  modules/developer_manual/pages/webdav_api/search/search_files.adoc
  modules/user_manual/pages/apps/index.adoc
  site.yml
Labels: bug, deployment, enhancement, p2-high, review required

#1377 Fix pdf generation process master
  .drone.yml
  Makefile
  bin/cli
  books/ownCloud_Admin_Manual.adoc
  books/ownCloud_Developer_Manual.adoc
  books/ownCloud_User_Manual.adoc
  modules/ROOT/pages/index.adoc
  modules/admin_manual/pages/appliance/configuration/index.adoc
  modules/admin_manual/pages/appliance/maintenance/index.adoc
  modules/admin_manual/pages/configuration/files/encryption/root.adoc
  modules/admin_manual/pages/configuration/files/external_storage/index.adoc
  modules/admin_manual/pages/configuration/ldap/index.adoc
  modules/admin_manual/pages/configuration/ldap/ldap_proxy_cache_server_setup.adoc
  modules/admin_manual/pages/configuration/server/antivirus_configuration.adoc
  modules/admin_manual/pages/configuration/server/index.adoc
  modules/admin_manual/pages/configuration/server/security/index.adoc
  modules/admin_manual/pages/enterprise/clients/index.adoc
  modules/admin_manual/pages/enterprise/collaboration/index.adoc
  modules/admin_manual/pages/enterprise/external_storage/index.adoc
  modules/admin_manual/pages/enterprise/file_management/index.adoc
  modules/admin_manual/pages/enterprise/firewall/index.adoc
  modules/admin_manual/pages/enterprise/logging/index.adoc
  modules/admin_manual/pages/enterprise/security/index.adoc
  modules/admin_manual/pages/enterprise/server_branding/index.adoc
  modules/admin_manual/pages/enterprise/user_management/index.adoc
  modules/admin_manual/pages/enterprise/user_management/user_auth_shibboleth.adoc
  modules/admin_manual/pages/installation/apps_management_installation.adoc
  modules/admin_manual/pages/installation/docker/index.adoc
  modules/admin_manual/pages/installation/installation_wizard.adoc
  modules/admin_manual/pages/installation/letsencrypt/index.adoc
  modules/admin_manual/pages/installation/letsencrypt/using_letsencrypt.adoc
  modules/admin_manual/pages/installation/manual_installation.adoc
  modules/admin_manual/pages/installation/nginx_configuration.adoc
  modules/admin_manual/pages/installation/ubuntu_18_04.adoc
  modules/admin_manual/pages/maintenance/encryption/index.adoc
  modules/admin_manual/pages/maintenance/manual_upgrade.adoc
  modules/admin_manual/pages/troubleshooting/index.adoc
  modules/developer_manual/pages/_partials/webdav_api/search/common_error_responses.adoc
  modules/developer_manual/pages/app/advanced/extstorage.adoc
  modules/developer_manual/pages/app/fundamentals/backgroundjobs.adoc
  modules/developer_manual/pages/app/fundamentals/filesystem.adoc
  modules/developer_manual/pages/core/apis/index.adoc
  modules/developer_manual/pages/core/apis/ocs-capabilities.adoc
  modules/developer_manual/pages/core/apis/ocs-share-api.adoc
  modules/developer_manual/pages/core/theming.adoc
  modules/developer_manual/pages/general/backporting.adoc
  modules/developer_manual/pages/testing/acceptance-tests.adoc
  modules/developer_manual/pages/testing/index.adoc
  modules/developer_manual/pages/testing/unit-testing.adoc
  modules/developer_manual/pages/webdav_api/groups/custom_groups_endpoints.adoc
  modules/developer_manual/pages/webdav_api/groups/group_membership_endpoints.adoc
  modules/developer_manual/pages/webdav_api/index.adoc
  modules/developer_manual/pages/webdav_api/search/filter_files.adoc
  modules/developer_manual/pages/webdav_api/search/search_files.adoc
  modules/user_manual/pages/apps/index.adoc
Labels: command-line, deployment, enhancement, p2-high, review required

#1372 [10.2] [PR 1371] Link to the new iOS Mobile App on the docs root page
  modules/ROOT/pages/index.adoc
Labels: enhancement, p3-medium

#1373 [10.1] [PR 1371] Link to the new iOS Mobile App on the docs root page
  modules/ROOT/pages/index.adoc
Labels: enhancement, p3-medium

#1374 [10.0] [PR 1371] Link to the new iOS Mobile App on the docs root page
  modules/ROOT/pages/index.adoc
Labels: enhancement, p3-medium

#1326 Remove enterprise reference for password policy app
  modules/admin_manual/pages/configuration/files/file_sharing_configuration.adoc
Labels: review required

#1362 Update windows-network-drive_configuration.adoc
  modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
Labels: admin docs

#1394 Update WebDAV documentation
  modules/admin_manual/pages/configuration/files/external_storage/webdav.adoc
Labels: admin docs, bug, clean up, enhancement, review required, waiting on feedback

#1398 Move the API code examples into tab blocks
  modules/developer_manual/pages/core/apis/externalapi.adoc
  modules/developer_manual/pages/core/apis/ocs-share-api.adoc
Labels: developer docs, enhancement, p3-medium, review required

#1395 [1387] Document the -y and --yes options for the occ encrypt-all command
  modules/admin_manual/pages/configuration/files/encryption/enabling-user-key-encryption.adoc
  modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
  modules/admin_manual/pages/configuration/files/encryption/encryption_configuration_quick_guide.adoc
  modules/admin_manual/pages/configuration/files/encryption/master-key-encryption.adoc
  modules/admin_manual/pages/configuration/server/occ_command.adoc
  modules/admin_manual/pages/configuration/user/encryption_configuration_quick_guide.adoc
  modules/admin_manual/pages/maintenance/encryption/migrating-from-user-key-to-master-key.adoc
Labels: admin docs, command-line, occ, p3-medium, review required, waiting on feedback

#1399 Clean up some of the API documentation
  modules/developer_manual/pages/core/apis/externalapi.adoc
  modules/developer_manual/pages/core/apis/ocs-recipient-api.adoc
  modules/developer_manual/pages/core/apis/ocs-share-api.adoc
  modules/developer_manual/pages/webdav_api/tags.adoc
Labels: clean up, p3-medium

#1397 Enable the Antora Tab Blocks Extension
  lib/extensions/tabs.js
  site.yml
Labels: Effort: 1d, enhancement, p3-medium, review required

#1337 Misleading general owncloud.log path
  modules/admin_manual/pages/configuration/server/harden_server.adoc
Labels: admin docs, installation & configuration, technical review, waiting on feedback

#1370 added app:enable encryption
  modules/admin_manual/pages/configuration/files/encryption/encryption_configuration_quick_guide.adoc
Labels: enhancement, installation & configuration, occ

#1396 Add Share permission to doc when creating shares
  modules/developer_manual/pages/core/apis/ocs-share-api.adoc
Labels: developer docs

#1342 Minor fixes to the occ and manual installation documentation
  modules/admin_manual/pages/configuration/server/occ_command.adoc
  modules/admin_manual/pages/installation/manual_installation.adoc
Labels: p4-low

#1412 Fix a set of links corrupted during the migration from Sphinx-Doc
  modules/admin_manual/pages/configuration/files/file_sharing_configuration.adoc
  modules/admin_manual/pages/configuration/server/index_php_less_urls.adoc
  modules/admin_manual/pages/configuration/server/occ_command.adoc
  modules/admin_manual/pages/configuration/server/security_setup_warnings.adoc
  modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
  modules/admin_manual/pages/installation/apps_management_installation.adoc
  modules/admin_manual/pages/installation/deployment_recommendations.adoc
  modules/admin_manual/pages/maintenance/upgrading/marketplace_apps.adoc
  modules/admin_manual/pages/maintenance/upgrading/upgrade_php.adoc
  modules/admin_manual/pages/release_notes.adoc
Labels: bug, clean up, p3-medium, review required

#1400 Document The New Trash bin WebDAV API in 10.3
  modules/developer_manual/examples/core/scripts/curl/dav/trashbin_api/delete-file-from-trashbin.sh
  modules/developer_manual/examples/core/scripts/curl/dav/trashbin_api/list-files-in-trashbin.sh
  modules/developer_manual/examples/core/scripts/curl/dav/trashbin_api/restore-file-to-trashbin.sh
  modules/developer_manual/examples/core/webdav_api/trashbin/list-files-in-trashbin-success-response.xml
  modules/developer_manual/nav.adoc
  modules/developer_manual/pages/webdav_api/trashbin.adoc
  site.yml
Labels: APIs, Effort: 1d, backport, core, developer docs, p3-medium, review required, waiting on feedback

#1427 Update finalise-install.sh example
  modules/admin_manual/examples/installation/ubuntu/18.04/finalise-install.sh
Labels: admin docs, installation & configuration

#1192 Update user_roles.adoc
  modules/admin_manual/pages/configuration/user/user_roles.adoc
Labels: admin docs, backport, bug

#1322 Fix 404s to configuration/files/encryption/encryption_configuration.adoc
  modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
Labels: admin docs, bug, p3-medium, review required

#1341 [1256] Reuse Existing LDAP Accounts, If Available
  modules/admin_manual/pages/configuration/server/occ_command.adoc
  modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
Labels: LDAP, admin docs, clean up, command-line, enhancement, installation & configuration, occ, p3-medium, technical review, waiting on feedback

#1229 Update source installation documentation
  modules/admin_manual/pages/installation/manual_installation.adoc
  modules/admin_manual/pages/installation/system_requirements.adoc
  site.yml
Labels: clean up, enhancement, review required

#1331 Fix incorrect reference to master in 10.2
  modules/ROOT/pages/index.adoc
  site.yml
Labels: deployment, waiting on feedback

#1464 Update and rename antivirus_configuration.adoc to virus-scanner-support.adoc
  modules/admin_manual/nav.adoc
  modules/admin_manual/pages/appliance/configuration/clamav.adoc
Labels: admin docs, clean up

#1469 restore Ubuntu 18.04 example to functional state
  modules/admin_manual/pages/installation/ubuntu_18_04.adoc
Labels: command-line, installation & configuration, p3-medium

#1470 removed non apache2 instructions
  modules/admin_manual/pages/installation/manual_installation.adoc
Labels: admin docs, clean up, deprecation, p4-low

#1475 [10.0] [PR 1470] removed non apache2 instructions
  modules/admin_manual/pages/installation/manual_installation.adoc
Labels: backport

#1476 [10.1] [PR 1470] removed non apache2 instructions
  modules/admin_manual/pages/installation/manual_installation.adoc
Labels: backport

#1477 [10.2] [PR 1470] removed non apache2 instructions
  modules/admin_manual/pages/installation/manual_installation.adoc
Labels: backport

#1471 update let's encrypt
  modules/admin_manual/pages/installation/letsencrypt/index.adoc
Labels: admin docs, enhancement, p4-low, waiting on feedback

#1479 Document the new OCS TOTP Validation API
  modules/developer_manual/examples/core/apis/ocs/totp-validation/responses/json/totp-is-invalid.json
  modules/developer_manual/examples/core/apis/ocs/totp-validation/responses/json/totp-is-valid.json
  modules/developer_manual/examples/core/apis/ocs/totp-validation/responses/json/totp-user-is-not-found.json
  modules/developer_manual/examples/core/apis/ocs/totp-validation/responses/xml/totp-is-invalid.xml
  modules/developer_manual/examples/core/apis/ocs/totp-validation/responses/xml/totp-is-valid.xml
  modules/developer_manual/examples/core/apis/ocs/totp-validation/responses/xml/totp-user-is-not-valid.xml
  modules/developer_manual/examples/core/scripts/curl/ocs/validate-totp.sh
  modules/developer_manual/nav.adoc
  modules/developer_manual/pages/core/apis/ocs-totp-validation-api.adoc
Labels: APIs, developer docs, enhancement, p3-medium, review required

#1510 [10.2] [PR 1479] Document the new OCS TOTP Validation API
  modules/developer_manual/examples/core/apis/ocs/totp-validation/responses/json/totp-is-invalid.json
  modules/developer_manual/examples/core/apis/ocs/totp-validation/responses/json/totp-is-valid.json
  modules/developer_manual/examples/core/apis/ocs/totp-validation/responses/json/totp-user-is-not-found.json
  modules/developer_manual/examples/core/apis/ocs/totp-validation/responses/xml/totp-is-invalid.xml
  modules/developer_manual/examples/core/apis/ocs/totp-validation/responses/xml/totp-is-valid.xml
  modules/developer_manual/examples/core/apis/ocs/totp-validation/responses/xml/totp-user-is-not-valid.xml
  modules/developer_manual/examples/core/scripts/curl/ocs/validate-totp.sh
  modules/developer_manual/nav.adoc
  modules/developer_manual/pages/core/apis/ocs-totp-validation-api.adoc
Labels: backport

#1511 [10.1] [PR 1479] Document the new OCS TOTP Validation API
  modules/developer_manual/examples/core/apis/ocs/totp-validation/responses/json/totp-is-invalid.json
  modules/developer_manual/examples/core/apis/ocs/totp-validation/responses/json/totp-is-valid.json
  modules/developer_manual/examples/core/apis/ocs/totp-validation/responses/json/totp-user-is-not-found.json
  modules/developer_manual/examples/core/apis/ocs/totp-validation/responses/xml/totp-is-invalid.xml
  modules/developer_manual/examples/core/apis/ocs/totp-validation/responses/xml/totp-is-valid.xml
  modules/developer_manual/examples/core/apis/ocs/totp-validation/responses/xml/totp-user-is-not-valid.xml
  modules/developer_manual/examples/core/scripts/curl/ocs/validate-totp.sh
  modules/developer_manual/nav.adoc
  modules/developer_manual/pages/core/apis/ocs-totp-validation-api.adoc
Labels: backport

#1512 [10.0] [PR 1479] Document the new OCS TOTP Validation API
  modules/developer_manual/examples/core/apis/ocs/totp-validation/responses/json/totp-is-invalid.json
  modules/developer_manual/examples/core/apis/ocs/totp-validation/responses/json/totp-is-valid.json
  modules/developer_manual/examples/core/apis/ocs/totp-validation/responses/json/totp-user-is-not-found.json
  modules/developer_manual/examples/core/apis/ocs/totp-validation/responses/xml/totp-is-invalid.xml
  modules/developer_manual/examples/core/apis/ocs/totp-validation/responses/xml/totp-is-valid.xml
  modules/developer_manual/examples/core/apis/ocs/totp-validation/responses/xml/totp-user-is-not-valid.xml
  modules/developer_manual/examples/core/scripts/curl/ocs/validate-totp.sh
  modules/developer_manual/nav.adoc
  modules/developer_manual/pages/core/apis/ocs-totp-validation-api.adoc
Labels: backport

#1340 [968] - Document Secure View with Collabora Online
  modules/admin_manual/assets/images/enterprise/collaboration/access-denied.png
  modules/admin_manual/assets/images/enterprise/collaboration/access-exception.png
  modules/admin_manual/assets/images/enterprise/collaboration/collabora-online-administration.png
  modules/admin_manual/assets/images/enterprise/collaboration/configuration-options.png
  modules/admin_manual/assets/images/enterprise/collaboration/share-options.png
  modules/admin_manual/assets/images/enterprise/collaboration/sharer-view.png
  modules/admin_manual/nav.adoc
  modules/admin_manual/pages/enterprise/collaboration/collabora_online_integration.adoc
  modules/user_manual/assets/images/collaboration/secure-view/access-denied.png
  modules/user_manual/assets/images/collaboration/secure-view/secure-view-share-configuration-options.png
  modules/user_manual/assets/images/enterprise/collaboration/secure-view/access-denied.png
  modules/user_manual/assets/images/enterprise/collaboration/secure-view/collabora-online-administration.png
  modules/user_manual/assets/images/enterprise/collaboration/secure-view/secure-view-share-configuration-options.png
  modules/user_manual/nav.adoc
  modules/user_manual/pages/online_collaboration.adoc
Labels: admin docs, enhancement, enterprise docs, installation & configuration, p2-high, review required, user docs, waiting on feedback

#1516 code brackets set to dashes insdead of dots
  modules/admin_manual/pages/installation/manual_installation.adoc
Labels: bug, clean up, enhancement

#1517 change code brackets to dashes instead of dots
  modules/admin_manual/pages/installation/manual_installation.adoc
Labels: bug, clean up, enhancement

#1518 [10.2] Backport #1468
  modules/admin_manual/pages/configuration/files/file_sharing_configuration.adoc
  modules/admin_manual/pages/configuration/user/user_configuration.adoc
  modules/admin_manual/pages/enterprise/firewall/file_firewall.adoc
  modules/admin_manual/pages/release_notes.adoc
  modules/developer_manual/pages/core/apis/ocs-capabilities.adoc
  modules/developer_manual/pages/core/apis/ocs-share-api.adoc
  modules/user_manual/pages/files/access_webdav.adoc
  modules/user_manual/pages/files/gallery_app.adoc
  modules/user_manual/pages/files/webgui/overview.adoc
  modules/user_manual/pages/files/webgui/quota.adoc
  modules/user_manual/pages/files/webgui/sharing.adoc
Labels: review required

#1519 [10.1] Backport #1468
  modules/admin_manual/pages/configuration/files/file_sharing_configuration.adoc
  modules/admin_manual/pages/configuration/user/user_configuration.adoc
  modules/admin_manual/pages/enterprise/firewall/file_firewall.adoc
  modules/admin_manual/pages/release_notes.adoc
  modules/developer_manual/pages/core/apis/ocs-capabilities.adoc
  modules/developer_manual/pages/core/apis/ocs-share-api.adoc
  modules/user_manual/pages/files/access_webdav.adoc
  modules/user_manual/pages/files/gallery_app.adoc
  modules/user_manual/pages/files/webgui/overview.adoc
  modules/user_manual/pages/files/webgui/quota.adoc
  modules/user_manual/pages/files/webgui/sharing.adoc
Labels: review required

#1520 [10.0] Backport #1468
  modules/admin_manual/pages/configuration/files/file_sharing_configuration.adoc
  modules/admin_manual/pages/configuration/user/user_configuration.adoc
  modules/admin_manual/pages/enterprise/firewall/file_firewall.adoc
  modules/admin_manual/pages/release_notes.adoc
  modules/developer_manual/pages/core/apis/ocs-capabilities.adoc
  modules/developer_manual/pages/core/apis/ocs-share-api.adoc
  modules/user_manual/pages/files/access_webdav.adoc
  modules/user_manual/pages/files/gallery_app.adoc
  modules/user_manual/pages/files/webgui/overview.adoc
  modules/user_manual/pages/files/webgui/quota.adoc
  modules/user_manual/pages/files/webgui/sharing.adoc
Labels: review required

#1534 Fix self-referencing page alias
  modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
Labels: bug

#1533 [10.0] [PR 1521] Third party apps in package installation
  modules/admin_manual/pages/maintenance/package_upgrade.adoc
Labels: backport

#1532 [10.1] [PR 1521] Third party apps in package installation
  modules/admin_manual/pages/maintenance/package_upgrade.adoc
Labels: backport

#1531 [10.2] [PR 1521] Third party apps in package installation
  modules/admin_manual/pages/maintenance/package_upgrade.adoc
Labels: backport

#1513 [10.2] [PR 1340] [968] - Document Secure View with Collabora Online
  modules/admin_manual/assets/images/enterprise/collaboration/access-denied.png
  modules/admin_manual/assets/images/enterprise/collaboration/access-exception.png
  modules/admin_manual/assets/images/enterprise/collaboration/collabora-online-administration.png
  modules/admin_manual/assets/images/enterprise/collaboration/configuration-options.png
  modules/admin_manual/assets/images/enterprise/collaboration/share-options.png
  modules/admin_manual/assets/images/enterprise/collaboration/sharer-view.png
  modules/admin_manual/nav.adoc
  modules/admin_manual/pages/enterprise/collaboration/collabora_online_integration.adoc
  modules/user_manual/assets/images/collaboration/secure-view/access-denied.png
  modules/user_manual/assets/images/collaboration/secure-view/secure-view-share-configuration-options.png
  modules/user_manual/assets/images/enterprise/collaboration/secure-view/access-denied.png
  modules/user_manual/assets/images/enterprise/collaboration/secure-view/collabora-online-administration.png
  modules/user_manual/assets/images/enterprise/collaboration/secure-view/secure-view-share-configuration-options.png
  modules/user_manual/nav.adoc
  modules/user_manual/pages/online_collaboration.adoc
Labels: backport

#1550 Fix miss newline
  modules/admin_manual/pages/maintenance/package_upgrade.adoc
Labels: Effort: trivial, admin docs, bug, good first issue, p4-low

#1552 [10.2] [PR 1550] Fix miss newline
  modules/admin_manual/pages/maintenance/package_upgrade.adoc
Labels: backport

#1553 [10.1] [PR 1550] Fix miss newline
  modules/admin_manual/pages/maintenance/package_upgrade.adoc
Labels: backport

#1554 [10.0] [PR 1550] Fix miss newline
  modules/admin_manual/pages/maintenance/package_upgrade.adoc
Labels: backport

#1557 [10.0] [PR 1539] add links to the documents inside
  modules/admin_manual/pages/enterprise/user_management/index.adoc
Labels: backport

#1555 [10.2] [PR 1539] add links to the documents inside
  modules/admin_manual/pages/enterprise/user_management/index.adoc
Labels: backport

#1556 [10.1] [PR 1539] add links to the documents inside
  modules/admin_manual/pages/enterprise/user_management/index.adoc
Labels: backport

#1588 Fix Docker install after repo changes
  modules/admin_manual/pages/installation/docker/index.adoc
Labels: admin docs, backport, installation & configuration, review required

#1558 Add a GitHub settings yaml file to the project
  .github/settings.yml
Labels: enhancement, review required
