Repository owncloud/docs, pull requests merged in 2019-10, with the labels that each got.

#1870 Minor grammatical and formatting revisions
  modules/admin_manual/pages/maintenance/encryption/migrating-from-user-key-to-master-key.adoc
Labels: admin docs, encryption, review required

#1874 Document the attributes field of the create-share API
  modules/developer_manual/examples/core/scripts/curl/create-share.sh
  modules/developer_manual/pages/core/apis/ocs-share-api.adoc
Labels: APIs, developer docs

#1880 Add the first draft of the notify public link by email api documentation
  modules/developer_manual/examples/core/scripts/curl/ocs/notify-public-link-by-email.sh
  modules/developer_manual/examples/core/scripts/php/notify-public-link-by-email.php
  modules/developer_manual/nav.adoc
  modules/developer_manual/pages/core/apis/ocs-notify-public-link-by-email.adoc
Labels: developer docs, enhancement, p2-high

#1890 Fix broken reference to partial in user manual
  modules/user_manual/pages/apps/index.adoc
Labels: Effort: trivial, bug, p4-low, user docs

#1873 Documentation of the Roles API
  modules/developer_manual/examples/core/apis/ocs/roles/responses/success.json
  modules/developer_manual/examples/core/apis/ocs/roles/responses/success.xml
  modules/developer_manual/nav.adoc
  modules/developer_manual/pages/core/apis/roles-api.adoc
Labels: APIs, developer docs, review required, technical review

#1793 Document oC 10.3 upgrade requirements for Amazon S3
  modules/admin_manual/pages/configuration/files/external_storage/amazons3.adoc
  site.yml
Labels: admin docs, enhancement, p3-medium, review required, waiting on feedback

#1881 Server 10.3 Release Notes
  modules/admin_manual/pages/release_notes.adoc
Labels: review required

#1794 Add current version attribute to 10.3
  site.yml
Labels: admin docs

#1745 Update playbook configuration for the 10.3 release
  site.yml
Labels: Effort: trivial, deployment, no backport, p3-medium, review required, technical review

#1729 Update version numbers for the 10.3 release
  modules/ROOT/pages/index.adoc
  modules/admin_manual/pages/configuration/server/activity_configuration.adoc
  site.yml
Labels: p3-medium, review required, waiting on feedback

#1879 Document the public-files WebDAV API endpoint
  modules/developer_manual/examples/core/scripts/curl/dav/public_files/view_public_link.sh
  modules/developer_manual/examples/core/scripts/php/dav/public_files/view_public_link.php
  modules/developer_manual/examples/core/webdav_api/public_files/response/listing-members-is-disabled.xml
  modules/developer_manual/examples/core/webdav_api/public_files/response/no-read-privileges-on-public-link.xml
  modules/developer_manual/examples/core/webdav_api/public_files/response/public-link-is-available.xml
  modules/developer_manual/nav.adoc
  modules/developer_manual/pages/webdav_api/public_files.adoc
Labels: APIs, developer docs, review required, technical review, waiting on feedback

#1877 [1869] Document how to configure federation behind a proxy
  modules/admin_manual/pages/configuration/files/federated_cloud_sharing_configuration.adoc
Labels: admin docs, review required, technical review

#1931 Fix several broken xrefs
  modules/admin_manual/pages/release_notes.adoc
  modules/user_manual/pages/_partials/files/not-encrypted-files.adoc
Labels: bug

#1938 Integrate go.php redirects directly into the docs
  modules/admin_manual/pages/configuration/database/db_conversion.adoc
  modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
  modules/admin_manual/pages/configuration/files/external_storage_configuration_gui.adoc
  modules/admin_manual/pages/configuration/files/federated_cloud_sharing_configuration.adoc
  modules/admin_manual/pages/configuration/files/file_sharing_configuration.adoc
  modules/admin_manual/pages/configuration/files/files_locking_transactional.adoc
  modules/admin_manual/pages/configuration/general_topics/general_troubleshooting.adoc
  modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc
  modules/admin_manual/pages/configuration/server/email_configuration.adoc
  modules/admin_manual/pages/configuration/server/harden_server.adoc
  modules/admin_manual/pages/configuration/server/oc_server_tuning.adoc
  modules/admin_manual/pages/configuration/server/occ_command.adoc
  modules/admin_manual/pages/configuration/server/reverse_proxy_configuration.adoc
  modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
  modules/admin_manual/pages/configuration/user/user_provisioning_api.adoc
  modules/admin_manual/pages/enterprise/installation/install.adoc
  modules/admin_manual/pages/installation/configuration_notes_and_tips.adoc
  modules/admin_manual/pages/installation/index.adoc
  modules/admin_manual/pages/installation/installation_wizard.adoc
  modules/admin_manual/pages/maintenance/backup.adoc
  modules/admin_manual/pages/maintenance/migrating.adoc
  modules/admin_manual/pages/maintenance/upgrading/marketplace_apps.adoc
  modules/developer_manual/pages/app/advanced/code_signing.adoc
  modules/developer_manual/pages/core/theming.adoc
  modules/user_manual/pages/files/access_webdav.adoc
  modules/user_manual/pages/files/deleted_file_management.adoc
  modules/user_manual/pages/files/encrypting_files.adoc
  modules/user_manual/pages/files/federated_cloud_sharing.adoc
  modules/user_manual/pages/files/index.adoc
  modules/user_manual/pages/files/version_control.adoc
  modules/user_manual/pages/index.adoc
  modules/user_manual/pages/pim/calendar.adoc
  modules/user_manual/pages/pim/contacts.adoc
Labels: enhancement, p3-medium

#1939 [10.3] [PR 1938] Integrate go.php redirects directly into the docs
  modules/admin_manual/pages/configuration/database/db_conversion.adoc
  modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
  modules/admin_manual/pages/configuration/files/external_storage_configuration_gui.adoc
  modules/admin_manual/pages/configuration/files/federated_cloud_sharing_configuration.adoc
  modules/admin_manual/pages/configuration/files/file_sharing_configuration.adoc
  modules/admin_manual/pages/configuration/files/files_locking_transactional.adoc
  modules/admin_manual/pages/configuration/general_topics/general_troubleshooting.adoc
  modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc
  modules/admin_manual/pages/configuration/server/email_configuration.adoc
  modules/admin_manual/pages/configuration/server/harden_server.adoc
  modules/admin_manual/pages/configuration/server/oc_server_tuning.adoc
  modules/admin_manual/pages/configuration/server/occ_command.adoc
  modules/admin_manual/pages/configuration/server/reverse_proxy_configuration.adoc
  modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
  modules/admin_manual/pages/configuration/user/user_provisioning_api.adoc
  modules/admin_manual/pages/enterprise/installation/install.adoc
  modules/admin_manual/pages/installation/configuration_notes_and_tips.adoc
  modules/admin_manual/pages/installation/index.adoc
  modules/admin_manual/pages/installation/installation_wizard.adoc
  modules/admin_manual/pages/maintenance/backup.adoc
  modules/admin_manual/pages/maintenance/migrating.adoc
  modules/admin_manual/pages/maintenance/upgrading/marketplace_apps.adoc
  modules/developer_manual/pages/app/advanced/code_signing.adoc
  modules/developer_manual/pages/core/theming.adoc
  modules/user_manual/pages/files/access_webdav.adoc
  modules/user_manual/pages/files/deleted_file_management.adoc
  modules/user_manual/pages/files/encrypting_files.adoc
  modules/user_manual/pages/files/federated_cloud_sharing.adoc
  modules/user_manual/pages/files/index.adoc
  modules/user_manual/pages/files/version_control.adoc
  modules/user_manual/pages/index.adoc
  modules/user_manual/pages/pim/calendar.adoc
  modules/user_manual/pages/pim/contacts.adoc
Labels: waiting on feedback

#1940 [10.2] [PR 1938] Integrate go.php redirects directly into the docs
  modules/admin_manual/pages/configuration/database/db_conversion.adoc
  modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
  modules/admin_manual/pages/configuration/files/external_storage_configuration_gui.adoc
  modules/admin_manual/pages/configuration/files/federated_cloud_sharing_configuration.adoc
  modules/admin_manual/pages/configuration/files/file_sharing_configuration.adoc
  modules/admin_manual/pages/configuration/files/files_locking_transactional.adoc
  modules/admin_manual/pages/configuration/general_topics/general_troubleshooting.adoc
  modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc
  modules/admin_manual/pages/configuration/server/email_configuration.adoc
  modules/admin_manual/pages/configuration/server/harden_server.adoc
  modules/admin_manual/pages/configuration/server/oc_server_tuning.adoc
  modules/admin_manual/pages/configuration/server/occ_command.adoc
  modules/admin_manual/pages/configuration/server/reverse_proxy_configuration.adoc
  modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
  modules/admin_manual/pages/configuration/user/user_provisioning_api.adoc
  modules/admin_manual/pages/enterprise/installation/install.adoc
  modules/admin_manual/pages/installation/configuration_notes_and_tips.adoc
  modules/admin_manual/pages/installation/index.adoc
  modules/admin_manual/pages/installation/installation_wizard.adoc
  modules/admin_manual/pages/maintenance/backup.adoc
  modules/admin_manual/pages/maintenance/migrating.adoc
  modules/admin_manual/pages/maintenance/upgrading/marketplace_apps.adoc
  modules/developer_manual/pages/app/advanced/code_signing.adoc
  modules/developer_manual/pages/core/theming.adoc
  modules/user_manual/pages/files/access_webdav.adoc
  modules/user_manual/pages/files/deleted_file_management.adoc
  modules/user_manual/pages/files/encrypting_files.adoc
  modules/user_manual/pages/files/federated_cloud_sharing.adoc
  modules/user_manual/pages/files/index.adoc
  modules/user_manual/pages/files/version_control.adoc
  modules/user_manual/pages/index.adoc
  modules/user_manual/pages/pim/calendar.adoc
  modules/user_manual/pages/pim/contacts.adoc
Labels: waiting on feedback

#1941 [10.1] [PR 1938] Integrate go.php redirects directly into the docs
  modules/admin_manual/pages/configuration/database/db_conversion.adoc
  modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
  modules/admin_manual/pages/configuration/files/external_storage_configuration_gui.adoc
  modules/admin_manual/pages/configuration/files/federated_cloud_sharing_configuration.adoc
  modules/admin_manual/pages/configuration/files/file_sharing_configuration.adoc
  modules/admin_manual/pages/configuration/files/files_locking_transactional.adoc
  modules/admin_manual/pages/configuration/general_topics/general_troubleshooting.adoc
  modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc
  modules/admin_manual/pages/configuration/server/email_configuration.adoc
  modules/admin_manual/pages/configuration/server/harden_server.adoc
  modules/admin_manual/pages/configuration/server/oc_server_tuning.adoc
  modules/admin_manual/pages/configuration/server/occ_command.adoc
  modules/admin_manual/pages/configuration/server/reverse_proxy_configuration.adoc
  modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
  modules/admin_manual/pages/configuration/user/user_provisioning_api.adoc
  modules/admin_manual/pages/enterprise/installation/install.adoc
  modules/admin_manual/pages/installation/configuration_notes_and_tips.adoc
  modules/admin_manual/pages/installation/index.adoc
  modules/admin_manual/pages/installation/installation_wizard.adoc
  modules/admin_manual/pages/maintenance/backup.adoc
  modules/admin_manual/pages/maintenance/migrating.adoc
  modules/admin_manual/pages/maintenance/upgrading/marketplace_apps.adoc
  modules/developer_manual/pages/app/advanced/code_signing.adoc
  modules/developer_manual/pages/core/theming.adoc
  modules/user_manual/pages/files/access_webdav.adoc
  modules/user_manual/pages/files/deleted_file_management.adoc
  modules/user_manual/pages/files/encrypting_files.adoc
  modules/user_manual/pages/files/federated_cloud_sharing.adoc
  modules/user_manual/pages/files/index.adoc
  modules/user_manual/pages/files/version_control.adoc
  modules/user_manual/pages/index.adoc
  modules/user_manual/pages/pim/calendar.adoc
  modules/user_manual/pages/pim/contacts.adoc
Labels: waiting on feedback

#1951 Remove the build-artifacts build step
  .drone.yml
Labels: clean up, deployment, review required

#1957 Update activity_configuration.adoc
  modules/admin_manual/pages/configuration/server/activity_configuration.adoc
Labels: admin docs, backport

#1956 Document the user personal settings
  modules/user_manual/assets/images/personal-settings/external-storage.png
  modules/user_manual/assets/images/personal-settings/general.png
  modules/user_manual/assets/images/personal-settings/general/auto-save-fullname.png
  modules/user_manual/assets/images/personal-settings/general/cannot-change-fullname.png
  modules/user_manual/assets/images/personal-settings/general/choose-profile-picture-button.png
  modules/user_manual/assets/images/personal-settings/general/general.png
  modules/user_manual/assets/images/personal-settings/general/other.png
  modules/user_manual/assets/images/personal-settings/general/profile-picture-overview-annotated.png
  modules/user_manual/assets/images/personal-settings/general/profile-picture-overview.png
  modules/user_manual/assets/images/personal-settings/general/remove-profile-picture-button.png
  modules/user_manual/assets/images/personal-settings/general/select-profile-picture.png
  modules/user_manual/assets/images/personal-settings/general/set-profile-picture.png
  modules/user_manual/assets/images/personal-settings/general/update-email-successfully.png
  modules/user_manual/assets/images/personal-settings/general/update-language.png
  modules/user_manual/assets/images/personal-settings/general/update-password.png
  modules/user_manual/assets/images/personal-settings/general/upload-profile-picture.png
  modules/user_manual/assets/images/personal-settings/personal-settings-menu.png
  modules/user_manual/assets/images/personal-settings/security.png
  modules/user_manual/assets/images/personal-settings/security/app-password-tokens-section.png
  modules/user_manual/assets/images/personal-settings/security/confirm-cors-white-listed-domain-removal.png
  modules/user_manual/assets/images/personal-settings/security/cors-section-with-white-listed-domains.png
  modules/user_manual/assets/images/personal-settings/security/cors-section.png
  modules/user_manual/assets/images/personal-settings/security/create-new-app-password-token.png
  modules/user_manual/assets/images/personal-settings/security/disconnect-button.png
  modules/user_manual/assets/images/personal-settings/security/sessions-section.png
  modules/user_manual/assets/images/personal-settings/sharing.png
  modules/user_manual/nav.adoc
  modules/user_manual/pages/personal_settings/general.adoc
  modules/user_manual/pages/personal_settings/index.adoc
  modules/user_manual/pages/personal_settings/security.adoc
  modules/user_manual/pages/personal_settings/sharing.adoc
  modules/user_manual/pages/personal_settings/storage.adoc
  modules/user_manual/pages/userpreferences.adoc
Labels: user docs

#1962 Redis Session Locking
  modules/admin_manual/pages/configuration/server/caching_configuration.adoc
Labels: admin docs, installation & configuration, p3-medium

#1963 Document php-cs-fixer in the developer documentation
  modules/developer_manual/nav.adoc
  modules/developer_manual/pages/core/code-standard.adoc
Labels: Effort: 0.25d, developer docs, p3-medium, review required, waiting on feedback

#1967 [10.3] [PR 1963] Document php-cs-fixer in the developer documentation
  modules/developer_manual/nav.adoc
  modules/developer_manual/pages/core/code-standard.adoc
Labels: backport

#1968 [10.2] [PR 1963] Document php-cs-fixer in the developer documentation
  modules/developer_manual/nav.adoc
  modules/developer_manual/pages/core/code-standard.adoc
Labels: backport

#1964 [10.3] [PR 1956] Document the user personal settings
  modules/user_manual/assets/images/personal-settings/external-storage.png
  modules/user_manual/assets/images/personal-settings/general.png
  modules/user_manual/assets/images/personal-settings/general/auto-save-fullname.png
  modules/user_manual/assets/images/personal-settings/general/cannot-change-fullname.png
  modules/user_manual/assets/images/personal-settings/general/choose-profile-picture-button.png
  modules/user_manual/assets/images/personal-settings/general/general.png
  modules/user_manual/assets/images/personal-settings/general/other.png
  modules/user_manual/assets/images/personal-settings/general/profile-picture-overview-annotated.png
  modules/user_manual/assets/images/personal-settings/general/profile-picture-overview.png
  modules/user_manual/assets/images/personal-settings/general/remove-profile-picture-button.png
  modules/user_manual/assets/images/personal-settings/general/select-profile-picture.png
  modules/user_manual/assets/images/personal-settings/general/set-profile-picture.png
  modules/user_manual/assets/images/personal-settings/general/update-email-successfully.png
  modules/user_manual/assets/images/personal-settings/general/update-language.png
  modules/user_manual/assets/images/personal-settings/general/update-password.png
  modules/user_manual/assets/images/personal-settings/general/upload-profile-picture.png
  modules/user_manual/assets/images/personal-settings/personal-settings-menu.png
  modules/user_manual/assets/images/personal-settings/security.png
  modules/user_manual/assets/images/personal-settings/security/app-password-tokens-section.png
  modules/user_manual/assets/images/personal-settings/security/confirm-cors-white-listed-domain-removal.png
  modules/user_manual/assets/images/personal-settings/security/cors-section-with-white-listed-domains.png
  modules/user_manual/assets/images/personal-settings/security/cors-section.png
  modules/user_manual/assets/images/personal-settings/security/create-new-app-password-token.png
  modules/user_manual/assets/images/personal-settings/security/disconnect-button.png
  modules/user_manual/assets/images/personal-settings/security/sessions-section.png
  modules/user_manual/assets/images/personal-settings/sharing.png
  modules/user_manual/nav.adoc
  modules/user_manual/pages/personal_settings/general.adoc
  modules/user_manual/pages/personal_settings/index.adoc
  modules/user_manual/pages/personal_settings/security.adoc
  modules/user_manual/pages/personal_settings/sharing.adoc
  modules/user_manual/pages/personal_settings/storage.adoc
  modules/user_manual/pages/userpreferences.adoc
Labels: backport

#1969 [10.1] [PR 1963] Document php-cs-fixer in the developer documentation
  modules/developer_manual/nav.adoc
  modules/developer_manual/pages/core/code-standard.adoc
Labels: backport

#1976 php_codesniffer code style documentation
  modules/developer_manual/pages/core/code-standard.adoc
Labels: backport

#1965 [10.2] [PR 1956] Document the user personal settings
  modules/user_manual/assets/images/personal-settings/external-storage.png
  modules/user_manual/assets/images/personal-settings/general.png
  modules/user_manual/assets/images/personal-settings/general/auto-save-fullname.png
  modules/user_manual/assets/images/personal-settings/general/cannot-change-fullname.png
  modules/user_manual/assets/images/personal-settings/general/choose-profile-picture-button.png
  modules/user_manual/assets/images/personal-settings/general/general.png
  modules/user_manual/assets/images/personal-settings/general/other.png
  modules/user_manual/assets/images/personal-settings/general/profile-picture-overview-annotated.png
  modules/user_manual/assets/images/personal-settings/general/profile-picture-overview.png
  modules/user_manual/assets/images/personal-settings/general/remove-profile-picture-button.png
  modules/user_manual/assets/images/personal-settings/general/select-profile-picture.png
  modules/user_manual/assets/images/personal-settings/general/set-profile-picture.png
  modules/user_manual/assets/images/personal-settings/general/update-email-successfully.png
  modules/user_manual/assets/images/personal-settings/general/update-language.png
  modules/user_manual/assets/images/personal-settings/general/update-password.png
  modules/user_manual/assets/images/personal-settings/general/upload-profile-picture.png
  modules/user_manual/assets/images/personal-settings/personal-settings-menu.png
  modules/user_manual/assets/images/personal-settings/security.png
  modules/user_manual/assets/images/personal-settings/security/app-password-tokens-section.png
  modules/user_manual/assets/images/personal-settings/security/confirm-cors-white-listed-domain-removal.png
  modules/user_manual/assets/images/personal-settings/security/cors-section-with-white-listed-domains.png
  modules/user_manual/assets/images/personal-settings/security/cors-section.png
  modules/user_manual/assets/images/personal-settings/security/create-new-app-password-token.png
  modules/user_manual/assets/images/personal-settings/security/disconnect-button.png
  modules/user_manual/assets/images/personal-settings/security/sessions-section.png
  modules/user_manual/assets/images/personal-settings/sharing.png
  modules/user_manual/nav.adoc
  modules/user_manual/pages/personal_settings/general.adoc
  modules/user_manual/pages/personal_settings/index.adoc
  modules/user_manual/pages/personal_settings/security.adoc
  modules/user_manual/pages/personal_settings/sharing.adoc
  modules/user_manual/pages/personal_settings/storage.adoc
  modules/user_manual/pages/userpreferences.adoc
Labels: backport

#1975 [10.1] [PR 1970] Uploaded appliance setup screen shots
  modules/admin_manual/assets/images/appliance/setup/1.png
  modules/admin_manual/assets/images/appliance/setup/10.png
  modules/admin_manual/assets/images/appliance/setup/11.png
  modules/admin_manual/assets/images/appliance/setup/12.png
  modules/admin_manual/assets/images/appliance/setup/13.png
  modules/admin_manual/assets/images/appliance/setup/15.png
  modules/admin_manual/assets/images/appliance/setup/2.png
  modules/admin_manual/assets/images/appliance/setup/3.png
  modules/admin_manual/assets/images/appliance/setup/4.png
  modules/admin_manual/assets/images/appliance/setup/5.png
  modules/admin_manual/assets/images/appliance/setup/6.png
  modules/admin_manual/assets/images/appliance/setup/7.png
  modules/admin_manual/assets/images/appliance/setup/9.png
Labels: backport

#1974 [10.2] [PR 1970] Uploaded appliance setup screen shots
  modules/admin_manual/assets/images/appliance/setup/1.png
  modules/admin_manual/assets/images/appliance/setup/10.png
  modules/admin_manual/assets/images/appliance/setup/11.png
  modules/admin_manual/assets/images/appliance/setup/12.png
  modules/admin_manual/assets/images/appliance/setup/13.png
  modules/admin_manual/assets/images/appliance/setup/15.png
  modules/admin_manual/assets/images/appliance/setup/2.png
  modules/admin_manual/assets/images/appliance/setup/3.png
  modules/admin_manual/assets/images/appliance/setup/4.png
  modules/admin_manual/assets/images/appliance/setup/5.png
  modules/admin_manual/assets/images/appliance/setup/6.png
  modules/admin_manual/assets/images/appliance/setup/7.png
  modules/admin_manual/assets/images/appliance/setup/9.png
Labels: backport

#1973 [10.3] [PR 1970] Uploaded appliance setup screen shots
  modules/admin_manual/assets/images/appliance/setup/1.png
  modules/admin_manual/assets/images/appliance/setup/10.png
  modules/admin_manual/assets/images/appliance/setup/11.png
  modules/admin_manual/assets/images/appliance/setup/12.png
  modules/admin_manual/assets/images/appliance/setup/13.png
  modules/admin_manual/assets/images/appliance/setup/15.png
  modules/admin_manual/assets/images/appliance/setup/2.png
  modules/admin_manual/assets/images/appliance/setup/3.png
  modules/admin_manual/assets/images/appliance/setup/4.png
  modules/admin_manual/assets/images/appliance/setup/5.png
  modules/admin_manual/assets/images/appliance/setup/6.png
  modules/admin_manual/assets/images/appliance/setup/7.png
  modules/admin_manual/assets/images/appliance/setup/9.png
Labels: backport

#1234 Document the system:cron command
  modules/admin_manual/pages/_partials/configuration/server/occ_command/system_command.adoc
  modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc
  modules/admin_manual/pages/configuration/server/occ_command.adoc
Labels: admin docs, enhancement, occ, review required, technical review

#1977 Backport systemcron docs to master
  modules/admin_manual/pages/_partials/configuration/server/occ_command/system_command.adoc
  modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc
  modules/admin_manual/pages/configuration/server/occ_command.adoc
Labels: admin docs, backport

#1966 [10.1] [PR 1956] Document the user personal settings
  modules/user_manual/assets/images/personal-settings/external-storage.png
  modules/user_manual/assets/images/personal-settings/general.png
  modules/user_manual/assets/images/personal-settings/general/auto-save-fullname.png
  modules/user_manual/assets/images/personal-settings/general/cannot-change-fullname.png
  modules/user_manual/assets/images/personal-settings/general/choose-profile-picture-button.png
  modules/user_manual/assets/images/personal-settings/general/general.png
  modules/user_manual/assets/images/personal-settings/general/other.png
  modules/user_manual/assets/images/personal-settings/general/profile-picture-overview-annotated.png
  modules/user_manual/assets/images/personal-settings/general/profile-picture-overview.png
  modules/user_manual/assets/images/personal-settings/general/remove-profile-picture-button.png
  modules/user_manual/assets/images/personal-settings/general/select-profile-picture.png
  modules/user_manual/assets/images/personal-settings/general/set-profile-picture.png
  modules/user_manual/assets/images/personal-settings/general/update-email-successfully.png
  modules/user_manual/assets/images/personal-settings/general/update-language.png
  modules/user_manual/assets/images/personal-settings/general/update-password.png
  modules/user_manual/assets/images/personal-settings/general/upload-profile-picture.png
  modules/user_manual/assets/images/personal-settings/personal-settings-menu.png
  modules/user_manual/assets/images/personal-settings/security.png
  modules/user_manual/assets/images/personal-settings/security/app-password-tokens-section.png
  modules/user_manual/assets/images/personal-settings/security/confirm-cors-white-listed-domain-removal.png
  modules/user_manual/assets/images/personal-settings/security/cors-section-with-white-listed-domains.png
  modules/user_manual/assets/images/personal-settings/security/cors-section.png
  modules/user_manual/assets/images/personal-settings/security/create-new-app-password-token.png
  modules/user_manual/assets/images/personal-settings/security/disconnect-button.png
  modules/user_manual/assets/images/personal-settings/security/sessions-section.png
  modules/user_manual/assets/images/personal-settings/sharing.png
  modules/user_manual/nav.adoc
  modules/user_manual/pages/personal_settings/general.adoc
  modules/user_manual/pages/personal_settings/index.adoc
  modules/user_manual/pages/personal_settings/security.adoc
  modules/user_manual/pages/personal_settings/sharing.adoc
  modules/user_manual/pages/personal_settings/storage.adoc
  modules/user_manual/pages/userpreferences.adoc
Labels: backport

#1978 Fix little typo in conditions option
  modules/admin_manual/pages/configuration/server/logging/logging_configuration.adoc
Labels: Effort: trivial, admin docs, bug

#1979 Updated config sample parameters file from core (10.3)
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Labels: admin docs, enhancement, installation & configuration

#1980 [10.2] [PR 1978] Fix little typo in conditions option
  modules/admin_manual/pages/configuration/server/logging/logging_configuration.adoc
Labels: admin docs, backport

#1981 [10.3] [PR 1978] Fix little typo in conditions option
  modules/admin_manual/pages/configuration/server/logging/logging_configuration.adoc
Labels: admin docs, backport

#1982 [10.1] [PR 1978] Fix little typo in conditions option
  modules/admin_manual/pages/configuration/server/logging/logging_configuration.adoc
Labels: admin docs, backport

#1985 Updated config sample files from updated core
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Labels: admin docs, waiting on PR merge

#1986 [10.3] [PR 1985] Updated config sample files from updated core
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Labels: backport

#1990 Reference filtering and other search options in endpoint docs
  modules/developer_manual/examples/core/webdav_api/search/request/search_files/filter_results.xml
  modules/developer_manual/examples/core/webdav_api/search/request/search_files/limit_number_of_results.xml
  modules/developer_manual/pages/webdav_api/search/search_files.adoc
Labels: developer docs, waiting on feedback

#1994 [10.3] [PR 1987] updated the docs
  modules/admin_manual/pages/enterprise/installation/install.adoc
  modules/admin_manual/pages/maintenance/upgrade.adoc
Labels: backport

#1992 [10.2] [PR 1990] Reference filtering and other search options in endpoint docs
  modules/developer_manual/examples/core/webdav_api/search/request/search_files/filter_results.xml
  modules/developer_manual/examples/core/webdav_api/search/request/search_files/limit_number_of_results.xml
  modules/developer_manual/pages/webdav_api/search/search_files.adoc
Labels: backport

#1993 [10.1] [PR 1990] Reference filtering and other search options in endpoint docs
  modules/developer_manual/examples/core/webdav_api/search/request/search_files/filter_results.xml
  modules/developer_manual/examples/core/webdav_api/search/request/search_files/limit_number_of_results.xml
  modules/developer_manual/pages/webdav_api/search/search_files.adoc
Labels: backport

#1988 Appliance setup rework
  modules/admin_manual/pages/appliance/installation/installation.adoc
Labels: appliance docs

#2000 [10.3] [PR 1988] Appliance setup rework
  modules/admin_manual/pages/appliance/installation/installation.adoc
Labels: backport

#2001 [10.2] [PR 1988] Appliance setup rework
  modules/admin_manual/pages/appliance/installation/installation.adoc
Labels: backport

#2002 [10.1] [PR 1988] Appliance setup rework
  modules/admin_manual/pages/appliance/installation/installation.adoc
Labels: backport

#1998 Remove references to php -f for occ command
  modules/admin_manual/pages/_partials/configuration/server/occ_command/system_command.adoc
  modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc
  modules/admin_manual/pages/release_notes.adoc
  site.yml
Labels: admin docs, clean up, p4-low, review required, technical review

#2004 [10.3] [PR 1998] Remove references to php -f for occ command
  modules/admin_manual/pages/_partials/configuration/server/occ_command/system_command.adoc
  modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc
  modules/admin_manual/pages/release_notes.adoc
  site.yml
Labels: backport

#1997 [10.1] [PR 1995] Add missing cron job
  modules/admin_manual/pages/installation/ubuntu_18_04.adoc
Labels: backport

#1996 [10.2] [PR 1995] Add missing cron job
  modules/admin_manual/pages/installation/ubuntu_18_04.adoc
Labels: backport

#1983 Document the --progress/-p options for system:cron
  modules/admin_manual/pages/_partials/configuration/server/occ_command/system_command.adoc
Labels: Effort: 0.25d, admin docs, command-line, occ, p3-medium, review required, technical review

#2005 [10.3] [PR 1983] Document the --progress/-p options for system:cron
  modules/admin_manual/pages/_partials/configuration/server/occ_command/system_command.adoc
Labels: backport

#2006 removed the index.html
  modules/admin_manual/pages/installation/linux_installation.adoc
Labels: admin docs, installation & configuration

#2011 Refine wording in API documentation
  modules/admin_manual/pages/configuration/user/user_provisioning_api.adoc
Labels: APIs, clean up, work in progress

#2012 [10.3] [PR 2011] Refine wording in API documentation
  modules/admin_manual/pages/configuration/user/user_provisioning_api.adoc
Labels: backport

#2013 [10.2] [PR 2011] Refine wording in API documentation
  modules/admin_manual/pages/configuration/user/user_provisioning_api.adoc
Labels: backport

#2008 Update the supported PHP versions to include PHP 7.3
  modules/admin_manual/pages/installation/system_requirements.adoc
  site.yml
Labels: Effort: trivial, clean up, installation & configuration, p2-high, review required

#2015 [10.3] [PR 2008] Update the supported PHP versions to include PHP 7.3
  modules/admin_manual/pages/installation/system_requirements.adoc
  site.yml
Labels: backport

#1945 Escape reference to antora-like attribute in PHP script
  modules/developer_manual/examples/core/scripts/php/dav/public_files/view_public_link.php
Labels: review required, waiting on feedback

#1675 Update file_sharing_configuration.adoc
  modules/admin_manual/pages/configuration/files/file_sharing_configuration.adoc
Labels: admin docs, clean up, waiting on feedback

#2016 [10.3] [PR 1945] Escape reference to antora-like attribute in PHP script
  modules/developer_manual/examples/core/scripts/php/dav/public_files/view_public_link.php
Labels: backport

#2018 Cleanup Exclude groups from sharing text
  modules/admin_manual/pages/configuration/files/file_sharing_configuration.adoc
Labels: review required
