Repository owncloud/docs, pull requests merged in 2019-09, with the labels that each got.

#1728 Add missing partial referenced in maintenance upgrade docs
  modules/admin_manual/pages/_partials/maintenance/major_release_note.adoc
Labels: Effort: trivial, bug, p4-low, review required

#1727 Update JavaScript dependencies
  yarn.lock
Labels: p3-medium, review required, security

#1658 Consolidate admin manual's logging documentation
  modules/admin_manual/nav.adoc
  modules/admin_manual/pages/configuration/server/logging/logging_configuration.adoc
  modules/admin_manual/pages/configuration/server/logging/providing_logs_and_config_files.adoc
  modules/admin_manual/pages/configuration/server/logging/request_tracing.adoc
Labels: Effort: trivial, admin docs, clean up, installation & configuration, logging, p4-low, review required, technical review, waiting on feedback

#1744 Fix component descriptor name
  antora.yml
  modules/ROOT/pages/index.adoc
Labels: Effort: trivial, bug, deployment, p3-medium, review required, technical review

#1748 [10.1] [PR 1658] Consolidate admin manual's logging documentation
  modules/admin_manual/nav.adoc
  modules/admin_manual/pages/configuration/server/logging/logging_configuration.adoc
  modules/admin_manual/pages/configuration/server/logging/providing_logs_and_config_files.adoc
  modules/admin_manual/pages/configuration/server/logging/request_tracing.adoc
Labels: backport

#1747 [10.2] [PR 1658] Consolidate admin manual's logging documentation
  modules/admin_manual/nav.adoc
  modules/admin_manual/pages/configuration/server/logging/logging_configuration.adoc
  modules/admin_manual/pages/configuration/server/logging/providing_logs_and_config_files.adoc
  modules/admin_manual/pages/configuration/server/logging/request_tracing.adoc
Labels: backport

#1746 [10.3] [PR 1658] Consolidate admin manual's logging documentation
  modules/admin_manual/nav.adoc
  modules/admin_manual/pages/configuration/general_topics/general_troubleshooting.adoc
  modules/admin_manual/pages/configuration/server/logging/logging_configuration.adoc
  modules/admin_manual/pages/configuration/server/logging/providing_logs_and_config_files.adoc
  modules/admin_manual/pages/configuration/server/logging/request_tracing.adoc
  modules/admin_manual/pages/enterprise/logging/enterprise_logging_apps.adoc
  modules/developer_manual/pages/app/fundamentals/logging.adoc
Labels: backport

#1768 fix_missing_deprecs2.png
  modules/admin_manual/assets/images/installation/deprecs-2.png
Labels: admin docs, backport, bug

#1774 fix_missing_section_page.adoc_in_user_manual
  modules/user_manual/pages/_partials/section_page.adoc
Labels: backport, bug, user docs

#1754 Fix build errors
  modules/admin_manual/pages/configuration/files/encryption/encryption_configuration_quick_guide.adoc
  modules/admin_manual/pages/configuration/files/encryption/index.adoc
  modules/admin_manual/pages/configuration/server/occ_command.adoc
  modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
  modules/admin_manual/pages/installation/installation_wizard.adoc
  modules/admin_manual/pages/installation/ubuntu_18_04.adoc
  modules/developer_manual/examples/core/apis/ocs/totp-validation/responses/xml/totp-user-is-not-found.xml
  modules/developer_manual/pages/_partials/webdav_api/core_curl_request.adoc
  modules/developer_manual/pages/core/apis/ocs-share-api.adoc
  modules/developer_manual/pages/core/apis/ocs-totp-validation-api.adoc
  modules/developer_manual/pages/webdav_api/groups/custom_groups_endpoints.adoc
  modules/developer_manual/pages/webdav_api/groups/group_membership_endpoints.adoc
  modules/developer_manual/pages/webdav_api/tags.adoc
  modules/developer_manual/pages/webdav_api/trashbin.adoc
Labels: bug, deployment, review required

#1772 Update JavaScript Dependencies
  yarn.lock
Labels: dependencies, review required, technical review

#1674 Document recommendations for using NFS storage
  modules/admin_manual/nav.adoc
  modules/admin_manual/pages/installation/deployment_recommendations.adoc
  modules/admin_manual/pages/installation/deployment_recommendations/nfs.adoc
Labels: admin docs, enhancement, installation & configuration, p3-medium

#1796 Add missing font files for generating PDFs
  fonts/mplus-1mn-bold.ttf
  fonts/mplus-1mn-medium.ttf
  fonts/mplus-1mn-regular.ttf
  fonts/mplus-1mn-thin.ttf
  fonts/mplus-1p-regular.ttf
  resources/themes/owncloud-theme.yml
Labels: bug, pdf generation, review required

#1604 Add script to check for orphaned example files
  bin/find-orphaned-files.sh
Labels: admin docs, backport, developer docs, enhancement, p4-low, review required, technical review, user docs

#1801 Remove outdated drone clone plugin
  .drone.yml
Labels: bug, deployment, review required, technical review

#1800 [10.0] [PR 1674] Document recommendations for using NFS storage
  modules/admin_manual/nav.adoc
  modules/admin_manual/pages/installation/deployment_recommendations.adoc
  modules/admin_manual/pages/installation/deployment_recommendations/nfs.adoc
Labels: backport

#1799 [10.1] [PR 1674] Document recommendations for using NFS storage
  modules/admin_manual/nav.adoc
  modules/admin_manual/pages/installation/deployment_recommendations.adoc
  modules/admin_manual/pages/installation/deployment_recommendations/nfs.adoc
Labels: backport

#1798 [10.3] [PR 1674] Document recommendations for using NFS storage
  modules/admin_manual/nav.adoc
  modules/admin_manual/pages/installation/deployment_recommendations.adoc
  modules/admin_manual/pages/installation/deployment_recommendations/nfs.adoc
Labels: backport

#1797 [10.2] [PR 1674] Document recommendations for using NFS storage
  modules/admin_manual/nav.adoc
  modules/admin_manual/pages/installation/deployment_recommendations.adoc
  modules/admin_manual/pages/installation/deployment_recommendations/nfs.adoc
Labels: backport

#1607 Remove references to the Gallery app
  modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
  modules/admin_manual/pages/configuration/files/encryption/index.adoc
  modules/admin_manual/pages/configuration/files/previews_configuration.adoc
  modules/admin_manual/pages/configuration/server/logging/logging_configuration.adoc
  modules/admin_manual/pages/configuration/server/occ_command.adoc
  modules/admin_manual/pages/enterprise/external_storage/s3_swift_as_primary_object_store_configuration.adoc
  modules/admin_manual/pages/installation/apps_supported.adoc
  modules/developer_manual/pages/core/translation.adoc
  modules/user_manual/pages/files/encrypting_files.adoc
  modules/user_manual/pages/files/gallery_app.adoc
  modules/user_manual/pages/webinterface.adoc
Labels: clean up, deprecation, p3-medium, review required, technical review, waiting on feedback

#1819 Left align PDF content
  resources/themes/owncloud-theme.yml
Labels: pdf generation, review required, waiting on feedback

#1820 Add page to encourage users to report documentation mistakes
  modules/admin_manual/nav.adoc
  modules/admin_manual/pages/found_a_mistake.adoc
  modules/developer_manual/nav.adoc
  modules/developer_manual/pages/found_a_mistake.adoc
  modules/user_manual/nav.adoc
  modules/user_manual/pages/found_a_mistake.adoc
Labels: admin docs, developer docs, enhancement, review required, user docs, waiting on feedback

#1818 680 - Fix Small User Manual Issues
  modules/user_manual/assets/images/files/access_webdav/dolphin-add-network-folder.png
  modules/user_manual/assets/images/files/access_webdav/dolphin-network-folder-wizard.png
  modules/user_manual/assets/images/files/activity-pane.png
  modules/user_manual/pages/files/access_webdav.adoc
  modules/user_manual/pages/files/encrypting_files.adoc
  modules/user_manual/pages/files/federated_cloud_sharing.adoc
  modules/user_manual/pages/files/webgui/activity.adoc
  modules/user_manual/pages/files/webgui/details.adoc
  modules/user_manual/pages/files/webgui/navigating.adoc
  modules/user_manual/pages/files/webgui/overview.adoc
  modules/user_manual/pages/files/webgui/sharing.adoc
  modules/user_manual/pages/index.adoc
  modules/user_manual/pages/pim/sync_thunderbird.adoc
  modules/user_manual/pages/webinterface.adoc
Labels: review required, user docs, waiting on feedback

#1700 Document admin aspect of installing the Media Viewer app
  modules/admin_manual/nav.adoc
  modules/admin_manual/pages/installation/apps/index.adoc
  modules/admin_manual/pages/installation/apps/mediaviewer/index.adoc
  modules/admin_manual/pages/installation/apps_supported.adoc
Labels: admin docs, enhancement, installation & configuration, p3-medium, review required, waiting on feedback

#1856 Document The New Trash bin WebDAV API in 10.3 (#1400)
  modules/developer_manual/examples/core/scripts/curl/dav/trashbin_api/delete-file-from-trashbin.sh
  modules/developer_manual/examples/core/scripts/curl/dav/trashbin_api/list-files-in-trashbin.sh
  modules/developer_manual/examples/core/scripts/curl/dav/trashbin_api/restore-file-to-trashbin.sh
  modules/developer_manual/examples/core/webdav_api/trashbin/list-files-in-trashbin-success-response.xml
  modules/developer_manual/nav.adoc
  modules/developer_manual/pages/webdav_api/trashbin.adoc
Labels: APIs, backport, review required

#1595 Update cli script
  bin/cli
Labels: command-line, enhancement

#1839 Consolidate documentation covering files which are not encrypted
  modules/admin_manual/pages/_partials/configuration/files/external_storage/further_reading.adoc
  modules/admin_manual/pages/_partials/configuration/files/not-encrypted-files.adoc
  modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
  modules/admin_manual/pages/configuration/files/encryption/index.adoc
  modules/user_manual/pages/_partials/files/not-encrypted-files.adoc
  modules/user_manual/pages/files/encrypting_files.adoc
Labels: admin docs, clean up, review required, user docs, waiting on feedback
