Repository owncloud/docs, pull requests merged in 2019-12, with the labels that each got.

#2124 [10.3] [PR 2115] Create nginx_configuration.adoc
  modules/admin_manual/pages/installation/nginx_configuration.adoc
Labels: backport

#2126 fix: Fix admonition in enable encryption guide
  modules/admin_manual/pages/configuration/files/encryption/enable-encryption.adoc
Labels: admin docs, bug, review required

#2125 Fix error in database example
  modules/admin_manual/pages/configuration/files/encryption/encryption_configuration_quick_guide.adoc
Labels: admin docs, bug, review required, technical review

#2122 Restructure file_locking document
  modules/admin_manual/pages/configuration/files/files_locking_transactional.adoc
Labels: enhancement

#2049 [WIP] Fix build errors in 10.3
  modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc
Labels: bug, deployment, work in progress

#2131 Upgrade JavaScript dependencies
  yarn.lock
Labels: deployment

#2130 [10.3] [PR 2125] Fix error in database example
  modules/admin_manual/pages/configuration/files/encryption/encryption_configuration_quick_guide.adoc
Labels: backport

#1545 Document the Full Text Search app
  modules/admin_manual/assets/images/apps/search_elastic/configuration_successful.png
  modules/admin_manual/assets/images/apps/search_elastic/elasticsearch_server_unreachable.png
  modules/admin_manual/assets/images/apps/search_elastic/search_elastic_configuration_full_window.png
  modules/admin_manual/assets/images/apps/search_elastic/warning_could_not_setup_indexes_connection_failure.png
  modules/admin_manual/assets/images/apps/search_elastic/warning_could_not_setup_indexes_unknown_key.png
  modules/admin_manual/nav.adoc
  modules/admin_manual/pages/configuration/search/index.adoc
  modules/admin_manual/pages/configuration/server/occ_command.adoc
  modules/admin_manual/pages/configuration/server/occ_command/full_text_search_commands.adoc
Labels: admin docs, enhancement, occ, waiting for release

#2129 [10.3] [PR 2126] fix: Fix admonition in enable encryption guide
  modules/admin_manual/pages/configuration/files/encryption/enable-encryption.adoc
Labels: backport

#2133 [10.3] [PR 1545] Document the Full Text Search app
  modules/admin_manual/assets/images/apps/search_elastic/configuration_successful.png
  modules/admin_manual/assets/images/apps/search_elastic/elasticsearch_server_unreachable.png
  modules/admin_manual/assets/images/apps/search_elastic/search_elastic_configuration_full_window.png
  modules/admin_manual/assets/images/apps/search_elastic/warning_could_not_setup_indexes_connection_failure.png
  modules/admin_manual/assets/images/apps/search_elastic/warning_could_not_setup_indexes_unknown_key.png
  modules/admin_manual/nav.adoc
  modules/admin_manual/pages/configuration/search/index.adoc
  modules/admin_manual/pages/configuration/server/occ_command.adoc
  modules/admin_manual/pages/configuration/server/occ_command/full_text_search_commands.adoc
Labels: backport, p2-high

#2134 Update the full text search app's known limitations
  modules/admin_manual/pages/configuration/search/index.adoc
Labels: clean up, p4-low, review required, waiting on feedback

#2138 Update index.adoc
  modules/admin_manual/pages/configuration/search/index.adoc
Labels: admin docs

#2139 [10.3] [PR 2138] Update index.adoc
  modules/admin_manual/pages/configuration/search/index.adoc
Labels: backport

#2142 Replace PHP 7.2 with 7.3 in the Ubuntu Setup doc
  modules/admin_manual/pages/installation/ubuntu_18_04.adoc
Labels: admin docs, installation & configuration, review required, technical review, waiting on feedback

#2137 [10.3] [PR 2134] Update the full text search app's known limitations
  modules/admin_manual/pages/configuration/search/index.adoc
Labels: backport

#2073 [10.1] Fix build errors
  modules/admin_manual/pages/configuration/files/encryption/enable-encryption.adoc
  modules/admin_manual/pages/configuration/files/file_sharing_configuration.adoc
  modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc
  modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc
  modules/admin_manual/pages/configuration/user/reset_user_password.adoc
  modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
  modules/admin_manual/pages/configuration/user/user_provisioning_api.adoc
  modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
  modules/developer_manual/examples/core/unit-testing/MyClass.php
  modules/developer_manual/examples/core/unit-testing/MyClassTest.php
  modules/developer_manual/pages/_partials/section_page.adoc
  modules/developer_manual/pages/_partials/webdav_api/core_curl_request.adoc
  modules/developer_manual/pages/testing/index.adoc
  modules/developer_manual/pages/webdav_api/index.adoc
Labels: review required

#2028 Document the ability to specify repair steps in appinfo/info.xml
  modules/developer_manual/pages/_partials/app/fundamentals/complete-info.xml
  modules/developer_manual/pages/app/fundamentals/info.adoc
Labels: developer docs, p4-low, review required, technical review, waiting on feedback

#2119 [10.3] [PR 2118] Reorder the admin nav items into alphabetical order
  modules/admin_manual/nav.adoc
Labels: backport, waiting on feedback

#2135 Add go.php redirects for core#36315
  modules/admin_manual/pages/configuration/server/harden_server.adoc
Labels: 10.4, waiting for release

#1999 Update the WebDAV file/search properties
  modules/developer_manual/examples/core/webdav_api/search/request/search_files/search_body_with_properties.xml
  modules/developer_manual/pages/_partials/webdav_api/search/file_properties.adoc
Labels: APIs, developer docs, waiting on feedback

#2146 Update standard PROPFIND request attributes
  modules/developer_manual/pages/webdav_api/comments.adoc
  modules/developer_manual/pages/webdav_api/tags.adoc
Labels: APIs, review required, technical review

#2092 Document ability to disable WND Notify functionality
  modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
Labels: admin docs, enterprise docs, installation & configuration, review required, technical review, waiting on feedback

#2149 [10.3] [PR 2146] Update standard PROPFIND request attributes
  modules/developer_manual/pages/webdav_api/comments.adoc
  modules/developer_manual/pages/webdav_api/tags.adoc
Labels: backport

#2151 [10.3] [PR 2092] Document ability to disable WND Notify functionality
  modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
Labels: backport

#2153 Move providing logs and config files back to the troubleshooting section
  modules/admin_manual/nav.adoc
  modules/admin_manual/pages/troubleshooting/providing_logs_and_config_files.adoc
Labels: admin docs, review required, technical review

#2155 [10.3] [PR 2153] Move providing logs and config files back to the troubleshooting section
  modules/admin_manual/nav.adoc
  modules/admin_manual/pages/troubleshooting/providing_logs_and_config_files.adoc
Labels: backport

#2147 Update the list of PROPFIND properties and their descriptions
  modules/developer_manual/pages/_partials/webdav_api/search/file_properties.adoc
Labels: APIs, review required, technical review

#2162 Move notifications api docs to dev docs
  modules/developer_manual/examples/core/apis/ocs/notifications/delete-user-notification-response.json
  modules/developer_manual/examples/core/apis/ocs/notifications/get-server-capabilities-response.json
  modules/developer_manual/examples/core/apis/ocs/notifications/get-server-capabilities-response.xml
  modules/developer_manual/examples/core/apis/ocs/notifications/get-user-notifications-no-notifications-response.json
  modules/developer_manual/examples/core/apis/ocs/notifications/get-user-notifications-response.json
  modules/developer_manual/examples/core/scripts/curl/ocs/notifications/get-server-capabilities.sh
  modules/developer_manual/examples/core/scripts/curl/ocs/notifications/get-user-notifications.sh
  modules/developer_manual/nav.adoc
  modules/developer_manual/pages/app/advanced/notifications.adoc
  modules/developer_manual/pages/core/apis/ocs/notifications/index.adoc
  modules/developer_manual/pages/core/apis/ocs/notifications/ocs-endpoint-v1.adoc
  site.yml
Labels: APIs, developer docs, review required, technical review

#2171 Specificate exact version
  modules/admin_manual/pages/_partials/maintenance/major_release_note.adoc
Labels: clean up

#2173 [10.3] [PR 2171] Specificate exact version
  modules/admin_manual/pages/_partials/maintenance/major_release_note.adoc
Labels: backport

#2174 Remove unrequired xref to notification workflow file
  modules/developer_manual/pages/core/apis/ocs/notifications/index.adoc
Labels: review required
