Repository owncloud/docs, pull requests merged in 2019-08, with the labels that each got.

#1596 Fix TOC title in admin PDF manual
  books/ownCloud_Admin_Manual.adoc
  modules/admin_manual/pages/configuration/server/occ_command.adoc
  modules/admin_manual/pages/configuration/user/user_roles.adoc
Labels: bug, command-line, review required

#1587 improve wording in skeleton doc
  modules/admin_manual/pages/configuration/files/default_files_configuration.adoc
Labels: admin docs, enhancement, work in progress

#1598 [10.2] [PR 1596] Fix TOC title in admin PDF manual
  modules/admin_manual/pages/configuration/server/occ_command.adoc
  modules/admin_manual/pages/configuration/user/user_roles.adoc
Labels: clean up, pdf generation

#1599 [10.1] [PR 1596] Fix TOC title in admin PDF manual
  books/ownCloud_Admin_Manual.adoc
  modules/admin_manual/pages/configuration/server/occ_command.adoc
  modules/admin_manual/pages/configuration/user/user_roles.adoc
Labels: clean up, pdf generation

#1600 [10.0] [PR 1596] Fix TOC title in admin PDF manual
  books/ownCloud_Admin_Manual.adoc
  modules/admin_manual/pages/configuration/server/occ_command.adoc
  modules/admin_manual/pages/configuration/user/user_roles.adoc
Labels: clean up, pdf generation

#1605 Remove package-lock.json
  package-lock.json
Labels: clean up, deprecation, p4-low

#1615 Document the x-request-id functionality in ownCloud server
  modules/admin_manual/nav.adoc
  modules/admin_manual/pages/configuration/server/request_tracing.adoc
Labels: admin docs, enhancement, p3-medium, review required, technical review

#1621 Update package dependencies
  package.json
  yarn.lock
Labels: encryption, review required, technical review

#1622 Document how to limit access to Microsoft Office Online
  modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
Labels: admin docs, enhancement, review required, technical review, waiting on feedback

#1617 Improving Best Practices
  docs/best-practices.md
Labels: backport, enhancement

#1630 [10.2] [PR 1622] Document how to limit access to Microsoft Office Online
  modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
Labels: admin docs, backport, enhancement

#1633 Minor fix to limit access to Microsoft Office Online changes
  modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
Labels: admin docs, clean up, enhancement, installation & configuration, review required, technical review

#1634 [10.2] [PR 1633] Minor fix to limit access to Microsoft Office Online changes
  modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
Labels: backport

#1636 [10.1] [PR 1633] Minor fix to limit access to Microsoft Office Online changes
  modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
Labels: backport

#1635 [10.0] [PR 1633] Minor fix to limit access to Microsoft Office Online changes
  modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
Labels: backport

#1637 Create redirect for deprecated server/admin_manual/appliance/Clamav.html
  modules/admin_manual/pages/appliance/configuration/clamav.adoc
Labels: admin docs, appliance docs, bug, enhancement, p2-high, review required, technical review, waiting on feedback

#1642 [10.0] [PR 1637] Create redirect for deprecated server/admin_manual/appliance/Clamav.html
  modules/admin_manual/pages/appliance/configuration/clamav.adoc
Labels: backport

#1646 added explanation for sharing permissions
  modules/admin_manual/pages/configuration/files/file_sharing_configuration.adoc
Labels: admin docs, p4-low, shares

#1652 [10.2] [PR 1646] added explanation for sharing permissions
  modules/admin_manual/pages/configuration/files/file_sharing_configuration.adoc
Labels: backport

#1655 [10.3] [PR 1646] added explanation for sharing permissions
  modules/admin_manual/pages/configuration/files/file_sharing_configuration.adoc
Labels: backport

#1654 [10.0] [PR 1646] added explanation for sharing permissions
  modules/admin_manual/pages/configuration/files/file_sharing_configuration.adoc
Labels: backport

#1653 [10.1] [PR 1646] added explanation for sharing permissions
  modules/admin_manual/pages/configuration/files/file_sharing_configuration.adoc
Labels: backport

#1645 added known limitation for sync
  modules/admin_manual/pages/faq/index.adoc
Labels: admin docs, clean up, p4-low, review required, technical review, waiting on feedback

#1570 Update the OCS Share API Get Shares From Specific File or Folder docs
  modules/developer_manual/examples/core/scripts/curl/accept-pending-share.sh
  modules/developer_manual/examples/core/scripts/curl/decline-pending-share.sh
  modules/developer_manual/examples/core/scripts/curl/list-all-shares.sh
  modules/developer_manual/examples/core/scripts/curl/list-share-details.sh
  modules/developer_manual/examples/core/scripts/go/accept-pending-share.go
  modules/developer_manual/examples/core/scripts/go/decline-pending-share.go
  modules/developer_manual/examples/core/scripts/php/accept-pending-share.php
  modules/developer_manual/examples/core/scripts/php/decline-pending-share.php
  modules/developer_manual/examples/core/scripts/responses/shares/accept-pending-share-failure.xml
  modules/developer_manual/examples/core/scripts/responses/shares/accept-pending-share-success.xml
  modules/developer_manual/examples/core/scripts/responses/shares/get-all-shares-success-with-shares.xml
  modules/developer_manual/examples/core/scripts/responses/shares/list-share-details-success.json
  modules/developer_manual/examples/core/scripts/ruby/accept-pending-share.rb
  modules/developer_manual/examples/core/scripts/ruby/decline-pending-share.rb
  modules/developer_manual/pages/core/apis/ocs-share-api.adoc
Labels: developer docs, p3-medium, review required

#1641 [10.1] [PR 1637] Create redirect for deprecated server/admin_manual/appliance/Clamav.html
  modules/admin_manual/pages/appliance/configuration/clamav.adoc
Labels: backport

#1640 [10.2] [PR 1637] Create redirect for deprecated server/admin_manual/appliance/Clamav.html
  modules/admin_manual/pages/appliance/configuration/clamav.adoc
Labels: backport

#1659 Document the occ encryption:fix-encrypted-version command
  modules/admin_manual/pages/configuration/server/occ_command.adoc
Labels: Effort: trivial, admin docs, enhancement, occ, p4-low, review required, technical review, waiting on feedback

#1665 [10.2] [PR 1570] Update the OCS Share API Get Shares From Specific File or Folder docs
  modules/developer_manual/examples/core/scripts/curl/accept-pending-share.sh
  modules/developer_manual/examples/core/scripts/curl/decline-pending-share.sh
  modules/developer_manual/examples/core/scripts/curl/list-all-shares.sh
  modules/developer_manual/examples/core/scripts/curl/list-share-details.sh
  modules/developer_manual/examples/core/scripts/go/accept-pending-share.go
  modules/developer_manual/examples/core/scripts/go/decline-pending-share.go
  modules/developer_manual/examples/core/scripts/php/accept-pending-share.php
  modules/developer_manual/examples/core/scripts/php/decline-pending-share.php
  modules/developer_manual/examples/core/scripts/responses/shares/accept-pending-share-failure.xml
  modules/developer_manual/examples/core/scripts/responses/shares/accept-pending-share-success.xml
  modules/developer_manual/examples/core/scripts/responses/shares/get-all-shares-success-with-shares.xml
  modules/developer_manual/examples/core/scripts/responses/shares/list-share-details-success.json
  modules/developer_manual/examples/core/scripts/ruby/accept-pending-share.rb
  modules/developer_manual/examples/core/scripts/ruby/decline-pending-share.rb
  modules/developer_manual/pages/core/apis/ocs-share-api.adoc
Labels: backport

#1664 [10.3] [PR 1570] Update the OCS Share API Get Shares From Specific File or Folder docs
  modules/developer_manual/examples/core/scripts/curl/accept-pending-share.sh
  modules/developer_manual/examples/core/scripts/curl/decline-pending-share.sh
  modules/developer_manual/examples/core/scripts/curl/list-all-shares.sh
  modules/developer_manual/examples/core/scripts/curl/list-share-details.sh
  modules/developer_manual/examples/core/scripts/go/accept-pending-share.go
  modules/developer_manual/examples/core/scripts/go/decline-pending-share.go
  modules/developer_manual/examples/core/scripts/php/accept-pending-share.php
  modules/developer_manual/examples/core/scripts/php/decline-pending-share.php
  modules/developer_manual/examples/core/scripts/responses/shares/accept-pending-share-failure.xml
  modules/developer_manual/examples/core/scripts/responses/shares/accept-pending-share-success.xml
  modules/developer_manual/examples/core/scripts/responses/shares/get-all-shares-success-with-shares.xml
  modules/developer_manual/examples/core/scripts/responses/shares/list-share-details-success.json
  modules/developer_manual/examples/core/scripts/ruby/accept-pending-share.rb
  modules/developer_manual/examples/core/scripts/ruby/decline-pending-share.rb
  modules/developer_manual/pages/core/apis/ocs-share-api.adoc
Labels: backport

#1663 [10.1] [PR 1570] Update the OCS Share API Get Shares From Specific File or Folder docs
  modules/developer_manual/examples/core/scripts/curl/accept-pending-share.sh
  modules/developer_manual/examples/core/scripts/curl/decline-pending-share.sh
  modules/developer_manual/examples/core/scripts/curl/list-all-shares.sh
  modules/developer_manual/examples/core/scripts/curl/list-share-details.sh
  modules/developer_manual/examples/core/scripts/go/accept-pending-share.go
  modules/developer_manual/examples/core/scripts/go/decline-pending-share.go
  modules/developer_manual/examples/core/scripts/php/accept-pending-share.php
  modules/developer_manual/examples/core/scripts/php/decline-pending-share.php
  modules/developer_manual/examples/core/scripts/responses/shares/accept-pending-share-failure.xml
  modules/developer_manual/examples/core/scripts/responses/shares/accept-pending-share-success.xml
  modules/developer_manual/examples/core/scripts/responses/shares/get-all-shares-success-with-shares.xml
  modules/developer_manual/examples/core/scripts/responses/shares/list-share-details-success.json
  modules/developer_manual/examples/core/scripts/ruby/accept-pending-share.rb
  modules/developer_manual/examples/core/scripts/ruby/decline-pending-share.rb
  modules/developer_manual/pages/core/apis/ocs-share-api.adoc
Labels: backport

#1662 [10.0] [PR 1570] Update the OCS Share API Get Shares From Specific File or Folder docs
  modules/developer_manual/examples/core/scripts/curl/accept-pending-share.sh
  modules/developer_manual/examples/core/scripts/curl/decline-pending-share.sh
  modules/developer_manual/examples/core/scripts/curl/list-all-shares.sh
  modules/developer_manual/examples/core/scripts/curl/list-share-details.sh
  modules/developer_manual/examples/core/scripts/go/accept-pending-share.go
  modules/developer_manual/examples/core/scripts/go/decline-pending-share.go
  modules/developer_manual/examples/core/scripts/php/accept-pending-share.php
  modules/developer_manual/examples/core/scripts/php/decline-pending-share.php
  modules/developer_manual/examples/core/scripts/responses/shares/accept-pending-share-failure.xml
  modules/developer_manual/examples/core/scripts/responses/shares/accept-pending-share-success.xml
  modules/developer_manual/examples/core/scripts/responses/shares/get-all-shares-success-with-shares.xml
  modules/developer_manual/examples/core/scripts/responses/shares/list-share-details-success.json
  modules/developer_manual/examples/core/scripts/ruby/accept-pending-share.rb
  modules/developer_manual/examples/core/scripts/ruby/decline-pending-share.rb
  modules/developer_manual/pages/core/apis/ocs-share-api.adoc
Labels: backport

#1666 [10.3] [PR 1659] Document the occ encryption:fix-encrypted-version command
  modules/admin_manual/pages/configuration/server/occ_command.adoc
Labels: backport

#1677 Document selenium chrome testing version
  modules/developer_manual/pages/testing/ui-testing.adoc
Labels: review required

#1657 Unify the wording around skipping major releases when upgrading
  modules/admin_manual/pages/maintenance/package_upgrade.adoc
  modules/admin_manual/pages/maintenance/upgrade.adoc
Labels: Effort: trivial, admin docs, clean up, installation & configuration, p3-medium, review required, technical review

#1651 document migration step commands
  modules/admin_manual/pages/configuration/server/occ_command.adoc
Labels: command-line, installation & configuration, occ, p4-low, waiting on feedback

#1629 Minor text fixes to the best practices update
  docs/best-practices.md
Labels: clean up, review required

#1650 Document new options for adding users via provisioning API and occ
  modules/admin_manual/pages/configuration/server/occ_command.adoc
  modules/admin_manual/pages/configuration/user/user_provisioning_api.adoc
Labels: APIs, admin docs, command-line, enhancement, occ, p2-high, review required, technical review, user docs, waiting on feedback

#1597 Updating Server Prep Ubuntu 18.04
  modules/admin_manual/pages/installation/server_prep_ubuntu_18.04.adoc
Labels: admin docs, backport, installation & configuration

#1722 Upgrade write-good from version 0.13.1 to 1.0.2
  package.json
  yarn.lock
Labels: deployment

#1721 Upgrade @antora/site-generator-default to 2.1.0
  yarn.lock
Labels: deployment

#1720 Upgrade @antora to version 2.1.0
  yarn.lock
Labels: deployment, p3-medium, work in progress
