Repository owncloud/docs, pull requests merged in 2019-11, with the labels that each got.

#2017 Remove note about mtime
  modules/admin_manual/pages/configuration/files/file_sharing_configuration.adoc
  modules/admin_manual/pages/enterprise/file_management/files_tagging.adoc
  modules/developer_manual/pages/app/advanced/custom-cache-backend.adoc
  modules/developer_manual/pages/app/advanced/storage-backend.adoc
Labels: review required

#2022 [10.3] [PR 2017] Remove note about mtime
  modules/admin_manual/pages/configuration/files/file_sharing_configuration.adoc
  modules/admin_manual/pages/enterprise/file_management/files_tagging.adoc
  modules/developer_manual/pages/app/advanced/custom-cache-backend.adoc
  modules/developer_manual/pages/app/advanced/storage-backend.adoc
Labels: backport

#2023 [10.2] [PR 2017] Remove note about mtime
  modules/admin_manual/pages/configuration/files/file_sharing_configuration.adoc
  modules/admin_manual/pages/enterprise/file_management/files_tagging.adoc
  modules/developer_manual/pages/app/advanced/custom-cache-backend.adoc
  modules/developer_manual/pages/app/advanced/storage-backend.adoc
Labels: backport

#2021 Correct developer documentation mistakes
  modules/developer_manual/pages/app/fundamentals/container.adoc
  modules/developer_manual/pages/app/fundamentals/controllers.adoc
  modules/developer_manual/pages/app/fundamentals/routes.adoc
  modules/developer_manual/pages/app/tutorial/development_environment.adoc
Labels: bug, developer docs, p4-low, review required, technical review

#2024 [10.1] [PR 2017] Remove note about mtime
  modules/admin_manual/pages/configuration/files/file_sharing_configuration.adoc
  modules/admin_manual/pages/enterprise/file_management/files_tagging.adoc
  modules/developer_manual/pages/app/advanced/custom-cache-backend.adoc
  modules/developer_manual/pages/app/advanced/storage-backend.adoc
Labels: backport

#2025 [10.3] [PR 2021] Correct developer documentation mistakes
  modules/developer_manual/pages/app/fundamentals/container.adoc
  modules/developer_manual/pages/app/fundamentals/controllers.adoc
  modules/developer_manual/pages/app/fundamentals/routes.adoc
  modules/developer_manual/pages/app/tutorial/development_environment.adoc
Labels: backport

#2026 [10.2] [PR 2021] Correct developer documentation mistakes
  modules/developer_manual/pages/app/fundamentals/container.adoc
  modules/developer_manual/pages/app/fundamentals/controllers.adoc
  modules/developer_manual/pages/app/fundamentals/routes.adoc
  modules/developer_manual/pages/app/tutorial/development_environment.adoc
Labels: backport

#2027 [10.1] [PR 2021] Correct developer documentation mistakes
  modules/developer_manual/pages/app/fundamentals/container.adoc
  modules/developer_manual/pages/app/fundamentals/controllers.adoc
  modules/developer_manual/pages/app/fundamentals/routes.adoc
  modules/developer_manual/pages/app/tutorial/development_environment.adoc
Labels: backport

#2019 Document that password changes log out all user sessions
  modules/admin_manual/pages/_partials/configuration/user/update-password-note.adoc
  modules/admin_manual/pages/configuration/server/occ_command.adoc
  modules/admin_manual/pages/configuration/user/reset_admin_password.adoc
  modules/admin_manual/pages/configuration/user/reset_user_password.adoc
  modules/user_manual/pages/_partials/configuration/user/update-password-note.adoc
  modules/user_manual/pages/personal_settings/general.adoc
Labels: admin docs, p4-low, user docs

#2029 [10.3] [PR 2019] Document that password changes log out all user sessions
  modules/admin_manual/pages/_partials/configuration/user/update-password-note.adoc
  modules/admin_manual/pages/configuration/server/occ_command.adoc
  modules/admin_manual/pages/configuration/user/reset_admin_password.adoc
  modules/admin_manual/pages/configuration/user/reset_user_password.adoc
  modules/user_manual/pages/_partials/configuration/user/update-password-note.adoc
  modules/user_manual/pages/personal_settings/general.adoc
Labels: backport

#2030 [10.2] [PR 2019] Document that password changes log out all user sessions
  modules/admin_manual/pages/_partials/configuration/user/update-password-note.adoc
  modules/admin_manual/pages/configuration/server/occ_command.adoc
  modules/admin_manual/pages/configuration/user/reset_admin_password.adoc
  modules/admin_manual/pages/configuration/user/reset_user_password.adoc
  modules/user_manual/pages/_partials/configuration/user/update-password-note.adoc
  modules/user_manual/pages/personal_settings/general.adoc
Labels: backport

#2031 [10.1] [PR 2019] Document that password changes log out all user sessions
  modules/admin_manual/pages/_partials/configuration/user/update-password-note.adoc
  modules/admin_manual/pages/configuration/server/occ_command.adoc
  modules/admin_manual/pages/configuration/user/reset_admin_password.adoc
  modules/admin_manual/pages/configuration/user/reset_user_password.adoc
  modules/user_manual/pages/_partials/configuration/user/update-password-note.adoc
  modules/user_manual/pages/personal_settings/general.adoc
Labels: backport

#2032 [275] Update documentation of the occ config:list command
  modules/admin_manual/pages/_partials/configuration/server/occ_command/config-list-report.json
  modules/admin_manual/pages/configuration/server/occ_command.adoc
Labels: admin docs, occ, p4-low, review required

#2037 [10.3] [PR 2032] Update documentation of the occ config:list command
  modules/admin_manual/pages/_partials/configuration/server/occ_command/config-list-report.json
  modules/admin_manual/pages/configuration/server/occ_command.adoc
Labels: backport

#2038 [10.2] [PR 2032] Update documentation of the occ config:list command
  modules/admin_manual/pages/_partials/configuration/server/occ_command/config-list-report.json
  modules/admin_manual/pages/configuration/server/occ_command.adoc
Labels: backport

#2039 [10.1] [PR 2032] Update documentation of the occ config:list command
  modules/admin_manual/pages/_partials/configuration/server/occ_command/config-list-report.json
  modules/admin_manual/pages/configuration/server/occ_command.adoc
Labels: backport

#1971 Update code-standard.adoc
  modules/developer_manual/pages/core/code-standard.adoc
Labels: developer docs

#2044 [10.1] [PR 1971] Update code-standard.adoc
  modules/developer_manual/pages/core/code-standard.adoc
Labels: backport

#2043 [10.2] [PR 1971] Update code-standard.adoc
  modules/developer_manual/pages/core/code-standard.adoc
Labels: backport

#2042 [10.3] [PR 1971] Update code-standard.adoc
  modules/developer_manual/pages/core/code-standard.adoc
Labels: backport

#2041 Fix docs pdf errors
  modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc
  modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc
Labels: review required

#2046 [10.3] Fix docs pdf errors
  modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc
  modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc
Labels: backport

#2047 [10.2] Fix docs pdf errors
  modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc
  modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc
Labels: backport

#2036 Extract occ config command into partial
  modules/admin_manual/pages/configuration/server/occ_command.adoc
  modules/admin_manual/pages/configuration/server/occ_command/config.adoc
Labels: admin docs, p4-low

#2048 [10.1] Fix docs pdf errors
  modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc
  modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc
Labels: backport

#2050 [10.3] Extract occ config command into partial
  modules/admin_manual/pages/configuration/server/occ_command.adoc
  modules/admin_manual/pages/configuration/server/occ_command/config.adoc
Labels: backport

#2051 [10.2] Extract occ config command into partial
  modules/admin_manual/pages/configuration/server/occ_command.adoc
  modules/admin_manual/pages/configuration/server/occ_command/config.adoc
Labels: backport

#2052 [10.1] Extract occ config command into partial
  modules/admin_manual/pages/configuration/server/occ_command.adoc
  modules/admin_manual/pages/configuration/server/occ_command/config.adoc
Labels: backport

#2058 [10.3] [PR 2056] Update virus-scanner-support.adoc
  modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc
Labels: backport

#2059 [10.2] [PR 2056] Update virus-scanner-support.adoc
  modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc
Labels: backport

#2060 [10.1] [PR 2056] Update virus-scanner-support.adoc
  modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc
Labels: backport

#2054 [10.2] [PR 1821] Remove manual section ids
  modules/admin_manual/pages/configuration/files/federated_cloud_sharing_configuration.adoc
  modules/admin_manual/pages/configuration/server/occ_command.adoc
  modules/admin_manual/pages/configuration/user/user_configuration.adoc
  modules/admin_manual/pages/enterprise/collaboration/collabora_online_integration.adoc
  modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
  modules/admin_manual/pages/installation/deployment_considerations.adoc
  modules/admin_manual/pages/installation/manual_installation.adoc
  modules/admin_manual/pages/maintenance/encryption/migrating-from-user-key-to-master-key.adoc
  modules/admin_manual/pages/maintenance/manually-moving-data-folders.adoc
  modules/admin_manual/pages/maintenance/upgrade.adoc
Labels: backport, review required

#2067 [10.3] 10.3.1 release notes
  modules/admin_manual/pages/release_notes.adoc
Labels: backport

#2068 [10.2] 10.3.1 release notes #2067
  modules/admin_manual/pages/release_notes.adoc
Labels: backport

#2069 [10.1] 10.3.1 release notes #2067
  modules/admin_manual/pages/release_notes.adoc
Labels: backport

#2071 [10.2] Fix docs pdf errors
  modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc
Labels: backport

#2072 Updated the branching workflow
  docs/the-branching-workflow.md
Labels: clean up, p4-low, review required, work in progress

#2075 [10.3] Updated the branching workflow
  docs/the-branching-workflow.md
Labels: backport

#2077 Update wnd_setup.adoc
  modules/admin_manual/pages/appliance/configuration/wnd_setup.adoc
Labels: admin docs, clean up, installation & configuration

#2070 update config sample files
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Labels: admin docs

#2078 [10.3] [PR 2077] Update wnd_setup.adoc
  modules/admin_manual/pages/appliance/configuration/wnd_setup.adoc
Labels: backport

#2079 Fix broken link to admin_manual/upgrading/marketplace_apps.html
  modules/admin_manual/pages/maintenance/upgrading/marketplace_apps.adoc
Labels: admin docs, bug, clean up, deprecation, p4-low, review required

#2080 [10.3] update config sample files
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Labels: backport

#2082 fixed the 10.1 manual upgrade document
  modules/admin_manual/pages/maintenance/manual_upgrade.adoc
Labels: admin docs, clean up

#2081 [10.3] Fix broken link to admin_manual/upgrading/marketplace_apps.html
  modules/admin_manual/pages/maintenance/upgrading/marketplace_apps.adoc
Labels: backport

#2083 Change manual upgrade toc level to 2
  modules/admin_manual/pages/maintenance/manual_upgrade.adoc
Labels: admin docs, clean up, review required

#2085 Updated requiered oC version from 10.2 to 10.3
  modules/admin_manual/pages/enterprise/collaboration/collabora_online_integration.adoc
Labels: admin docs

#2086 [10.3] [PR 2085] Updated requiered oC version from 10.2 to 10.3
  modules/admin_manual/pages/enterprise/collaboration/collabora_online_integration.adoc
Labels: backport

#2087 Remove final references to Swift from the documentation
  modules/admin_manual/nav.adoc
  modules/admin_manual/pages/configuration/server/occ_command.adoc
  modules/admin_manual/pages/enterprise/external_storage/s3_swift_as_primary_object_store_configuration.adoc
  modules/admin_manual/pages/installation/apps_supported.adoc
  modules/user_manual/pages/files/access_webdav.adoc
Labels: admin docs, clean up, installation & configuration, p4-low, review required, user docs

#2090 [10.3] [PR 2087] Remove final references to Swift from the documentation
  modules/admin_manual/nav.adoc
  modules/admin_manual/pages/configuration/server/occ_command.adoc
  modules/admin_manual/pages/enterprise/external_storage/s3_swift_as_primary_object_store_configuration.adoc
  modules/admin_manual/pages/installation/apps_supported.adoc
  modules/user_manual/pages/files/access_webdav.adoc
Labels: backport

#2093 [PR 324] Document how to send notifications from apps
  modules/developer_manual/examples/app/advanced/notifications/intro-notification.php
  modules/developer_manual/examples/app/advanced/notifications/notification-with-object.php
  modules/developer_manual/nav.adoc
  modules/developer_manual/pages/app/advanced/notifications.adoc
Labels: developer docs, review required, technical review

#2095 [10.3] [PR 2093] [PR 324] Document how to send notifications from apps
  modules/developer_manual/examples/app/advanced/notifications/intro-notification.php
  modules/developer_manual/examples/app/advanced/notifications/notification-with-object.php
  modules/developer_manual/nav.adoc
  modules/developer_manual/pages/app/advanced/notifications.adoc
Labels: backport

#2094 [553] Document known federated sharing bugs
  modules/admin_manual/pages/configuration/files/federated_cloud_sharing_configuration.adoc
Labels: admin docs, bug, review required, waiting on feedback

#2097 [10.3] [PR 2094] [553] Document known federated sharing bugs
  modules/admin_manual/pages/configuration/files/federated_cloud_sharing_configuration.adoc
Labels: backport

#2099 Delete double present command files_external:create
  modules/admin_manual/pages/configuration/server/occ_command.adoc
Labels: admin docs, bug

#2089 Document ACL support in the Windows Network Drive app
  modules/admin_manual/assets/images/enterprise/external_storage/windows_network_drive/acl-permissions-manager.png
  modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
Labels: admin docs, enterprise docs, review required, technical review

#2101 [10.3] [PR 2099] Delete double present command files_external:create
  modules/admin_manual/pages/configuration/server/occ_command.adoc
Labels: backport

#2088 [321] Add note about migrations in database tutorial docs
  modules/developer_manual/pages/app/fundamentals/database.adoc
  modules/developer_manual/pages/app/tutorial/database_connectivity.adoc
Labels: clean up, database, review required, technical review, waiting on feedback

#2103 [10.3] [PR 2088] [321] Add note about migrations in database tutorial docs
  modules/developer_manual/pages/app/fundamentals/database.adoc
  modules/developer_manual/pages/app/tutorial/database_connectivity.adoc
Labels: backport

#2102 [10.3] [PR 2089] Document ACL support in the Windows Network Drive app
  modules/admin_manual/assets/images/enterprise/external_storage/windows_network_drive/acl-permissions-manager.png
  modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
Labels: backport

#2035 Document the Activity app
  modules/admin_manual/pages/configuration/server/activity_configuration.adoc
  modules/user_manual/assets/images/apps/activity/activity-menu.png
  modules/user_manual/assets/images/apps/activity/activity-settings-limit-to-favorites.png
  modules/user_manual/assets/images/apps/activity/activity-settings.png
  modules/user_manual/assets/images/apps/activity/all-activity.png
  modules/user_manual/assets/images/apps/activity/comment-activity.png
  modules/user_manual/nav.adoc
  modules/user_manual/pages/apps/activity.adoc
Labels: review required, user docs, waiting on feedback

#2104 [10.3] [PR 2035] Document the Activity app
  modules/admin_manual/pages/configuration/server/activity_configuration.adoc
  modules/user_manual/assets/images/apps/activity/activity-menu.png
  modules/user_manual/assets/images/apps/activity/activity-settings-limit-to-favorites.png
  modules/user_manual/assets/images/apps/activity/activity-settings.png
  modules/user_manual/assets/images/apps/activity/all-activity.png
  modules/user_manual/assets/images/apps/activity/comment-activity.png
  modules/user_manual/nav.adoc
  modules/user_manual/pages/apps/activity.adoc
Labels: backport

#2098 Document how to use custom section settings icons
  modules/developer_manual/pages/core/theming.adoc
Labels: developer docs, review required, technical review, waiting on feedback

#2096 New option in files_external:list --mount-options
  modules/admin_manual/pages/configuration/server/occ_command.adoc
Labels: admin docs, backport

#2061 Deprecate the automatic configuration documentation
  modules/admin_manual/nav.adoc
  modules/admin_manual/pages/configuration/server/automatic_configuration.adoc
Labels: admin docs, installation & configuration, p4-low, review required, technical review

#2109 [10.3] [PR 2061] Deprecate the automatic configuration documentation
  modules/admin_manual/nav.adoc
  modules/admin_manual/pages/configuration/server/automatic_configuration.adoc
Labels: backport

#2108 [10.3] [PR 2098] Document how to use custom section settings icons
  modules/developer_manual/pages/core/theming.adoc
Labels: backport

#2003 [292] Document extra logging fields and string interpolation in logging
  modules/developer_manual/pages/app/fundamentals/logging.adoc
Labels: developer docs, logging, p4-low, waiting on feedback

#2111 [10.3] [PR 2003] [292] Document extra logging fields and string interpolation in logging
  modules/developer_manual/pages/app/fundamentals/logging.adoc
Labels: backport

#2118 Reorder the admin nav items into alphabetical order
  modules/admin_manual/nav.adoc
Labels: enhancement
