Repository owncloud/docs, pull requests merged in 2020-01, with the labels that each got.

#2163 [10.3] [PR 2162] Move notifications api docs to dev docs
  modules/developer_manual/examples/core/apis/ocs/notifications/delete-user-notification-response.json
  modules/developer_manual/examples/core/apis/ocs/notifications/get-server-capabilities-response.json
  modules/developer_manual/examples/core/apis/ocs/notifications/get-server-capabilities-response.xml
  modules/developer_manual/examples/core/apis/ocs/notifications/get-user-notifications-no-notifications-response.json
  modules/developer_manual/examples/core/apis/ocs/notifications/get-user-notifications-response.json
  modules/developer_manual/examples/core/scripts/curl/ocs/notifications/get-server-capabilities.sh
  modules/developer_manual/examples/core/scripts/curl/ocs/notifications/get-user-notifications.sh
  modules/developer_manual/nav.adoc
  modules/developer_manual/pages/app/advanced/notifications.adoc
  modules/developer_manual/pages/core/apis/ocs/notifications/index.adoc
  modules/developer_manual/pages/core/apis/ocs/notifications/ocs-endpoint-v1.adoc
  site.yml
Labels: backport

#2164 Update notifications.adoc
  modules/developer_manual/pages/app/advanced/notifications.adoc
Labels: developer docs

#2177 Update the background jobs configuration documentation
  modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc
Labels: admin docs, occ, review required, technical review

#2179 add images
  modules/admin_manual/pages/appliance/configuration/app_settings.adoc
Labels: admin docs, enhancement

#2178 [10.3] [PR 2164] Update notifications.adoc
  modules/developer_manual/pages/app/advanced/notifications.adoc
Labels: backport

#2143 [10.3] [PR 2142] Replace PHP 7.2 with 7.3 in the Ubuntu Setup doc
  modules/admin_manual/pages/installation/ubuntu_18_04.adoc
Labels: backport

#2180 [10.3] [PR 2177] Update the background jobs configuration documentation
  modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc
Labels: backport

#2181 Port corrections from 79b1423 to master
  modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc
Labels: backport

#2185 Backport 2180 to master
  modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc
Labels: review required

#2175 Document the ability to disable admins from administering custom groups
  modules/user_manual/pages/files/webgui/custom_groups.adoc
Labels: enhancement, installation & configuration, review required, technical review, user docs, waiting on feedback

#2186 [10.3] [PR 2175] Document the ability to disable admins from administering custom groups
  modules/user_manual/pages/files/webgui/custom_groups.adoc
Labels: backport

#2161 Rename the document to distinguish it
  modules/admin_manual/pages/appliance/configuration/index.php-less_URLs.adoc
Labels: admin docs

#2156 Document how to login to the Marketplace from the Market app
  modules/user_manual/assets/images/apps/market/login-step-1.png
  modules/user_manual/assets/images/apps/market/login-step-2.png
  modules/user_manual/assets/images/apps/market/login-step-3.png
  modules/user_manual/assets/images/apps/market/login-step-4.png
  modules/user_manual/assets/images/apps/market/top-level-navigation-bar-highlighting-the-market-app.png
  modules/user_manual/nav.adoc
  modules/user_manual/pages/apps/market.adoc
Labels: marketplace, review required, user docs, waiting on feedback

#2189 [10.3] [PR 2156] Document how to login to the Marketplace from the Market app
  modules/user_manual/assets/images/apps/market/login-step-1.png
  modules/user_manual/assets/images/apps/market/login-step-2.png
  modules/user_manual/assets/images/apps/market/login-step-3.png
  modules/user_manual/assets/images/apps/market/login-step-4.png
  modules/user_manual/assets/images/apps/market/top-level-navigation-bar-highlighting-the-market-app.png
  modules/user_manual/nav.adoc
  modules/user_manual/pages/apps/market.adoc
Labels: backport

#2188 [10.3] [PR 2161] Rename the document to distinguish it
  modules/admin_manual/pages/appliance/configuration/index.php-less_URLs.adoc
Labels: backport

#2183 [10.4] update config sample
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Labels: 10.4

#2132 [10.4] Document the occ maintenance:install database-connection-string option
  modules/admin_manual/pages/configuration/server/occ_command.adoc
Labels: 10.4, installation & configuration, occ, review required, technical review, waiting on feedback

#2195 [10.4] Document the occ maintenance:install database-connection-string option
  modules/admin_manual/pages/configuration/server/occ_command.adoc
Labels: 10.4, backport

#2144 [10.4] Document the enable and disable options to occ app:list
  modules/admin_manual/pages/configuration/server/occ_command.adoc
Labels: 10.4, occ, waiting for release

#2190 Removed reference to ppa:ondrej/php repository
  modules/admin_manual/pages/installation/ubuntu_18_04.adoc
Labels: admin docs, clean up

#2182 Add missing file which caused PDF manual generation to throw errors
  modules/developer_manual/pages/_partials/section_page.adoc
  modules/developer_manual/pages/core/apis/index.adoc
  modules/developer_manual/pages/testing/index.adoc
  modules/developer_manual/pages/webdav_api/index.adoc
Labels: bug, developer docs

#2197 [10.4] [PR 2190] Removed reference to ppa:ondrej/php repository
  modules/admin_manual/pages/installation/ubuntu_18_04.adoc
Labels: backport

#2198 [10.3] [PR 2190] Removed reference to ppa:ondrej/php repository
  modules/admin_manual/pages/installation/ubuntu_18_04.adoc
Labels: backport

#2200 Fix asciidoctor build warnings
  modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
  modules/user_manual/pages/apps/market.adoc
Labels: admin docs, bug, user docs

#2204 [10.4] [PR 2200] Fix asciidoctor build warnings
  modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
  modules/user_manual/pages/apps/market.adoc
Labels: backport

#2203 [10.3] [PR 2200] Fix asciidoctor build warnings
  modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
  modules/user_manual/pages/apps/market.adoc
Labels: backport

#2114 Document the occ encryption:hsmdaemon command
  modules/admin_manual/pages/configuration/server/occ_command.adoc
Labels: admin docs, occ, review required, technical review

#2160 [10.3] Backport changes to big_file_upload_configuration.adoc from master
  modules/admin_manual/pages/configuration/database/linux_database_configuration.adoc
  modules/admin_manual/pages/configuration/files/big_file_upload_configuration.adoc
  modules/admin_manual/pages/configuration/ldap/ldap_proxy_cache_server_setup.adoc
  modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc
  modules/admin_manual/pages/configuration/server/security/oauth2.adoc
  modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
  modules/admin_manual/pages/release_notes.adoc
  modules/developer_manual/pages/testing/ui-testing.adoc
Labels: admin docs, review required

#2170 [2169] Update major release note to reflect latest releases
  modules/admin_manual/pages/_partials/maintenance/major_release_note.adoc
Labels: clean up, review required

#2207 [10.3] [PR 2170] [2169] Update major release note to reflect latest releases
  modules/admin_manual/pages/_partials/maintenance/major_release_note.adoc
Labels: backport

#2206 [10.4] Document the occ encryption:hsmdaemon command
  modules/admin_manual/pages/configuration/server/occ_command.adoc
Labels: backport

#2205 [10.3] Document the occ encryption:hsmdaemon command
  modules/admin_manual/pages/configuration/server/occ_command.adoc
Labels: backport

#2208 [10.4] [PR 2207] [10.3] [PR 2170] [2169] Update major release note to reflect latest releases
  modules/admin_manual/pages/_partials/maintenance/major_release_note.adoc
Labels: backport

#2199 Update: Migrating User Key-based Encryption to Master Key Encryption
  modules/admin_manual/pages/maintenance/encryption/migrating-from-user-key-to-master-key.adoc
Labels: admin docs, enhancement

#2212 [10.4] Update: Migrating User Key-based Encryption to Master Key Encryption
  modules/admin_manual/pages/maintenance/encryption/migrating-from-user-key-to-master-key.adoc
Labels: backport

#2211 [10.3] Update: Migrating User Key-based Encryption to Master Key Encryption
  modules/admin_manual/pages/maintenance/encryption/migrating-from-user-key-to-master-key.adoc
Labels: backport

#2202 Remove apt install software-properties-common
  modules/admin_manual/pages/installation/ubuntu_18_04.adoc
Labels: clean up

#2213 [10.4] Fix version name so that it's unique for this branch
  antora.yml
Labels: 10.4, p2-high

#2210 Updating the version
  modules/admin_manual/pages/maintenance/manual_upgrade.adoc
  site.yml
Labels: clean up

#2214 [10.4] [PR 2202] Remove apt install software-properties-common
  modules/admin_manual/pages/installation/ubuntu_18_04.adoc
Labels: backport

#2215 [10.3] [PR 2202] Remove apt install software-properties-common
  modules/admin_manual/pages/installation/ubuntu_18_04.adoc
Labels: backport

#2216 Remove specific reference to PHP 7.3 in the Ubuntu 18 guide
  modules/admin_manual/pages/installation/ubuntu_18_04.adoc
Labels: admin docs, review required, technical review, waiting on feedback

#2193 Update docs for 10.4 release
  modules/ROOT/pages/index.adoc
  site.yml
Labels: 10.4, waiting on feedback

#2219 [10.4] [PR 2216] Remove specific reference to PHP 7.3 in the Ubuntu 18 guide
  modules/admin_manual/pages/installation/ubuntu_18_04.adoc
Labels: backport

#2221 [10.3] [PR 2216] Remove specific reference to PHP 7.3 in the Ubuntu 18 guide
  modules/admin_manual/pages/installation/ubuntu_18_04.adoc
Labels: backport

#2220 remove unnecessary LDAP documentation structure
  modules/admin_manual/nav.adoc
  modules/admin_manual/pages/configuration/ldap/index.adoc
Labels: LDAP, admin docs, clean up, p3-medium

#2184 Update nav.adoc and Troubleshooting
  modules/admin_manual/nav.adoc
  modules/admin_manual/pages/appliance/troubleshooting.adoc
Labels: clean up

#2222 [10.4] [PR 2220] remove unnecessary LDAP documentation structure
  modules/admin_manual/nav.adoc
  modules/admin_manual/pages/configuration/ldap/index.adoc
Labels: backport

#2223 [10.3] [PR 2220] remove unnecessary LDAP documentation structure
  modules/admin_manual/nav.adoc
  modules/admin_manual/pages/configuration/ldap/index.adoc
Labels: backport

#2218 Read latest stable and previous version info from attributes
  modules/ROOT/pages/index.adoc
Labels: backport

#2217 Split the occ commands out into separate files
  modules/admin_manual/pages/configuration/server/app_commands/2fa_commands.adoc
  modules/admin_manual/pages/configuration/server/app_commands/antivirus_commands.adoc
  modules/admin_manual/pages/configuration/server/app_commands/brute_force_protection_commands.adoc
  modules/admin_manual/pages/configuration/server/app_commands/calendar_commands.adoc
  modules/admin_manual/pages/configuration/server/app_commands/contacts_commands.adoc
  modules/admin_manual/pages/configuration/server/app_commands/data_explorer_commands.adoc
  modules/admin_manual/pages/configuration/server/app_commands/ldap_integration_commands.adoc
  modules/admin_manual/pages/configuration/server/app_commands/market_commands.adoc
  modules/admin_manual/pages/configuration/server/app_commands/password_policy_commands.adoc
  modules/admin_manual/pages/configuration/server/app_commands/ransomware_protection_commands.adoc
  modules/admin_manual/pages/configuration/server/app_commands/s3objectstore_commands.adoc
  modules/admin_manual/pages/configuration/server/app_commands/saml_sso_shibboleth_integration_commands.adoc
  modules/admin_manual/pages/configuration/server/maintenance_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command.adoc
  modules/admin_manual/pages/configuration/server/occ_command/app_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/background_jobs_selector.adoc
  modules/admin_manual/pages/configuration/server/occ_command/command_line_installation_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/command_line_upgrade_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/config_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/config_reports_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/database_conversion_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/dav_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/encryption_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/federation_sync_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/file_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/files_external_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/group_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/incoming_shares_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/integrity_check_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/localisation_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/logging_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/maintenance_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/managing_background_jobs.adoc
  modules/admin_manual/pages/configuration/server/occ_command/migration_steps_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/mimetype_update_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/notifications_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/security_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/sharing_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/trashbin_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/user_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/versions_commands.adoc
Labels: admin docs, clean up, occ, p3-medium, review required, technical review

#2228 Move the overriding default (custom groups) behavior to the admin manual
  modules/admin_manual/pages/configuration/user/user_configuration.adoc
  modules/user_manual/pages/files/webgui/custom_groups.adoc
Labels: admin docs, clean up, p3-medium

#2227 [10.4] [PR 2217] Split the occ commands out into separate files
  modules/admin_manual/pages/configuration/server/app_commands/2fa_commands.adoc
  modules/admin_manual/pages/configuration/server/app_commands/antivirus_commands.adoc
  modules/admin_manual/pages/configuration/server/app_commands/brute_force_protection_commands.adoc
  modules/admin_manual/pages/configuration/server/app_commands/calendar_commands.adoc
  modules/admin_manual/pages/configuration/server/app_commands/contacts_commands.adoc
  modules/admin_manual/pages/configuration/server/app_commands/data_explorer_commands.adoc
  modules/admin_manual/pages/configuration/server/app_commands/ldap_integration_commands.adoc
  modules/admin_manual/pages/configuration/server/app_commands/market_commands.adoc
  modules/admin_manual/pages/configuration/server/app_commands/password_policy_commands.adoc
  modules/admin_manual/pages/configuration/server/app_commands/ransomware_protection_commands.adoc
  modules/admin_manual/pages/configuration/server/app_commands/s3objectstore_commands.adoc
  modules/admin_manual/pages/configuration/server/app_commands/saml_sso_shibboleth_integration_commands.adoc
  modules/admin_manual/pages/configuration/server/maintenance_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command.adoc
  modules/admin_manual/pages/configuration/server/occ_command/app_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/background_jobs_selector.adoc
  modules/admin_manual/pages/configuration/server/occ_command/command_line_installation_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/command_line_upgrade_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/config_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/config_reports_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/database_conversion_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/dav_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/encryption_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/federation_sync_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/file_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/files_external_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/group_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/incoming_shares_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/integrity_check_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/localisation_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/logging_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/maintenance_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/managing_background_jobs.adoc
  modules/admin_manual/pages/configuration/server/occ_command/migration_steps_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/mimetype_update_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/notifications_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/security_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/sharing_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/trashbin_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/user_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/versions_commands.adoc
Labels: backport

#2226 [10.3] [PR 2217] Split the occ commands out into separate files
  modules/admin_manual/pages/configuration/server/app_commands/2fa_commands.adoc
  modules/admin_manual/pages/configuration/server/app_commands/antivirus_commands.adoc
  modules/admin_manual/pages/configuration/server/app_commands/brute_force_protection_commands.adoc
  modules/admin_manual/pages/configuration/server/app_commands/calendar_commands.adoc
  modules/admin_manual/pages/configuration/server/app_commands/contacts_commands.adoc
  modules/admin_manual/pages/configuration/server/app_commands/data_explorer_commands.adoc
  modules/admin_manual/pages/configuration/server/app_commands/ldap_integration_commands.adoc
  modules/admin_manual/pages/configuration/server/app_commands/market_commands.adoc
  modules/admin_manual/pages/configuration/server/app_commands/password_policy_commands.adoc
  modules/admin_manual/pages/configuration/server/app_commands/ransomware_protection_commands.adoc
  modules/admin_manual/pages/configuration/server/app_commands/s3objectstore_commands.adoc
  modules/admin_manual/pages/configuration/server/app_commands/saml_sso_shibboleth_integration_commands.adoc
  modules/admin_manual/pages/configuration/server/maintenance_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command.adoc
  modules/admin_manual/pages/configuration/server/occ_command/app_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/background_jobs_selector.adoc
  modules/admin_manual/pages/configuration/server/occ_command/command_line_installation_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/command_line_upgrade_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/config_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/config_reports_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/database_conversion_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/dav_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/encryption_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/federation_sync_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/file_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/files_external_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/group_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/incoming_shares_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/integrity_check_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/localisation_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/logging_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/maintenance_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/managing_background_jobs.adoc
  modules/admin_manual/pages/configuration/server/occ_command/migration_steps_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/mimetype_update_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/notifications_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/security_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/sharing_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/trashbin_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/user_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/versions_commands.adoc
Labels: backport

#2230 [10.4] [PR 2228] Move the overriding default (custom groups) behavior to the admin manual
  modules/admin_manual/pages/configuration/user/user_configuration.adoc
  modules/user_manual/pages/files/webgui/custom_groups.adoc
Labels: backport

#2229 [10.3] [PR 2228] Move the overriding default (custom groups) behavior to the admin manual
  modules/admin_manual/pages/configuration/user/user_configuration.adoc
  modules/user_manual/pages/files/webgui/custom_groups.adoc
Labels: backport

#2231 Use tabs only when rendering content in HTML format
  modules/developer_manual/pages/core/apis/externalapi.adoc
  modules/developer_manual/pages/core/apis/ocs-notify-public-link-by-email.adoc
  modules/developer_manual/pages/core/apis/ocs-share-api.adoc
  modules/developer_manual/pages/core/apis/ocs-totp-validation-api.adoc
  modules/developer_manual/pages/core/apis/ocs/notifications/ocs-endpoint-v1.adoc
  modules/developer_manual/pages/core/apis/roles-api.adoc
  modules/developer_manual/pages/webdav_api/public_files.adoc
  modules/developer_manual/pages/webdav_api/trashbin.adoc
Labels: bug

#2232 Update link to docker-compose.yml
  modules/admin_manual/pages/installation/docker/index.adoc
Labels: 10.4, admin docs, docker, installation & configuration

#2237 Built 10.4 docs should be uploaded to doc.owncloud.com
  .drone.yml
Labels: 10.4, p2-high

#2233 Update build tools to be format-aware
  .drone.yml
  bin/cli
Labels: deployment, developer docs

#2172 Update upgrade steps documentation
  modules/admin_manual/pages/_partials/maintenance/upgrading/upgrade_steps.adoc
  modules/admin_manual/pages/maintenance/upgrading/upgrade_php.adoc
Labels: review required, technical review, waiting on feedback

#2239 [10.3] [PR 2233] Update build tools to be format-aware
  .drone.yml
  bin/cli
Labels: backport

#2242 Update index.adoc
  modules/user_manual/pages/pim/index.adoc
Labels: clean up

#2238 [10.4] [PR 2233] Update build tools to be format-aware
  .drone.yml
  bin/cli
Labels: backport

#2241 [10.4] [PR 2172] Update upgrade steps documentation
  modules/admin_manual/pages/_partials/maintenance/upgrading/upgrade_steps.adoc
  modules/admin_manual/pages/maintenance/upgrading/upgrade_php.adoc
Labels: 10.4, backport

#2252 update backgroundjob configuration
  modules/admin_manual/pages/_partials/configuration/server/occ_command/system_command.adoc
  modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc
Labels: admin docs

#2249 [10.3] [PR 2242] Update index.adoc
  modules/user_manual/pages/pim/index.adoc
Labels: backport

#2256 [10.3] [PR 2252] update backgroundjob configuration #2255
  modules/admin_manual/pages/_partials/configuration/server/occ_command/system_command.adoc
  modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc
Labels: backport

#2248 Remove dav.enable.tech_preview from example
  modules/admin_manual/pages/_partials/configuration/server/occ_command/config-list-report.json
Labels: 10.4, blocked

#2257 [10.4] [PR 2248] Remove dav.enable.tech_preview from example
  modules/admin_manual/pages/_partials/configuration/server/occ_command/config-list-report.json
Labels: backport

#2251 Enable experimental attribute when building the PDF manuals
  bin/cli
Labels: bug

#2260 Add page redirect for old ransomware protection documentation
  modules/admin_manual/pages/enterprise/security/ransomware-protection/index.adoc
Labels: bug, review required

#2261 Add page redirect for old ransomware protection documentation
  modules/admin_manual/pages/enterprise/security/ransomware-protection/index.adoc
Labels: backport

#2262 [10.3] [PR 2261] Add page redirect for old ransomware protection documentation
  modules/admin_manual/pages/enterprise/security/ransomware-protection/index.adoc
Labels: backport

#2255 [10.4] [PR 2252] update backgroundjob configuration
  modules/admin_manual/pages/_partials/configuration/server/occ_command/system_command.adoc
  modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc
Labels: backport

#2268 [10.4] [PR 2264] add requirements
  modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
Labels: 10.4, backport

#2267 [10.3] [PR 2264] add requirements
  modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
Labels: backport

#2234 Document single user-sync endpoint
  modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
  modules/developer_manual/examples/core/apis/ocs/user-sync/successful-response.xml
  modules/developer_manual/examples/core/scripts/curl/ocs/user-sync.sh
  modules/developer_manual/examples/core/scripts/php/ocs/user-sync.php
  modules/developer_manual/examples/core/scripts/php/user-sync.php
  modules/developer_manual/nav.adoc
  modules/developer_manual/pages/core/apis/ocs/user-sync-api.adoc
Labels: developer docs, review required, technical review

#2269 [10.4] [PR 2234] Document single user-sync endpoint
  modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
  modules/developer_manual/examples/core/apis/ocs/user-sync/successful-response.xml
  modules/developer_manual/examples/core/scripts/curl/ocs/user-sync.sh
  modules/developer_manual/examples/core/scripts/php/ocs/user-sync.php
  modules/developer_manual/examples/core/scripts/php/user-sync.php
  modules/developer_manual/nav.adoc
  modules/developer_manual/pages/core/apis/ocs/user-sync-api.adoc
Labels: 10.4, backport

#2250 [10.4] [PR 2242] Update index.adoc
  modules/user_manual/pages/pim/index.adoc
Labels: 10.4, backport

#2154 Update the formatting of the installation instructions
  modules/admin_manual/examples/installation/appinfo.xml
  modules/admin_manual/pages/installation/apps_management_installation.adoc
Labels: admin docs, installation & configuration
