Repository owncloud/docs, pull requests merged in 2020-10, with the labels that each got.

#2820 [10.5] [PR 2819] add doc for strict login checking required for disab…
  modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
Labels: backport

#2821 Migrate desktop & mobile system requirements
  modules/admin_manual/pages/installation/system_requirements.adoc
Labels: desktop client docs, mobile docs, sync client

#2831 update links to owncloud.org/support
  modules/admin_manual/pages/configuration/general_topics/code_signing.adoc
  modules/admin_manual/pages/maintenance/manual_upgrade.adoc
  site.yml
Labels: outdated documentation
