Repository owncloud/docs, pull requests merged in 2020-03, with the labels that each got.

#2347 Rework the Linux Database Configuration documentation
  modules/admin_manual/pages/configuration/database/linux_database_configuration.adoc
  modules/admin_manual/pages/configuration/server/occ_command/command_line_installation_commands.adoc
Labels: admin docs, database

#2363 [10.4] [PR 2347] Rework the Linux Database Configuration documentation
  modules/admin_manual/pages/configuration/database/linux_database_configuration.adoc
  modules/admin_manual/pages/configuration/server/occ_command/command_line_installation_commands.adoc
Labels: backport

#2362 [10.3] [PR 2347] Rework the Linux Database Configuration documentation
  modules/admin_manual/pages/configuration/database/linux_database_configuration.adoc
  modules/admin_manual/pages/configuration/server/occ_command/command_line_installation_commands.adoc
Labels: backport

#2358 add crucial part of secure view prerequisites
  modules/admin_manual/pages/enterprise/collaboration/collabora_online_integration.adoc
Labels: admin docs

#2350 restructure of the memory caching document
  modules/admin_manual/pages/configuration/server/caching_configuration.adoc
Labels: admin docs, clean up

#2371 [10.4] [PR 2350] restructure of the memory caching document
  modules/admin_manual/pages/configuration/server/caching_configuration.adoc
Labels: backport

#2370 [10.3] [PR 2350] restructure of the memory caching document
  modules/admin_manual/pages/configuration/server/caching_configuration.adoc
Labels: backport

#2372 Add scenario tags to acceptance test docs
  modules/developer_manual/pages/testing/acceptance-tests.adoc
Labels: review required

#2376 Fix privateLinks typo
  modules/developer_manual/pages/core/apis/ocs-capabilities.adoc
Labels: review required

#2378 [10.3] Fix privateLinks typo
  modules/developer_manual/pages/core/apis/ocs-capabilities.adoc
Labels: review required

#2377 [10.4] Fix privateLinks typo
  modules/developer_manual/pages/core/apis/ocs-capabilities.adoc
Labels: review required

#2334 [2326] Update deployment recommendations example for finding the PHP session.save_path value
  modules/admin_manual/examples/installation/deployment_recommendations/set_session_path.sh
  modules/admin_manual/pages/installation/deployment_recommendations.adoc
Labels: Effort: 0.25d, admin docs, clean up, p3-medium, review required, technical review, waiting on feedback

#2380 [10.4] [PR 2334] [2326] Update deployment recommendations example for finding the PHP session.save_path value
  modules/admin_manual/examples/installation/deployment_recommendations/set_session_path.sh
  modules/admin_manual/pages/installation/deployment_recommendations.adoc
Labels: backport

#2381 [10.3] [PR 2334] [2326] Update deployment recommendations example for finding the PHP session.save_path value
  modules/admin_manual/examples/installation/deployment_recommendations/set_session_path.sh
  modules/admin_manual/pages/installation/deployment_recommendations.adoc
Labels: backport

#2379 Fix Content-Type typo
  modules/developer_manual/examples/core/scripts/php/vendor/guzzlehttp/psr7/tests/MultipartStreamTest.php
Labels: Effort: trivial, admin docs, developer docs, p4-low

#2382 [10.3] [PR 2379] Fix Content-Type typo
  modules/developer_manual/examples/core/scripts/php/vendor/guzzlehttp/psr7/tests/MultipartStreamTest.php
Labels: backport

#2375 Fix typos in developer docs
  modules/developer_manual/examples/core/scripts/php/vendor/guzzlehttp/guzzle/CHANGELOG.md
  modules/developer_manual/examples/core/scripts/php/vendor/guzzlehttp/guzzle/UPGRADING.md
  modules/developer_manual/examples/core/scripts/php/vendor/guzzlehttp/promises/src/functions.php
  modules/developer_manual/examples/core/scripts/php/vendor/guzzlehttp/psr7/tests/LimitStreamTest.php
  modules/developer_manual/examples/core/scripts/php/vendor/guzzlehttp/psr7/tests/PumpStreamTest.php
  modules/developer_manual/examples/core/scripts/php/vendor/psr/http-message/CHANGELOG.md
  modules/developer_manual/pages/app/advanced/l10n.adoc
  modules/developer_manual/pages/app/fundamentals/container.adoc
  modules/developer_manual/pages/app/tutorial/testing.adoc
  modules/developer_manual/pages/general/backporting.adoc
  modules/developer_manual/pages/general/devenv.adoc
  modules/developer_manual/pages/mobile_development/android_library/examples.adoc
  modules/developer_manual/pages/mobile_development/ios_library/examples.adoc
  modules/developer_manual/pages/testing/test-pilots.adoc
Labels: Effort: trivial, developer docs, p4-low

#2366 Deprecate the ldap:update-group from occ commands
  modules/admin_manual/pages/configuration/server/app_commands/ldap_integration_commands.adoc
Labels: LDAP, admin docs, deprecation, review required, technical review

#2386 [10.4] [PR 2366] Deprecate the ldap:update-group from occ commands
  modules/admin_manual/pages/configuration/server/app_commands/ldap_integration_commands.adoc
Labels: backport

#2387 [10.3] [PR 2366] Deprecate the ldap:update-group from occ commands
  modules/admin_manual/pages/configuration/server/app_commands/ldap_integration_commands.adoc
Labels: backport

#2365 [10.3] [PR 2361] add locking to the doc of wopi app
  modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
Labels: backport

#2364 [10.4] [PR 2361] add locking to the doc of wopi app
  modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
Labels: backport

#2281 Add missing core theming documentation
  modules/developer_manual/assets/images/core/theming/2_ow_login.png
  modules/developer_manual/assets/images/core/theming/3_cu_login.png
  modules/developer_manual/assets/images/core/theming/4_oc_header.png
  modules/developer_manual/assets/images/core/theming/5_cu_header.png
  modules/developer_manual/pages/core/theming.adoc
Labels: Effort: 0.5d, developer docs, p4-low

#2390 [10.4] [PR 2281] Add missing core theming documentation
  modules/developer_manual/assets/images/core/theming/2_ow_login.png
  modules/developer_manual/assets/images/core/theming/3_cu_login.png
  modules/developer_manual/assets/images/core/theming/4_oc_header.png
  modules/developer_manual/assets/images/core/theming/5_cu_header.png
  modules/developer_manual/pages/core/theming.adoc
Labels: backport

#2389 [10.3] [PR 2281] Add missing core theming documentation
  modules/developer_manual/assets/images/core/theming/2_ow_login.png
  modules/developer_manual/assets/images/core/theming/3_cu_login.png
  modules/developer_manual/assets/images/core/theming/4_oc_header.png
  modules/developer_manual/assets/images/core/theming/5_cu_header.png
  modules/developer_manual/pages/core/theming.adoc
Labels: backport

#2316 Redirect the external storage configuration to the relevant occ commands
  modules/admin_manual/pages/configuration/files/external_storage_configuration.adoc
  modules/admin_manual/pages/configuration/server/occ_command.adoc
Labels: admin docs, p4-low, waiting on feedback

#2395 [10.4] [PR 2316] Redirect the external storage configuration to the relevant occ commands
  modules/admin_manual/pages/configuration/files/external_storage_configuration.adoc
  modules/admin_manual/pages/configuration/server/occ_command.adoc
Labels: backport

#2406 [master] [PR 2401] mention quick eval option
  modules/admin_manual/pages/installation/docker/index.adoc
Labels: backport

#2405 [10.3] [PR 2401] mention quick eval option
  modules/admin_manual/pages/installation/docker/index.adoc
Labels: backport

#2408 Remove link to deprecated external storage configuration documentation
  modules/admin_manual/nav.adoc
Labels: admin docs, backport, bug

#2407 Remove link to deprecated external storage configuration documentation
  modules/admin_manual/nav.adoc
Labels: admin docs, backport, bug

#2409 [10.3] [PR 2397] Ransomware protection list updated
  modules/admin_manual/pages/enterprise/security/ransomware-protection/index.adoc
Labels: backport

#2410 [10.4] [PR 2397] Ransomware protection list updated
  modules/admin_manual/pages/enterprise/security/ransomware-protection/index.adoc
Labels: backport

#2348 Improve excluded_and_blacklisted_doc
  modules/admin_manual/pages/configuration/server/excluded_blacklisted_files.adoc
Labels: admin docs

#2411 [10.3] [PR 2348] Improve excluded_and_blacklisted_doc
  modules/admin_manual/pages/configuration/server/excluded_blacklisted_files.adoc
Labels: backport

#2412 [10.4] [PR 2348] Improve excluded_and_blacklisted_doc
  modules/admin_manual/pages/configuration/server/excluded_blacklisted_files.adoc
Labels: backport

#2400 Backporting page update
  modules/developer_manual/pages/general/backporting.adoc
Labels: developer docs

#2414 [10.4] [PR 2400] Backporting page update
  modules/developer_manual/pages/general/backporting.adoc
Labels: backport

#2413 [10.3] [PR 2400] Backporting page update
  modules/developer_manual/pages/general/backporting.adoc
Labels: backport

#2368 Update ubuntu install example in admin manual nav structure
  modules/admin_manual/nav.adoc
Labels: clean up, installation & configuration

#2393 Document the changes to the Activity app in ver 2.5.3
  modules/admin_manual/pages/configuration/server/app_commands/activity_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command.adoc
  modules/user_manual/pages/apps/activity.adoc
Labels: admin docs, apps, enhancement, occ, p3-medium, user docs, waiting on feedback

#2110 Document OIDC in ownCloudDocument OIDC in ownCloud
  modules/admin_manual/assets/images/configuration/user/oidc/OAuth-code-flow-sequence-diagram.png
  modules/admin_manual/nav.adoc
  modules/admin_manual/pages/configuration/user/oidc/index.adoc
Labels: admin docs, p2-high

#2415 [10.3] [PR 2368] Update ubuntu install example in admin manual nav st…
  modules/admin_manual/nav.adoc
Labels: backport

#2416 [10.4] [PR 2368] Update ubuntu install example in admin manual nav st…
  modules/admin_manual/nav.adoc
Labels: backport

#2418 [10.4] [PR 2393] Document the changes to the Activity app in ver 2.5.3
  modules/admin_manual/pages/configuration/server/app_commands/activity_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command.adoc
  modules/user_manual/pages/apps/activity.adoc
Labels: backport

#2417 [10.3] [PR 2393] Document the changes to the Activity app in ver 2.5.3
  modules/admin_manual/pages/configuration/server/app_commands/activity_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command.adoc
  modules/user_manual/pages/apps/activity.adoc
Labels: backport

#2419 [10.4] [PR 2110] Document OIDC in ownCloudDocument OIDC in ownCloud
  modules/admin_manual/assets/images/configuration/user/oidc/OAuth-code-flow-sequence-diagram.png
  modules/admin_manual/nav.adoc
  modules/admin_manual/pages/configuration/user/oidc/index.adoc
Labels: backport

#2367 [2354] Replace lingering references to cron.php with system:cron
  modules/admin_manual/pages/configuration/files/federated_cloud_sharing_configuration.adoc
  modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc
  modules/admin_manual/pages/installation/ubuntu_18_04.adoc
  modules/developer_manual/pages/app/fundamentals/backgroundjobs.adoc
Labels: admin docs, command-line

#2421 [10.4] [PR 2367] [2354] Replace lingering references to cron.php with system:cron
  modules/admin_manual/pages/configuration/files/federated_cloud_sharing_configuration.adoc
  modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc
  modules/admin_manual/pages/installation/ubuntu_18_04.adoc
  modules/developer_manual/pages/app/fundamentals/backgroundjobs.adoc
Labels: backport

#2420 [10.3] [PR 2367] [2354] Replace lingering references to cron.php with system:cron
  modules/admin_manual/pages/configuration/files/federated_cloud_sharing_configuration.adoc
  modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc
  modules/admin_manual/pages/installation/ubuntu_18_04.adoc
  modules/developer_manual/pages/app/fundamentals/backgroundjobs.adoc
Labels: backport

#2426 Add a NOTE about volumes and about apps management
  modules/admin_manual/pages/installation/docker/index.adoc
Labels: admin docs, docker

#2394 [10.3] [PR 2316] Redirect the external storage configuration to the relevant occ commands
  modules/admin_manual/nav.adoc
  modules/admin_manual/pages/configuration/files/external_storage_configuration.adoc
  modules/admin_manual/pages/configuration/files/index.adoc
  modules/admin_manual/pages/configuration/server/occ_command.adoc
Labels: backport

#2428 Remove lingering xref pointing to external storage configuration
  modules/admin_manual/pages/configuration/files/index.adoc
Labels: admin docs, bug, deprecation, review required

#2429 Remove lingering xref pointing to external storage configuration
  modules/admin_manual/pages/configuration/files/index.adoc
Labels: 10.4, admin docs, bug, deprecation, review required

#2430 Small improvement for the post install script
  modules/admin_manual/examples/installation/post-installation-steps.sh
Labels: admin docs, enhancement

#2433 [10.3] [PR 2430] Small improvement for the post install script
  modules/admin_manual/examples/installation/post-installation-steps.sh
Labels: backport

#2434 [10.4] [PR 2430] Small improvement for the post install script
  modules/admin_manual/examples/installation/post-installation-steps.sh
Labels: backport

#2432 Improvement of Redis setup
  modules/admin_manual/pages/configuration/server/caching_configuration.adoc
Labels: admin docs

#2436 [10.4] [PR 2432] Improvement of Redis setup
  modules/admin_manual/pages/configuration/server/caching_configuration.adoc
Labels: backport

#2435 [10.3] [PR 2432] Improvement of Redis setup
  modules/admin_manual/pages/configuration/server/caching_configuration.adoc
Labels: backport

#2431 [2425] Integrate easier TLS config changes into the User Auth LDAP docs
  modules/admin_manual/assets/images/apps/user_ldap/ldap-wizard/advanced-tab-connection-settings.png
  modules/admin_manual/assets/images/apps/user_ldap/ldap-wizard/advanced-tab-directory-settings.png
  modules/admin_manual/assets/images/apps/user_ldap/ldap-wizard/advanced-tab-special-attributes.png
  modules/admin_manual/assets/images/apps/user_ldap/ldap-wizard/expert-tab.png
  modules/admin_manual/assets/images/apps/user_ldap/ldap-wizard/groups-tab.png
  modules/admin_manual/assets/images/apps/user_ldap/ldap-wizard/login-attributes-tab.png
  modules/admin_manual/assets/images/apps/user_ldap/ldap-wizard/server-tab.png
  modules/admin_manual/assets/images/apps/user_ldap/ldap-wizard/users-tab.png
  modules/admin_manual/examples/configuration/user/user_auth_ldap/group_filter.ldif
  modules/admin_manual/examples/configuration/user/user_auth_ldap/multi_group_search.ldif
  modules/admin_manual/examples/configuration/user/user_auth_ldap/only_username.ldif
  modules/admin_manual/examples/configuration/user/user_auth_ldap/single_group_search.ldif
  modules/admin_manual/examples/configuration/user/user_auth_ldap/username_email.ldif
  modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
Labels: LDAP, admin docs, p3-medium, review required, technical review, waiting on feedback

#2444 [10.4] [PR 2431] [2425] Integrate easier TLS config changes into the User Auth LDAP docs
  modules/admin_manual/assets/images/apps/user_ldap/ldap-wizard/advanced-tab-connection-settings.png
  modules/admin_manual/assets/images/apps/user_ldap/ldap-wizard/advanced-tab-directory-settings.png
  modules/admin_manual/assets/images/apps/user_ldap/ldap-wizard/advanced-tab-special-attributes.png
  modules/admin_manual/assets/images/apps/user_ldap/ldap-wizard/expert-tab.png
  modules/admin_manual/assets/images/apps/user_ldap/ldap-wizard/groups-tab.png
  modules/admin_manual/assets/images/apps/user_ldap/ldap-wizard/login-attributes-tab.png
  modules/admin_manual/assets/images/apps/user_ldap/ldap-wizard/server-tab.png
  modules/admin_manual/assets/images/apps/user_ldap/ldap-wizard/users-tab.png
  modules/admin_manual/examples/configuration/user/user_auth_ldap/group_filter.ldif
  modules/admin_manual/examples/configuration/user/user_auth_ldap/multi_group_search.ldif
  modules/admin_manual/examples/configuration/user/user_auth_ldap/only_username.ldif
  modules/admin_manual/examples/configuration/user/user_auth_ldap/single_group_search.ldif
  modules/admin_manual/examples/configuration/user/user_auth_ldap/username_email.ldif
  modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
Labels: backport

#2445 [10.3] [PR 2431] [2425] Integrate easier TLS config changes into the User Auth LDAP docs
  modules/admin_manual/assets/images/apps/user_ldap/ldap-wizard/advanced-tab-connection-settings.png
  modules/admin_manual/assets/images/apps/user_ldap/ldap-wizard/advanced-tab-directory-settings.png
  modules/admin_manual/assets/images/apps/user_ldap/ldap-wizard/advanced-tab-special-attributes.png
  modules/admin_manual/assets/images/apps/user_ldap/ldap-wizard/expert-tab.png
  modules/admin_manual/assets/images/apps/user_ldap/ldap-wizard/groups-tab.png
  modules/admin_manual/assets/images/apps/user_ldap/ldap-wizard/login-attributes-tab.png
  modules/admin_manual/assets/images/apps/user_ldap/ldap-wizard/server-tab.png
  modules/admin_manual/assets/images/apps/user_ldap/ldap-wizard/users-tab.png
  modules/admin_manual/examples/configuration/user/user_auth_ldap/group_filter.ldif
  modules/admin_manual/examples/configuration/user/user_auth_ldap/multi_group_search.ldif
  modules/admin_manual/examples/configuration/user/user_auth_ldap/only_username.ldif
  modules/admin_manual/examples/configuration/user/user_auth_ldap/single_group_search.ldif
  modules/admin_manual/examples/configuration/user/user_auth_ldap/username_email.ldif
  modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
Labels: backport

#2449 Remove all references to PHP versions prior to the min supported (7.1)
  modules/admin_manual/pages/configuration/server/caching_configuration.adoc
  modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
  modules/admin_manual/pages/enterprise/installation/oracle_db_configuration.adoc
  modules/admin_manual/pages/installation/configuration_notes_and_tips.adoc
  modules/admin_manual/pages/maintenance/upgrading/upgrade_php.adoc
  modules/developer_manual/pages/app/tutorial/requirements.adoc
  site.yml
Labels: bug, clean up, review required, technical review

#2452 Document how to retrieve PHP details from the command-line
  modules/admin_manual/pages/configuration/general_topics/general_troubleshooting.adoc
Labels: admin docs, enhancement

#2454 [10.4] Rename site attribute
  site.yml
Labels: bug

#2455 Rename site attribute to fix render bug
  site.yml
Labels: bug

#2456 [10.3] Merge changes to upgrade_php.adoc from 10.4
  modules/admin_manual/pages/_partials/maintenance/upgrading/upgrade_steps.adoc
  modules/admin_manual/pages/maintenance/upgrading/upgrade_php.adoc
Labels: backport, command-line, installation & configuration, review required, technical review

#2453 [10.3] Add missing text substitutions and enclose attribute in single quotes
  site.yml
Labels: admin docs, bug, clean up

#2427 compose down with everything?
  modules/admin_manual/pages/installation/docker/index.adoc
Labels: admin docs, clean up, docker

#2457 [10.4] [PR 2427] compose down with everything?
  modules/admin_manual/pages/installation/docker/index.adoc
Labels: backport

#2458 [10.3] [PR 2427] compose down with everything?
  modules/admin_manual/pages/installation/docker/index.adoc
Labels: backport

#2462 [10.4] Clarify the description of Office Online unlocking
  modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
Labels: clean up

#2464 [2448] Document that QuickTime is not supported in Chrome
  modules/admin_manual/pages/installation/apps/mediaviewer/index.adoc
  modules/user_manual/pages/files/media_viewer_app.adoc
Labels: enhancement, user docs

#2466 [10.3] [PR 2464] [2448] Document that QuickTime is not supported in Chrome
  modules/admin_manual/pages/installation/apps/mediaviewer/index.adoc
  modules/user_manual/pages/files/media_viewer_app.adoc
Labels: backport

#2465 [10.4] [PR 2464] [2448] Document that QuickTime is not supported in Chrome
  modules/admin_manual/pages/installation/apps/mediaviewer/index.adoc
  modules/user_manual/pages/files/media_viewer_app.adoc
Labels: backport, p3-medium

#2460 Improve server_prep_ubuntu_18.04
  modules/admin_manual/pages/installation/server_prep_ubuntu_18.04.adoc
Labels: admin docs

#2467 [10.3] [PR 2460] Improve server_prep_ubuntu_18.04
  modules/admin_manual/pages/installation/server_prep_ubuntu_18.04.adoc
Labels: backport

#2468 [10.4] [PR 2460] Improve server_prep_ubuntu_18.04
  modules/admin_manual/pages/installation/server_prep_ubuntu_18.04.adoc
Labels: backport

#2369 Document the options for the occ files:checksums:verify command
  modules/admin_manual/pages/configuration/server/occ_command/file_commands.adoc
Labels: admin docs, command-line, occ, waiting on feedback

#2473 [10.3] [PR 2369] Document the options for the occ files:checksums:verify command
  modules/admin_manual/pages/configuration/server/occ_command/file_commands.adoc
Labels: backport

#2472 [10.4] [PR 2369] Document the options for the occ files:checksums:verify command
  modules/admin_manual/pages/configuration/server/occ_command/file_commands.adoc
Labels: backport

#2423 Update background jobs selector documentation
  modules/admin_manual/pages/configuration/server/occ_command/background_jobs_selector.adoc
Labels: admin docs, command-line, review required, technical review

#2475 [10.4] [PR 2423] Update background jobs selector documentation
  modules/admin_manual/pages/configuration/server/occ_command/background_jobs_selector.adoc
Labels: backport

#2476 [10.3] [PR 2423] Update background jobs selector documentation
  modules/admin_manual/pages/configuration/server/occ_command/background_jobs_selector.adoc
Labels: backport

#2477 Deprecate the What's New page in the admin manual
  modules/admin_manual/nav.adoc
  modules/admin_manual/pages/index.adoc
  modules/admin_manual/pages/release_notes.adoc
  modules/admin_manual/pages/whats_new_admin.adoc
Labels: admin docs, deprecation, review required

#2474 [2469] Document Document Locking Issue With Office Online and Chrome
  modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
Labels: bug, enterprise docs, review required, technical review

#2485 Slight update to the files:transfer-ownership documentation
  modules/admin_manual/pages/configuration/server/occ_command/file_commands.adoc
Labels: admin docs, occ, question

#2486 [10.4] [PR 2485] Slight update to the files:transfer-ownership documentation
  modules/admin_manual/pages/configuration/server/occ_command/file_commands.adoc
Labels: backport

#2497 adding occ command files:check-cache
  modules/admin_manual/pages/configuration/server/occ_command/file_commands.adoc
Labels: 10.4, admin docs

#2499 Fix broken link to sync-exclude.list on GitHub
  modules/admin_manual/pages/faq/index.adoc
Labels: admin docs, bug

#2500 [10.4] [PR 2497] adding occ command files:check-cache
  modules/admin_manual/pages/configuration/server/occ_command/file_commands.adoc
Labels: backport

#2501 [10.4] [PR 2499] Fix broken link to sync-exclude.list on GitHub
  modules/admin_manual/pages/faq/index.adoc
Labels: backport

#2502 [10.3] [PR 2499] Fix broken link to sync-exclude.list on GitHub
  modules/admin_manual/pages/faq/index.adoc
Labels: backport

#2504 [10.3] [PR 1999] Update the WebDAV file/search properties
  modules/developer_manual/examples/core/webdav_api/search/request/search_files/search_body_with_properties.xml
  modules/developer_manual/pages/_partials/webdav_api/search/file_properties.adoc
Labels: backport

#2507 [10.3] [PR 2503] Update all external links to follow the style guide
  modules/admin_manual/pages/installation/deployment_recommendations.adoc
Labels: backport

#2506 [10.4] [PR 2503] Update all external links to follow the style guide
  modules/admin_manual/pages/installation/deployment_recommendations.adoc
Labels: backport

#2166 [269] Update Files Versions API documentation
  modules/developer_manual/examples/core/webdav_api/files_versions/successful-response-which-contains-files.xml
  modules/developer_manual/examples/core/webdav_api/files_versions/successful-response-which-contains-multiple-versions.xml
  modules/developer_manual/examples/core/webdav_api/files_versions/successful-response-which-contains-one-version.xml
  modules/developer_manual/pages/webdav_api/files_versions.adoc
  modules/developer_manual/pages/webdav_api/files_versions/list_files_versions.adoc
Labels: APIs, developer docs, review required, technical review, waiting on feedback

#2508 [10.4] [PR 2166] [269] Update Files Versions API documentation
  modules/developer_manual/examples/core/webdav_api/files_versions/successful-response-which-contains-files.xml
  modules/developer_manual/examples/core/webdav_api/files_versions/successful-response-which-contains-multiple-versions.xml
  modules/developer_manual/examples/core/webdav_api/files_versions/successful-response-which-contains-one-version.xml
  modules/developer_manual/pages/webdav_api/files_versions.adoc
  modules/developer_manual/pages/webdav_api/files_versions/list_files_versions.adoc
Labels: backport

#2509 [10.3] [PR 2166] [269] Update Files Versions API documentation
  modules/developer_manual/examples/core/webdav_api/files_versions/successful-response-which-contains-files.xml
  modules/developer_manual/examples/core/webdav_api/files_versions/successful-response-which-contains-multiple-versions.xml
  modules/developer_manual/examples/core/webdav_api/files_versions/successful-response-which-contains-one-version.xml
  modules/developer_manual/pages/webdav_api/files_versions.adoc
  modules/developer_manual/pages/webdav_api/files_versions/list_files_versions.adoc
Labels: backport

#2510 Adding php-ssh2 recommended for oidc
  modules/admin_manual/pages/installation/server_prep_ubuntu_18.04.adoc
Labels: admin docs

#2511 [10.4] [PR 2510] Adding php-ssh2 recommended for oidc
  modules/admin_manual/pages/installation/server_prep_ubuntu_18.04.adoc
Labels: backport

#2512 [10.3] [PR 2510] Adding php-ssh2 recommended for oidc
  modules/admin_manual/pages/installation/server_prep_ubuntu_18.04.adoc
Labels: backport

#683 Release notes foreign keys
  modules/admin_manual/pages/release_notes.adoc
Labels: waiting on feedback

#2514 [10.3] [PR 683] Release notes foreign keys
  modules/admin_manual/pages/release_notes.adoc
Labels: backport

#2515 [10.4] [PR 683] Release notes foreign keys
  modules/admin_manual/pages/release_notes.adoc
Labels: backport
