Repository owncloud/docs, pull requests merged in 2020-12, with the labels that each got.

#2918 Update access_webdav.adoc
  modules/user_manual/pages/files/access_webdav.adoc
Labels: user docs

#2920 [Backport 27fb479 10.5] added keyword to user manual: access webDAV
  modules/user_manual/pages/files/access_webdav.adoc
Labels: user docs

#2924 [Backport 10.4] added keyword to user manual: access webDAV
  modules/user_manual/pages/files/access_webdav.adoc
Labels: user docs

#2901 Update Google Drive (Allow subfolders for Google Drive mounts)
  modules/admin_manual/assets/images/configuration/files/external_storage/google_drive/015.png
  modules/admin_manual/assets/images/configuration/files/external_storage/google_drive/022.png
  modules/admin_manual/pages/configuration/files/external_storage/google.adoc
Labels: admin docs

#2928 Added example to user:sync in user_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/user_commands.adoc
Labels: admin docs, occ

#2937 Clarifying WND null Permission manager
  modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
Labels: admin docs

#2945 Missing config sample changes from core 10.6
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Labels: admin docs

#2946 [10.6] [PR 2945] Missing config sample changes from core 10.6
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Labels: backport

#2954 Update backporting.adoc
  modules/developer_manual/pages/general/backporting.adoc
Labels: admin docs

#2956 [10.6] [PR 2954] Update backporting.adoc
  modules/developer_manual/pages/general/backporting.adoc
Labels: backport

#2957 [10.5] [PR 2954] Update backporting.adoc
  modules/developer_manual/pages/general/backporting.adoc
Labels: backport

#2958 Improve Manual Installation
  modules/admin_manual/examples/installation/manual_installation/instance.sh
  modules/admin_manual/examples/installation/manual_installation/owncloud_prep.sh
  modules/admin_manual/examples/installation/ubuntu/18.04/memcache-configuration.php
  modules/admin_manual/nav.adoc
  modules/admin_manual/pages/_partials/configuration/server/occ_command/background_jobs_selector.adoc
  modules/admin_manual/pages/_partials/installation/manual_installation/mariadb.adoc
  modules/admin_manual/pages/configuration/database/linux_database_configuration.adoc
  modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc
  modules/admin_manual/pages/configuration/server/caching_configuration.adoc
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
  modules/admin_manual/pages/installation/command_line_installation.adoc
  modules/admin_manual/pages/installation/installation_wizard.adoc
  modules/admin_manual/pages/installation/linux_packetmanager_install.adoc
  modules/admin_manual/pages/installation/manual_installation.adoc
  modules/admin_manual/pages/installation/manual_installation/index.adoc
  modules/admin_manual/pages/installation/manual_installation/manual_installation.adoc
  modules/admin_manual/pages/installation/manual_installation/manual_installation_apache.adoc
  modules/admin_manual/pages/installation/manual_installation/manual_installation_db.adoc
  modules/admin_manual/pages/installation/manual_installation/manual_installation_prerequisites.adoc
  modules/admin_manual/pages/installation/manual_installation/script_guided_install.adoc
  modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_18.04.adoc
  modules/admin_manual/pages/installation/quick_guides/index.adoc
  modules/admin_manual/pages/installation/quick_guides/ubuntu_18_04.adoc
Labels: admin docs

#2963 [10.6] [PR 2958] Improve Manual Installation
  modules/admin_manual/examples/installation/manual_installation/instance.sh
  modules/admin_manual/examples/installation/manual_installation/owncloud_prep.sh
  modules/admin_manual/examples/installation/ubuntu/18.04/memcache-configuration.php
  modules/admin_manual/nav.adoc
  modules/admin_manual/pages/_partials/configuration/server/occ_command/background_jobs_selector.adoc
  modules/admin_manual/pages/_partials/installation/manual_installation/mariadb.adoc
  modules/admin_manual/pages/configuration/database/linux_database_configuration.adoc
  modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc
  modules/admin_manual/pages/configuration/server/caching_configuration.adoc
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
  modules/admin_manual/pages/installation/command_line_installation.adoc
  modules/admin_manual/pages/installation/installation_wizard.adoc
  modules/admin_manual/pages/installation/linux_packetmanager_install.adoc
  modules/admin_manual/pages/installation/manual_installation.adoc
  modules/admin_manual/pages/installation/manual_installation/index.adoc
  modules/admin_manual/pages/installation/manual_installation/manual_installation.adoc
  modules/admin_manual/pages/installation/manual_installation/manual_installation_apache.adoc
  modules/admin_manual/pages/installation/manual_installation/manual_installation_db.adoc
  modules/admin_manual/pages/installation/manual_installation/manual_installation_prerequisites.adoc
  modules/admin_manual/pages/installation/manual_installation/script_guided_install.adoc
  modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_18.04.adoc
  modules/admin_manual/pages/installation/quick_guides/index.adoc
  modules/admin_manual/pages/installation/quick_guides/ubuntu_18_04.adoc
Labels: backport

#2965 [10.6] [PR 2851] Update ubuntu_18_04.adoc
  modules/admin_manual/pages/installation/quick_guides/ubuntu_18_04.adoc
Labels: backport

#2966 [10.5] [PR 2851] Update ubuntu_18_04.adoc
  modules/admin_manual/pages/installation/quick_guides/ubuntu_18_04.adoc
Labels: backport

#2967 [10.4] [PR 2851] Update ubuntu_18_04.adoc
  modules/admin_manual/pages/installation/ubuntu_18_04.adoc
Labels: backport

#2968 [10.6] [PR 2828] Update ubuntu_18_04.adoc
  modules/admin_manual/pages/installation/quick_guides/ubuntu_18_04.adoc
Labels: backport

#2969 [10.5] [PR 2828] Update ubuntu_18_04.adoc
  modules/admin_manual/pages/installation/quick_guides/ubuntu_18_04.adoc
Labels: backport

#2970 [10.6] [PR 2856] Add note about username and password
  modules/admin_manual/pages/installation/docker/index.adoc
Labels: backport

#2971 [10.5] [PR 2856] Add note about username and password
  modules/admin_manual/pages/installation/docker/index.adoc
Labels: backport

#2972 [10.6] [PR 2826] Update index.adoc
  modules/admin_manual/pages/installation/index.adoc
Labels: backport

#2973 [10.5] [PR 2826] Update index.adoc
  modules/admin_manual/pages/installation/index.adoc
Labels: backport

#2975 Small Fixes
  modules/admin_manual/assets/images/installation/top_menu_showing_market_app.png
  modules/admin_manual/nav.adoc
Labels: admin docs

#2976 [10.6] [PR 2975] Small Fixes
  modules/admin_manual/assets/images/installation/top_menu_showing_market_app.png
  modules/admin_manual/nav.adoc
Labels: backport

#2977 [10.5] [PR 2975] Small Fixes
  modules/admin_manual/assets/images/installation/top_menu_showing_market_app.png
  modules/admin_manual/nav.adoc
Labels: backport

#2978 force https for some links
  modules/admin_manual/pages/configuration/server/caching_configuration.adoc
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Labels: admin docs

#2979 [10.6] [PR 2978] force https for some links
  modules/admin_manual/pages/configuration/server/caching_configuration.adoc
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Labels: backport

#2980 [10.5] [PR 2978] force https for some links
  modules/admin_manual/pages/configuration/server/caching_configuration.adoc
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Labels: backport
