Repository owncloud/docs, pull requests merged in 2020-04, with the labels that each got.

#1673 Update Unit Testing Documentation
  modules/developer_manual/assets/attachments/core/Makefile.example
  modules/developer_manual/pages/testing/unit-testing.adoc
Labels: developer docs, enhancement, p4-low, waiting on feedback

#2517 [10.4] Update unit test documentation
  modules/developer_manual/assets/attachments/core/Makefile.example
  modules/developer_manual/pages/testing/unit-testing.adoc
Labels: backport

#2518 [10.3] Update unit test documentation
  modules/developer_manual/assets/attachments/core/Makefile.example
  modules/developer_manual/pages/testing/unit-testing.adoc
Labels: backport

#2527 [10.4] Remove old ownCloud9 phpunit docs
  modules/developer_manual/pages/testing/unit-testing.adoc
Labels: backport

#2528 [10.3] Remove old ownCloud9 phpunit docs
  modules/developer_manual/pages/testing/unit-testing.adoc
Labels: backport

#2530 Remove lingering user:sync Shibboleth example
  modules/admin_manual/pages/configuration/server/occ_command/user_commands.adoc
Labels: admin docs, review required, technical review, waiting on feedback

#2532 [10.3] [PR 2530] Remove lingering user:sync Shibboleth example
  modules/admin_manual/pages/configuration/server/occ_command/user_commands.adoc
Labels: backport

#2531 [10.4] [PR 2530] Remove lingering user:sync Shibboleth example
  modules/admin_manual/pages/configuration/server/occ_command/user_commands.adoc
Labels: backport

#2159 [2157] Document WebDAV Meta endpoint
  modules/developer_manual/examples/core/webdav_api/meta/meta-files-filter.xml
  modules/developer_manual/examples/core/webdav_api/meta/report-propfind.xml
  modules/developer_manual/examples/core/webdav_api/meta/response-failure.xml
  modules/developer_manual/examples/core/webdav_api/meta/response-success.xml
  modules/developer_manual/nav.adoc
  modules/developer_manual/pages/webdav_api/meta.adoc
  site.yml
Labels: APIs, developer docs, review required, technical review, waiting on feedback

#2534 [2522] Fix up build errors in the core documentation
  modules/admin_manual/pages/configuration/server/app_commands/password_policy_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command.adoc
  modules/admin_manual/pages/configuration/server/occ_command/security_commands.adoc
  modules/developer_manual/pages/app/fundamentals/routes.adoc
  modules/developer_manual/pages/app/tutorial/routes_and_controllers.adoc
  modules/developer_manual/pages/core/apis/ocs/notifications/ocs-endpoint-v1.adoc
  modules/developer_manual/pages/core/apis/ocs/user-sync-api.adoc
  modules/developer_manual/pages/webdav_api/files_versions/list_files_versions.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit.adoc
Labels: bug, review required, technical review

#2535 [10.3] [PR 2159] [2157] Document WebDAV Meta endpoint
  modules/developer_manual/examples/core/webdav_api/meta/meta-files-filter.xml
  modules/developer_manual/examples/core/webdav_api/meta/report-propfind.xml
  modules/developer_manual/examples/core/webdav_api/meta/response-failure.xml
  modules/developer_manual/examples/core/webdav_api/meta/response-success.xml
  modules/developer_manual/nav.adoc
  modules/developer_manual/pages/webdav_api/meta.adoc
  site.yml
Labels: backport, developer docs

#2536 [10.4] [PR 2159] [2157] Document WebDAV Meta endpoint
  modules/developer_manual/examples/core/webdav_api/meta/meta-files-filter.xml
  modules/developer_manual/examples/core/webdav_api/meta/report-propfind.xml
  modules/developer_manual/examples/core/webdav_api/meta/response-failure.xml
  modules/developer_manual/examples/core/webdav_api/meta/response-success.xml
  modules/developer_manual/nav.adoc
  modules/developer_manual/pages/webdav_api/meta.adoc
  site.yml
Labels: backport, developer docs

#2539 Backporting script: update git key names
  modules/developer_manual/examples/scripts/backport.sh
Labels: developer docs

#2541 [10.4] [PR 2539] Backporting script: update git key names
  modules/developer_manual/examples/scripts/backport.sh
Labels: backport, developer docs

#2540 [10.3] [PR 2539] Backporting script: update git key names
  modules/developer_manual/examples/scripts/backport.sh
Labels: backport, developer docs

#2542 Fix build errors in master
  modules/developer_manual/pages/_partials/webdav_api/search/file_properties.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit.adoc
Labels: bug, review required, technical review, waiting on feedback

#2543 Fix build errors in 10.4
  modules/developer_manual/pages/_partials/webdav_api/search/file_properties.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit.adoc
Labels: bug, review required, technical review, waiting on feedback

#2544 Fix leveloffset errors
  modules/user_manual/pages/apps/enterprise/admin_audit.adoc
Labels: bug, review required, technical review, waiting on feedback

#2533 [2529] Update federated cloud shares documentation
  modules/admin_manual/pages/configuration/files/federated_cloud_sharing_configuration.adoc
  modules/developer_manual/pages/core/apis/ocs-share-api.adoc
Labels: admin docs, installation & configuration, p4-low, review required, technical review, waiting on feedback

#2545 [10.4] [PR 2533] [2529] Update federated cloud shares documentation
  modules/admin_manual/pages/configuration/files/federated_cloud_sharing_configuration.adoc
  modules/developer_manual/pages/core/apis/ocs-share-api.adoc
Labels: backport

#2546 [10.3] [PR 2533] [2529] Update federated cloud shares documentation
  modules/admin_manual/pages/configuration/files/federated_cloud_sharing_configuration.adoc
  modules/developer_manual/pages/core/apis/ocs-share-api.adoc
Labels: backport

#2551 Correctly format the OAuth2 overview quote
  modules/admin_manual/pages/configuration/server/security/oauth2.adoc
Labels: admin docs, bug

#2549 Document OAuth2 app requirements
  modules/admin_manual/pages/configuration/server/security/oauth2.adoc
Labels: admin docs, installation & configuration, p3-medium, review required, technical review

#2558 [10.4] [PR 2549] Document OAuth2 app requirements
  modules/admin_manual/pages/configuration/server/security/oauth2.adoc
Labels: backport

#2523 Document that files:transfer-ownership changes in 10.4.1
  modules/admin_manual/pages/configuration/server/occ_command/file_commands.adoc
Labels: 10.4, admin docs, occ

#2562 [10.4] [PR 2523] Document that files:transfer-ownership changes in 10.4.1
  modules/admin_manual/pages/configuration/server/occ_command/file_commands.adoc
Labels: backport

#2563 Update developer manual database fundamentals documentation
  modules/developer_manual/examples/app/fundamentals/database/author-access-attributes.php
  modules/developer_manual/examples/app/fundamentals/database/author.php
  modules/developer_manual/examples/app/fundamentals/database/authormapper.php
  modules/developer_manual/examples/app/fundamentals/database/create-migration-step.php
  modules/developer_manual/examples/app/fundamentals/database/custom-attribute-to-database-column-mapping.php
  modules/developer_manual/examples/app/fundamentals/database/database-access.php
  modules/developer_manual/examples/app/fundamentals/database/migrations.php
  modules/developer_manual/examples/app/fundamentals/database/schema-migration-step.php
  modules/developer_manual/examples/app/fundamentals/database/schema-update.xml
  modules/developer_manual/examples/app/fundamentals/database/slug.php
  modules/developer_manual/examples/app/fundamentals/database/sql-migration-step.php
  modules/developer_manual/pages/app/fundamentals/database.adoc
Labels: clean up, developer docs, review required, technical review

#2564 [10.4] [PR 2563] Update developer manual database fundamentals documentation
  modules/developer_manual/examples/app/fundamentals/database/author-access-attributes.php
  modules/developer_manual/examples/app/fundamentals/database/author.php
  modules/developer_manual/examples/app/fundamentals/database/authormapper.php
  modules/developer_manual/examples/app/fundamentals/database/create-migration-step.php
  modules/developer_manual/examples/app/fundamentals/database/custom-attribute-to-database-column-mapping.php
  modules/developer_manual/examples/app/fundamentals/database/database-access.php
  modules/developer_manual/examples/app/fundamentals/database/migrations.php
  modules/developer_manual/examples/app/fundamentals/database/schema-migration-step.php
  modules/developer_manual/examples/app/fundamentals/database/schema-update.xml
  modules/developer_manual/examples/app/fundamentals/database/slug.php
  modules/developer_manual/examples/app/fundamentals/database/sql-migration-step.php
  modules/developer_manual/pages/app/fundamentals/database.adoc
Labels: backport

#2516 Add Server 10.4.1 release notes
  modules/admin_manual/pages/release_notes.adoc
Labels: 10.4

#2565 [10.3] [PR 2563] Update developer manual database fundamentals documentation
  modules/developer_manual/examples/app/fundamentals/database/author-access-attributes.php
  modules/developer_manual/examples/app/fundamentals/database/author.php
  modules/developer_manual/examples/app/fundamentals/database/authormapper.php
  modules/developer_manual/examples/app/fundamentals/database/create-migration-step.php
  modules/developer_manual/examples/app/fundamentals/database/custom-attribute-to-database-column-mapping.php
  modules/developer_manual/examples/app/fundamentals/database/database-access.php
  modules/developer_manual/examples/app/fundamentals/database/migrations.php
  modules/developer_manual/examples/app/fundamentals/database/schema-migration-step.php
  modules/developer_manual/examples/app/fundamentals/database/schema-update.xml
  modules/developer_manual/examples/app/fundamentals/database/slug.php
  modules/developer_manual/examples/app/fundamentals/database/sql-migration-step.php
  modules/developer_manual/pages/app/fundamentals/database.adoc
Labels: backport

#2567 [10.4] Add Server 10.4.1 release notes
  modules/admin_manual/pages/release_notes.adoc
Labels: 10.4

#2557 Update finalise-install to render correctly
  modules/admin_manual/examples/installation/ubuntu/18.04/finalise-install.sh
  modules/admin_manual/pages/installation/ubuntu_18_04.adoc
Labels: bug, review required, technical review

#2569 [10.4] [PR 2557] Update finalise-install to render correctly
  modules/admin_manual/examples/installation/ubuntu/18.04/finalise-install.sh
  modules/admin_manual/pages/installation/ubuntu_18_04.adoc
Labels: backport

#2571 [10.3] [PR 2557] Update finalise-install to render correctly
  modules/admin_manual/examples/installation/ubuntu/18.04/finalise-install.sh
  modules/admin_manual/pages/installation/ubuntu_18_04.adoc
Labels: backport

#2573 [10.1] [PR 2557] Update finalise-install to render correctly
  modules/admin_manual/examples/installation/ubuntu/18.04/finalise-install.sh
  modules/admin_manual/pages/installation/ubuntu_18_04.adoc
Labels: backport

#2574 [10.4] [PR 2570] Update finalise install script
  modules/admin_manual/examples/installation/ubuntu/18.04/finalise-install.sh
Labels: backport

#2575 [10.3] [PR 2570] Update finalise install script
  modules/admin_manual/examples/installation/ubuntu/18.04/finalise-install.sh
Labels: backport

#2576 [10.2] [PR 2570] Update finalise install script
  modules/admin_manual/examples/installation/ubuntu/18.04/finalise-install.sh
Labels: backport

#2577 [10.1] [PR 2570] Update finalise install script
  modules/admin_manual/examples/installation/ubuntu/18.04/finalise-install.sh
Labels: backport

#2561 Add missing Redis server to recommended system requirements image
  modules/admin_manual/assets/images/installation/deprecs-2.odg
  modules/admin_manual/assets/images/installation/deprecs-2.png
Labels: admin docs, review required, waiting on feedback

#2581 [10.4] [PR 2561] Add missing Redis server to recommended system requirements image
  modules/admin_manual/assets/images/installation/deprecs-2.odg
  modules/admin_manual/assets/images/installation/deprecs-2.png
Labels: backport

#2578 [10.1] [PR 2561] Add missing Redis server to recommended system requirements image
  modules/admin_manual/assets/images/installation/deprecs-2.odg
  modules/admin_manual/assets/images/installation/deprecs-2.png
Labels: backport

#2580 [10.3] [PR 2561] Add missing Redis server to recommended system requirements image
  modules/admin_manual/assets/images/installation/deprecs-2.odg
  modules/admin_manual/assets/images/installation/deprecs-2.png
Labels: backport

#2579 [10.2] [PR 2561] Add missing Redis server to recommended system requirements image
  modules/admin_manual/assets/images/installation/deprecs-2.odg
  modules/admin_manual/assets/images/installation/deprecs-2.png
Labels: backport

#2584 Fix .htaccess permissions and file owner in finalise-install script
  modules/admin_manual/examples/installation/ubuntu/18.04/finalise-install.sh
Labels: bug, installation & configuration, review required, technical review

#2585 [10.1] [PR 2584] Fix .htaccess permissions and file owner in finalise-install script
  modules/admin_manual/examples/installation/ubuntu/18.04/finalise-install.sh
Labels: backport

#2586 [10.2] [PR 2584] Fix .htaccess permissions and file owner in finalise-install script
  modules/admin_manual/examples/installation/ubuntu/18.04/finalise-install.sh
Labels: backport

#2587 [10.3] [PR 2584] Fix .htaccess permissions and file owner in finalise-install script
  modules/admin_manual/examples/installation/ubuntu/18.04/finalise-install.sh
Labels: backport

#2588 [10.4] [PR 2584] Fix .htaccess permissions and file owner in finalise-install script
  modules/admin_manual/examples/installation/ubuntu/18.04/finalise-install.sh
Labels: backport

#2589 Update finalise-install script
  modules/admin_manual/examples/installation/ubuntu/18.04/finalise-install.sh
Labels: bug, installation & configuration, review required, technical review

#2591 Add site-wide variable for managing the outdated docs status
  site.yml
Labels: enhancement

#2592 Add site-wide variable for managing the outdated docs status
  site.yml
Labels: enhancement

#2590 Add site-wide variable for managing the outdated docs status
  site.yml
Labels: enhancement

#2593 Add site-wide variable for managing the outdated docs status
  site.yml
Labels: enhancement

#2594 Add site-wide variable for managing the outdated docs status
  site.yml
Labels: enhancement

#2600 [10.4] [PR 2589] Update finalise-install script
  modules/admin_manual/examples/installation/ubuntu/18.04/finalise-install.sh
Labels: backport

#2599 [10.3] [PR 2589] Update finalise-install script
  modules/admin_manual/examples/installation/ubuntu/18.04/finalise-install.sh
Labels: backport

#2598 [10.2] [PR 2589] Update finalise-install script
  modules/admin_manual/examples/installation/ubuntu/18.04/finalise-install.sh
Labels: backport

#2597 [10.1] [PR 2589] Update finalise-install script
  modules/admin_manual/examples/installation/ubuntu/18.04/finalise-install.sh
Labels: backport

#2601 Add Drone environment variable to set the latest version
  .drone.yml
Labels: deployment, review required, technical review

#2596 Update create-vhost-config.sh
  modules/admin_manual/examples/installation/ubuntu/18.04/create-vhost-config.sh
Labels: installation & configuration

#2604 [10.3] [PR 2601] Add Drone environment variable to set the latest version
  .drone.yml
Labels: backport

#2603 [10.4] [PR 2601] Add Drone environment variable to set the latest version
  .drone.yml
Labels: backport

#2606 [10.4] [PR 2596] Update create-vhost-config.sh
  modules/admin_manual/examples/installation/ubuntu/18.04/create-vhost-config.sh
Labels: backport

#2607 [10.2] [PR 2601] Add Drone environment variable to set the latest version
  .drone.yml
Labels: backport

#2605 [10.3] [PR 2596] Update create-vhost-config.sh
  modules/admin_manual/examples/installation/ubuntu/18.04/create-vhost-config.sh
Labels: backport

#2608 [10.1] [PR 2601] Add Drone environment variable to set the latest version
  .drone.yml
Labels: backport

#2616 Fix invalid xrefs
  modules/ROOT/pages/index.adoc
  modules/admin_manual/pages/release_notes.adoc
Labels: bug, p2-high, review required

#2613 Add 10.4 branch to 10.3 build
  site.yml
Labels: bug, p2-high, review required

#2614 Add 10.4 to 10.2 build
  site.yml
Labels: bug, p2-high, review required

#2615 Add 10.4 to the 10.1 build
  site.yml
Labels: bug, p2-high, review required

#2602 Remove orphaned NGINX configuration documentation
  modules/admin_manual/pages/installation/nginx_configuration.adoc
Labels: clean up
