Repository owncloud/docs, pull requests merged in 2020-02, with the labels that each got.

#2273 [10.4] [PR 2154] Update the formatting of the installation instructions
  modules/admin_manual/examples/installation/appinfo.xml
  modules/admin_manual/pages/installation/apps_management_installation.adoc
  site.yml
Labels: backport

#2274 [10.3] [PR 2154] Update the formatting of the installation instructions
  modules/admin_manual/examples/installation/appinfo.xml
  modules/admin_manual/pages/installation/apps_management_installation.adoc
  site.yml
Labels: backport

#2271 Correct level offset values for included pages
  modules/admin_manual/pages/configuration/server/occ_command/database_conversion_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/sharing_commands.adoc
Labels: review required, waiting on feedback

#2275 [10.3] [PR 2271] Correct level offset values for included pages
  modules/admin_manual/pages/configuration/server/occ_command/database_conversion_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/sharing_commands.adoc
Labels: backport

#2276 [10.4] [PR 2271] Correct level offset values for included pages
  modules/admin_manual/pages/configuration/server/occ_command/database_conversion_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/sharing_commands.adoc
Labels: backport

#2272 Document the Admin Audit app
  modules/user_manual/nav.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/apps.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/auth.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/comments.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/config.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/console.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/custom_groups.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/file_lifecycle.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/files.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/holding_period.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/impersonate.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/sharing.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/smb_acl.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/tags.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/user_preference.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/users.adoc
Labels: work in progress

#2283 [10.3] [PR 2272] Document the Admin Audit app
  modules/user_manual/nav.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/apps.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/auth.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/comments.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/config.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/console.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/custom_groups.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/file_lifecycle.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/files.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/holding_period.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/impersonate.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/sharing.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/smb_acl.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/tags.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/user_preference.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/users.adoc
Labels: backport

#2282 [10.4] [PR 2272] Document the Admin Audit app
  modules/user_manual/nav.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/apps.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/auth.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/comments.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/config.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/console.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/custom_groups.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/file_lifecycle.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/files.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/holding_period.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/impersonate.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/sharing.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/smb_acl.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/tags.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/user_preference.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/users.adoc
Labels: backport

#2285 [10.3] [PR 2280] Square Parenthesis needed
  modules/developer_manual/examples/core/scripts/curl/ocs/notify-public-link-by-email.sh
Labels: backport

#2286 [10.4] [PR 2280] Square Parenthesis needed
  modules/developer_manual/examples/core/scripts/curl/ocs/notify-public-link-by-email.sh
Labels: backport

#2288 [10.4] [PR 2287] fix simple typo
  modules/user_manual/pages/session_management.adoc
Labels: backport

#2289 [10.3] [PR 2287] fix simple typo
  modules/user_manual/pages/session_management.adoc
Labels: backport

#2290 Update of config.sample files with latest changes from core
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Labels: admin docs

#2291 [10.4] [PR 2290] Update of config.sample files with latest changes from core
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Labels: 10.4, backport

#2245 Move release notes and what's new pages to the ROOT module
  modules/ROOT/nav.adoc
  modules/ROOT/pages/release_notes.adoc
  modules/ROOT/pages/whats_new_admin.adoc
  modules/admin_manual/nav.adoc
  modules/user_manual/nav.adoc
  modules/user_manual/pages/whats_new.adoc
Labels: clean up, review required, waiting on feedback

#2263 Remove unused Apache environment variables
  modules/admin_manual/pages/installation/manual_installation.adoc
Labels: admin docs, installation & configuration, review required, technical review

#2298 [2293] Add mimetype list to the firewall docs
  modules/admin_manual/assets/images/enterprise/firewall/block-by-mimetype-configuration.png
  modules/admin_manual/pages/enterprise/firewall/file_firewall.adoc
Labels: admin docs, review required, security, technical review

#2303 [10.3] [PR 2298] [2293] Add mimetype list to the firewall docs
  modules/admin_manual/assets/images/enterprise/firewall/block-by-mimetype-configuration.png
  modules/admin_manual/pages/enterprise/firewall/file_firewall.adoc
Labels: backport

#2306 [10.4] [PR 2299] 10.4 Release notes
  modules/admin_manual/pages/release_notes.adoc
  site.yml
Labels: backport

#2308 [10.4] [PR 2307] Add PHP 7.1 deprecation note to 10.4 release notes
  modules/admin_manual/pages/release_notes.adoc
Labels: backport

#2305 [10.3] [PR 2299] 10.4 Release notes
  modules/admin_manual/pages/release_notes.adoc
  site.yml
Labels: backport

#2309 [10.3] [PR 2307] Add PHP 7.1 deprecation note to 10.4 release notes
  modules/admin_manual/pages/release_notes.adoc
Labels: backport

#2310 Add missing occ commands
  modules/admin_manual/pages/configuration/server/occ_command.adoc
Labels: bug

#2304 [10.4] [PR 2298] [2293] Add mimetype list to the firewall docs
  modules/admin_manual/assets/images/enterprise/firewall/block-by-mimetype-configuration.png
  modules/admin_manual/pages/enterprise/firewall/file_firewall.adoc
Labels: backport

#2284 Update the navigation files to fix the navigation bug in the PDF files
  modules/admin_manual/nav.adoc
  modules/developer_manual/nav.adoc
  modules/developer_manual/pages/index.adoc
  modules/user_manual/nav.adoc
Labels: admin docs, bug, developer docs, review required, user docs

#2312 [10.4] [PR 2310] Add missing occ commands
  modules/admin_manual/pages/configuration/server/occ_command.adoc
Labels: backport

#2311 [10.3] [PR 2310] Add missing occ commands
  modules/admin_manual/pages/configuration/server/occ_command.adoc
Labels: backport

#2315 [10.4] [PR 2284] Update the navigation files to fix the navigation bug in the PDF files
  modules/admin_manual/nav.adoc
  modules/developer_manual/nav.adoc
  modules/developer_manual/pages/index.adoc
  modules/user_manual/nav.adoc
Labels: backport

#2314 [10.3] [PR 2284] Update the navigation files to fix the navigation bug in the PDF files
  modules/admin_manual/nav.adoc
  modules/developer_manual/nav.adoc
  modules/developer_manual/pages/index.adoc
  modules/user_manual/nav.adoc
Labels: backport

#2329 Correct grammar mistake in the file firewall docs
  modules/admin_manual/pages/enterprise/firewall/file_firewall.adoc
Labels: admin docs

#2331 [10.4] [PR 2329] Correct grammar mistake in the file firewall docs
  modules/admin_manual/pages/enterprise/firewall/file_firewall.adoc
Labels: admin docs, backport

#2330 [10.3] [PR 2329] Correct grammar mistake in the file firewall docs
  modules/admin_manual/pages/enterprise/firewall/file_firewall.adoc
Labels: admin docs, backport

#2335 Add Mobile OS back in and remove redundant desktop OS section
  modules/admin_manual/pages/installation/system_requirements.adoc
Labels: clean up, review required

#2333 Backport changes in system requirements from 10.3 to 10.4
  modules/admin_manual/pages/installation/system_requirements.adoc
Labels: admin docs, backport

#2337 [10.4] [PR 2319] add common mimetypes
  modules/admin_manual/pages/enterprise/firewall/file_firewall.adoc
Labels: 10.4, backport

#2338 [10.3] [PR 2319] add common mimetypes
  modules/admin_manual/pages/enterprise/firewall/file_firewall.adoc
Labels: backport

#2332 Forward port system requirements differences in 10.3
  modules/admin_manual/pages/installation/system_requirements.adoc
Labels: backport

#2339 Update manually-moving-data-folders.adoc
  modules/admin_manual/pages/maintenance/manually-moving-data-folders.adoc
Labels: admin docs
