Repository owncloud/docs, pull requests merged in 2021-12, with the labels that each got.

#4434 Removal of Openstack, see changelog of 10.3
  modules/admin_manual/pages/_partials/nav.adoc
  modules/admin_manual/pages/configuration/files/external_storage/openstack.adoc
Labels: admin docs

#4435 [10.9] [PR 4434] Removal of Openstack, see changelog of 10.3
  modules/admin_manual/pages/_partials/nav.adoc
  modules/admin_manual/pages/configuration/files/external_storage/openstack.adoc
Labels: backport

#4436 [10.8] [PR 4434] Removal of Openstack, see changelog of 10.3
  modules/admin_manual/pages/_partials/nav.adoc
  modules/admin_manual/pages/configuration/files/external_storage/openstack.adoc
Labels: backport

#4437 [10.7] [PR 4434] Removal of Openstack, see changelog of 10.3
  modules/admin_manual/pages/_partials/nav.adoc
  modules/admin_manual/pages/configuration/files/external_storage/openstack.adoc
Labels: backport

#4442 [10.9] [PR 4441] add more known and patched jquery issues
  modules/admin_manual/pages/configuration/server/security/jquery_warnings.adoc
Labels: backport

#4443 [10.8] [PR 4441] add more known and patched jquery issues
  modules/admin_manual/pages/configuration/server/security/jquery_warnings.adoc
Labels: backport

#4444 [10.7] [PR 4441] add more known and patched jquery issues
  modules/admin_manual/pages/configuration/server/security/jquery_warnings.adoc
Labels: backport

#4440 Add guide for registering file actions in JavaScript
  modules/developer_manual/pages/app/fundamentals/js.adoc
Labels: developer docs

#4300 occ LDAP update
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_ldap_integration_commands.adoc
Labels: admin docs

#4446 [10.9] [PR 4445] remove hint about 2FA in notifications API dev doc
  modules/developer_manual/pages/core/apis/ocs-notification-endpoint-v1.adoc
Labels: backport

#4447 [10.8] [PR 4445] remove hint about 2FA in notifications API dev doc
  modules/developer_manual/pages/core/apis/ocs-notification-endpoint-v1.adoc
Labels: backport

#4448 [10.7] [PR 4445] remove hint about 2FA in notifications API dev doc
  modules/developer_manual/pages/core/apis/ocs-notification-endpoint-v1.adoc
Labels: backport

#4449 [10.9] [PR 4440] Add guide for registering file actions in JavaScript
  modules/developer_manual/pages/app/fundamentals/js.adoc
Labels: backport

#4450 [10.8] [PR 4440] Add guide for registering file actions in JavaScript
  modules/developer_manual/pages/app/fundamentals/js.adoc
Labels: backport

#4451 [10.7] [PR 4440] Add guide for registering file actions in JavaScript
  modules/developer_manual/pages/app/fundamentals/js.adoc
Labels: backport

#4452 [10.9] [PR 4300] occ LDAP update
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_ldap_integration_commands.adoc
Labels: backport

#4453 [10.8] [PR 4300] occ LDAP update
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_ldap_integration_commands.adoc
Labels: backport

#4454 Add note for user:move occ command
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_user_commands.adoc
Labels: admin docs

#4458 [10.8] [PR 4455] Minor edits after occ LDAP update PR 4300
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_ldap_integration_commands.adoc
Labels: backport

#4457 [10.9] [PR 4455] Minor edits after occ LDAP update PR 4300
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_ldap_integration_commands.adoc
Labels: backport

#4456 [10.9] [PR 4454] Add note for user:move occ command
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_user_commands.adoc
Labels: backport

#4464 Changes necessary for the iOS 11.8 branch
  modules/ROOT/pages/client_releases.adoc
  site.yml
Labels: deployment

#4465 [10.9] [4464] Changes necessary for the iOS 11.8 branch
  modules/ROOT/pages/client_releases.adoc
  site.yml
Labels: backport

#4468 [10.7] [4464] Changes necessary for the iOS 11.8 branch
  modules/ROOT/pages/client_releases.adoc
  site.yml
Labels: backport

#4469 [10.8] [4464] Changes necessary for the iOS 11.8 branch
  modules/ROOT/pages/client_releases.adoc
  site.yml
Labels: backport

#4470 Fixing the ios-app client attribute
  modules/ROOT/pages/client_releases.adoc
Labels: deployment

#4471 [10.9] [PR 4470] Fixing the ios-app client attribute
  modules/ROOT/pages/client_releases.adoc
Labels: backport

#4472 [10.9] [PR 4155] Content for search elastic v2
  modules/admin_manual/pages/configuration/search/index.adoc
  modules/user_manual/pages/files/webgui/search.adoc
Labels: backport

#4473 [10.8] [PR 4155] Content for search elastic v2
  modules/admin_manual/pages/configuration/search/index.adoc
  modules/user_manual/pages/files/webgui/search.adoc
Labels: backport

#4474 [10.7] [PR 4155] Content for search elastic v2
  modules/admin_manual/pages/configuration/search/index.adoc
  modules/user_manual/pages/files/webgui/search.adoc
Labels: backport

#4475 fixing error in wildcards
  modules/user_manual/pages/files/webgui/search.adoc
Labels: admin docs

#4476 [10.9] [PR 4475] fixing error in wildcards
  modules/user_manual/pages/files/webgui/search.adoc
Labels: backport

#4477 [10.8] [PR 4475] fixing error in wildcards
  modules/user_manual/pages/files/webgui/search.adoc
Labels: backport

#4478 [10.7] [PR 4475] fixing error in wildcards
  modules/user_manual/pages/files/webgui/search.adoc
Labels: backport

#4485 [10.9] [PR 4484] Add limitations to Secure View documentation
  modules/admin_manual/pages/enterprise/collaboration/collabora_secure_view.adoc
Labels: backport

#4486 [10.8] [PR 4484] Add limitations to Secure View documentation
  modules/admin_manual/pages/enterprise/collaboration/collabora_secure_view.adoc
Labels: backport

#4487 [10.7] [PR 4484] Add limitations to Secure View documentation
  modules/admin_manual/pages/enterprise/collaboration/collabora_secure_view.adoc
Labels: backport

#4482 Add rsync to the manuall install prerequisites
  modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_18.04.adoc
  modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc
Labels: admin docs

#4483 Do not use temp directory targets for user:move
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_user_commands.adoc
Labels: admin docs

#4489 [10.9] [PR 4483] Do not use temp directory targets for user:move
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_user_commands.adoc
Labels: backport

#4488 [10.9] [PR 4482] Add rsync to the manuall install prerequisites
  modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_18.04.adoc
  modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc
Labels: backport

#4493 config-to-docs run
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Labels: admin docs

#4494 [10.9] [PR 4493] config-to-docs run
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Labels: backport

#4496 [10.9] [PR 4495] Explain quota and last_login fields of Get User API response
  modules/developer_manual/pages/core/apis/provisioning-api.adoc
Labels: backport

#4497 [10.8] [PR 4495] Explain quota and last_login fields of Get User API response
  modules/developer_manual/pages/core/apis/provisioning-api.adoc
Labels: backport

#4498 [10.7] [PR 4495] Explain quota and last_login fields of Get User API response
  modules/developer_manual/pages/core/apis/provisioning-api.adoc
Labels: backport

#4500 Move branch specific attributes from global site.yml to branch relevant antora.yml
  antora.yml
  site.yml
Labels: deployment

#4501 [10.9] [PR 4500] Move branch specific attributes from global site.yml to branch relevant antora.yml
  antora.yml
  site.yml
Labels: backport

#4502 [10.8] [PR 4500] Move branch specific attributes from global site.yml to branch relevant antora.yml
  antora.yml
  site.yml
Labels: backport

#4503 [10.7] [PR 4500] Move branch specific attributes from global site.yml to branch relevant antora.yml
  antora.yml
  site.yml
Labels: backport

#4499 Document occ user:home
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_user_commands.adoc
  modules/admin_manual/pages/configuration/user/user_management.adoc
Labels: admin docs

#4504 Correct php values for 10.8 only
  antora.yml
Labels: deployment

#4505 Correct php values for 10.7 only
  antora.yml
Labels: deployment

#4506 [10.9] [PR 4499] Document occ user:home
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_user_commands.adoc
  modules/admin_manual/pages/configuration/user/user_management.adoc
Labels: backport

#4509 Update Manual File Locking
  modules/admin_manual/assets/images/configuration/files/manual_file_locking/file-locked-details.png
  modules/admin_manual/assets/images/configuration/files/manual_file_locking/file-locked-hint.png
  modules/admin_manual/assets/images/configuration/files/manual_file_locking/file-locked-symbol.png
  modules/admin_manual/assets/images/configuration/files/manual_file_locking/file-locked-unlock-symbol.png
  modules/admin_manual/assets/images/configuration/files/manual_file_locking/lock-file-not-visible.png
  modules/admin_manual/assets/images/configuration/files/manual_file_locking/lock-file-visible.png
  modules/admin_manual/assets/images/configuration/files/manual_file_locking/manual-file-locking-without-lock-breaker.png
  modules/admin_manual/pages/configuration/files/manual_file_locking.adoc
  modules/user_manual/assets/images/files/manual_file_locking/file-locked-details.png
  modules/user_manual/assets/images/files/manual_file_locking/file-locked-hint.png
  modules/user_manual/assets/images/files/manual_file_locking/file-locked-symbol.png
  modules/user_manual/assets/images/files/manual_file_locking/file-locked-unlock-symbol.png
  modules/user_manual/assets/images/files/manual_file_locking/lock-file-not-visible.png
  modules/user_manual/assets/images/files/manual_file_locking/lock-file-visible.png
  modules/user_manual/assets/images/files/manual_file_locking/manual-file-locking-without-lock-breaker.png
  modules/user_manual/pages/_partials/nav.adoc
  modules/user_manual/pages/files/manual_file_locking.adoc
Labels: user docs, admin docs

#4510 [10.9] [PR 4509] Update Manual File Locking
  modules/admin_manual/assets/images/configuration/files/manual_file_locking/file-locked-details.png
  modules/admin_manual/assets/images/configuration/files/manual_file_locking/file-locked-hint.png
  modules/admin_manual/assets/images/configuration/files/manual_file_locking/file-locked-symbol.png
  modules/admin_manual/assets/images/configuration/files/manual_file_locking/file-locked-unlock-symbol.png
  modules/admin_manual/assets/images/configuration/files/manual_file_locking/lock-file-not-visible.png
  modules/admin_manual/assets/images/configuration/files/manual_file_locking/lock-file-visible.png
  modules/admin_manual/assets/images/configuration/files/manual_file_locking/manual-file-locking-without-lock-breaker.png
  modules/admin_manual/pages/configuration/files/manual_file_locking.adoc
  modules/user_manual/assets/images/files/manual_file_locking/file-locked-details.png
  modules/user_manual/assets/images/files/manual_file_locking/file-locked-hint.png
  modules/user_manual/assets/images/files/manual_file_locking/file-locked-symbol.png
  modules/user_manual/assets/images/files/manual_file_locking/file-locked-unlock-symbol.png
  modules/user_manual/assets/images/files/manual_file_locking/lock-file-not-visible.png
  modules/user_manual/assets/images/files/manual_file_locking/lock-file-visible.png
  modules/user_manual/assets/images/files/manual_file_locking/manual-file-locking-without-lock-breaker.png
  modules/user_manual/pages/_partials/nav.adoc
  modules/user_manual/pages/files/manual_file_locking.adoc
Labels: backport

#4511 [10.8] [PR 4509] Update Manual File Locking
  modules/admin_manual/assets/images/configuration/files/manual_file_locking/file-locked-details.png
  modules/admin_manual/assets/images/configuration/files/manual_file_locking/file-locked-hint.png
  modules/admin_manual/assets/images/configuration/files/manual_file_locking/file-locked-symbol.png
  modules/admin_manual/assets/images/configuration/files/manual_file_locking/file-locked-unlock-symbol.png
  modules/admin_manual/assets/images/configuration/files/manual_file_locking/lock-file-not-visible.png
  modules/admin_manual/assets/images/configuration/files/manual_file_locking/lock-file-visible.png
  modules/admin_manual/assets/images/configuration/files/manual_file_locking/manual-file-locking-without-lock-breaker.png
  modules/admin_manual/pages/configuration/files/manual_file_locking.adoc
  modules/user_manual/assets/images/files/manual_file_locking/file-locked-details.png
  modules/user_manual/assets/images/files/manual_file_locking/file-locked-hint.png
  modules/user_manual/assets/images/files/manual_file_locking/file-locked-symbol.png
  modules/user_manual/assets/images/files/manual_file_locking/file-locked-unlock-symbol.png
  modules/user_manual/assets/images/files/manual_file_locking/lock-file-not-visible.png
  modules/user_manual/assets/images/files/manual_file_locking/lock-file-visible.png
  modules/user_manual/assets/images/files/manual_file_locking/manual-file-locking-without-lock-breaker.png
  modules/user_manual/pages/_partials/nav.adoc
  modules/user_manual/pages/files/manual_file_locking.adoc
Labels: backport

#4512 [10.7] [PR 4509] Update Manual File Locking
  modules/admin_manual/assets/images/configuration/files/manual_file_locking/file-locked-details.png
  modules/admin_manual/assets/images/configuration/files/manual_file_locking/file-locked-hint.png
  modules/admin_manual/assets/images/configuration/files/manual_file_locking/file-locked-symbol.png
  modules/admin_manual/assets/images/configuration/files/manual_file_locking/file-locked-unlock-symbol.png
  modules/admin_manual/assets/images/configuration/files/manual_file_locking/lock-file-not-visible.png
  modules/admin_manual/assets/images/configuration/files/manual_file_locking/lock-file-visible.png
  modules/admin_manual/assets/images/configuration/files/manual_file_locking/manual-file-locking-without-lock-breaker.png
  modules/admin_manual/pages/configuration/files/manual_file_locking.adoc
  modules/user_manual/assets/images/files/manual_file_locking/file-locked-details.png
  modules/user_manual/assets/images/files/manual_file_locking/file-locked-hint.png
  modules/user_manual/assets/images/files/manual_file_locking/file-locked-symbol.png
  modules/user_manual/assets/images/files/manual_file_locking/file-locked-unlock-symbol.png
  modules/user_manual/assets/images/files/manual_file_locking/lock-file-not-visible.png
  modules/user_manual/assets/images/files/manual_file_locking/lock-file-visible.png
  modules/user_manual/assets/images/files/manual_file_locking/manual-file-locking-without-lock-breaker.png
  modules/user_manual/pages/_partials/nav.adoc
  modules/user_manual/pages/files/manual_file_locking.adoc
Labels: backport

#4309 Changes necessary for 10.9 branch
  .drone.star
  modules/ROOT/pages/server_releases.adoc
  site.yml
Labels: deployment

#4513 Manual File Locking - Lock Breakers
  modules/admin_manual/assets/images/configuration/files/manual_file_locking/manual-file-locking-with-lock-breaker.png
  modules/admin_manual/assets/images/configuration/files/manual_file_locking/manual-file-locking-without-lock-breaker.png
  modules/admin_manual/pages/configuration/files/manual_file_locking.adoc
  modules/user_manual/pages/files/manual_file_locking.adoc
Labels: user docs, admin docs

#4514 [10.9] [PR 4513] Manual File Locking - Lock Breakers
  modules/admin_manual/assets/images/configuration/files/manual_file_locking/manual-file-locking-with-lock-breaker.png
  modules/admin_manual/assets/images/configuration/files/manual_file_locking/manual-file-locking-without-lock-breaker.png
  modules/admin_manual/pages/configuration/files/manual_file_locking.adoc
  modules/user_manual/pages/files/manual_file_locking.adoc
Labels: backport

#4519 Small typo-fix for occ user:move-home
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_user_commands.adoc
Labels: admin docs

#4528 Remove php-gettext from Ubuntu 20.04 quick install guide
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
Labels: admin docs

#4529 [10.9] [PR 4528] Remove php-gettext from Ubuntu 20.04 quick install guide
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
Labels: backport

#4530 [10.8] [PR 4528] Remove php-gettext from Ubuntu 20.04 quick install guide
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
Labels: backport

#4531 Fix orphaned search in user docs
  modules/user_manual/pages/_partials/nav.adoc
Labels: user docs

#4532 [10.9] [PR 4531] Fix orphaned search in user docs
  modules/user_manual/pages/_partials/nav.adoc
Labels: backport

#4533 [10.8] [PR 4531] Fix orphaned search in user docs
  modules/user_manual/pages/_partials/nav.adoc
Labels: backport

#4534 Updates for the Full Text Search App
  modules/admin_manual/pages/configuration/search/index.adoc
  modules/user_manual/pages/files/webgui/search.adoc
Labels: user docs, admin docs

#4535 [10.9] [PR 4534] Updates for the Full Text Search App
  modules/admin_manual/pages/configuration/search/index.adoc
  modules/user_manual/pages/files/webgui/search.adoc
Labels: backport

#4536 [10.8] [PR 4534] Updates for the Full Text Search App
  modules/admin_manual/pages/configuration/search/index.adoc
  modules/user_manual/pages/files/webgui/search.adoc
Labels: backport

#4539 Known Issue: Marketplace not working after upgrade from 10.8 to 10.9
  modules/ROOT/pages/server_release_notes.adoc
Labels: installation & configuration

#4540 [10.9] [PR 4539] Known Issue: Marketplace not working after upgrade from 10.8 to 10.9
  modules/ROOT/pages/server_release_notes.adoc
Labels: backport

#4541 Fix a pdf build issue
  docs/best-practices.md
  docs/build-the-docs.md
  modules/developer_manual/pages/bugtracker/triaging.adoc
Labels: enhancement, developer docs

#4547 [10.9] [PR 4541] Fix a pdf build issue
  docs/best-practices.md
  docs/build-the-docs.md
  modules/developer_manual/pages/bugtracker/triaging.adoc
Labels: backport

#4548 [10.8] [PR 4541] Fix a pdf build issue
  docs/best-practices.md
  docs/build-the-docs.md
  modules/developer_manual/pages/bugtracker/triaging.adoc
Labels: backport

#4549 [10.9] [PR 4546] Added Known issue (encryption)
  modules/ROOT/pages/server_release_notes.adoc
Labels: backport

#4550 Itemize the known issues section for 10.9
  modules/ROOT/pages/server_release_notes.adoc
Labels: enhancement

#4551 [10.9] [PR 4550] Itemize the known issues section for 10.9
  modules/ROOT/pages/server_release_notes.adoc
Labels: backport

#4554 Global Attribute Cleanup
  modules/ROOT/pages/server_release_notes.adoc
  modules/admin_manual/pages/appliance/configuration/wnd_setup.adoc
  modules/admin_manual/pages/configuration/general_topics/general_troubleshooting.adoc
  modules/admin_manual/pages/configuration/integration/ms-teams.adoc
  modules/admin_manual/pages/configuration/server/security_setup_warnings.adoc
  modules/admin_manual/pages/installation/configuration_notes_and_tips.adoc
  modules/admin_manual/pages/installation/manual_installation/manual_installation.adoc
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
  modules/admin_manual/pages/troubleshooting/providing_logs_and_config_files.adoc
  modules/developer_manual/pages/commun/help_and_communication.adoc
  modules/developer_manual/pages/core/semantic-versioning-guidelines.adoc
  site.yml
Labels: developer docs, admin docs

#4555 [10.9] [PR 4554] Global Attribute Cleanup
  modules/ROOT/pages/server_release_notes.adoc
  modules/admin_manual/pages/appliance/configuration/wnd_setup.adoc
  modules/admin_manual/pages/configuration/general_topics/general_troubleshooting.adoc
  modules/admin_manual/pages/configuration/integration/ms-teams.adoc
  modules/admin_manual/pages/configuration/server/security_setup_warnings.adoc
  modules/admin_manual/pages/installation/configuration_notes_and_tips.adoc
  modules/admin_manual/pages/installation/manual_installation/manual_installation.adoc
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
  modules/admin_manual/pages/troubleshooting/providing_logs_and_config_files.adoc
  modules/developer_manual/pages/commun/help_and_communication.adoc
  modules/developer_manual/pages/core/semantic-versioning-guidelines.adoc
  site.yml
Labels: backport

#4556 [10.8] [PR 4554] Global Attribute Cleanup
  modules/ROOT/pages/server_release_notes.adoc
  modules/admin_manual/pages/appliance/configuration/wnd_setup.adoc
  modules/admin_manual/pages/configuration/general_topics/general_troubleshooting.adoc
  modules/admin_manual/pages/configuration/integration/ms-teams.adoc
  modules/admin_manual/pages/configuration/server/security_setup_warnings.adoc
  modules/admin_manual/pages/installation/configuration_notes_and_tips.adoc
  modules/admin_manual/pages/installation/manual_installation/manual_installation.adoc
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
  modules/admin_manual/pages/troubleshooting/providing_logs_and_config_files.adoc
  modules/developer_manual/pages/commun/help_and_communication.adoc
  modules/developer_manual/pages/core/semantic-versioning-guidelines.adoc
  site.yml
Labels: backport

#4558 [10.8] [PR 4553] revert #4381
  modules/admin_manual/pages/installation/docker/index.adoc
Labels: backport

#4557 [10.9] [PR 4553] revert #4381
  modules/admin_manual/pages/installation/docker/index.adoc
Labels: backport

#4559 imagemagick required for 2FA
  modules/admin_manual/pages/configuration/user/user_auth_twofactor.adoc
Labels: admin docs

#4560 [10.9] [PR 4559] imagemagick required for 2FA
  modules/admin_manual/pages/configuration/user/user_auth_twofactor.adoc
Labels: backport

#4561 [10.8] [PR 4559] imagemagick required for 2FA
  modules/admin_manual/pages/configuration/user/user_auth_twofactor.adoc
Labels: backport

#4563 Removing Ubuntu 18.04 from manual installation
  modules/admin_manual/pages/_partials/nav.adoc
  modules/admin_manual/pages/installation/deployment_recommendations.adoc
  modules/admin_manual/pages/installation/manual_installation/index.adoc
  modules/admin_manual/pages/installation/manual_installation/manual_installation.adoc
  modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_18.04.adoc
  modules/admin_manual/pages/installation/system_requirements.adoc
Labels: admin docs

#4564 [10.9] [PR 4563] Removing Ubuntu 18.04 from manual installation
  modules/admin_manual/pages/_partials/nav.adoc
  modules/admin_manual/pages/installation/deployment_recommendations.adoc
  modules/admin_manual/pages/installation/manual_installation/index.adoc
  modules/admin_manual/pages/installation/manual_installation/manual_installation.adoc
  modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_18.04.adoc
  modules/admin_manual/pages/installation/system_requirements.adoc
Labels: backport

#4562 Removing Ubuntu 18.04 quick install
  modules/admin_manual/pages/installation/quick_guides/index.adoc
  modules/admin_manual/pages/installation/quick_guides/ubuntu_18_04.adoc
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
Labels: admin docs

#4565 [10.9] [PR 4562] Removing Ubuntu 18.04 quick install
  modules/admin_manual/pages/installation/quick_guides/index.adoc
  modules/admin_manual/pages/installation/quick_guides/ubuntu_18_04.adoc
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
Labels: backport

#4566 added imagemagick among the common prerequisites
  modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc
Labels: admin docs

#4567 [10.9] [PR 4566] added imagemagick among the common prerequisites
  modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc
Labels: backport

#4568 [10.8] [PR 4566] added imagemagick among the common prerequisites
  modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc
Labels: backport

#4569 Last references to Ubuntu 18.04
  modules/admin_manual/pages/configuration/files/previews_configuration.adoc
  modules/admin_manual/pages/configuration/general_topics/general_troubleshooting.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_config_commands.adoc
  modules/admin_manual/pages/installation/letsencrypt/apache.adoc
  modules/admin_manual/pages/installation/manual_installation/manual_imagick7.adoc
Labels: admin docs

#4570 [10.9] [PR 4569] Last references to Ubuntu 18.04
  modules/admin_manual/pages/configuration/files/previews_configuration.adoc
  modules/admin_manual/pages/configuration/general_topics/general_troubleshooting.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_config_commands.adoc
  modules/admin_manual/pages/installation/letsencrypt/apache.adoc
  modules/admin_manual/pages/installation/manual_installation/manual_imagick7.adoc
Labels: backport

#4571 Lower case in secure view
  modules/admin_manual/pages/enterprise/collaboration/collabora_secure_view.adoc
Labels: admin docs

#4572 [10.9] [PR 4571] Lower case in secure view
  modules/admin_manual/pages/enterprise/collaboration/collabora_secure_view.adoc
Labels: backport

#4573 [10.8] [PR 4571] Lower case in secure view
  modules/admin_manual/pages/enterprise/collaboration/collabora_secure_view.adoc
Labels: backport
