Repository owncloud/docs, pull requests merged in 2021-02, with the labels that each got.

#3093 Update site.yml : client, a branch needs to be in single quote marks
  site.yml
Labels: bug

#3095 small update and fixes
  modules/admin_manual/pages/release_notes.adoc
Labels: admin docs

#3098 Changed RestartSec to avoid DefaultStartLimitBurst
  modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
Labels: backport

#3111 Fixing missing attribute warnings
  docs/build-the-docs.md
  modules/admin_manual/examples/configuration/oc_permit.sh
  modules/developer_manual/examples/core/apis/ocs/notifications/delete-user-notification-response.json
  modules/developer_manual/examples/core/scripts/curl/accept-pending-share.sh
  modules/developer_manual/examples/core/scripts/curl/create-share.sh
  modules/developer_manual/examples/core/scripts/curl/decline-pending-share.sh
  modules/developer_manual/examples/core/scripts/curl/delete-share.sh
  modules/developer_manual/examples/core/scripts/curl/get-share-info.sh
  modules/developer_manual/examples/core/scripts/curl/list-all-shares.sh
  modules/developer_manual/examples/core/scripts/curl/list-share-details.sh
  modules/developer_manual/examples/core/scripts/curl/provisioning_api/add-user.curl
  modules/developer_manual/examples/core/scripts/curl/update-share.sh
  modules/developer_manual/examples/core/scripts/go/accept-pending-share.go
  modules/developer_manual/examples/core/scripts/go/create-share.go
  modules/developer_manual/examples/core/scripts/go/decline-pending-share.go
  modules/developer_manual/examples/core/scripts/go/delete-share.go
  modules/developer_manual/examples/core/scripts/go/get-share-info.go
  modules/developer_manual/examples/core/scripts/go/list-all-shares.go
  modules/developer_manual/examples/core/scripts/go/list-share-details.go
  modules/developer_manual/examples/core/scripts/go/update-share.go
  modules/developer_manual/examples/core/scripts/java/get-share-info.java
  modules/developer_manual/examples/core/scripts/kotlin/get-share-info.kt
  modules/developer_manual/examples/core/scripts/php/composer.json
  modules/developer_manual/examples/core/scripts/php/composer.lock
  modules/developer_manual/examples/core/scripts/php/create-share.php
  modules/developer_manual/examples/core/scripts/php/delete-share.php
  modules/developer_manual/examples/core/scripts/php/get-share-info.php
  modules/developer_manual/examples/core/scripts/php/list-all-shares.php
  modules/developer_manual/examples/core/scripts/php/list-share-details.php
  modules/developer_manual/examples/core/scripts/php/update-share.php
  modules/developer_manual/examples/core/scripts/php/user-sync.php
  modules/developer_manual/examples/core/scripts/python/login.py
  modules/developer_manual/examples/core/scripts/recipient/search.go
  modules/developer_manual/examples/core/scripts/recipient/search.php
  modules/developer_manual/examples/core/scripts/recipient/search.rb
  modules/developer_manual/examples/core/scripts/recipient/search.sh
  modules/developer_manual/examples/core/scripts/responses/recipients/response-success.json
  modules/developer_manual/examples/core/scripts/responses/shares/get-all-shares-success-with-shares.xml
  modules/developer_manual/examples/core/scripts/responses/shares/list-all-shares-failure.xml
  modules/developer_manual/examples/core/scripts/responses/shares/list-all-shares-success.xml
  modules/developer_manual/examples/core/scripts/ruby/accept-pending-share.rb
  modules/developer_manual/examples/core/scripts/ruby/create-share.rb
  modules/developer_manual/examples/core/scripts/ruby/decline-pending-share.rb
  modules/developer_manual/examples/core/scripts/ruby/delete-share.rb
  modules/developer_manual/examples/core/scripts/ruby/get-share-info.rb
  modules/developer_manual/examples/core/scripts/ruby/list-all-shares.rb
  modules/developer_manual/examples/core/scripts/ruby/list-share-details.rb
  modules/developer_manual/examples/core/scripts/ruby/update-share.rb
  modules/developer_manual/examples/core/webdav_api/files_versions/successful-response-which-contains-files.xml
  modules/developer_manual/examples/core/webdav_api/meta/report-propfind.xml
  modules/developer_manual/examples/core/webdav_api/public_files/response/no-read-privileges-on-public-link.xml
  modules/developer_manual/examples/core/webdav_api/search/request/search_files/filter_results.xml
  modules/developer_manual/pages/core/apis/ocs-share-api.adoc
  modules/developer_manual/pages/core/apis/ocs-totp-validation-api.adoc
  package.json
Labels: deployment, developer docs

#3108 Update Best Practices Guide
  docs/best-practices.md
Labels: enhancement

#3118 [10.5] [PR 3111] Fixing missing attribute warnings
  docs/build-the-docs.md
  modules/admin_manual/examples/configuration/oc_permit.sh
  modules/developer_manual/examples/core/apis/ocs/notifications/delete-user-notification-response.json
  modules/developer_manual/examples/core/scripts/curl/accept-pending-share.sh
  modules/developer_manual/examples/core/scripts/curl/create-share.sh
  modules/developer_manual/examples/core/scripts/curl/decline-pending-share.sh
  modules/developer_manual/examples/core/scripts/curl/delete-share.sh
  modules/developer_manual/examples/core/scripts/curl/get-share-info.sh
  modules/developer_manual/examples/core/scripts/curl/list-all-shares.sh
  modules/developer_manual/examples/core/scripts/curl/list-share-details.sh
  modules/developer_manual/examples/core/scripts/curl/provisioning_api/add-user.curl
  modules/developer_manual/examples/core/scripts/curl/update-share.sh
  modules/developer_manual/examples/core/scripts/go/accept-pending-share.go
  modules/developer_manual/examples/core/scripts/go/create-share.go
  modules/developer_manual/examples/core/scripts/go/decline-pending-share.go
  modules/developer_manual/examples/core/scripts/go/delete-share.go
  modules/developer_manual/examples/core/scripts/go/get-share-info.go
  modules/developer_manual/examples/core/scripts/go/list-all-shares.go
  modules/developer_manual/examples/core/scripts/go/list-share-details.go
  modules/developer_manual/examples/core/scripts/go/update-share.go
  modules/developer_manual/examples/core/scripts/java/get-share-info.java
  modules/developer_manual/examples/core/scripts/kotlin/get-share-info.kt
  modules/developer_manual/examples/core/scripts/php/composer.json
  modules/developer_manual/examples/core/scripts/php/composer.lock
  modules/developer_manual/examples/core/scripts/php/create-share.php
  modules/developer_manual/examples/core/scripts/php/delete-share.php
  modules/developer_manual/examples/core/scripts/php/get-share-info.php
  modules/developer_manual/examples/core/scripts/php/list-all-shares.php
  modules/developer_manual/examples/core/scripts/php/list-share-details.php
  modules/developer_manual/examples/core/scripts/php/update-share.php
  modules/developer_manual/examples/core/scripts/php/user-sync.php
  modules/developer_manual/examples/core/scripts/python/login.py
  modules/developer_manual/examples/core/scripts/recipient/search.go
  modules/developer_manual/examples/core/scripts/recipient/search.php
  modules/developer_manual/examples/core/scripts/recipient/search.rb
  modules/developer_manual/examples/core/scripts/recipient/search.sh
  modules/developer_manual/examples/core/scripts/responses/recipients/response-success.json
  modules/developer_manual/examples/core/scripts/responses/shares/get-all-shares-success-with-shares.xml
  modules/developer_manual/examples/core/scripts/responses/shares/list-all-shares-failure.xml
  modules/developer_manual/examples/core/scripts/responses/shares/list-all-shares-success.xml
  modules/developer_manual/examples/core/scripts/ruby/accept-pending-share.rb
  modules/developer_manual/examples/core/scripts/ruby/create-share.rb
  modules/developer_manual/examples/core/scripts/ruby/decline-pending-share.rb
  modules/developer_manual/examples/core/scripts/ruby/delete-share.rb
  modules/developer_manual/examples/core/scripts/ruby/get-share-info.rb
  modules/developer_manual/examples/core/scripts/ruby/list-all-shares.rb
  modules/developer_manual/examples/core/scripts/ruby/list-share-details.rb
  modules/developer_manual/examples/core/scripts/ruby/update-share.rb
  modules/developer_manual/examples/core/webdav_api/files_versions/successful-response-which-contains-files.xml
  modules/developer_manual/examples/core/webdav_api/meta/report-propfind.xml
  modules/developer_manual/examples/core/webdav_api/public_files/response/no-read-privileges-on-public-link.xml
  modules/developer_manual/examples/core/webdav_api/search/request/search_files/filter_results.xml
  modules/developer_manual/pages/core/apis/ocs-share-api.adoc
  modules/developer_manual/pages/core/apis/ocs-totp-validation-api.adoc
  package.json
Labels: backport

#3117 [10.6] [PR 3111] Fixing missing attribute warnings
  docs/build-the-docs.md
  modules/admin_manual/examples/configuration/oc_permit.sh
  modules/developer_manual/examples/core/apis/ocs/notifications/delete-user-notification-response.json
  modules/developer_manual/examples/core/scripts/curl/accept-pending-share.sh
  modules/developer_manual/examples/core/scripts/curl/create-share.sh
  modules/developer_manual/examples/core/scripts/curl/decline-pending-share.sh
  modules/developer_manual/examples/core/scripts/curl/delete-share.sh
  modules/developer_manual/examples/core/scripts/curl/get-share-info.sh
  modules/developer_manual/examples/core/scripts/curl/list-all-shares.sh
  modules/developer_manual/examples/core/scripts/curl/list-share-details.sh
  modules/developer_manual/examples/core/scripts/curl/provisioning_api/add-user.curl
  modules/developer_manual/examples/core/scripts/curl/update-share.sh
  modules/developer_manual/examples/core/scripts/go/accept-pending-share.go
  modules/developer_manual/examples/core/scripts/go/create-share.go
  modules/developer_manual/examples/core/scripts/go/decline-pending-share.go
  modules/developer_manual/examples/core/scripts/go/delete-share.go
  modules/developer_manual/examples/core/scripts/go/get-share-info.go
  modules/developer_manual/examples/core/scripts/go/list-all-shares.go
  modules/developer_manual/examples/core/scripts/go/list-share-details.go
  modules/developer_manual/examples/core/scripts/go/update-share.go
  modules/developer_manual/examples/core/scripts/java/get-share-info.java
  modules/developer_manual/examples/core/scripts/kotlin/get-share-info.kt
  modules/developer_manual/examples/core/scripts/php/composer.json
  modules/developer_manual/examples/core/scripts/php/composer.lock
  modules/developer_manual/examples/core/scripts/php/create-share.php
  modules/developer_manual/examples/core/scripts/php/delete-share.php
  modules/developer_manual/examples/core/scripts/php/get-share-info.php
  modules/developer_manual/examples/core/scripts/php/list-all-shares.php
  modules/developer_manual/examples/core/scripts/php/list-share-details.php
  modules/developer_manual/examples/core/scripts/php/update-share.php
  modules/developer_manual/examples/core/scripts/php/user-sync.php
  modules/developer_manual/examples/core/scripts/python/login.py
  modules/developer_manual/examples/core/scripts/recipient/search.go
  modules/developer_manual/examples/core/scripts/recipient/search.php
  modules/developer_manual/examples/core/scripts/recipient/search.rb
  modules/developer_manual/examples/core/scripts/recipient/search.sh
  modules/developer_manual/examples/core/scripts/responses/recipients/response-success.json
  modules/developer_manual/examples/core/scripts/responses/shares/get-all-shares-success-with-shares.xml
  modules/developer_manual/examples/core/scripts/responses/shares/list-all-shares-failure.xml
  modules/developer_manual/examples/core/scripts/responses/shares/list-all-shares-success.xml
  modules/developer_manual/examples/core/scripts/ruby/accept-pending-share.rb
  modules/developer_manual/examples/core/scripts/ruby/create-share.rb
  modules/developer_manual/examples/core/scripts/ruby/decline-pending-share.rb
  modules/developer_manual/examples/core/scripts/ruby/delete-share.rb
  modules/developer_manual/examples/core/scripts/ruby/get-share-info.rb
  modules/developer_manual/examples/core/scripts/ruby/list-all-shares.rb
  modules/developer_manual/examples/core/scripts/ruby/list-share-details.rb
  modules/developer_manual/examples/core/scripts/ruby/update-share.rb
  modules/developer_manual/examples/core/webdav_api/files_versions/successful-response-which-contains-files.xml
  modules/developer_manual/examples/core/webdav_api/meta/report-propfind.xml
  modules/developer_manual/examples/core/webdav_api/public_files/response/no-read-privileges-on-public-link.xml
  modules/developer_manual/examples/core/webdav_api/search/request/search_files/filter_results.xml
  modules/developer_manual/pages/core/apis/ocs-share-api.adoc
  modules/developer_manual/pages/core/apis/ocs-totp-validation-api.adoc
  package.json
Labels: backport

#3110 add note to User-Auth with LDAP doc
  modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
Labels: admin docs

#3123 [10.6] [PR 3103] Name Change of the Server Documentation for WND
  modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
Labels: backport

#3122 [10.5] [PR 3103] Name Change of the Server Documentation for WND
  modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
Labels: backport

#3124 Recent changes and additions in config.sample from core
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Labels: admin docs

#3119 [10.6] [PR 3110] add note to User-Auth with LDAP doc
  modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
Labels: backport

#3120 [10.5] [PR 3110] add note to User-Auth with LDAP doc
  modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
Labels: backport

#3125 Update of user_auth_ldap.adoc
  modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
Labels: admin docs

#3130 [10.5] [PR 3125] Update of user_auth_ldap.adoc
  modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
Labels: backport

#3131 [10.6] [PR 3125] Update of user_auth_ldap.adoc
  modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
Labels: backport

#3136 Installing Docker Improvements
  modules/admin_manual/pages/installation/docker/index.adoc
Labels: admin docs

#3139 [10.5] [PR 3136] Installing Docker Improvements
  modules/admin_manual/pages/installation/docker/index.adoc
Labels: backport

#3140 [10.6] [PR 3136] Installing Docker Improvements
  modules/admin_manual/pages/installation/docker/index.adoc
Labels: backport

#3154 [10.5] [PR 3153] fix pdf links for old server version
  modules/ROOT/pages/index.adoc
Labels: backport

#3155 [10.6] [PR 3153] fix pdf links for old server version
  modules/ROOT/pages/index.adoc
Labels: backport

#3185 config-to-docs run
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Labels: admin docs

#3186 AV Improvements
  modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc
Labels: admin docs

#3189 [10.5] [PR 3186] AV Improvements
  modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc
Labels: backport

#3190 [10.6] [PR 3186] AV Improvements
  modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc
Labels: backport

#3197 Small improvements by using macros for recurring values
  modules/admin_manual/pages/appliance/configuration/enterprise_trial.adoc
  modules/admin_manual/pages/configuration/files/external_storage/ftp.adoc
  modules/admin_manual/pages/configuration/general_topics/impersonate_users.adoc
  modules/admin_manual/pages/configuration/search/index.adoc
  modules/admin_manual/pages/configuration/server/app_commands/2fa_commands.adoc
  modules/admin_manual/pages/configuration/server/app_commands/antivirus_commands.adoc
  modules/admin_manual/pages/configuration/server/app_commands/brute_force_protection_commands.adoc
  modules/admin_manual/pages/configuration/server/app_commands/calendar_commands.adoc
  modules/admin_manual/pages/configuration/server/app_commands/contacts_commands.adoc
  modules/admin_manual/pages/configuration/server/app_commands/ldap_integration_commands.adoc
  modules/admin_manual/pages/configuration/server/app_commands/market_commands.adoc
  modules/admin_manual/pages/configuration/server/app_commands/password_policy_commands.adoc
  modules/admin_manual/pages/configuration/server/app_commands/ransomware_protection_commands.adoc
  modules/admin_manual/pages/configuration/server/app_commands/s3objectstore_commands.adoc
  modules/admin_manual/pages/configuration/server/app_commands/saml_sso_shibboleth_integration_commands.adoc
  modules/admin_manual/pages/configuration/server/harden_server.adoc
  modules/admin_manual/pages/configuration/server/security/oauth2.adoc
  modules/admin_manual/pages/configuration/server/security/password_policy.adoc
  modules/admin_manual/pages/configuration/user/oidc/index.adoc
  modules/admin_manual/pages/configuration/user/user_roles.adoc
  modules/admin_manual/pages/document_classification/index.adoc
  modules/admin_manual/pages/enterprise/external_storage/ldap_home_connector_configuration.adoc
  modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
  modules/admin_manual/pages/enterprise/external_storage/wnd_quick_guide.adoc
  modules/admin_manual/pages/enterprise/file_management/files_lifecycle.adoc
  modules/admin_manual/pages/installation/apps/mediaviewer/index.adoc
  modules/admin_manual/pages/installation/apps_supported.adoc
  modules/admin_manual/pages/installation/manual_installation/manual_installation_apache.adoc
  modules/admin_manual/pages/maintenance/encryption/migrating-from-user-key-to-master-key.adoc
  modules/admin_manual/pages/maintenance/manual_upgrade.adoc
  modules/admin_manual/pages/release_notes.adoc
  modules/developer_manual/pages/_partials/app/fundamentals/complete-info.xml
  modules/developer_manual/pages/app/advanced/code_signing.adoc
  modules/developer_manual/pages/app/fundamentals/info.adoc
  modules/developer_manual/pages/app/introduction.adoc
  modules/developer_manual/pages/core/apis/ocs-totp-validation-api.adoc
  modules/developer_manual/pages/core/theming.adoc
  modules/developer_manual/pages/index.adoc
  modules/developer_manual/pages/testing/unit-testing.adoc
  modules/user_manual/pages/apps/market.adoc
  modules/user_manual/pages/files/media_viewer_app.adoc
  modules/user_manual/pages/files/webgui/sharing.adoc
  modules/user_manual/pages/pim/calendar.adoc
  modules/user_manual/pages/pim/contacts.adoc
Labels: admin docs, developer docs, user docs

#3199 [10.6] [PR 3197] Small improvements by using macros for recurring values
  modules/admin_manual/pages/appliance/configuration/enterprise_trial.adoc
  modules/admin_manual/pages/configuration/files/external_storage/ftp.adoc
  modules/admin_manual/pages/configuration/general_topics/impersonate_users.adoc
  modules/admin_manual/pages/configuration/search/index.adoc
  modules/admin_manual/pages/configuration/server/app_commands/2fa_commands.adoc
  modules/admin_manual/pages/configuration/server/app_commands/antivirus_commands.adoc
  modules/admin_manual/pages/configuration/server/app_commands/brute_force_protection_commands.adoc
  modules/admin_manual/pages/configuration/server/app_commands/calendar_commands.adoc
  modules/admin_manual/pages/configuration/server/app_commands/contacts_commands.adoc
  modules/admin_manual/pages/configuration/server/app_commands/ldap_integration_commands.adoc
  modules/admin_manual/pages/configuration/server/app_commands/market_commands.adoc
  modules/admin_manual/pages/configuration/server/app_commands/password_policy_commands.adoc
  modules/admin_manual/pages/configuration/server/app_commands/ransomware_protection_commands.adoc
  modules/admin_manual/pages/configuration/server/app_commands/s3objectstore_commands.adoc
  modules/admin_manual/pages/configuration/server/app_commands/saml_sso_shibboleth_integration_commands.adoc
  modules/admin_manual/pages/configuration/server/harden_server.adoc
  modules/admin_manual/pages/configuration/server/security/oauth2.adoc
  modules/admin_manual/pages/configuration/server/security/password_policy.adoc
  modules/admin_manual/pages/configuration/user/oidc/index.adoc
  modules/admin_manual/pages/configuration/user/user_roles.adoc
  modules/admin_manual/pages/document_classification/index.adoc
  modules/admin_manual/pages/enterprise/external_storage/ldap_home_connector_configuration.adoc
  modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
  modules/admin_manual/pages/enterprise/external_storage/wnd_quick_guide.adoc
  modules/admin_manual/pages/enterprise/file_management/files_lifecycle.adoc
  modules/admin_manual/pages/installation/apps/mediaviewer/index.adoc
  modules/admin_manual/pages/installation/apps_supported.adoc
  modules/admin_manual/pages/installation/manual_installation/manual_installation_apache.adoc
  modules/admin_manual/pages/maintenance/encryption/migrating-from-user-key-to-master-key.adoc
  modules/admin_manual/pages/maintenance/manual_upgrade.adoc
  modules/admin_manual/pages/release_notes.adoc
  modules/developer_manual/pages/_partials/app/fundamentals/complete-info.xml
  modules/developer_manual/pages/app/advanced/code_signing.adoc
  modules/developer_manual/pages/app/fundamentals/info.adoc
  modules/developer_manual/pages/app/introduction.adoc
  modules/developer_manual/pages/core/apis/ocs-totp-validation-api.adoc
  modules/developer_manual/pages/core/theming.adoc
  modules/developer_manual/pages/index.adoc
  modules/developer_manual/pages/testing/unit-testing.adoc
  modules/user_manual/pages/apps/market.adoc
  modules/user_manual/pages/files/media_viewer_app.adoc
  modules/user_manual/pages/files/webgui/sharing.adoc
  modules/user_manual/pages/pim/calendar.adoc
  modules/user_manual/pages/pim/contacts.adoc
Labels: backport

#3198 [10.5] [PR 3197] Small improvements by using macros for recurring values
  modules/admin_manual/pages/appliance/configuration/enterprise_trial.adoc
  modules/admin_manual/pages/configuration/files/external_storage/ftp.adoc
  modules/admin_manual/pages/configuration/general_topics/impersonate_users.adoc
  modules/admin_manual/pages/configuration/search/index.adoc
  modules/admin_manual/pages/configuration/server/app_commands/2fa_commands.adoc
  modules/admin_manual/pages/configuration/server/app_commands/antivirus_commands.adoc
  modules/admin_manual/pages/configuration/server/app_commands/brute_force_protection_commands.adoc
  modules/admin_manual/pages/configuration/server/app_commands/calendar_commands.adoc
  modules/admin_manual/pages/configuration/server/app_commands/contacts_commands.adoc
  modules/admin_manual/pages/configuration/server/app_commands/ldap_integration_commands.adoc
  modules/admin_manual/pages/configuration/server/app_commands/market_commands.adoc
  modules/admin_manual/pages/configuration/server/app_commands/password_policy_commands.adoc
  modules/admin_manual/pages/configuration/server/app_commands/ransomware_protection_commands.adoc
  modules/admin_manual/pages/configuration/server/app_commands/s3objectstore_commands.adoc
  modules/admin_manual/pages/configuration/server/app_commands/saml_sso_shibboleth_integration_commands.adoc
  modules/admin_manual/pages/configuration/server/harden_server.adoc
  modules/admin_manual/pages/configuration/server/security/oauth2.adoc
  modules/admin_manual/pages/configuration/server/security/password_policy.adoc
  modules/admin_manual/pages/configuration/user/oidc/index.adoc
  modules/admin_manual/pages/configuration/user/user_roles.adoc
  modules/admin_manual/pages/document_classification/index.adoc
  modules/admin_manual/pages/enterprise/external_storage/ldap_home_connector_configuration.adoc
  modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
  modules/admin_manual/pages/enterprise/external_storage/wnd_quick_guide.adoc
  modules/admin_manual/pages/enterprise/file_management/files_lifecycle.adoc
  modules/admin_manual/pages/installation/apps/mediaviewer/index.adoc
  modules/admin_manual/pages/installation/apps_supported.adoc
  modules/admin_manual/pages/installation/manual_installation/manual_installation_apache.adoc
  modules/admin_manual/pages/maintenance/encryption/migrating-from-user-key-to-master-key.adoc
  modules/admin_manual/pages/maintenance/manual_upgrade.adoc
  modules/admin_manual/pages/release_notes.adoc
  modules/developer_manual/pages/_partials/app/fundamentals/complete-info.xml
  modules/developer_manual/pages/app/advanced/code_signing.adoc
  modules/developer_manual/pages/app/fundamentals/info.adoc
  modules/developer_manual/pages/app/introduction.adoc
  modules/developer_manual/pages/core/apis/ocs-totp-validation-api.adoc
  modules/developer_manual/pages/core/theming.adoc
  modules/developer_manual/pages/index.adoc
  modules/developer_manual/pages/testing/unit-testing.adoc
  modules/user_manual/pages/apps/market.adoc
  modules/user_manual/pages/files/media_viewer_app.adoc
  modules/user_manual/pages/files/webgui/sharing.adoc
  modules/user_manual/pages/pim/calendar.adoc
  modules/user_manual/pages/pim/contacts.adoc
Labels: backport

#3212 Adding a antora-local command to predefine localhost to build the docs on.
  docs/build-the-docs.md
  package.json
Labels: deployment

#3217 Added new metrics documentation.
  modules/admin_manual/nav.adoc
  modules/admin_manual/pages/enterprise/metrics/metrics.adoc
Labels: admin docs

#3218 Improved metrics documentation
  modules/admin_manual/nav.adoc
  modules/admin_manual/pages/enterprise/monitoring/index.adoc
  modules/admin_manual/pages/enterprise/monitoring/metrics.adoc
Labels: admin docs

#3219 [10.6] [PR 3217] Added new metrics documentation.
  modules/admin_manual/nav.adoc
  modules/admin_manual/pages/enterprise/metrics/metrics.adoc
Labels: backport

#3220 [10.6] [PR 3218] Improved metrics documentation
  modules/admin_manual/nav.adoc
  modules/admin_manual/pages/enterprise/monitoring/index.adoc
  modules/admin_manual/pages/enterprise/monitoring/metrics.adoc
Labels: backport

#3221 Fix one bad anchor reference
  modules/admin_manual/pages/configuration/files/encryption/enabling-user-key-encryption.adoc
Labels: admin docs
