Repository owncloud/docs, pull requests merged in 2021-01, with the labels that each got.

#2984 [10.6] [PR 2846] remove useless use of sudo
  modules/admin_manual/examples/installation/ubuntu/18.04/create-vhost-config.sh
Labels: backport

#2985 [10.5] [PR 2846] remove useless use of sudo
  modules/admin_manual/examples/installation/ubuntu/18.04/create-vhost-config.sh
Labels: backport

#2983 Update server_prep_18.04 when using multiple PHP installs
  modules/admin_manual/pages/configuration/server/caching_configuration.adoc
  modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_18.04.adoc
Labels: admin docs

#3007 Fixes and Updates to smb.adoc
  modules/admin_manual/pages/configuration/files/external_storage/smb.adoc
Labels: admin docs

#3009 [10.5] [PR 3007] Fixes and Updates to smb.adoc
  modules/admin_manual/pages/configuration/files/external_storage/smb.adoc
Labels: backport

#3008 [10.6] [PR 3007] Fixes and Updates to smb.adoc
  modules/admin_manual/pages/configuration/files/external_storage/smb.adoc
Labels: backport

#3020 Use antora variable from site.yml in maintenance for the latest download version
  modules/admin_manual/pages/_partials/maintenance/major_release_note.adoc
Labels: admin docs

#3022 [10.6] [PR 3020] Use antora variable from site.yml in maintenance for the latest download version
  modules/admin_manual/pages/_partials/maintenance/major_release_note.adoc
Labels: backport

#3012 Add new picture security warnings
  modules/admin_manual/assets/images/security-setup-warning-1.png
  modules/admin_manual/assets/images/security-setup-warning-complete.png
  modules/admin_manual/pages/configuration/server/security_setup_warnings.adoc
Labels: admin docs

#3032 [10.6] [PR 3012] Add new picture security warnings
  modules/admin_manual/assets/images/security-setup-warning-1.png
  modules/admin_manual/assets/images/security-setup-warning-complete.png
  modules/admin_manual/pages/configuration/server/security_setup_warnings.adoc
Labels: backport

#3033 [10.5] [PR 3012] Add new picture security warnings
  modules/admin_manual/assets/images/security-setup-warning-1.png
  modules/admin_manual/assets/images/security-setup-warning-complete.png
  modules/admin_manual/pages/configuration/server/security_setup_warnings.adoc
Labels: backport

#3034 [10.4] [PR 3012] Add new picture security warnings
  modules/admin_manual/assets/images/security-setup-warning-1.png
  modules/admin_manual/assets/images/security-setup-warning-complete.png
  modules/admin_manual/pages/configuration/server/security_setup_warnings.adoc
Labels: backport

#3040 Update manual_upgrade.adoc
  modules/admin_manual/pages/maintenance/manual_upgrade.adoc
Labels: 10.7, admin docs

#3046 add background jobs to security warnings
  modules/admin_manual/pages/configuration/server/security_setup_warnings.adoc
Labels: admin docs

#3049 [10.6] [PR 3046] add background jobs to security warnings
  modules/admin_manual/pages/configuration/server/security_setup_warnings.adoc
Labels: backport

#3050 [10.5] [PR 3046] add background jobs to security warnings
  modules/admin_manual/pages/configuration/server/security_setup_warnings.adoc
Labels: backport

#3048 Enhance external storage configuration
  docs/checking-broken-links.md
  modules/admin_manual/assets/images/configuration/files/external_storage/enable-app.png
  modules/admin_manual/nav.adoc
  modules/admin_manual/pages/_partials/configuration/files/external_storage/further_reading.adoc
  modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
  modules/admin_manual/pages/configuration/files/encryption/index.adoc
  modules/admin_manual/pages/configuration/files/external_storage/amazons3.adoc
  modules/admin_manual/pages/configuration/files/external_storage/configuration.adoc
  modules/admin_manual/pages/configuration/files/external_storage/ftp.adoc
  modules/admin_manual/pages/configuration/files/external_storage/google.adoc
  modules/admin_manual/pages/configuration/files/external_storage/local.adoc
  modules/admin_manual/pages/configuration/files/external_storage/openstack.adoc
  modules/admin_manual/pages/configuration/files/external_storage/owncloud.adoc
  modules/admin_manual/pages/configuration/files/external_storage/sftp.adoc
  modules/admin_manual/pages/configuration/files/external_storage/smb.adoc
  modules/admin_manual/pages/configuration/files/external_storage/webdav.adoc
  modules/admin_manual/pages/release_notes.adoc
  modules/user_manual/pages/external_storage/external_storage.adoc
Labels: 10.7, review required

#3052 Recover page alias modules/admin_manual/pages/configuration/files/external_storage/configuration.adoc
  modules/admin_manual/pages/configuration/files/external_storage/configuration.adoc
Labels: bug

#3054 [10.5] [PR3048] Enhance external storage configuration
  docs/checking-broken-links.md
  modules/admin_manual/assets/images/configuration/files/external_storage/enable-app.png
  modules/admin_manual/nav.adoc
  modules/admin_manual/pages/_partials/configuration/files/external_storage/further_reading.adoc
  modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
  modules/admin_manual/pages/configuration/files/encryption/index.adoc
  modules/admin_manual/pages/configuration/files/external_storage/amazons3.adoc
  modules/admin_manual/pages/configuration/files/external_storage/configuration.adoc
  modules/admin_manual/pages/configuration/files/external_storage/ftp.adoc
  modules/admin_manual/pages/configuration/files/external_storage/google.adoc
  modules/admin_manual/pages/configuration/files/external_storage/local.adoc
  modules/admin_manual/pages/configuration/files/external_storage/openstack.adoc
  modules/admin_manual/pages/configuration/files/external_storage/owncloud.adoc
  modules/admin_manual/pages/configuration/files/external_storage/sftp.adoc
  modules/admin_manual/pages/configuration/files/external_storage/smb.adoc
  modules/admin_manual/pages/configuration/files/external_storage/webdav.adoc
  modules/admin_manual/pages/release_notes.adoc
  modules/user_manual/pages/external_storage/external_storage.adoc
Labels: backport

#3053 [10.6] [PR3048] Enhance external storage configuration
  docs/checking-broken-links.md
  modules/admin_manual/assets/images/configuration/files/external_storage/enable-app.png
  modules/admin_manual/nav.adoc
  modules/admin_manual/pages/_partials/configuration/files/external_storage/further_reading.adoc
  modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
  modules/admin_manual/pages/configuration/files/encryption/index.adoc
  modules/admin_manual/pages/configuration/files/external_storage/amazons3.adoc
  modules/admin_manual/pages/configuration/files/external_storage/configuration.adoc
  modules/admin_manual/pages/configuration/files/external_storage/ftp.adoc
  modules/admin_manual/pages/configuration/files/external_storage/google.adoc
  modules/admin_manual/pages/configuration/files/external_storage/local.adoc
  modules/admin_manual/pages/configuration/files/external_storage/openstack.adoc
  modules/admin_manual/pages/configuration/files/external_storage/owncloud.adoc
  modules/admin_manual/pages/configuration/files/external_storage/sftp.adoc
  modules/admin_manual/pages/configuration/files/external_storage/smb.adoc
  modules/admin_manual/pages/configuration/files/external_storage/webdav.adoc
  modules/admin_manual/pages/release_notes.adoc
  modules/user_manual/pages/external_storage/external_storage.adoc
Labels: backport

#3055 [10.6] [PR3052] Recover page alias modules/admin_manual/pages/configuration/files/external_storage/configuration.adoc
  modules/admin_manual/pages/configuration/files/external_storage/configuration.adoc
Labels: backport

#3056 [10.5] [PR3052] Recover page alias modules/admin_manual/pages/configuration/files/external_storage/configuration.adoc
  modules/admin_manual/pages/configuration/files/external_storage/configuration.adoc
Labels: backport

#3061 Change depreacted images/paragraphs, add a note for read only tag list
  modules/user_manual/assets/images/file_popup-menu.png
  modules/user_manual/assets/images/files_page-7.png
  modules/user_manual/pages/files/webgui/tagging.adoc
Labels: 10.7

#3068 Adding note about configreport
  modules/admin_manual/pages/troubleshooting/providing_logs_and_config_files.adoc
Labels: admin docs, backport

#3066 [10.6] [PR 3063] Fixes formatting of "Finalize the Installation" section
  modules/admin_manual/pages/maintenance/manual_upgrade.adoc
Labels: backport

#3067 [10.5] [PR 3063] Fixes formatting of "Finalize the Installation" section
  modules/admin_manual/pages/maintenance/manual_upgrade.adoc
Labels: backport

#3072 Add Running occ command section to admin_manual/pages/installation/docker/index.adoc
  modules/admin_manual/pages/installation/docker/index.adoc
Labels: 10.6, admin docs

#3075 Add Important Note for valid CORS entries
  modules/user_manual/pages/personal_settings/security.adoc
Labels: user docs

#3079 [10.6] [PR 3075] Add Important Note for valid CORS entries
  modules/user_manual/pages/personal_settings/security.adoc
Labels: backport

#3078 [10.5] [PR 3076] Update instance.sh
  modules/admin_manual/examples/installation/manual_installation/instance.sh
Labels: backport

#3080 Small update of the Backport Script reflecting recent changes on GH
  modules/developer_manual/examples/scripts/backport.sh
Labels: developer docs

#3077 [10.6] [PR 3076] Update instance.sh
  modules/admin_manual/examples/installation/manual_installation/instance.sh
Labels: backport

#3088 Changed modules/admin_manual/pages/configuration/user/guests_app.adoc
  modules/admin_manual/pages/configuration/user/guests_app.adoc
Labels: 10.5, 10.6, backport

#3085 Adjust Provisioning API
  modules/admin_manual/pages/configuration/user/user_provisioning_api.adoc
  modules/developer_manual/nav.adoc
  modules/developer_manual/pages/core/apis/provisioning-api.adoc
Labels: 10.6, developer docs, review required, user docs
