Repository owncloud/docs, pull requests merged in 2021-07, with the labels that each got.

#3763 Update windows-network-drive_configuration.adoc
  modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
Labels: admin docs

#3766 Configure master for 10.8
  .drone.star
  site.yml
Labels: deployment

#3765 Update Imagick to v7 for enhanced preview provider support
  modules/admin_manual/pages/_partials/installation/manual_installation/useful_tips.adoc
  modules/admin_manual/pages/installation/manual_installation/manual_imagick7.adoc
  modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc
Labels: admin docs

#3769 [10.8] [PR 3765] Update Imagick to v7 for enhanced preview provider support
  modules/admin_manual/pages/_partials/installation/manual_installation/useful_tips.adoc
  modules/admin_manual/pages/installation/manual_installation/manual_imagick7.adoc
  modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc
Labels: backport

#3770 [10.7] [PR 3765] Update Imagick to v7 for enhanced preview provider support
  modules/admin_manual/pages/_partials/installation/manual_installation/useful_tips.adoc
  modules/admin_manual/pages/installation/manual_installation/manual_imagick7.adoc
  modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc
Labels: backport

#3768 Update PHP min version to 7.2.5
  modules/admin_manual/pages/configuration/server/caching_configuration.adoc
  modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
  modules/admin_manual/pages/enterprise/installation/oracle_db_configuration.adoc
  modules/admin_manual/pages/installation/configuration_notes_and_tips.adoc
  modules/admin_manual/pages/maintenance/upgrading/upgrade_php.adoc
  modules/developer_manual/pages/app/tutorial/requirements.adoc
  site.yml
Labels: deployment

#3771 [10.8] [PR 3768] Update PHP min version to 7.2.5
  modules/admin_manual/pages/configuration/server/caching_configuration.adoc
  modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
  modules/admin_manual/pages/enterprise/installation/oracle_db_configuration.adoc
  modules/admin_manual/pages/installation/configuration_notes_and_tips.adoc
  modules/admin_manual/pages/maintenance/upgrading/upgrade_php.adoc
  modules/developer_manual/pages/app/tutorial/requirements.adoc
  site.yml
Labels: backport

#3772 Cleanup site.yml
  site.yml
Labels: deployment

#3776 [10.8] [PR 3773] Add PHP minimum version 7.2.5 to 10.8 release notes
  modules/admin_manual/pages/release_notes.adoc
Labels: backport

#3775 Cleanup site.yml for 10.7 only
  site.yml
Labels: deployment

#3778 User Manual Encryption, pdf fix file not found
  modules/user_manual/pages/_partials/configuration/files/encryption/not-encrypted-files.adoc
  modules/user_manual/pages/files/encrypting_files.adoc
Labels: user docs

#3779 [10.8] [PR 3778] User Manual Encryption, pdf fix file not found
  modules/user_manual/pages/_partials/configuration/files/encryption/not-encrypted-files.adoc
  modules/user_manual/pages/files/encrypting_files.adoc
Labels: backport

#3780 [10.7] [PR 3778] User Manual Encryption, pdf fix file not found
  modules/user_manual/pages/_partials/configuration/files/encryption/not-encrypted-files.adoc
  modules/user_manual/pages/files/encrypting_files.adoc
Labels: backport

#3777 Move preview content to docs
  modules/admin_manual/pages/configuration/files/previews_configuration.adoc
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
  modules/admin_manual/pages/installation/manual_installation/manual_imagick7.adoc
Labels: admin docs

#3781 [10.8] [PR 3777] Move preview content to docs
  modules/admin_manual/pages/configuration/files/previews_configuration.adoc
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
  modules/admin_manual/pages/installation/manual_installation/manual_imagick7.adoc
Labels: backport

#3782 [10.7] [PR 3777] Move preview content to docs
  modules/admin_manual/pages/configuration/files/previews_configuration.adoc
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
  modules/admin_manual/pages/installation/manual_installation/manual_imagick7.adoc
Labels: backport

#3783 ImageMagick revision
  modules/admin_manual/pages/installation/manual_installation/manual_imagick7.adoc
  modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc
Labels: admin docs

#3784 [10.7] [PR 3783] ImageMagick revision
  modules/admin_manual/pages/installation/manual_installation/manual_imagick7.adoc
  modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc
Labels: backport

#3785 [10.8] [PR 3783] ImageMagick revision
  modules/admin_manual/pages/installation/manual_installation/manual_imagick7.adoc
  modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc
Labels: backport

#3786 Fix Internal Redirects
  docs/new-version-branch.md
Labels: deployment

#3787 [10.8] [PR 3786] Fix Internal Redirects
  docs/new-version-branch.md
Labels: backport

#3788 [10.7] [PR 3786] Fix Internal Redirects
  docs/new-version-branch.md
Labels: backport

#3789 Remove outdated text references in LDAP
  modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
Labels: admin docs

#3795 [10.8] [PR 3772] Cleanup site.yml
  site.yml
Labels: backport

#3796 Replaced outdated Firebug URL
  modules/admin_manual/pages/configuration/general_topics/general_troubleshooting.adoc
Labels: admin docs

#3797 [10.8] [PR 3796] Replaced outdated Firebug URL
  modules/admin_manual/pages/configuration/general_topics/general_troubleshooting.adoc
Labels: backport

#3798 [10.7] [PR 3796] Replaced outdated Firebug URL
  modules/admin_manual/pages/configuration/general_topics/general_troubleshooting.adoc
Labels: backport

#3808 [10.8] [PR 3806] occ is redundant
  modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc
Labels: backport

#3809 [10.7] [PR 3806] occ is redundant
  modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc
Labels: backport

#3811 [10.7] [PR 3799] Add hints about loglevel
  modules/admin_manual/pages/installation/docker/index.adoc
Labels: backport

#3810 [10.8] [PR 3799] Add hints about loglevel
  modules/admin_manual/pages/installation/docker/index.adoc
Labels: backport

#3807 Update the ImageMagick install documentation
  modules/admin_manual/pages/installation/manual_installation/manual_imagick7.adoc
Labels: admin docs

#3812 [10.8] [PR 3807] Update the ImageMagick install documentation
  modules/admin_manual/pages/installation/manual_installation/manual_imagick7.adoc
Labels: backport

#3813 [10.7] [PR 3807] Update the ImageMagick install documentation
  modules/admin_manual/pages/installation/manual_installation/manual_imagick7.adoc
Labels: backport

#3814 Fixes a config sample typo
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Labels: admin docs

#3815 [10.8] [PR 3814] Fixes a config sample typo
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Labels: backport

#3822 Set page-aliases for external_storage_configuration_gui.adoc
  modules/admin_manual/pages/configuration/files/external_storage/configuration.adoc
Labels: admin docs

#3823 [10.8] [PR 3822] Set page-aliases for external_storage_configuration_gui.adoc
  modules/admin_manual/pages/configuration/files/external_storage/configuration.adoc
Labels: backport

#3824 [10.7] [PR 3822] Set page-aliases for external_storage_configuration_gui.adoc
  modules/admin_manual/pages/configuration/files/external_storage/configuration.adoc
Labels: backport

#3825 [10.8] [PR 3819] Caching Doc: Create separate entry for opcache
  modules/admin_manual/pages/configuration/server/caching_configuration.adoc
Labels: backport

#3826 [10.7] [PR 3819] Caching Doc: Create separate entry for opcache
  modules/admin_manual/pages/configuration/server/caching_configuration.adoc
Labels: backport

#3827 config-to-docs from release-10.8.0
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Labels: admin docs

#3828 Add an item in the BPG at the table section
  docs/best-practices.md
Labels: deployment

#3821 Added information about environment variables used while running acceptance tests
  modules/developer_manual/pages/testing/acceptance-tests.adoc
Labels: QA-team

#3838 Formatting fix for the IM7 document - no content change
  modules/admin_manual/pages/installation/manual_installation/manual_imagick7.adoc
Labels: admin docs

#3839 [10.8] [PR 3838] Formatting fix for the IM7 document - no content change
  modules/admin_manual/pages/installation/manual_installation/manual_imagick7.adoc
Labels: backport

#3840 [10.7] [PR 3838] Formatting fix for the IM7 document - no content change
  modules/admin_manual/pages/installation/manual_installation/manual_imagick7.adoc
Labels: backport

#3848 [10.7] [PR 3844] Update test-pilots.adoc
  modules/developer_manual/pages/testing/test-pilots.adoc
Labels: backport

#3847 [10.8] [PR 3844] Update test-pilots.adoc
  modules/developer_manual/pages/testing/test-pilots.adoc
Labels: backport

#3849 config-to-docs run
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Labels: admin docs

#3851 [10.8] [PR 3849] config-to-docs run
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Labels: backport

#3852 [10.7] [PR 3849] config-to-docs run
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Labels: backport

#3850 Link and owncloud tld fixes
  modules/ROOT/pages/index.adoc
  modules/admin_manual/pages/appliance/configuration/wnd_setup.adoc
  modules/admin_manual/pages/appliance/installation/installation.adoc
  modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
  modules/admin_manual/pages/configuration/general_topics/general_troubleshooting.adoc
  modules/admin_manual/pages/configuration/integration/ms-teams.adoc
  modules/admin_manual/pages/configuration/server/custom_client_repos.adoc
  modules/admin_manual/pages/configuration/server/security_setup_warnings.adoc
  modules/admin_manual/pages/index.adoc
  modules/admin_manual/pages/installation/configuration_notes_and_tips.adoc
  modules/admin_manual/pages/installation/system_requirements.adoc
  modules/admin_manual/pages/maintenance/update.adoc
  modules/admin_manual/pages/maintenance/upgrade.adoc
  modules/admin_manual/pages/maintenance/upgrading/marketplace_apps.adoc
  modules/admin_manual/pages/release_notes.adoc
  modules/admin_manual/pages/troubleshooting/providing_logs_and_config_files.adoc
  modules/developer_manual/pages/_partials/app/fundamentals/complete-info.xml
  modules/developer_manual/pages/app/fundamentals/publishing.adoc
  modules/developer_manual/pages/app/introduction.adoc
  modules/developer_manual/pages/bugtracker/codereviews.adoc
  modules/developer_manual/pages/bugtracker/triaging.adoc
  modules/developer_manual/pages/commun/help_and_communication.adoc
  modules/developer_manual/pages/core/apis/ocs-share-api.adoc
  modules/developer_manual/pages/core/semantic-versioning-guidelines.adoc
  modules/developer_manual/pages/general/backporting.adoc
  modules/developer_manual/pages/general/codingguidelines.adoc
  modules/developer_manual/pages/general/devenv_docker.adoc
  modules/developer_manual/pages/general/performance.adoc
  modules/developer_manual/pages/general/security.adoc
  modules/developer_manual/pages/mobile_development/android_library/index.adoc
  modules/developer_manual/pages/mobile_development/ios_library/index.adoc
  modules/user_manual/pages/files/access_webdav.adoc
  modules/user_manual/pages/files/desktop_mobile_sync.adoc
  modules/user_manual/pages/files/encrypting_files.adoc
  modules/user_manual/pages/pim/sync_osx.adoc
  site.yml
Labels: admin docs, developer docs, user docs

#3855 Post fix of #3850
  modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
  modules/admin_manual/pages/configuration/general_topics/general_troubleshooting.adoc
  modules/admin_manual/pages/installation/configuration_notes_and_tips.adoc
  modules/developer_manual/pages/bugtracker/codereviews.adoc
Labels: admin docs, developer docs

#3856 [10.8] [PR 3855] Post fix of #3850
  modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
  modules/admin_manual/pages/configuration/general_topics/general_troubleshooting.adoc
  modules/admin_manual/pages/installation/configuration_notes_and_tips.adoc
  modules/developer_manual/pages/bugtracker/codereviews.adoc
Labels: backport

#3857 [10.7] [PR 3855] Post fix of #3850
  modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
  modules/admin_manual/pages/configuration/general_topics/general_troubleshooting.adoc
  modules/admin_manual/pages/installation/configuration_notes_and_tips.adoc
  modules/developer_manual/pages/bugtracker/codereviews.adoc
Labels: backport

#3858 Removing ondrej ppa/adding refs to server hardening
  modules/admin_manual/pages/installation/manual_installation/index.adoc
  modules/admin_manual/pages/installation/manual_installation/manual_installation.adoc
  modules/admin_manual/pages/installation/quick_guides/index.adoc
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
Labels: admin docs

#3859 [10.8] [PR 3858] Removing ondrej ppa/adding refs to server hardening
  modules/admin_manual/pages/installation/manual_installation/index.adoc
  modules/admin_manual/pages/installation/manual_installation/manual_installation.adoc
  modules/admin_manual/pages/installation/quick_guides/index.adoc
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
Labels: backport

#3860 [10.7] [PR 3858] Removing ondrej ppa/adding refs to server hardening
  modules/admin_manual/pages/installation/manual_installation/index.adoc
  modules/admin_manual/pages/installation/manual_installation/manual_installation.adoc
  modules/admin_manual/pages/installation/quick_guides/index.adoc
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
Labels: backport

#3862 How to use occ commands with the Appliance
  modules/admin_manual/pages/appliance/configuration/login_information.adoc
  modules/admin_manual/pages/configuration/server/occ_command.adoc
Labels: admin docs, appliance docs

#3863 [10.8] [PR 3862] How to use occ commands with the Appliance
  modules/admin_manual/pages/appliance/configuration/login_information.adoc
  modules/admin_manual/pages/configuration/server/occ_command.adoc
Labels: backport

#3864 [10.7] [PR 3862] How to use occ commands with the Appliance
  modules/admin_manual/pages/appliance/configuration/login_information.adoc
  modules/admin_manual/pages/configuration/server/occ_command.adoc
Labels: backport

#3866 [10.8] [PR 3865] 10.8 release notes corrections
  modules/admin_manual/pages/release_notes.adoc
Labels: backport

#3868 [10.8] [PR 3867] Add issue 39034 about PHP 7.4.21 and open_basedir to known issues
  modules/admin_manual/pages/release_notes.adoc
Labels: backport

#3871 Update new version branch when and how latest is set
  docs/new-version-branch.md
Labels: deployment

#3872 [10.8] [PR 3871] Update new version branch when and how latest is set
  docs/new-version-branch.md
Labels: backport

#3873 [10.7] [PR 3871] Update new version branch when and how latest is set
  docs/new-version-branch.md
Labels: backport

#3876 Add reason when to use occ encryption:fix-encrypted-version
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/encryption_commands.adoc
Labels: admin docs

#3875 Fix missing occ link how to setup Collabora
  modules/admin_manual/pages/enterprise/collaboration/collabora_secure_view.adoc
Labels: admin docs

#3877 [10.8] [PR 3876] Add reason when to use occ encryption:fix-encrypted-version
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/encryption_commands.adoc
Labels: backport

#3878 [10.7] [PR 3876] Add reason when to use occ encryption:fix-encrypted-version
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/encryption_commands.adoc
Labels: backport

#3879 [10.8] [PR 3875] Fix missing occ link how to setup Collabora
  modules/admin_manual/pages/enterprise/collaboration/collabora_secure_view.adoc
Labels: backport

#3880 [10.7] [PR 3875] Fix missing occ link how to setup Collabora
  modules/admin_manual/pages/enterprise/collaboration/collabora_secure_view.adoc
Labels: backport

#3874 [master] [PR 3870] add hint about custom themes for login page to 10.8 release notes
  modules/admin_manual/pages/release_notes.adoc
Labels: backport

#3886 [10.7] [PR 3884] Fix OwnCloud -> ownCloud
  modules/ROOT/pages/index.adoc
Labels: backport

#3887 Fix QuickGuide php no installation candidate
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
Labels: admin docs

#3885 [10.8] [PR 3884] Fix OwnCloud -> ownCloud
  modules/ROOT/pages/index.adoc
Labels: backport

#3888 [10.8] [PR 3887] Fix QuickGuide php no installation candidate
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
Labels: backport

#3889 [10.7] [PR 3887] Fix QuickGuide php no installation candidate
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
Labels: backport

#3891 Removed empty table
  modules/user_manual/pages/troubleshooting.adoc
Labels: user docs

#3892 [10.8] [PR 3891] Removed empty table
  modules/user_manual/pages/troubleshooting.adoc
Labels: backport

#3893 [10.7] [PR 3891] Removed empty table
  modules/user_manual/pages/troubleshooting.adoc
Labels: backport

#3895 Dropbox integration updated
  modules/admin_manual/pages/configuration/files/external_storage/dropbox.adoc
Labels: admin docs

#3898 [10.8] [PR 3897] Clarified how to find and enable a SUSE security repo
  modules/admin_manual/pages/configuration/server/security/hsmdaemon/softhsm2.adoc
Labels: backport

#3899 [10.7] [PR 3897] Clarified how to find and enable a SUSE security repo
  modules/admin_manual/pages/configuration/server/security/hsmdaemon/softhsm2.adoc
Labels: backport

#3903 [10.8] [PR 3895] Dropbox integration updated and fixing issue
  modules/admin_manual/pages/configuration/files/external_storage/dropbox.adoc
Labels: backport

#3904 [10.7] [PR 3895] Dropbox integration updated and fixing issue #3903
  modules/admin_manual/pages/configuration/files/external_storage/dropbox.adoc
Labels: backport

#3902 SUSE security example upgraded to 15.3
  modules/admin_manual/pages/configuration/server/security/hsmdaemon/softhsm2.adoc
Labels: admin docs

#3905 [10.8] [PR 3902] SUSE security example upgraded to 15.3
  modules/admin_manual/pages/configuration/server/security/hsmdaemon/softhsm2.adoc
Labels: backport

#3906 [10.7] [PR 3902] SUSE security example upgraded to 15.3
  modules/admin_manual/pages/configuration/server/security/hsmdaemon/softhsm2.adoc
Labels: backport
