Repository owncloud/docs, pull requests merged in 2021-11, with the labels that each got.

#4187 Fix accidentially added occ richdocuments at 10.7
  modules/admin_manual/pages/configuration/server/occ_command.adoc
Labels: bug, admin docs

#4188 Make page-aliases in occ line by line
  modules/admin_manual/pages/configuration/server/occ_command.adoc
Labels: admin docs

#4189 Make page-aliases better readable when having multiple elements
  modules/ROOT/pages/server_release_notes.adoc
  modules/admin_manual/pages/appliance/configuration/clamav.adoc
  modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
  modules/admin_manual/pages/configuration/files/external_storage/configuration.adoc
  modules/admin_manual/pages/configuration/general_topics/general_troubleshooting.adoc
  modules/admin_manual/pages/configuration/server/harden_server.adoc
  modules/admin_manual/pages/enterprise/security/ransomware-protection/index.adoc
Labels: admin docs

#4192 [10.8] [PR 4188] Make page-aliases in occ line by line
  modules/admin_manual/pages/configuration/server/occ_command.adoc
Labels: backport

#4194 [10.7] [PR 4189] Make page-aliases better readable when having multip…
  modules/ROOT/pages/server_release_notes.adoc
  modules/admin_manual/pages/appliance/configuration/clamav.adoc
  modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
  modules/admin_manual/pages/configuration/files/external_storage/configuration.adoc
  modules/admin_manual/pages/configuration/general_topics/general_troubleshooting.adoc
  modules/admin_manual/pages/configuration/server/harden_server.adoc
  modules/admin_manual/pages/enterprise/security/ransomware-protection/index.adoc
Labels: backport

#4193 [10.8] [PR 4189] Make page-aliases better readable when having multip…
  modules/ROOT/pages/server_release_notes.adoc
  modules/admin_manual/pages/appliance/configuration/clamav.adoc
  modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
  modules/admin_manual/pages/configuration/files/external_storage/configuration.adoc
  modules/admin_manual/pages/configuration/general_topics/general_troubleshooting.adoc
  modules/admin_manual/pages/configuration/server/harden_server.adoc
  modules/admin_manual/pages/enterprise/security/ransomware-protection/index.adoc
Labels: backport

#4186 Prepare the repo to include external adoc files
  bin/makepdf
  lib/extensions/remote-include-processor.js
  site.yml
Labels: deployment

#4195 [10.8] [PR 4186] Prepare the repo to include external adoc files
  bin/makepdf
  lib/extensions/remote-include-processor.js
  site.yml
Labels: backport

#4196 [10.7] [PR 4186] Prepare the repo to include external adoc files
  bin/makepdf
  lib/extensions/remote-include-processor.js
  site.yml
Labels: backport

#4191 Add new oauth2 occ commands
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_oauth2_commands.adoc
Labels: admin docs

#4198 Minor text fix in occ files commands document
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_file_commands.adoc
Labels: admin docs

#4204 Enable the OAuth code flow sequence diagram
  modules/admin_manual/assets/attachments/configuration/user/oidc/OAuth-code-flow-sequence-diagram.png
  modules/admin_manual/pages/configuration/user/oidc/oidc.adoc
Labels: admin docs

#4205 [10.8] [PR 4204] Enable the OAuth code flow sequence diagram
  modules/admin_manual/assets/attachments/configuration/user/oidc/OAuth-code-flow-sequence-diagram.png
  modules/admin_manual/pages/configuration/user/oidc/oidc.adoc
Labels: backport

#4211 Fix page alias for encryption
  modules/admin_manual/pages/configuration/files/encryption/index.adoc
Labels: admin docs

#4210 Fix page alias for admin audit
  modules/admin_manual/pages/enterprise/logging/admin_audit.adoc
Labels: admin docs

#4212 [10.8] [PR 4211] Fix page alias for encryption
  modules/admin_manual/pages/configuration/files/encryption/index.adoc
Labels: backport

#4213 [10.7] [PR 4211] Fix page alias for encryption
  modules/admin_manual/pages/configuration/files/encryption/index.adoc
Labels: backport

#4214 [10.8] [PR 4210] Fix page alias for admin audit
  modules/admin_manual/pages/enterprise/logging/admin_audit.adoc
Labels: backport

#4216 Fix one item double component entry in user manual nav
  modules/user_manual/pages/_partials/nav.adoc
Labels: user docs

#4217 [10.8] [PR 4216] Fix one item double component entry in user manual nav
  modules/user_manual/pages/_partials/nav.adoc
Labels: backport

#4206 folder description in backup section
  modules/admin_manual/pages/maintenance/backup.adoc
Labels: admin docs

#4218 [10.8] [PR 4206] folder description in backup section
  modules/admin_manual/pages/maintenance/backup.adoc
Labels: backport

#4219 [10.7] [PR 4206] folder description in backup section
  modules/admin_manual/pages/maintenance/backup.adoc
Labels: backport

#4220 Part one fixing broken anchors (in- and inter-document references)
  .gitignore
  modules/ROOT/pages/client_releases.adoc
  modules/ROOT/pages/server_release_notes.adoc
  modules/ROOT/pages/server_releases.adoc
  modules/admin_manual/pages/_partials/configuration/files/encryption/not-encrypted-files.adoc
  modules/admin_manual/pages/configuration/database/linux_database_configuration.adoc
  modules/admin_manual/pages/installation/deployment_recommendations.adoc
  modules/admin_manual/pages/installation/troubleshooting.adoc
  modules/developer_manual/pages/app/advanced/custom-cache-backend.adoc
  modules/developer_manual/pages/app/fundamentals/hooks.adoc
  modules/developer_manual/pages/app/tutorial/database_connectivity.adoc
  modules/developer_manual/pages/app/tutorial/request.adoc
  modules/developer_manual/pages/general/_devenv_docker.adoc
  modules/developer_manual/pages/general/devenv.adoc
  modules/developer_manual/pages/mobile_development/ios_library/library_installation.adoc
  modules/developer_manual/pages/testing/test-pilots.adoc
  modules/developer_manual/pages/testing/ui-testing.adoc
  modules/developer_manual/pages/webdav_api/files_versions.adoc
  modules/user_manual/pages/_partials/configuration/files/encryption/not-encrypted-files.adoc
Labels: developer docs, user docs, admin docs

#4221 [10.8] [PR 4220] Part one fixing broken anchors (in- and inter-document references)
  .gitignore
  modules/ROOT/pages/client_releases.adoc
  modules/ROOT/pages/server_release_notes.adoc
  modules/ROOT/pages/server_releases.adoc
  modules/admin_manual/pages/_partials/configuration/files/encryption/not-encrypted-files.adoc
  modules/admin_manual/pages/configuration/database/linux_database_configuration.adoc
  modules/admin_manual/pages/installation/deployment_recommendations.adoc
  modules/admin_manual/pages/installation/troubleshooting.adoc
  modules/developer_manual/pages/app/advanced/custom-cache-backend.adoc
  modules/developer_manual/pages/app/fundamentals/hooks.adoc
  modules/developer_manual/pages/app/tutorial/database_connectivity.adoc
  modules/developer_manual/pages/app/tutorial/request.adoc
  modules/developer_manual/pages/general/_devenv_docker.adoc
  modules/developer_manual/pages/general/devenv.adoc
  modules/developer_manual/pages/mobile_development/ios_library/library_installation.adoc
  modules/developer_manual/pages/testing/test-pilots.adoc
  modules/developer_manual/pages/testing/ui-testing.adoc
  modules/developer_manual/pages/webdav_api/files_versions.adoc
  modules/user_manual/pages/_partials/configuration/files/encryption/not-encrypted-files.adoc
Labels: backport

#4222 [10.7] [PR 4220] Part one fixing broken anchors (in- and inter-document references)
  .gitignore
  modules/ROOT/pages/client_releases.adoc
  modules/ROOT/pages/server_release_notes.adoc
  modules/ROOT/pages/server_releases.adoc
  modules/admin_manual/pages/_partials/configuration/files/encryption/not-encrypted-files.adoc
  modules/admin_manual/pages/configuration/database/linux_database_configuration.adoc
  modules/admin_manual/pages/installation/deployment_recommendations.adoc
  modules/admin_manual/pages/installation/troubleshooting.adoc
  modules/developer_manual/pages/app/advanced/custom-cache-backend.adoc
  modules/developer_manual/pages/app/fundamentals/hooks.adoc
  modules/developer_manual/pages/app/tutorial/database_connectivity.adoc
  modules/developer_manual/pages/app/tutorial/request.adoc
  modules/developer_manual/pages/general/_devenv_docker.adoc
  modules/developer_manual/pages/general/devenv.adoc
  modules/developer_manual/pages/mobile_development/ios_library/library_installation.adoc
  modules/developer_manual/pages/testing/test-pilots.adoc
  modules/developer_manual/pages/testing/ui-testing.adoc
  modules/developer_manual/pages/webdav_api/files_versions.adoc
  modules/user_manual/pages/_partials/configuration/files/encryption/not-encrypted-files.adoc
Labels: backport

#4224 Part two fixing broken anchors (in- and inter-document references)
  modules/ROOT/pages/server_release_notes.adoc
  modules/admin_manual/pages/installation/apps_management_installation.adoc
  modules/admin_manual/pages/installation/configuration_notes_and_tips.adoc
  modules/admin_manual/pages/installation/installation_wizard.adoc
  modules/admin_manual/pages/installation/linux_packetmanager_install.adoc
  modules/admin_manual/pages/installation/manual_installation/manual_installation.adoc
  modules/admin_manual/pages/installation/manual_installation/manual_installation_prerequisites.adoc
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
  modules/admin_manual/pages/installation/system_requirements.adoc
  modules/admin_manual/pages/maintenance/manual_upgrade.adoc
  modules/admin_manual/pages/maintenance/package_upgrade.adoc
  modules/admin_manual/pages/maintenance/restore.adoc
  modules/admin_manual/pages/maintenance/update.adoc
  modules/developer_manual/pages/core/apis/ocs-share-api.adoc
  modules/developer_manual/pages/core/apis/ocs-totp-validation-api.adoc
  modules/developer_manual/pages/general/devenv.adoc
Labels: developer docs, admin docs

#4225 [10.8] [PR 4224] Part two fixing broken anchors (in- and inter-document references)
  modules/ROOT/pages/server_release_notes.adoc
  modules/admin_manual/pages/installation/apps_management_installation.adoc
  modules/admin_manual/pages/installation/configuration_notes_and_tips.adoc
  modules/admin_manual/pages/installation/installation_wizard.adoc
  modules/admin_manual/pages/installation/linux_packetmanager_install.adoc
  modules/admin_manual/pages/installation/manual_installation/manual_installation.adoc
  modules/admin_manual/pages/installation/manual_installation/manual_installation_prerequisites.adoc
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
  modules/admin_manual/pages/installation/system_requirements.adoc
  modules/admin_manual/pages/maintenance/manual_upgrade.adoc
  modules/admin_manual/pages/maintenance/package_upgrade.adoc
  modules/admin_manual/pages/maintenance/restore.adoc
  modules/admin_manual/pages/maintenance/update.adoc
  modules/developer_manual/pages/core/apis/ocs-share-api.adoc
  modules/developer_manual/pages/core/apis/ocs-totp-validation-api.adoc
  modules/developer_manual/pages/general/devenv.adoc
Labels: backport

#4226 [10.7] [PR 4224] Part two fixing broken anchors (in- and inter-document references)
  modules/ROOT/pages/server_release_notes.adoc
  modules/admin_manual/pages/installation/apps_management_installation.adoc
  modules/admin_manual/pages/installation/configuration_notes_and_tips.adoc
  modules/admin_manual/pages/installation/installation_wizard.adoc
  modules/admin_manual/pages/installation/linux_packetmanager_install.adoc
  modules/admin_manual/pages/installation/manual_installation/manual_installation.adoc
  modules/admin_manual/pages/installation/manual_installation/manual_installation_prerequisites.adoc
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
  modules/admin_manual/pages/installation/system_requirements.adoc
  modules/admin_manual/pages/maintenance/manual_upgrade.adoc
  modules/admin_manual/pages/maintenance/package_upgrade.adoc
  modules/admin_manual/pages/maintenance/restore.adoc
  modules/admin_manual/pages/maintenance/update.adoc
  modules/developer_manual/pages/core/apis/ocs-share-api.adoc
  modules/developer_manual/pages/core/apis/ocs-totp-validation-api.adoc
  modules/developer_manual/pages/general/devenv.adoc
Labels: backport

#4227 Part three fixing broken anchors (in- and inter-document references)
  modules/admin_manual/pages/_partials/configuration/server/occ_command/background_jobs_selector.adoc
  modules/admin_manual/pages/appliance/configuration/clamav.adoc
  modules/admin_manual/pages/appliance/configuration/login_information.adoc
  modules/admin_manual/pages/appliance/configuration/wnd_setup.adoc
  modules/admin_manual/pages/appliance/installation/installation.adoc
  modules/admin_manual/pages/appliance/maintenance/howto-update-owncloud.adoc
  modules/admin_manual/pages/configuration/database/linux_database_configuration.adoc
  modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
  modules/admin_manual/pages/configuration/files/external_storage/local.adoc
  modules/admin_manual/pages/configuration/general_topics/general_troubleshooting.adoc
  modules/admin_manual/pages/configuration/search/index.adoc
  modules/admin_manual/pages/configuration/server/activity_configuration.adoc
  modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc
  modules/admin_manual/pages/configuration/server/caching_configuration.adoc
  modules/admin_manual/pages/configuration/server/excluded_blacklisted_files.adoc
  modules/admin_manual/pages/configuration/server/index_php_less_urls.adoc
  modules/admin_manual/pages/configuration/server/occ_command.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_wnd_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_command_line_installation_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_encryption_commands.adoc
  modules/admin_manual/pages/configuration/server/security/hsmdaemon/index.adoc
  modules/admin_manual/pages/configuration/server/security/hsmdaemon/softhsm2.adoc
  modules/admin_manual/pages/configuration/server/security_setup_warnings.adoc
  modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc
  modules/admin_manual/pages/configuration/user/user_auth_ftp_smb_imap.adoc
  modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
  modules/admin_manual/pages/configuration/user/user_roles.adoc
  modules/admin_manual/pages/enterprise/collaboration/collabora_secure_view.adoc
  modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
  modules/admin_manual/pages/enterprise/installation/install.adoc
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
  modules/admin_manual/pages/installation/system_requirements.adoc
  modules/admin_manual/pages/maintenance/encryption/migrating-from-user-key-to-master-key.adoc
  modules/admin_manual/pages/maintenance/export_import_instance_data.adoc
  modules/admin_manual/pages/maintenance/migrating.adoc
  modules/admin_manual/pages/maintenance/update.adoc
Labels: developer docs, admin docs

#4228 [10.8] [PR 4227] Part three fixing broken anchors (in- and inter-document references)
  modules/admin_manual/pages/_partials/configuration/server/occ_command/background_jobs_selector.adoc
  modules/admin_manual/pages/appliance/configuration/clamav.adoc
  modules/admin_manual/pages/appliance/configuration/login_information.adoc
  modules/admin_manual/pages/appliance/configuration/wnd_setup.adoc
  modules/admin_manual/pages/appliance/installation/installation.adoc
  modules/admin_manual/pages/appliance/maintenance/howto-update-owncloud.adoc
  modules/admin_manual/pages/configuration/database/linux_database_configuration.adoc
  modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
  modules/admin_manual/pages/configuration/files/external_storage/local.adoc
  modules/admin_manual/pages/configuration/general_topics/general_troubleshooting.adoc
  modules/admin_manual/pages/configuration/search/index.adoc
  modules/admin_manual/pages/configuration/server/activity_configuration.adoc
  modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc
  modules/admin_manual/pages/configuration/server/caching_configuration.adoc
  modules/admin_manual/pages/configuration/server/excluded_blacklisted_files.adoc
  modules/admin_manual/pages/configuration/server/index_php_less_urls.adoc
  modules/admin_manual/pages/configuration/server/occ_command.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_wnd_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_command_line_installation_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_encryption_commands.adoc
  modules/admin_manual/pages/configuration/server/security/hsmdaemon/index.adoc
  modules/admin_manual/pages/configuration/server/security/hsmdaemon/softhsm2.adoc
  modules/admin_manual/pages/configuration/server/security_setup_warnings.adoc
  modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc
  modules/admin_manual/pages/configuration/user/user_auth_ftp_smb_imap.adoc
  modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
  modules/admin_manual/pages/configuration/user/user_roles.adoc
  modules/admin_manual/pages/enterprise/collaboration/collabora_secure_view.adoc
  modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
  modules/admin_manual/pages/enterprise/installation/install.adoc
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
  modules/admin_manual/pages/installation/system_requirements.adoc
  modules/admin_manual/pages/maintenance/encryption/migrating-from-user-key-to-master-key.adoc
  modules/admin_manual/pages/maintenance/export_import_instance_data.adoc
  modules/admin_manual/pages/maintenance/migrating.adoc
  modules/admin_manual/pages/maintenance/update.adoc
Labels: backport

#4229 [10.7] [PR 4227] Part three fixing broken anchors (in- and inter-document references)
  modules/admin_manual/pages/_partials/configuration/server/occ_command/background_jobs_selector.adoc
  modules/admin_manual/pages/appliance/configuration/clamav.adoc
  modules/admin_manual/pages/appliance/configuration/login_information.adoc
  modules/admin_manual/pages/appliance/configuration/wnd_setup.adoc
  modules/admin_manual/pages/appliance/installation/installation.adoc
  modules/admin_manual/pages/appliance/maintenance/howto-update-owncloud.adoc
  modules/admin_manual/pages/configuration/database/linux_database_configuration.adoc
  modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
  modules/admin_manual/pages/configuration/files/external_storage/local.adoc
  modules/admin_manual/pages/configuration/general_topics/general_troubleshooting.adoc
  modules/admin_manual/pages/configuration/search/index.adoc
  modules/admin_manual/pages/configuration/server/activity_configuration.adoc
  modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc
  modules/admin_manual/pages/configuration/server/caching_configuration.adoc
  modules/admin_manual/pages/configuration/server/excluded_blacklisted_files.adoc
  modules/admin_manual/pages/configuration/server/index_php_less_urls.adoc
  modules/admin_manual/pages/configuration/server/occ_command.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_wnd_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_command_line_installation_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_encryption_commands.adoc
  modules/admin_manual/pages/configuration/server/security/hsmdaemon/index.adoc
  modules/admin_manual/pages/configuration/server/security/hsmdaemon/softhsm2.adoc
  modules/admin_manual/pages/configuration/server/security_setup_warnings.adoc
  modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc
  modules/admin_manual/pages/configuration/user/user_auth_ftp_smb_imap.adoc
  modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
  modules/admin_manual/pages/configuration/user/user_roles.adoc
  modules/admin_manual/pages/enterprise/collaboration/collabora_secure_view.adoc
  modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
  modules/admin_manual/pages/enterprise/installation/install.adoc
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
  modules/admin_manual/pages/installation/system_requirements.adoc
  modules/admin_manual/pages/maintenance/encryption/migrating-from-user-key-to-master-key.adoc
  modules/admin_manual/pages/maintenance/export_import_instance_data.adoc
  modules/admin_manual/pages/maintenance/migrating.adoc
  modules/admin_manual/pages/maintenance/update.adoc
Labels: backport

#4231 [10.8] [PR 4230] Part four fixing broken anchors (in- and inter-document references)
  modules/admin_manual/pages/configuration/general_topics/general_troubleshooting.adoc
  modules/admin_manual/pages/configuration/search/index.adoc
  modules/admin_manual/pages/configuration/server/security/hsmdaemon/index.adoc
  modules/admin_manual/pages/configuration/server/security/hsmdaemon/softhsm2.adoc
  modules/admin_manual/pages/configuration/server/security_setup_warnings.adoc
Labels: backport

#4232 [10.7] [PR 4230] Part four fixing broken anchors (in- and inter-document references)
  modules/admin_manual/pages/configuration/general_topics/general_troubleshooting.adoc
  modules/admin_manual/pages/configuration/search/index.adoc
  modules/admin_manual/pages/configuration/server/security/hsmdaemon/index.adoc
  modules/admin_manual/pages/configuration/server/security/hsmdaemon/softhsm2.adoc
  modules/admin_manual/pages/configuration/server/security_setup_warnings.adoc
Labels: backport

#4234 Remove the page-noindex attribute for _richdocuments.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_richdocuments.adoc
Labels: admin docs

#4236 [10.8] [PR 4233] Remove the page-noindex attribute for occ files (no longer necessary)
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_2fa_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_activity_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_admin_audit_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_antivirus_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_brute_force_protection_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_calendar_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_contacts_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_data_explorer_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_files_lifecycle.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_ldap_integration_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_market_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_metrics_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_oauth2_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_password_policy_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_richdocuments.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_s3objectstore_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_saml_sso_shibboleth_integration_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_wnd_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_app_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_background_jobs_selector.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_command_line_installation_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_command_line_upgrade_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_config_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_config_reports_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_database_conversion_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_dav_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_encryption_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_federation_sync_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_file_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_files_external_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_full_text_search_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_group_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_incoming_shares_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_integrity_check_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_localisation_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_logging_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_maintenance_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_managing_background_jobs.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_migration_steps_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_mimetype_update_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_notifications_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_security_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_sharing_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_trashbin_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_user_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_versions_commands.adoc
Labels: backport

#4235 Part five fixing broken anchors (in- and inter-document references)
  modules/admin_manual/pages/configuration/server/security/oauth2.adoc
  modules/admin_manual/pages/enterprise/collaboration/collabora_secure_view.adoc
Labels: admin docs

#4238 Update checking broken link page and package.json
  docs/checking-broken-links.md
  package.json
  yarn.lock
Labels: deployment, dependencies

#4240 [10.8] [PR 4238] Update checking broken link page and package.json
  docs/checking-broken-links.md
  package.json
  yarn.lock
Labels: backport

#4241 [10.7] [PR 4238] Update checking broken link page and package.json
  docs/checking-broken-links.md
  package.json
  yarn.lock
Labels: backport

#4243 Add new user:list option
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_user_commands.adoc
Labels: admin docs

#4244 Exchange the enterprise repo link with the corresponding core PR link
  modules/ROOT/pages/server_release_notes.adoc
Labels: bug

#4245 [10.8] [PR 4244] Exchange the enterprise repo link with the corresponding core PR link
  modules/ROOT/pages/server_release_notes.adoc
Labels: backport

#3943 Updates for WND 2.1.0
  modules/admin_manual/assets/images/enterprise/external_storage/enterprise-only-auth/auth_backends-1.png
  modules/admin_manual/assets/images/enterprise/external_storage/windows_network_drive/wnd-2.png
  modules/admin_manual/assets/images/enterprise/external_storage/windows_network_drive/wnd-4.png
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_wnd_commands.adoc
  modules/admin_manual/pages/enterprise/external_storage/enterprise_only_auth.adoc
  modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
Labels: admin docs

#4246 [10.8] [PR 3943] Updates for WND 2.1.0
  modules/admin_manual/assets/images/enterprise/external_storage/enterprise-only-auth/auth_backends-1.png
  modules/admin_manual/assets/images/enterprise/external_storage/windows_network_drive/wnd-2.png
  modules/admin_manual/assets/images/enterprise/external_storage/windows_network_drive/wnd-4.png
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_wnd_commands.adoc
  modules/admin_manual/pages/enterprise/external_storage/enterprise_only_auth.adoc
  modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
Labels: backport

#4247 Fixing external links returning 404
  modules/ROOT/pages/client_releases.adoc
  modules/ROOT/pages/server_release_notes.adoc
  modules/admin_manual/pages/configuration/database/linux_database_configuration.adoc
  modules/admin_manual/pages/configuration/general_topics/general_troubleshooting.adoc
  modules/admin_manual/pages/configuration/server/harden_server.adoc
  modules/admin_manual/pages/configuration/server/legal_settings_configuration.adoc
  modules/admin_manual/pages/configuration/server/logging/request_tracing.adoc
  modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
  modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
  modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
  modules/admin_manual/pages/installation/deployment_recommendations.adoc
  modules/developer_manual/pages/app/fundamentals/database.adoc
  modules/developer_manual/pages/app/fundamentals/info.adoc
  modules/developer_manual/pages/bugtracker/triaging.adoc
  modules/developer_manual/pages/core/apis/ocs-notification-endpoint-v1.adoc
  modules/user_manual/pages/_partials/direct_file_access_tip.adoc
  modules/user_manual/pages/files/access_webdav.adoc
  modules/user_manual/pages/pim/sync_thunderbird.adoc
Labels: developer docs, user docs, admin docs

#4248 [10.8] [PR 4247] Fixing external links returning 404
  modules/ROOT/pages/client_releases.adoc
  modules/ROOT/pages/server_release_notes.adoc
  modules/admin_manual/pages/configuration/database/linux_database_configuration.adoc
  modules/admin_manual/pages/configuration/general_topics/general_troubleshooting.adoc
  modules/admin_manual/pages/configuration/server/harden_server.adoc
  modules/admin_manual/pages/configuration/server/legal_settings_configuration.adoc
  modules/admin_manual/pages/configuration/server/logging/request_tracing.adoc
  modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
  modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
  modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
  modules/admin_manual/pages/installation/deployment_recommendations.adoc
  modules/developer_manual/pages/app/fundamentals/database.adoc
  modules/developer_manual/pages/app/fundamentals/info.adoc
  modules/developer_manual/pages/bugtracker/triaging.adoc
  modules/developer_manual/pages/core/apis/ocs-notification-endpoint-v1.adoc
  modules/user_manual/pages/_partials/direct_file_access_tip.adoc
  modules/user_manual/pages/files/access_webdav.adoc
  modules/user_manual/pages/pim/sync_thunderbird.adoc
Labels: backport

#4209 Fix occ twofactor
  modules/admin_manual/pages/_partials/nav.adoc
  modules/admin_manual/pages/configuration/server/occ_command.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_2fa_app_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_2fa_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_2fa_core_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_file_commands.adoc
  modules/admin_manual/pages/configuration/user/user_auth_twofactor.adoc
  modules/admin_manual/pages/configuration/user/user_management.adoc
  modules/user_manual/assets/images/personal-settings/general.png
  modules/user_manual/assets/images/personal-settings/general/general.png
  modules/user_manual/assets/images/personal-settings/oc_personal_settings_dropdown.png
  modules/user_manual/assets/images/personal-settings/security.png
  modules/user_manual/assets/images/personal-settings/security/activate-2fa-totp.png
  modules/user_manual/assets/images/personal-settings/security/enable-2fa-totp.png
  modules/user_manual/assets/images/personal-settings/sharing/sharing.png
  modules/user_manual/assets/images/personal-settings/storage/external-storage.png
  modules/user_manual/assets/images/personal_settings.png
  modules/user_manual/pages/index.adoc
  modules/user_manual/pages/personal_settings/general.adoc
  modules/user_manual/pages/personal_settings/index.adoc
  modules/user_manual/pages/personal_settings/security.adoc
  modules/user_manual/pages/personal_settings/sharing.adoc
  modules/user_manual/pages/personal_settings/storage.adoc
Labels: admin docs

#4250 [10.8] [PR 4209] Fix occ twofactor
  modules/admin_manual/pages/_partials/nav.adoc
  modules/admin_manual/pages/configuration/server/occ_command.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_2fa_app_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_2fa_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_2fa_core_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_file_commands.adoc
  modules/admin_manual/pages/configuration/user/user_auth_twofactor.adoc
  modules/admin_manual/pages/configuration/user/user_management.adoc
  modules/user_manual/assets/images/personal-settings/general.png
  modules/user_manual/assets/images/personal-settings/general/general.png
  modules/user_manual/assets/images/personal-settings/oc_personal_settings_dropdown.png
  modules/user_manual/assets/images/personal-settings/security.png
  modules/user_manual/assets/images/personal-settings/security/activate-2fa-totp.png
  modules/user_manual/assets/images/personal-settings/security/enable-2fa-totp.png
  modules/user_manual/assets/images/personal-settings/sharing/sharing.png
  modules/user_manual/assets/images/personal-settings/storage/external-storage.png
  modules/user_manual/assets/images/personal_settings.png
  modules/user_manual/pages/index.adoc
  modules/user_manual/pages/personal_settings/general.adoc
  modules/user_manual/pages/personal_settings/index.adoc
  modules/user_manual/pages/personal_settings/security.adoc
  modules/user_manual/pages/personal_settings/sharing.adoc
  modules/user_manual/pages/personal_settings/storage.adoc
Labels: backport

#4251 [10.7] [PR 4209] Fix occ twofactor
  modules/admin_manual/pages/_partials/nav.adoc
  modules/admin_manual/pages/configuration/server/occ_command.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_2fa_app_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_2fa_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_2fa_core_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_file_commands.adoc
  modules/admin_manual/pages/configuration/user/user_auth_twofactor.adoc
  modules/admin_manual/pages/configuration/user/user_management.adoc
  modules/user_manual/assets/images/personal-settings/general.png
  modules/user_manual/assets/images/personal-settings/general/general.png
  modules/user_manual/assets/images/personal-settings/oc_personal_settings_dropdown.png
  modules/user_manual/assets/images/personal-settings/security.png
  modules/user_manual/assets/images/personal-settings/security/activate-2fa-totp.png
  modules/user_manual/assets/images/personal-settings/security/enable-2fa-totp.png
  modules/user_manual/assets/images/personal-settings/sharing/sharing.png
  modules/user_manual/assets/images/personal-settings/storage/external-storage.png
  modules/user_manual/assets/images/personal_settings.png
  modules/user_manual/pages/index.adoc
  modules/user_manual/pages/personal_settings/general.adoc
  modules/user_manual/pages/personal_settings/index.adoc
  modules/user_manual/pages/personal_settings/security.adoc
  modules/user_manual/pages/personal_settings/sharing.adoc
  modules/user_manual/pages/personal_settings/storage.adoc
Labels: backport

#4254 Fixing external links returning 404 (part two)
  docs/checking-broken-links.md
  modules/ROOT/pages/client_releases.adoc
  modules/ROOT/pages/how_to_contribute.adoc
  modules/ROOT/pages/server_release_notes.adoc
  modules/admin_manual/pages/configuration/database/linux_database_configuration.adoc
  modules/admin_manual/pages/configuration/files/previews_configuration.adoc
  modules/admin_manual/pages/configuration/server/caching_configuration.adoc
  modules/admin_manual/pages/configuration/server/harden_server.adoc
  modules/admin_manual/pages/configuration/server/index_php_less_urls.adoc
  modules/admin_manual/pages/configuration/server/legal_settings_configuration.adoc
  modules/admin_manual/pages/configuration/server/logging/logging_configuration.adoc
  modules/admin_manual/pages/configuration/server/oc_server_tuning.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_password_policy_commands.adoc
  modules/admin_manual/pages/configuration/server/security/hsmdaemon/index.adoc
  modules/admin_manual/pages/configuration/user/user_auth_ftp_smb_imap.adoc
  modules/admin_manual/pages/enterprise/user_management/saml_2.0_sso.adoc
  modules/admin_manual/pages/installation/apps/mediaviewer/index.adoc
  modules/admin_manual/pages/installation/configuration_notes_and_tips.adoc
  modules/admin_manual/pages/installation/manual_installation/manual_installation_apache.adoc
  modules/admin_manual/pages/installation/manual_installation/manual_installation_prerequisites.adoc
  modules/admin_manual/pages/installation/manual_installation/script_guided_install.adoc
  modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc
  modules/admin_manual/pages/installation/system_requirements.adoc
  modules/developer_manual/examples/core/scripts/php/vendor/guzzlehttp/guzzle/src/functions.php
  modules/developer_manual/examples/core/scripts/php/vendor/guzzlehttp/psr7/src/InflateStream.php
  modules/developer_manual/examples/core/scripts/php/vendor/guzzlehttp/psr7/src/UploadedFile.php
  modules/developer_manual/examples/core/scripts/php/vendor/psr/http-message/src/StreamInterface.php
  modules/developer_manual/examples/core/scripts/php/vendor/psr/http-message/src/UploadedFileInterface.php
  modules/developer_manual/examples/scripts/read-config.php
  modules/developer_manual/pages/app/advanced/custom-storage-backend.adoc
  modules/developer_manual/pages/app/advanced/l10n.adoc
  modules/developer_manual/pages/app/advanced/storage-backend.adoc
  modules/developer_manual/pages/app/fundamentals/database.adoc
  modules/developer_manual/pages/app/fundamentals/info.adoc
  modules/developer_manual/pages/app/tutorial/database_connectivity.adoc
  modules/developer_manual/pages/general/security.adoc
  modules/user_manual/pages/files/access_webdav.adoc
  site.yml
Labels: developer docs, user docs, admin docs

#4257 [10.8] [PR 4254] Fixing external links returning 404 (part two)
  docs/checking-broken-links.md
  modules/ROOT/pages/client_releases.adoc
  modules/ROOT/pages/how_to_contribute.adoc
  modules/ROOT/pages/server_release_notes.adoc
  modules/admin_manual/pages/configuration/database/linux_database_configuration.adoc
  modules/admin_manual/pages/configuration/files/previews_configuration.adoc
  modules/admin_manual/pages/configuration/server/caching_configuration.adoc
  modules/admin_manual/pages/configuration/server/harden_server.adoc
  modules/admin_manual/pages/configuration/server/index_php_less_urls.adoc
  modules/admin_manual/pages/configuration/server/legal_settings_configuration.adoc
  modules/admin_manual/pages/configuration/server/logging/logging_configuration.adoc
  modules/admin_manual/pages/configuration/server/oc_server_tuning.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_password_policy_commands.adoc
  modules/admin_manual/pages/configuration/server/security/hsmdaemon/index.adoc
  modules/admin_manual/pages/configuration/user/user_auth_ftp_smb_imap.adoc
  modules/admin_manual/pages/enterprise/user_management/saml_2.0_sso.adoc
  modules/admin_manual/pages/installation/apps/mediaviewer/index.adoc
  modules/admin_manual/pages/installation/configuration_notes_and_tips.adoc
  modules/admin_manual/pages/installation/manual_installation/manual_installation_apache.adoc
  modules/admin_manual/pages/installation/manual_installation/manual_installation_prerequisites.adoc
  modules/admin_manual/pages/installation/manual_installation/script_guided_install.adoc
  modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc
  modules/admin_manual/pages/installation/system_requirements.adoc
  modules/developer_manual/examples/core/scripts/php/vendor/guzzlehttp/guzzle/src/functions.php
  modules/developer_manual/examples/core/scripts/php/vendor/guzzlehttp/psr7/src/InflateStream.php
  modules/developer_manual/examples/core/scripts/php/vendor/guzzlehttp/psr7/src/UploadedFile.php
  modules/developer_manual/examples/core/scripts/php/vendor/psr/http-message/src/StreamInterface.php
  modules/developer_manual/examples/core/scripts/php/vendor/psr/http-message/src/UploadedFileInterface.php
  modules/developer_manual/examples/scripts/read-config.php
  modules/developer_manual/pages/app/advanced/custom-storage-backend.adoc
  modules/developer_manual/pages/app/advanced/l10n.adoc
  modules/developer_manual/pages/app/advanced/storage-backend.adoc
  modules/developer_manual/pages/app/fundamentals/database.adoc
  modules/developer_manual/pages/app/fundamentals/info.adoc
  modules/developer_manual/pages/app/tutorial/database_connectivity.adoc
  modules/developer_manual/pages/general/security.adoc
  modules/user_manual/pages/files/access_webdav.adoc
  site.yml
Labels: backport

#4258 [10.7] [PR 4254] Fixing external links returning 404 (part two)
  docs/checking-broken-links.md
  modules/ROOT/pages/client_releases.adoc
  modules/ROOT/pages/how_to_contribute.adoc
  modules/ROOT/pages/server_release_notes.adoc
  modules/admin_manual/pages/configuration/database/linux_database_configuration.adoc
  modules/admin_manual/pages/configuration/files/previews_configuration.adoc
  modules/admin_manual/pages/configuration/server/caching_configuration.adoc
  modules/admin_manual/pages/configuration/server/harden_server.adoc
  modules/admin_manual/pages/configuration/server/index_php_less_urls.adoc
  modules/admin_manual/pages/configuration/server/legal_settings_configuration.adoc
  modules/admin_manual/pages/configuration/server/logging/logging_configuration.adoc
  modules/admin_manual/pages/configuration/server/oc_server_tuning.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_password_policy_commands.adoc
  modules/admin_manual/pages/configuration/server/security/hsmdaemon/index.adoc
  modules/admin_manual/pages/configuration/user/user_auth_ftp_smb_imap.adoc
  modules/admin_manual/pages/enterprise/user_management/saml_2.0_sso.adoc
  modules/admin_manual/pages/installation/apps/mediaviewer/index.adoc
  modules/admin_manual/pages/installation/configuration_notes_and_tips.adoc
  modules/admin_manual/pages/installation/manual_installation/manual_installation_apache.adoc
  modules/admin_manual/pages/installation/manual_installation/manual_installation_prerequisites.adoc
  modules/admin_manual/pages/installation/manual_installation/script_guided_install.adoc
  modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc
  modules/admin_manual/pages/installation/system_requirements.adoc
  modules/developer_manual/examples/core/scripts/php/vendor/guzzlehttp/guzzle/src/functions.php
  modules/developer_manual/examples/core/scripts/php/vendor/guzzlehttp/psr7/src/InflateStream.php
  modules/developer_manual/examples/core/scripts/php/vendor/guzzlehttp/psr7/src/UploadedFile.php
  modules/developer_manual/examples/core/scripts/php/vendor/psr/http-message/src/StreamInterface.php
  modules/developer_manual/examples/core/scripts/php/vendor/psr/http-message/src/UploadedFileInterface.php
  modules/developer_manual/examples/scripts/read-config.php
  modules/developer_manual/pages/app/advanced/custom-storage-backend.adoc
  modules/developer_manual/pages/app/advanced/l10n.adoc
  modules/developer_manual/pages/app/advanced/storage-backend.adoc
  modules/developer_manual/pages/app/fundamentals/database.adoc
  modules/developer_manual/pages/app/fundamentals/info.adoc
  modules/developer_manual/pages/app/tutorial/database_connectivity.adoc
  modules/developer_manual/pages/general/security.adoc
  modules/user_manual/pages/files/access_webdav.adoc
  site.yml
Labels: backport

#4256 Small fixes (section name, missing toc)
  modules/admin_manual/pages/enterprise/external_storage/enterprise_only_auth.adoc
  modules/admin_manual/pages/maintenance/manually-moving-data-folders.adoc
Labels: admin docs

#4255 Adding occ command setting to hide the upload estimation
  modules/admin_manual/assets/images/configuration/server/ui-configuration/upload-progress-bar.png
  modules/admin_manual/pages/_partials/nav.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_config_commands.adoc
  modules/admin_manual/pages/configuration/server/ui-configuration.adoc
Labels: admin docs

#4259 Update the Apache and Lets Encrypt documentation
  modules/admin_manual/pages/installation/letsencrypt/apache.adoc
  modules/admin_manual/pages/installation/letsencrypt/using_letsencrypt.adoc
  modules/admin_manual/pages/installation/manual_installation/manual_installation_apache.adoc
Labels: admin docs

#4261 [10.7] [PR 4256] Small fixes (section name, missing toc)
  modules/admin_manual/pages/enterprise/external_storage/enterprise_only_auth.adoc
  modules/admin_manual/pages/maintenance/manually-moving-data-folders.adoc
Labels: backport

#4260 [10.8] [PR 4256] Small fixes (section name, missing toc)
  modules/admin_manual/pages/enterprise/external_storage/enterprise_only_auth.adoc
  modules/admin_manual/pages/maintenance/manually-moving-data-folders.adoc
Labels: backport

#4263 [10.7] [PR 4259] Update the Apache and Lets Encrypt documentation
  modules/admin_manual/pages/installation/letsencrypt/apache.adoc
  modules/admin_manual/pages/installation/letsencrypt/using_letsencrypt.adoc
  modules/admin_manual/pages/installation/manual_installation/manual_installation_apache.adoc
Labels: backport

#4262 [10.8] [PR 4259] Update the Apache and Lets Encrypt documentation
  modules/admin_manual/pages/installation/letsencrypt/apache.adoc
  modules/admin_manual/pages/installation/letsencrypt/using_letsencrypt.adoc
  modules/admin_manual/pages/installation/manual_installation/manual_installation_apache.adoc
Labels: backport

#4264 Fixing external links returning 404 (part three)
  modules/ROOT/pages/client_releases.adoc
  modules/developer_manual/pages/app/fundamentals/info.adoc
  modules/developer_manual/pages/bugtracker/triaging.adoc
Labels: developer docs

#4265 [10.8] [PR 4264] Fixing external links returning 404 (part three)
  modules/ROOT/pages/client_releases.adoc
  modules/developer_manual/pages/app/fundamentals/info.adoc
  modules/developer_manual/pages/bugtracker/triaging.adoc
Labels: backport

#4266 [10.7] [PR 4264] Fixing external links returning 404 (part three)
  modules/ROOT/pages/client_releases.adoc
  modules/developer_manual/pages/app/fundamentals/info.adoc
  modules/developer_manual/pages/bugtracker/triaging.adoc
Labels: backport

#4268 Config to docs run from recent changes in core
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Labels: admin docs

#4271 [10.7] [PR 4268] Config to docs run from recent changes in core
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Labels: backport

#4270 [10.8] [PR 4268] Config to docs run from recent changes in core
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Labels: backport

#4267 Fix redirect issues and external anchors
  modules/ROOT/pages/server_release_notes.adoc
  modules/admin_manual/pages/configuration/server/legal_settings_configuration.adoc
  modules/admin_manual/pages/configuration/server/oc_server_tuning.adoc
  modules/admin_manual/pages/configuration/user/oidc/kopano-setup.adoc
  modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
  modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
  modules/admin_manual/pages/index.adoc
  modules/admin_manual/pages/installation/apps/mediaviewer/index.adoc
  modules/admin_manual/pages/installation/configuration_notes_and_tips.adoc
  modules/admin_manual/pages/installation/linux_packetmanager_install.adoc
  modules/admin_manual/pages/installation/manual_installation/manual_installation_prerequisites.adoc
  modules/admin_manual/pages/maintenance/manual_upgrade.adoc
  modules/developer_manual/pages/app/fundamentals/controllers.adoc
  modules/developer_manual/pages/app/fundamentals/logging.adoc
  modules/developer_manual/pages/bugtracker/index.adoc
  modules/developer_manual/pages/bugtracker/triaging.adoc
  modules/developer_manual/pages/general/debugging.adoc
  modules/developer_manual/pages/general/security.adoc
  modules/developer_manual/pages/mobile_development/ios_library/library_installation.adoc
  modules/developer_manual/pages/testing/acceptance-tests.adoc
  modules/developer_manual/pages/testing/ui-testing.adoc
  modules/user_manual/pages/files/webgui/navigating.adoc
  modules/user_manual/pages/pim/sync_thunderbird.adoc
Labels: developer docs, user docs, admin docs

#4273 [10.7] [PR 4267] Fix redirect issues and external anchors
  modules/ROOT/pages/server_release_notes.adoc
  modules/admin_manual/pages/configuration/server/legal_settings_configuration.adoc
  modules/admin_manual/pages/configuration/server/oc_server_tuning.adoc
  modules/admin_manual/pages/configuration/user/oidc/kopano-setup.adoc
  modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
  modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
  modules/admin_manual/pages/index.adoc
  modules/admin_manual/pages/installation/apps/mediaviewer/index.adoc
  modules/admin_manual/pages/installation/configuration_notes_and_tips.adoc
  modules/admin_manual/pages/installation/linux_packetmanager_install.adoc
  modules/admin_manual/pages/installation/manual_installation/manual_installation_prerequisites.adoc
  modules/admin_manual/pages/maintenance/manual_upgrade.adoc
  modules/developer_manual/pages/app/fundamentals/controllers.adoc
  modules/developer_manual/pages/app/fundamentals/logging.adoc
  modules/developer_manual/pages/bugtracker/index.adoc
  modules/developer_manual/pages/bugtracker/triaging.adoc
  modules/developer_manual/pages/general/debugging.adoc
  modules/developer_manual/pages/general/security.adoc
  modules/developer_manual/pages/mobile_development/ios_library/library_installation.adoc
  modules/developer_manual/pages/testing/acceptance-tests.adoc
  modules/developer_manual/pages/testing/ui-testing.adoc
  modules/user_manual/pages/files/webgui/navigating.adoc
  modules/user_manual/pages/pim/sync_thunderbird.adoc
Labels: backport

#4272 [10.8] [PR 4267] Fix redirect issues and external anchors
  modules/ROOT/pages/server_release_notes.adoc
  modules/admin_manual/pages/configuration/server/legal_settings_configuration.adoc
  modules/admin_manual/pages/configuration/server/oc_server_tuning.adoc
  modules/admin_manual/pages/configuration/user/oidc/kopano-setup.adoc
  modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
  modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
  modules/admin_manual/pages/index.adoc
  modules/admin_manual/pages/installation/apps/mediaviewer/index.adoc
  modules/admin_manual/pages/installation/configuration_notes_and_tips.adoc
  modules/admin_manual/pages/installation/linux_packetmanager_install.adoc
  modules/admin_manual/pages/installation/manual_installation/manual_installation_prerequisites.adoc
  modules/admin_manual/pages/maintenance/manual_upgrade.adoc
  modules/developer_manual/pages/app/fundamentals/controllers.adoc
  modules/developer_manual/pages/app/fundamentals/logging.adoc
  modules/developer_manual/pages/bugtracker/index.adoc
  modules/developer_manual/pages/bugtracker/triaging.adoc
  modules/developer_manual/pages/general/debugging.adoc
  modules/developer_manual/pages/general/security.adoc
  modules/developer_manual/pages/mobile_development/ios_library/library_installation.adoc
  modules/developer_manual/pages/testing/acceptance-tests.adoc
  modules/developer_manual/pages/testing/ui-testing.adoc
  modules/user_manual/pages/files/webgui/navigating.adoc
  modules/user_manual/pages/pim/sync_thunderbird.adoc
Labels: backport

#4281 Fix konnect attributes (for 10.7 only)
  modules/admin_manual/pages/configuration/user/oidc/kopano-setup.adoc
Labels: admin docs

#4276 [10.8] [PR 4274] s3_compatible_object_storage_as_primary.adoc use marketplace with /apps/
  modules/admin_manual/pages/configuration/files/external_storage/s3_compatible_object_storage_as_primary.adoc
Labels: backport

#4277 [10.7] [PR 4274] s3_compatible_object_storage_as_primary.adoc use marketplace with /apps/
  modules/admin_manual/pages/configuration/files/external_storage/s3_compatible_object_storage_as_primary.adoc
Labels: backport

#4278 [10.8] [PR 4275] suggest to end PHP variable assignements with semicolon
  modules/admin_manual/pages/configuration/files/external_storage/s3_compatible_object_storage_as_primary.adoc
Labels: backport

#4279 [10.7] [PR 4275] suggest to end PHP variable assignements with semicolon
  modules/admin_manual/pages/configuration/files/external_storage/s3_compatible_object_storage_as_primary.adoc
Labels: backport

#4282 New Android version
  site.yml
Labels: deployment

#4283 [10.8] [PR 4282] New Android version
  site.yml
Labels: backport

#4284 [10.7] [PR 4282] New Android version
  site.yml
Labels: backport

#4285 Adding Android previous release
  modules/ROOT/pages/client_releases.adoc
Labels: deployment

#4287 [10.7] [PR 4285] Adding Android previous release
  modules/ROOT/pages/client_releases.adoc
Labels: backport

#4286 [10.8] [PR 4285] Adding Android previous release
  modules/ROOT/pages/client_releases.adoc
Labels: backport

#4291 [10.8] [PR 4288] consistent use of semicolon
  modules/admin_manual/pages/configuration/files/external_storage/s3_compatible_object_storage_as_primary.adoc
Labels: backport

#4293 [10.8] [PR 4289] typo in s3_compatible_object_storage_as_primary.adoc
  modules/admin_manual/pages/configuration/files/external_storage/s3_compatible_object_storage_as_primary.adoc
Labels: backport

#4294 [10.7] [PR 4289] typo in s3_compatible_object_storage_as_primary.adoc
  modules/admin_manual/pages/configuration/files/external_storage/s3_compatible_object_storage_as_primary.adoc
Labels: backport

#4296 Fix user:list command
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_user_commands.adoc
Labels: admin docs

#4298 Add new app:list option -m
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_app_commands.adoc
Labels: admin docs

#4299 Add new encryption:fix-encrypted-version option -i
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_encryption_commands.adoc
Labels: admin docs

#4297 Revise LDAP Home Connector
  modules/admin_manual/pages/enterprise/external_storage/ldap_home_connector_configuration.adoc
Labels: admin docs

#4295 Revision of the Deployment Recommendation document
  modules/admin_manual/pages/installation/deployment_recommendations.adoc
Labels: admin docs

#4301 [10.8] [PR 4297] Revise LDAP Home Connector
  modules/admin_manual/pages/enterprise/external_storage/ldap_home_connector_configuration.adoc
Labels: backport

#4302 [10.7] [PR 4297] Revise LDAP Home Connector
  modules/admin_manual/pages/enterprise/external_storage/ldap_home_connector_configuration.adoc
Labels: backport

#4304 [10.7] [PR 4295] Revision of the Deployment Recommendation document
  modules/admin_manual/pages/installation/deployment_recommendations.adoc
Labels: backport

#4303 [10.8] [PR 4295] Revision of the Deployment Recommendation document
  modules/admin_manual/pages/installation/deployment_recommendations.adoc
Labels: backport

#4310 correct name of the server release file
  docs/new-version-branch.md
Labels: deployment

#4311 [10.8] [PR 4310] correct name of the server release file
  docs/new-version-branch.md
Labels: backport

#4312 [10.7] [PR 4310] correct name of the server release file
  docs/new-version-branch.md
Labels: backport

#4313 Improve new version branch text
  docs/new-version-branch.md
Labels: deployment

#4315 [10.9] [PR 4310] correct name of the server release file
  docs/new-version-branch.md
Labels: backport

#4316 Add page alias for encryption_configuration
  modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
Labels: admin docs

#4319 [10.7] [PR 4316] Add page alias for encryption_configuration
  modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
Labels: backport

#4317 [10.9] [PR 4316] Add page alias for encryption_configuration
  modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
Labels: backport

#4318 [10.8] [PR 4316] Add page alias for encryption_configuration
  modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
Labels: backport

#4322 [10.7] [PR 4313] Improve new version branch text
  docs/new-version-branch.md
Labels: backport

#4321 [10.8] [PR 4313] Improve new version branch text
  docs/new-version-branch.md
Labels: backport

#4320 [10.9] [PR 4313] Improve new version branch text
  docs/new-version-branch.md
Labels: backport

#4314 Improve Letsencrypt and Apache
  modules/admin_manual/examples/installation/lets_encrypt/cli.ini
  modules/admin_manual/pages/installation/letsencrypt/apache.adoc
  modules/admin_manual/pages/installation/letsencrypt/using_letsencrypt.adoc
Labels: admin docs

#4323 [10.9] [PR 4314] Improve Letsencrypt and Apache
  modules/admin_manual/examples/installation/lets_encrypt/cli.ini
  modules/admin_manual/pages/installation/letsencrypt/apache.adoc
  modules/admin_manual/pages/installation/letsencrypt/using_letsencrypt.adoc
Labels: backport

#4324 [10.8] [PR 4314] Improve Letsencrypt and Apache
  modules/admin_manual/examples/installation/lets_encrypt/cli.ini
  modules/admin_manual/pages/installation/letsencrypt/apache.adoc
  modules/admin_manual/pages/installation/letsencrypt/using_letsencrypt.adoc
Labels: backport

#4325 [10.7] [PR 4314] Improve Letsencrypt and Apache
  modules/admin_manual/examples/installation/lets_encrypt/cli.ini
  modules/admin_manual/pages/installation/letsencrypt/apache.adoc
  modules/admin_manual/pages/installation/letsencrypt/using_letsencrypt.adoc
Labels: backport

#4330 Improve S3 primary
  modules/admin_manual/pages/configuration/files/external_storage/configuration.adoc
  modules/admin_manual/pages/configuration/files/external_storage/s3_compatible_object_storage_as_primary.adoc
Labels: admin docs

#4331 Fix occ user commands
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_user_commands.adoc
Labels: admin docs

#4333 [10.8] [PR 4330] Improve S3 primary
  modules/admin_manual/pages/configuration/files/external_storage/configuration.adoc
  modules/admin_manual/pages/configuration/files/external_storage/s3_compatible_object_storage_as_primary.adoc
Labels: backport

#4334 [10.7] [PR 4330] Improve S3 primary
  modules/admin_manual/pages/configuration/files/external_storage/configuration.adoc
  modules/admin_manual/pages/configuration/files/external_storage/s3_compatible_object_storage_as_primary.adoc
Labels: backport

#4338 [10.8] [PR 4331] Fix occ user commands
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_user_commands.adoc
Labels: backport

#4337 [10.9] [PR 4331] Fix occ user commands
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_user_commands.adoc
Labels: backport

#4339 [10.7] [PR 4331] Fix occ user commands
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_user_commands.adoc
Labels: backport

#4340 Update MariaDB guide
  modules/admin_manual/pages/_partials/installation/manual_installation/mariadb.adoc
  modules/admin_manual/pages/installation/manual_installation/manual_installation_db.adoc
Labels: admin docs

#4342 [10.9] [PR 4340] Update MariaDB guide
  modules/admin_manual/pages/_partials/installation/manual_installation/mariadb.adoc
  modules/admin_manual/pages/installation/manual_installation/manual_installation_db.adoc
Labels: backport

#4343 [10.8] [PR 4340] Update MariaDB guide
  modules/admin_manual/pages/_partials/installation/manual_installation/mariadb.adoc
  modules/admin_manual/pages/installation/manual_installation/manual_installation_db.adoc
Labels: backport

#4344 [10.7] [PR 4340] Update MariaDB guide
  modules/admin_manual/pages/_partials/installation/manual_installation/mariadb.adoc
  modules/admin_manual/pages/installation/manual_installation/manual_installation_db.adoc
Labels: backport

#4341 Maintenance upgrades
  modules/admin_manual/pages/_partials/nav.adoc
  modules/admin_manual/pages/maintenance/backup_and_restore/backup.adoc
  modules/admin_manual/pages/maintenance/backup_and_restore/index.adoc
  modules/admin_manual/pages/maintenance/backup_and_restore/restore.adoc
  modules/admin_manual/pages/maintenance/enable_maintenance.adoc
  modules/admin_manual/pages/maintenance/migrating.adoc
  modules/admin_manual/pages/maintenance/upgrading/index.adoc
  modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
  modules/admin_manual/pages/maintenance/upgrading/package_upgrade.adoc
  modules/admin_manual/pages/maintenance/upgrading/update.adoc
  modules/admin_manual/pages/maintenance/upgrading/upgrade.adoc
  modules/admin_manual/pages/qnap/index.adoc
Labels: admin docs

#4345 [10.9] [PR 4341] Maintenance upgrades
  modules/admin_manual/pages/_partials/nav.adoc
  modules/admin_manual/pages/maintenance/backup_and_restore/backup.adoc
  modules/admin_manual/pages/maintenance/backup_and_restore/index.adoc
  modules/admin_manual/pages/maintenance/backup_and_restore/restore.adoc
  modules/admin_manual/pages/maintenance/enable_maintenance.adoc
  modules/admin_manual/pages/maintenance/migrating.adoc
  modules/admin_manual/pages/maintenance/upgrading/index.adoc
  modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
  modules/admin_manual/pages/maintenance/upgrading/package_upgrade.adoc
  modules/admin_manual/pages/maintenance/upgrading/update.adoc
  modules/admin_manual/pages/maintenance/upgrading/upgrade.adoc
  modules/admin_manual/pages/qnap/index.adoc
Labels: backport

#4347 [10.8] [PR 4341] Maintenance upgrades
  modules/admin_manual/pages/_partials/nav.adoc
  modules/admin_manual/pages/maintenance/backup_and_restore/backup.adoc
  modules/admin_manual/pages/maintenance/backup_and_restore/index.adoc
  modules/admin_manual/pages/maintenance/backup_and_restore/restore.adoc
  modules/admin_manual/pages/maintenance/enable_maintenance.adoc
  modules/admin_manual/pages/maintenance/migrating.adoc
  modules/admin_manual/pages/maintenance/upgrading/index.adoc
  modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
  modules/admin_manual/pages/maintenance/upgrading/package_upgrade.adoc
  modules/admin_manual/pages/maintenance/upgrading/update.adoc
  modules/admin_manual/pages/maintenance/upgrading/upgrade.adoc
  modules/admin_manual/pages/qnap/index.adoc
Labels: backport

#4348 [10.7] [PR 4341] Maintenance upgrades
  modules/admin_manual/pages/_partials/nav.adoc
  modules/admin_manual/pages/maintenance/backup_and_restore/backup.adoc
  modules/admin_manual/pages/maintenance/backup_and_restore/index.adoc
  modules/admin_manual/pages/maintenance/backup_and_restore/restore.adoc
  modules/admin_manual/pages/maintenance/enable_maintenance.adoc
  modules/admin_manual/pages/maintenance/migrating.adoc
  modules/admin_manual/pages/maintenance/upgrading/index.adoc
  modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
  modules/admin_manual/pages/maintenance/upgrading/package_upgrade.adoc
  modules/admin_manual/pages/maintenance/upgrading/update.adoc
  modules/admin_manual/pages/maintenance/upgrading/upgrade.adoc
Labels: backport

#4351 [10.7] Minor installation doc changes
  modules/admin_manual/pages/_partials/installation/manual_installation/mariadb.adoc
  modules/admin_manual/pages/_partials/installation/manual_installation/useful_tips.adoc
  modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
Labels: backport

#4356 [10.9] [PR 4354] Empty system and app config keys cannot be set
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_config_commands.adoc
Labels: backport

#4355 MariaDB text improvements
  modules/admin_manual/pages/_partials/installation/manual_installation/mariadb.adoc
Labels: admin docs

#4357 [10.9] [PR 4355] MariaDB text improvements
  modules/admin_manual/pages/_partials/installation/manual_installation/mariadb.adoc
Labels: backport

#4358 [10.8] [PR 4355] MariaDB text improvements
  modules/admin_manual/pages/_partials/installation/manual_installation/mariadb.adoc
Labels: backport

#4359 [10.7] [PR 4355] MariaDB text improvements
  modules/admin_manual/pages/_partials/installation/manual_installation/mariadb.adoc
Labels: backport

#4362 Improve webserver text in manual upgrade
  modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
Labels: admin docs

#4364 [10.8] [PR 4362] Improve webserver text in manual upgrade
  modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
Labels: backport

#4363 [10.9] [PR 4362] Improve webserver text in manual upgrade
  modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
Labels: backport

#4365 [10.7] [PR 4362] Improve webserver text in manual upgrade
  modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
Labels: backport

#4361 New occ command user:move
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_user_commands.adoc
  modules/admin_manual/pages/configuration/user/user_management.adoc
Labels: admin docs

#4366 [10.9] [PR 4361] New occ command user:move
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_user_commands.adoc
  modules/admin_manual/pages/configuration/user/user_management.adoc
Labels: backport

#4360 Upgrade guide for MariaDB 10.6
  modules/admin_manual/pages/_partials/nav.adoc
  modules/admin_manual/pages/maintenance/upgrading/database_upgrade.adoc
Labels: admin docs

#4367 [10.9] [PR 4360] Upgrade guide for MariaDB 10.6
  modules/admin_manual/pages/_partials/nav.adoc
  modules/admin_manual/pages/maintenance/upgrading/database_upgrade.adoc
Labels: backport

#4353 Fix Backup and Restore
  modules/admin_manual/pages/maintenance/backup_and_restore/backup.adoc
  modules/admin_manual/pages/maintenance/backup_and_restore/restore.adoc
Labels: admin docs

#4368 [10.7] [PR 4353] Fix Backup and Restore
  modules/admin_manual/pages/maintenance/backup_and_restore/backup.adoc
  modules/admin_manual/pages/maintenance/backup_and_restore/restore.adoc
Labels: backport

#4369 [10.8] [PR 4353] Fix Backup and Restore
  modules/admin_manual/pages/maintenance/backup_and_restore/backup.adoc
  modules/admin_manual/pages/maintenance/backup_and_restore/restore.adoc
Labels: backport

#4370 [10.9] [PR 4353] Fix Backup and Restore
  modules/admin_manual/pages/maintenance/backup_and_restore/backup.adoc
  modules/admin_manual/pages/maintenance/backup_and_restore/restore.adoc
Labels: backport

#4371 Add MariaDB 10.6 to system requirements
  modules/admin_manual/pages/installation/system_requirements.adoc
Labels: admin docs

#4373 [10.9] [PR 4371] Add MariaDB 10.6 to system requirements
  modules/admin_manual/pages/installation/system_requirements.adoc
Labels: backport

#4374 [10.8] [PR 4371] Add MariaDB 10.6 to system requirements
  modules/admin_manual/pages/installation/system_requirements.adoc
Labels: backport

#4375 [10.7] [PR 4371] Add MariaDB 10.6 to system requirements
  modules/admin_manual/pages/installation/system_requirements.adoc
Labels: backport

#4372 Cleanup of occ dav commands
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_dav_commands.adoc
Labels: admin docs

#4376 [10.9] [PR 4372] Cleanup of occ dav commands
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_dav_commands.adoc
Labels: backport

#4378 [10.7] [PR 4372] Cleanup of occ dav commands
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_dav_commands.adoc
Labels: backport

#4377 [10.8] [PR 4372] Cleanup of occ dav commands
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_dav_commands.adoc
Labels: backport

#4384 [master] [PR 4381] [10.8] Fix Admin Username / Password Typo
  modules/admin_manual/pages/installation/docker/index.adoc
Labels: backport
