Repository owncloud/docs, pull requests merged in 2021-03, with the labels that each got.

#3223 [10.6] [PR 3221] Fix one bad anchor reference
  modules/admin_manual/pages/configuration/files/encryption/enabling-user-key-encryption.adoc
Labels: backport

#3222 [10.5] [PR 3221] Fix one bad anchor reference
  modules/admin_manual/pages/configuration/files/encryption/enabling-user-key-encryption.adoc
Labels: backport

#3225 Reporting not Monitoring
  modules/admin_manual/nav.adoc
  modules/admin_manual/pages/enterprise/monitoring/index.adoc
  modules/admin_manual/pages/enterprise/reporting/index.adoc
  modules/admin_manual/pages/enterprise/reporting/metrics.adoc
Labels: admin docs

#3226 [10.6] [PR 3225] Reporting not Monitoring
  modules/admin_manual/nav.adoc
  modules/admin_manual/pages/enterprise/monitoring/index.adoc
  modules/admin_manual/pages/enterprise/reporting/index.adoc
  modules/admin_manual/pages/enterprise/reporting/metrics.adoc
Labels: backport

#3227 [10.5] [PR 3217] Added new metrics documentation.
  modules/admin_manual/nav.adoc
  modules/admin_manual/pages/enterprise/metrics/metrics.adoc
Labels: backport

#3228 Correct list_files_versions.adoc partials
  modules/developer_manual/pages/_partials/webdav_api/files_versions/list_files_versions.adoc
  modules/developer_manual/pages/webdav_api/files_versions.adoc
Labels: admin docs

#3229 [10.5] [PR 3218] Improved metrics documentation
  modules/admin_manual/nav.adoc
  modules/admin_manual/pages/enterprise/monitoring/index.adoc
  modules/admin_manual/pages/enterprise/monitoring/metrics.adoc
Labels: backport

#3230 [10.5] [PR 3225] Reporting not Monitoring
  modules/admin_manual/nav.adoc
  modules/admin_manual/pages/enterprise/monitoring/index.adoc
  modules/admin_manual/pages/enterprise/reporting/index.adoc
  modules/admin_manual/pages/enterprise/reporting/metrics.adoc
Labels: backport

#3232 [10.6] [PR 3228] Correct list_files_versions.adoc partials
  modules/developer_manual/pages/_partials/webdav_api/files_versions/list_files_versions.adoc
  modules/developer_manual/pages/webdav_api/files_versions.adoc
Labels: backport

#3231 [10.5] [PR 3228] Correct list_files_versions.adoc partials
  modules/developer_manual/pages/_partials/webdav_api/files_versions/list_files_versions.adoc
  modules/developer_manual/pages/webdav_api/files_versions.adoc
Labels: backport

#3234 [10.6] [PR 3224] fixed json instead of xml
  modules/developer_manual/pages/core/apis/ocs-totp-validation-api.adoc
Labels: backport

#3233 [10.5] [PR 3224] fixed json instead of xml
  modules/developer_manual/pages/core/apis/ocs-totp-validation-api.adoc
Labels: backport

#3235 Fix trailing slashes when using examplesdir
  modules/admin_manual/pages/installation/quick_guides/ubuntu_18_04.adoc
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
  modules/developer_manual/pages/webdav_api/meta.adoc
Labels: admin docs

#3244 [10.6] [PR 3235] Fix trailing slashes when using examplesdir
  modules/admin_manual/pages/installation/quick_guides/ubuntu_18_04.adoc
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
  modules/developer_manual/pages/webdav_api/meta.adoc
Labels: backport

#3243 [10.5] [PR 3235] Fix trailing slashes when using examplesdir
  modules/admin_manual/pages/installation/quick_guides/ubuntu_18_04.adoc
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
  modules/developer_manual/pages/webdav_api/meta.adoc
Labels: backport

#2986 Server Preparation Guide for Ubuntu 20.04
  modules/admin_manual/assets/attachments/installation/manual_installation/bootstrap.sh
  modules/admin_manual/assets/images/installation/manual_installation/phpmyadmin_v4.9.5deb2.png
  modules/admin_manual/assets/images/installation/manual_installation/phpmyadmin_v5.0.4.png
  modules/admin_manual/pages/_partials/installation/manual_installation/mariadb.adoc
  modules/admin_manual/pages/_partials/installation/manual_installation/useful_tips.adoc
  modules/admin_manual/pages/installation/manual_installation/compile_samba.adoc
  modules/admin_manual/pages/installation/manual_installation/manual_installation.adoc
  modules/admin_manual/pages/installation/manual_installation/manual_installation_db.adoc
  modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_18.04.adoc
  modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc
  modules/admin_manual/pages/installation/manual_installation/upgrade_install_phpmyadmin.adoc
Labels: admin docs

#3258 [10.6] [PR 2986] Server Preparation Guide for Ubuntu 20.04
  modules/admin_manual/assets/attachments/installation/manual_installation/bootstrap.sh
  modules/admin_manual/assets/images/installation/manual_installation/phpmyadmin_v4.9.5deb2.png
  modules/admin_manual/assets/images/installation/manual_installation/phpmyadmin_v5.0.4.png
  modules/admin_manual/pages/_partials/installation/manual_installation/mariadb.adoc
  modules/admin_manual/pages/_partials/installation/manual_installation/useful_tips.adoc
  modules/admin_manual/pages/installation/manual_installation/compile_samba.adoc
  modules/admin_manual/pages/installation/manual_installation/manual_installation.adoc
  modules/admin_manual/pages/installation/manual_installation/manual_installation_db.adoc
  modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_18.04.adoc
  modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc
  modules/admin_manual/pages/installation/manual_installation/upgrade_install_phpmyadmin.adoc
Labels: backport

#3259 [10.5] [PR 2986] Server Preparation Guide for Ubuntu 20.04
  modules/admin_manual/assets/attachments/installation/manual_installation/bootstrap.sh
  modules/admin_manual/assets/images/installation/manual_installation/phpmyadmin_v4.9.5deb2.png
  modules/admin_manual/assets/images/installation/manual_installation/phpmyadmin_v5.0.4.png
  modules/admin_manual/pages/_partials/installation/manual_installation/mariadb.adoc
  modules/admin_manual/pages/_partials/installation/manual_installation/useful_tips.adoc
  modules/admin_manual/pages/installation/manual_installation/compile_samba.adoc
  modules/admin_manual/pages/installation/manual_installation/manual_installation.adoc
  modules/admin_manual/pages/installation/manual_installation/manual_installation_db.adoc
  modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_18.04.adoc
  modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc
  modules/admin_manual/pages/installation/manual_installation/upgrade_install_phpmyadmin.adoc
Labels: backport

#3266 Add infos to docs about jQuery outdated warning
  modules/admin_manual/nav.adoc
  modules/admin_manual/pages/configuration/server/security/index.adoc
  modules/admin_manual/pages/configuration/server/security/jquery_warning.adoc
Labels: admin docs

#3268 [10.5] [PR 3266] Add infos to docs about jQuery outdated warning
  modules/admin_manual/nav.adoc
  modules/admin_manual/pages/configuration/server/security/index.adoc
  modules/admin_manual/pages/configuration/server/security/jquery_warning.adoc
Labels: backport

#3267 [10.6] [PR 3266] Add infos to docs about jQuery outdated warning
  modules/admin_manual/nav.adoc
  modules/admin_manual/pages/configuration/server/security/index.adoc
  modules/admin_manual/pages/configuration/server/security/jquery_warning.adoc
Labels: backport

#3269 Update jQuery Warning Info
  modules/admin_manual/pages/configuration/server/security/jquery_warnings.adoc
Labels: admin docs

#3270 [10.6] [PR 3269] Update jQuery Warning Info
  modules/admin_manual/pages/configuration/server/security/jquery_warnings.adoc
Labels: backport

#3271 [10.5] [PR 3269] Update jQuery Warning Info
  modules/admin_manual/pages/configuration/server/security/jquery_warnings.adoc
Labels: backport

#3290 OnlyOffice documentation for license path new
  modules/admin_manual/pages/appliance/configuration/office.adoc
Labels: admin docs

#3291 [10.6] [PR 3290] OnlyOffice documentation for license path new
  modules/admin_manual/pages/appliance/configuration/office.adoc
Labels: backport

#3292 [10.5] [PR 3290] OnlyOffice documentation for license path new
  modules/admin_manual/pages/appliance/configuration/office.adoc
Labels: backport

#3296 [10.6] [PR 3294] added checklist for troubleshooting
  modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
Labels: backport

#3297 [10.5] [PR 3294] added checklist for troubleshooting
  modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
Labels: backport

#3298 [10.6] [PR 3295] changes to unclear LDAP Quota
  modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
Labels: backport

#3299 [10.5] [PR 3295] changes to unclear LDAP Quota
  modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
Labels: backport

#3301 Some improvements and fixes
  modules/admin_manual/pages/configuration/server/maintenance_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/full_text_search_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/managing_background_jobs.adoc
  modules/admin_manual/pages/configuration/server/security/hsmdaemon/index.adoc
  modules/developer_manual/pages/core/apis/ocs-share-api.adoc
  modules/developer_manual/pages/testing/acceptance-tests.adoc
  modules/developer_manual/pages/testing/unit-testing.adoc
Labels: admin docs, developer docs

#3302 [10.5] [PR 3301] Some improvements and fixes
  modules/admin_manual/pages/configuration/server/maintenance_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/full_text_search_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/managing_background_jobs.adoc
  modules/admin_manual/pages/configuration/server/security/hsmdaemon/index.adoc
  modules/developer_manual/pages/core/apis/ocs-share-api.adoc
  modules/developer_manual/pages/testing/acceptance-tests.adoc
  modules/developer_manual/pages/testing/unit-testing.adoc
Labels: backport

#3303 [10.6] [PR 3301] Some improvements and fixes
  modules/admin_manual/pages/configuration/server/maintenance_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/full_text_search_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command/managing_background_jobs.adoc
  modules/admin_manual/pages/configuration/server/security/hsmdaemon/index.adoc
  modules/developer_manual/pages/core/apis/ocs-share-api.adoc
  modules/developer_manual/pages/testing/acceptance-tests.adoc
  modules/developer_manual/pages/testing/unit-testing.adoc
Labels: backport

#3309 [10.6] [PR 3307] ubuntu 20.04 -- append to crontab
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
Labels: backport

#3310 [10.5] [PR 3307] ubuntu 20.04 -- append to crontab
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
Labels: backport

#3337 Fix to dynamically create the attribute-to-argument list for asciidoctor-pdf
  bin/cli
  bin/yamlparse.sh
  bin/yamltest.sh
Labels: deployment

#3339 [10.5] [PR 3337] Fix to dynamically create the attribute-to-argument list for asciidoctor-pdf
  bin/cli
  bin/yamlparse.sh
  bin/yamltest.sh
Labels: backport

#3340 [10.6] [PR 3337] Fix to dynamically create the attribute-to-argument list for asciidoctor-pdf
  bin/cli
  bin/yamlparse.sh
  bin/yamltest.sh
Labels: backport

#3345 [10.6] [PR 2818] Update saml_2.0_sso.adoc
  modules/admin_manual/pages/enterprise/user_management/saml_2.0_sso.adoc
Labels: backport

#3351 Update README.md
  README.md
Labels: deployment

#3352 [10.6][PR 3347] added limitation to the metrics app doc
  modules/admin_manual/pages/enterprise/reporting/metrics.adoc
Labels: backport

#3353 [10.5][PR 3347] added limitation to the metrics app doc
  modules/admin_manual/pages/enterprise/reporting/metrics.adoc
Labels: backport

#3355 correct redis port in oauth2.adoc
  modules/admin_manual/pages/configuration/server/security/oauth2.adoc
Labels: admin docs

#3356 [10.6][#3355] correct redis port in oauth2.adoc
  modules/admin_manual/pages/configuration/server/security/oauth2.adoc
Labels: backport

#3357 [10.5][#3355] correct redis port in oauth2.adoc
  modules/admin_manual/pages/configuration/server/security/oauth2.adoc
Labels: backport

#3360 transports config.sample changes from core to docs
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Labels: admin docs

#3361 added info on license key registration
  modules/admin_manual/pages/enterprise/installation/install.adoc
Labels: admin docs

#3362 [10.6][#3361] added info on license key registration
  modules/admin_manual/pages/enterprise/installation/install.adoc
Labels: backport

#3363 [10.5][#3361] added info on license key registration
  modules/admin_manual/pages/enterprise/installation/install.adoc
Labels: backport

#3364 link redis server attributes in docs
  modules/admin_manual/pages/configuration/server/occ_command/config_commands.adoc
  modules/admin_manual/pages/configuration/server/security/oauth2.adoc
  modules/admin_manual/pages/installation/quick_guides/ubuntu_18_04.adoc
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
Labels: admin docs

#3365 [10.6][#3364] link redis server attributes in docs
  modules/admin_manual/pages/configuration/server/occ_command/config_commands.adoc
  modules/admin_manual/pages/configuration/server/security/oauth2.adoc
  modules/admin_manual/pages/installation/quick_guides/ubuntu_18_04.adoc
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
Labels: backport

#3366 [10.5][#3364] link redis server attributes in docs
  modules/admin_manual/pages/configuration/server/occ_command/config_commands.adoc
  modules/admin_manual/pages/configuration/server/security/oauth2.adoc
  modules/admin_manual/pages/installation/quick_guides/ubuntu_18_04.adoc
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
Labels: backport

#3367 Necessary Branch Changes for 10.7
  .drone.star
  site.yml
Labels: deployment

#3370 Improved README.md how to create a new version branch
  README.md
  docs/new-version-branch.md
Labels: deployment

#3371 [10.6] [PR 3370] Improved README.md how to create a new version branch
  README.md
  docs/new-version-branch.md
Labels: deployment

#3372 [10.7] [PR 3370] Improved README.md how to create a new version branch
  README.md
  docs/new-version-branch.md
Labels: deployment

#3368 add link to introduction in code_signing.html
  modules/admin_manual/pages/configuration/general_topics/code_signing.adoc
Labels: admin docs

#3375 [10.7][#3368] add link to introduction in code_signing.html
  modules/admin_manual/pages/configuration/general_topics/code_signing.adoc
Labels: backport

#3381 [10.7][PR 3378] Update migrating.adoc
  modules/admin_manual/pages/maintenance/migrating.adoc
Labels: backport

#3382 [10.6] [PR 3378] Update migrating.adoc
  modules/admin_manual/pages/maintenance/migrating.adoc
Labels: backport

#3385 [10.7][PR 3384] fix best-practices guide changes
  docs/best-practices.md
Labels: backport

#3386 [10.6][PR 3384] fix best-practices guide changes
  docs/best-practices.md
Labels: backport

#3389 config.apps.sample changes from core
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
Labels: admin docs

#3390 [10.7] [PR 3389] config.apps.sample changes from core
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
Labels: backport

#3392 [master] [PR 3388] 10.7 Release Notes
  modules/admin_manual/pages/release_notes.adoc
Labels: backport

#3394 [10.7] [PR 3391] Updated according to the interface changes in 10.7 with regard to tagging
  modules/user_manual/pages/files/webgui/tagging.adoc
Labels: backport

#3397 [10.7] [PR 3396] Add migration info to 10.7 release notes
  modules/admin_manual/pages/release_notes.adoc
Labels: backport

#3400 Fix documenting new version branch
  docs/new-version-branch.md
Labels: deployment

#3401 Corrected the apps directory.
  modules/developer_manual/pages/core/theming.adoc
Labels: developer docs

#3406 Fixed layout problems in occ-commands.
  modules/admin_manual/pages/configuration/server/occ_command/files_external_commands.adoc
Labels: admin docs

#3407 [10.6] [PR 3406] Fixed layout problems in occ-commands.
  modules/admin_manual/pages/configuration/server/occ_command/files_external_commands.adoc
Labels: backport

#3408 [10.7] [PR 3406] Fixed layout problems in occ-commands.
  modules/admin_manual/pages/configuration/server/occ_command/files_external_commands.adoc
Labels: backport

#3410 Fixing enterprise images
  modules/admin_manual/assets/images/enterprise/external_storage/enterprise-only-auth/auth_backends-1.png
  modules/admin_manual/assets/images/enterprise/external_storage/enterprise-only-auth/auth_backends-2.png
  modules/admin_manual/assets/images/enterprise/external_storage/ldap-home-connector/ldap-home-connector-1.png
  modules/admin_manual/assets/images/enterprise/external_storage/ldap-home-connector/ldap-home-connector-2.png
  modules/admin_manual/assets/images/enterprise/external_storage/ldap-home-connector/ldap-home-connector-3.png
  modules/admin_manual/assets/images/enterprise/external_storage/sharepoint/sharepoint-1.png
  modules/admin_manual/assets/images/enterprise/external_storage/sharepoint/sharepoint-2.png
  modules/admin_manual/assets/images/enterprise/external_storage/sharepoint/sharepoint-3.png
  modules/admin_manual/assets/images/enterprise/external_storage/sharepoint/sharepoint-4.png
  modules/admin_manual/pages/enterprise/external_storage/enterprise_only_auth.adoc
  modules/admin_manual/pages/enterprise/external_storage/ldap_home_connector_configuration.adoc
  modules/admin_manual/pages/enterprise/external_storage/sharepoint-integration_configuration.adoc
Labels: admin docs

#3409 Add missing occ wnd commands
  modules/admin_manual/pages/configuration/server/app_commands/wnd_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_command.adoc
Labels: admin docs

#3402 don't change /usr/lib/systemd/system/httpd.service
  modules/admin_manual/pages/configuration/files/big_file_upload_configuration.adoc
Labels: admin docs

#3414 [10.7] [PR 3402] don't change /usr/lib/systemd/system/httpd.service
  modules/admin_manual/pages/configuration/files/big_file_upload_configuration.adoc
Labels: backport

#3416 [10.7] [PR 2739] Include documentation for the new WND feature
  modules/admin_manual/assets/images/enterprise/external_storage/windows_network_drive/activity_file_change_notification.png
  modules/admin_manual/assets/images/enterprise/external_storage/windows_network_drive/wnd-1.png
  modules/admin_manual/assets/images/enterprise/external_storage/windows_network_drive/wnd-2.png
  modules/admin_manual/assets/images/enterprise/external_storage/windows_network_drive/wnd-3.png
  modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
Labels: backport

#3415 [Master] [PR 3402] don't change /usr/lib/systemd/system/httpd.service
  modules/admin_manual/pages/configuration/files/big_file_upload_configuration.adoc
Labels: backport

#3417 Add Images to the Metrics documentation
  modules/admin_manual/assets/images/enterprise/reporting/metrics/metrics-system.png
  modules/admin_manual/assets/images/enterprise/reporting/metrics/metrics-user.png
  modules/admin_manual/pages/enterprise/reporting/metrics.adoc
Labels: admin docs

#3418 [10.7] [PR 3417] Add Images to the Metrics documentation
  modules/admin_manual/assets/images/enterprise/reporting/metrics/metrics-system.png
  modules/admin_manual/assets/images/enterprise/reporting/metrics/metrics-user.png
  modules/admin_manual/pages/enterprise/reporting/metrics.adoc
Labels: backport

#3422 10.7 known issues
  modules/admin_manual/pages/release_notes.adoc
Labels: admin docs

#3423 [10.7] [PR 3422] 10.7 known issues
  modules/admin_manual/pages/release_notes.adoc
Labels: backport

#3426 Switch Desktop branch to 2.8
  site.yml
Labels: desktop client docs
