Repository owncloud/docs, pull requests merged in 2021-06, with the labels that each got.

#3610 Configuration options for mount points will be encrypted if they are passwords
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/wnd_commands.adoc
  modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
Labels: admin docs

#3611 Missing config key for files_version
  modules/admin_manual/pages/configuration/files/file_versioning.adoc
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Labels: admin docs

#3612 [10.6] [PR 3611] Missing config key for files_version
  modules/admin_manual/pages/configuration/files/file_versioning.adoc
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Labels: backport

#3613 [10.7] [PR 3611] Missing config key for files_version
  modules/admin_manual/pages/configuration/files/file_versioning.adoc
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Labels: backport

#3607 Add Files Lifecycle occ command set
  modules/admin_manual/assets/images/apps/files_lifecycle/file-lifecycle-events.png
  modules/admin_manual/pages/configuration/server/occ_command.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/files_lifecycle.adoc
  modules/admin_manual/pages/enterprise/file_management/files_lifecycle.adoc
Labels: admin docs

#3616 [10.7] [PR 3607] Add Files Lifecycle occ command set
  modules/admin_manual/assets/images/apps/files_lifecycle/file-lifecycle-events.png
  modules/admin_manual/pages/configuration/server/occ_command.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/files_lifecycle.adoc
  modules/admin_manual/pages/enterprise/file_management/files_lifecycle.adoc
Labels: backport

#3615 [10.6] [PR 3607] Add Files Lifecycle occ command set
  modules/admin_manual/assets/images/apps/files_lifecycle/file-lifecycle-events.png
  modules/admin_manual/pages/configuration/server/occ_command.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/files_lifecycle.adoc
  modules/admin_manual/pages/enterprise/file_management/files_lifecycle.adoc
Labels: backport

#3619 Text fix for enterprise/logging/admin_audit.html#lifecycle_restored
  modules/admin_manual/pages/enterprise/logging/admin_audit.adoc
Labels: admin docs

#3622 [10.7] [PR 3619] Text fix for enterprise/logging/admin_audit.html#lifecycle_restored
  modules/admin_manual/pages/enterprise/logging/admin_audit.adoc
Labels: backport

#3620 Correct Apache header information for msteamsbridge
  modules/admin_manual/pages/configuration/integration/ms-teams.adoc
Labels: admin docs

#3618 Note that IE 11 is not compatible with Metrics
  modules/admin_manual/pages/enterprise/reporting/metrics.adoc
Labels: admin docs

#3623 [10.7] [PR 3620] Correct Apache header information for msteamsbridge
  modules/admin_manual/pages/configuration/integration/ms-teams.adoc
Labels: backport

#3624 [10.7] [PR 3618] Note that IE 11 is not compatible with Metrics
  modules/admin_manual/pages/enterprise/reporting/metrics.adoc
Labels: backport

#3621 Fix config.sample for preview providers
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Labels: admin docs

#3625 [10.7] [PR 3621] Fix config.sample for preview providers
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Labels: backport

#3627 Fix PDF preview provider
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Labels: admin docs

#3629 [10.7] [PR 3627] Fix PDF preview provider
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Labels: backport

#3628 Add the correct http.cookie.samesite for OIDC
  modules/admin_manual/pages/configuration/user/oidc/oidc.adoc
Labels: admin docs

#3630 [10.7] [PR 3628] Add the correct http.cookie.samesite for OIDC
  modules/admin_manual/pages/configuration/user/oidc/oidc.adoc
Labels: backport

#3631 Improved config key description for auto-provision for OIDC
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
Labels: admin docs

#3633 [10.7] [PR 3631] Improved config key description for auto-provision for OIDC
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
Labels: backport

#3634 Document auto-provision for AzureAD OIDC
  modules/admin_manual/pages/configuration/user/oidc/ms-azure-setup.adoc
Labels: admin docs

#3635 [10.7] [PR 3634] Document auto-provision for AzureAD OIDC
  modules/admin_manual/pages/configuration/user/oidc/ms-azure-setup.adoc
Labels: backport

#3637 [10.7] [PR 3636] update encryption size overhead note
  modules/admin_manual/pages/configuration/files/encryption/index.adoc
Labels: backport

#3638 Fix include locations for two occ commands
  modules/admin_manual/pages/configuration/server/app_commands/files_lifecycle.adoc
  modules/admin_manual/pages/configuration/server/occ_command.adoc
Labels: admin docs

#3640 Add Workflow / Tagging config key
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
Labels: admin docs

#3642 [10.7] [PR 3640] Add Workflow / Tagging config key
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
Labels: backport

#3639 Improved script-guided installation.
  modules/admin_manual/pages/installation/manual_installation/script_guided_install.adoc
Labels: admin docs

#3641 Fix Workflow / Tagging doc
  modules/admin_manual/assets/images/enterprise/file_management/update_workflow.png
  modules/admin_manual/pages/enterprise/file_management/files_tagging.adoc
Labels: admin docs

#3646 [10.7] [PR 3641] Fix Workflow / Tagging doc
  modules/admin_manual/assets/images/enterprise/file_management/update_workflow.png
  modules/admin_manual/pages/enterprise/file_management/files_tagging.adoc
Labels: backport

#3645 [10.6] [PR 3641] Fix Workflow / Tagging doc
  modules/admin_manual/assets/images/enterprise/file_management/update_workflow.png
  modules/admin_manual/pages/enterprise/file_management/files_tagging.adoc
Labels: backport

#3648 [10.7] [PR 3639] Improved script-guided installation
  modules/admin_manual/pages/installation/manual_installation/script_guided_install.adoc
Labels: backport

#3654 [10.7] [PR 3647] migrate client docs to new repo
  .drone.star
  bin/instructions_makepdf.md
  modules/ROOT/pages/how_to_contribute.adoc
  site.yml
Labels: backport

#3653 [10.6] [PR 3647] migrate client docs to new repo
  .drone.star
  bin/instructions_makepdf.md
  modules/ROOT/pages/how_to_contribute.adoc
  site.yml
Labels: backport

#3656 Update build-the-docs.md to reflect the changes on node
  docs/build-the-docs.md
Labels: deployment

#3657 [10.7] [PR 3656] Update build-the-docs.md to reflect the changes on node
  docs/build-the-docs.md
Labels: backport

#3658 [10.6] [PR 3655] refactor ci to work with all branches
  .drone.star
  .gitignore
Labels: backport

#3659 [10.7] [PR 3655] refactor ci to work with all branches
  .drone.star
  .gitignore
Labels: backport

#3661 10.6 fix user_manual nav for non existing references
  modules/user_manual/nav.adoc
Labels: admin docs

#3664 Correct X-XSS-Protection
  modules/admin_manual/pages/configuration/server/harden_server.adoc
Labels: admin docs

#3667 [10.7] [PR 3664] Correct X-XSS-Protection
  modules/admin_manual/pages/configuration/server/harden_server.adoc
Labels: backport

#3666 makepdf: add option for error output
  bin/makepdf
Labels: admin docs

#3668 [10.6] [PR 3666] makepdf: add option for error output
  bin/makepdf
Labels: backport

#3669 [10.7] [PR 3666] makepdf: add option for error output
  bin/makepdf
Labels: backport

#3670 minor fixes
  modules/admin_manual/pages/installation/docker/index.adoc
Labels: admin docs

#3676 [10.7] [PR 3673] Kick block; from X-XSS-Protection
  modules/admin_manual/pages/configuration/server/harden_server.adoc
Labels: backport

#3677 Correct_Preview_config.sample.php
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Labels: admin docs

#3679 New WND config key for Ldapmembership cache
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
Labels: admin docs

#3687 Update WND documentation for wnd.groupmembership.checkUserFirst
  modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
Labels: admin docs

#3692 [10.6] [PR 3688] Update server_prep_ubuntu_20.04.adoc
  modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc
Labels: backport

#3693 [10.7] [PR 3688] Update server_prep_ubuntu_20.04.adoc
  modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc
Labels: backport

#3701 fixed reference to manual installation
  modules/ROOT/pages/index.adoc
Labels: admin docs

#3702 [10.6] [PR 3701] fixed reference to manual installation
  modules/ROOT/pages/index.adoc
Labels: backport

#3703 [10.7] [PR 3701] fixed reference to manual installation
  modules/ROOT/pages/index.adoc
Labels: backport

#3691 added proper eval guidance
  modules/admin_manual/pages/installation/docker/index.adoc
Labels: admin docs

#3706 [10.7] [PR 3691] added proper eval guidance
  modules/admin_manual/pages/installation/docker/index.adoc
Labels: backport

#3707 [10.6] [PR 3691] added proper eval guidance
  modules/admin_manual/pages/installation/docker/index.adoc
Labels: backport

#3708 Make text for the http.cookie.samesite config value more clear
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Labels: admin docs

#3609 New occ commands for richdocuments
  modules/admin_manual/pages/configuration/server/occ_command.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/richdocuments.adoc
  modules/admin_manual/pages/enterprise/collaboration/collabora_secure_view.adoc
Labels: admin docs

#3709 [10.7] [PR 3708] Make text for the http.cookie.samesite config value more clear
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Labels: backport

#3712 Document expiration of outgoing remote shares
  modules/admin_manual/pages/configuration/files/file_sharing_configuration.adoc
  modules/user_manual/pages/files/webgui/sharing.adoc
Labels: admin docs

#3713 [10.6] [PR 3712] Document expiration of outgoing remote shares
  modules/admin_manual/pages/configuration/files/file_sharing_configuration.adoc
  modules/user_manual/pages/files/webgui/sharing.adoc
Labels: backport

#3714 [10.7] [PR 3712] Document expiration of outgoing remote shares
  modules/admin_manual/pages/configuration/files/file_sharing_configuration.adoc
  modules/user_manual/pages/files/webgui/sharing.adoc
Labels: backport

#3716 Small fixes setting attributes correctly
  modules/admin_manual/pages/configuration/files/manual_file_locking.adoc
Labels: admin docs

#3718 [10.6] [PR 3716] Small fixes setting attributes correctly
  modules/admin_manual/pages/configuration/files/manual_file_locking.adoc
Labels: backport

#3719 [10.7] [PR 3716] Small fixes setting attributes correctly
  modules/admin_manual/pages/configuration/files/manual_file_locking.adoc
Labels: backport

#3720 Add docs for 'tries to' in acceptance tests
  modules/developer_manual/pages/testing/acceptance-tests.adoc
Labels: developer docs

#3492 Desktop/mobile apps need branding to work with OIDC
  modules/admin_manual/pages/configuration/user/oidc/oidc.adoc
Labels: admin docs

#3723 [10.7] [PR 3492] Desktop/mobile apps need branding to work with OIDC
  modules/admin_manual/pages/configuration/user/oidc/oidc.adoc
Labels: backport

#3250 Example using Vault to fetch wnd password
  modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
Labels: admin docs

#3725 [10.7] [PR 3250] Example using Vault to fetch wnd password
  modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
Labels: backport

#3727 Add missing occ encryption commands
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/encryption_commands.adoc
Labels: admin docs

#3731 [10.6] [PR 3727] Add missing occ encryption commands
  modules/admin_manual/pages/configuration/server/occ_command/encryption_commands.adoc
Labels: backport

#3732 [10.7] [PR 3727] Add missing occ encryption commands
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/encryption_commands.adoc
Labels: backport

#3710 hsmdaemon install consistency and accuracy
  modules/admin_manual/pages/configuration/server/security/hsmdaemon/index.adoc
Labels: admin docs

#3733 [10.6] [PR 3710] hsmdaemon install consistency and accuracy
  modules/admin_manual/pages/configuration/server/security/hsmdaemon/index.adoc
Labels: backport

#3734 [10.7] [PR 3710] hsmdaemon install consistency and accuracy
  modules/admin_manual/pages/configuration/server/security/hsmdaemon/index.adoc
Labels: backport

#3736 [10.7] [PR 3730] chore: update node dependencies
  package.json
  yarn.lock
Labels: backport

#3735 [10.6] [PR 3730] chore: update node dependencies
  package.json
  yarn.lock
Labels: backport

#3737 occ usage with docker installations
  modules/ROOT/pages/index.adoc
  modules/admin_manual/pages/configuration/server/occ_command.adoc
  modules/admin_manual/pages/installation/docker/index.adoc
Labels: admin docs

#3738 [10.7] [PR 3737] occ usage with docker installations
  modules/ROOT/pages/index.adoc
  modules/admin_manual/pages/configuration/server/occ_command.adoc
  modules/admin_manual/pages/installation/docker/index.adoc
Labels: backport

#3739 [10.6] [PR 3737] occ usage with docker installations
  modules/ROOT/pages/index.adoc
  modules/admin_manual/pages/configuration/server/occ_command.adoc
  modules/admin_manual/pages/installation/docker/index.adoc
Labels: backport

#3741 Prerequisites before deploying 10.8
  modules/ROOT/nav.adoc
  modules/ROOT/pages/index.adoc
  modules/ROOT/pages/release_notes.adoc
  modules/admin_manual/pages/_partials/maintenance/major_release_note.adoc
  modules/admin_manual/pages/configuration/files/external_storage/amazons3.adoc
  modules/admin_manual/pages/installation/docker/index.adoc
  modules/admin_manual/pages/installation/quick_guides/ubuntu_18_04.adoc
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
  modules/admin_manual/pages/maintenance/manual_upgrade.adoc
  site.yml
Labels: deployment

#3743 [10.7] [PR 3741] Prerequisites before deploying 10.8
  modules/ROOT/nav.adoc
  modules/ROOT/pages/index.adoc
  modules/ROOT/pages/release_notes.adoc
  modules/admin_manual/pages/_partials/maintenance/major_release_note.adoc
  modules/admin_manual/pages/configuration/files/external_storage/amazons3.adoc
  modules/admin_manual/pages/installation/docker/index.adoc
  modules/admin_manual/pages/installation/quick_guides/ubuntu_18_04.adoc
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
  modules/admin_manual/pages/maintenance/manual_upgrade.adoc
  site.yml
Labels: backport

#3744 Delete single quotes in docker run command
  modules/admin_manual/pages/installation/docker/index.adoc
Labels: admin docs, docker

#3746 [10.7] [PR 3744] Delete single quotes in docker run command
  modules/admin_manual/pages/installation/docker/index.adoc
Labels: backport

#3747 [10.6] [PR 3744] Delete single quotes in docker run command
  modules/admin_manual/pages/installation/docker/index.adoc
Labels: backport

#3745 Small fixes to the BPG and the landing page
  docs/best-practices.md
  modules/ROOT/pages/index.adoc
Labels: admin docs

#3748 [10.7] [PR 3745] Small fixes to the BPG and the landing page
  docs/best-practices.md
  modules/ROOT/pages/index.adoc
Labels: backport

#3749 [10.7] [PR 3742] Add Secure View sharing note
  modules/admin_manual/pages/enterprise/collaboration/collabora_secure_view.adoc
Labels: backport

#3750 [10.6] [PR 3742] Add Secure View sharing note
  modules/admin_manual/pages/enterprise/collaboration/collabora_secure_view.adoc
Labels: backport

#3758 Redis Cluster Password config.sample
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Labels: admin docs

#3751 Update Encryption for 10.8
  modules/admin_manual/nav.adoc
  modules/admin_manual/pages/_partials/configuration/files/encryption/not-encrypted-files.adoc
  modules/admin_manual/pages/_partials/configuration/files/not-encrypted-files.adoc
  modules/admin_manual/pages/configuration/files/encryption/disabling-encryption.adoc
  modules/admin_manual/pages/configuration/files/encryption/enable-encryption.adoc
  modules/admin_manual/pages/configuration/files/encryption/enabling-user-key-encryption.adoc
  modules/admin_manual/pages/configuration/files/encryption/encryption-types.adoc
  modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
  modules/admin_manual/pages/configuration/files/encryption/encryption_configuration_quick_guide.adoc
  modules/admin_manual/pages/configuration/files/encryption/external-backends.adoc
  modules/admin_manual/pages/configuration/files/encryption/index.adoc
  modules/admin_manual/pages/configuration/files/encryption/master-key-encryption.adoc
  modules/admin_manual/pages/configuration/files/encryption/migration-guide.adoc
  modules/admin_manual/pages/configuration/files/encryption/moving-key-locations.adoc
  modules/admin_manual/pages/configuration/files/encryption/root.adoc
  modules/admin_manual/pages/configuration/files/encryption/sharing-encrypted-files.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/encryption_commands.adoc
  modules/user_manual/pages/_partials/files/not-encrypted-files.adoc
  modules/user_manual/pages/files/encrypting_files.adoc
Labels: admin docs, user docs

#3759 [10.7] [PR 3751] Update Encryption for 10.8
  modules/admin_manual/nav.adoc
  modules/admin_manual/pages/_partials/configuration/files/encryption/not-encrypted-files.adoc
  modules/admin_manual/pages/_partials/configuration/files/not-encrypted-files.adoc
  modules/admin_manual/pages/configuration/files/encryption/disabling-encryption.adoc
  modules/admin_manual/pages/configuration/files/encryption/enable-encryption.adoc
  modules/admin_manual/pages/configuration/files/encryption/enabling-user-key-encryption.adoc
  modules/admin_manual/pages/configuration/files/encryption/encryption-types.adoc
  modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
  modules/admin_manual/pages/configuration/files/encryption/encryption_configuration_quick_guide.adoc
  modules/admin_manual/pages/configuration/files/encryption/external-backends.adoc
  modules/admin_manual/pages/configuration/files/encryption/index.adoc
  modules/admin_manual/pages/configuration/files/encryption/master-key-encryption.adoc
  modules/admin_manual/pages/configuration/files/encryption/migration-guide.adoc
  modules/admin_manual/pages/configuration/files/encryption/moving-key-locations.adoc
  modules/admin_manual/pages/configuration/files/encryption/root.adoc
  modules/admin_manual/pages/configuration/files/encryption/sharing-encrypted-files.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/encryption_commands.adoc
  modules/user_manual/pages/_partials/files/not-encrypted-files.adoc
  modules/user_manual/pages/files/encrypting_files.adoc
Labels: backport

#3757 Fixing Building the Documentation Guide
  docs/build-the-docs.md
Labels: deployment

#3761 [10.6] [PR 3757] Fixing Building the Documentation Guide
  docs/build-the-docs.md
Labels: backport

#3760 [10.7] [PR 3757] Fixing Building the Documentation Guide
  docs/build-the-docs.md
Labels: backport
