Repository owncloud/docs, pull requests merged in 2021-08, with the labels that each got.

#3908 Fixes and improvments for the backporting script
  modules/developer_manual/examples/scripts/backport.sh
Labels: deployment

#3909 [10.8] [PR 3908] Fixes and improvments for the backporting script
  modules/developer_manual/examples/scripts/backport.sh
Labels: backport

#3910 [10.7] [PR 3908] Fixes and improvments for the backporting script
  modules/developer_manual/examples/scripts/backport.sh
Labels: backport

#3911 Fix query and fix documentation in bp script/documentation
  modules/developer_manual/examples/scripts/backport.sh
  modules/developer_manual/pages/general/backporting.adoc
Labels: admin docs, deployment

#3912 [10.8] [PR 3911] Fix query and fix documentation in bp script/documentation
  modules/developer_manual/examples/scripts/backport.sh
  modules/developer_manual/pages/general/backporting.adoc
Labels: backport

#3913 [10.7] [PR 3911] Fix query and fix documentation in bp script/documentation
  modules/developer_manual/examples/scripts/backport.sh
  modules/developer_manual/pages/general/backporting.adoc
Labels: backport

#3890 Add database as storage backend for settings
  modules/admin_manual/pages/configuration/user/oidc/oidc.adoc
Labels: admin docs

#3914 State that occ config:app is handled via the database
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/config_commands.adoc
Labels: admin docs

#3915 Remove the need for perl from the backport script
  modules/developer_manual/examples/scripts/backport.sh
Labels: Tooling

#3916 [10.8] [PR 3890] Add database as storage backend for settings
  modules/admin_manual/pages/configuration/user/oidc/oidc.adoc
Labels: backport

#3919 [10.8] [PR 3914] State that occ config:app is handled via the database
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/config_commands.adoc
Labels: backport

#3918 [10.7] [PR 3915] Remove the need for perl from the backport script
  modules/developer_manual/examples/scripts/backport.sh
Labels: backport

#3917 [10.8] [PR 3915] Remove the need for perl from the backport script
  modules/developer_manual/examples/scripts/backport.sh
Labels: backport

#3920 [10.7] [PR 3914] State that occ config:app is handled via the database
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/config_commands.adoc
Labels: backport

#3924 [10.8] [PR 3923] Richdocuments: occ - Open documents in a new tab
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/richdocuments.adoc
Labels: backport

#3925 Describe limits of preview generation
  modules/admin_manual/pages/configuration/files/previews_configuration.adoc
Labels: admin docs

#3927 [10.8] [PR 3925] Describe limits of preview generation
  modules/admin_manual/pages/configuration/files/previews_configuration.adoc
Labels: backport

#3926 [10.7] [PR 3925] Describe limits of preview generation
  modules/admin_manual/pages/configuration/files/previews_configuration.adoc
Labels: backport

#3930 added sudo where necessary in upgrade description
  modules/admin_manual/pages/maintenance/manual_upgrade.adoc
Labels: admin docs

#3931 [10.7] [PR 3930] added sudo where necessary in upgrade description
  modules/admin_manual/pages/maintenance/manual_upgrade.adoc
Labels: backport

#3932 [10.8] [PR 3930] added sudo where necessary in upgrade description
  modules/admin_manual/pages/maintenance/manual_upgrade.adoc
Labels: backport

#3933 Move a adoc varaible from a page to site.yml
  modules/ROOT/pages/index.adoc
  site.yml
Labels: admin docs

#3934 [10.8] [PR 3933] Move a adoc varaible from a page to site.yml
  modules/ROOT/pages/index.adoc
  site.yml
Labels: backport

#3935 [10.7] [PR 3933] Move a adoc varaible from a page to site.yml
  modules/ROOT/pages/index.adoc
  site.yml
Labels: backport

#3938 [10.7] [PR 3936] Docker upgrade missed end of maintenance step
  modules/admin_manual/pages/installation/docker/index.adoc
Labels: backport

#3937 [10.8] [PR 3936] Docker upgrade missed end of maintenance step
  modules/admin_manual/pages/installation/docker/index.adoc
Labels: backport

#3939 Describe which mount options are default for NFS
  modules/admin_manual/pages/installation/deployment_recommendations/nfs.adoc
Labels: admin docs

#3940 [10.8] [PR 3939] Describe which mount options are default for NFS
  modules/admin_manual/pages/installation/deployment_recommendations/nfs.adoc
Labels: backport

#3941 [10.7] [PR 3939] Describe which mount options are default for NFS
  modules/admin_manual/pages/installation/deployment_recommendations/nfs.adoc
Labels: backport

#3946 Fix guest app document
  modules/admin_manual/pages/configuration/user/guests_app.adoc
Labels: admin docs

#3948 [10.8] [PR 3946] Fix guest app document
  modules/admin_manual/pages/configuration/user/guests_app.adoc
Labels: backport

#3947 [10.7] [PR 3946] Fix guest app document
  modules/admin_manual/pages/configuration/user/guests_app.adoc
Labels: backport

#3950 Document Path and Filename Length Limitations
  modules/admin_manual/nav.adoc
  modules/admin_manual/pages/troubleshooting/path_filename_length.adoc
Labels: admin docs

#3952 [10.8] [PR 3950] Document Path and Filename Length Limitations
  modules/admin_manual/nav.adoc
  modules/admin_manual/pages/troubleshooting/path_filename_length.adoc
Labels: backport

#3953 [10.7] [PR 3950] Document Path and Filename Length Limitations
  modules/admin_manual/nav.adoc
  modules/admin_manual/pages/troubleshooting/path_filename_length.adoc
Labels: backport

#3956 [10.8] [PR 3954] Update ms-teams.adoc
  modules/admin_manual/pages/configuration/integration/ms-teams.adoc
Labels: backport

#3951 Add doc guidelines
  README.md
  docs/doc-guidelines.md
Labels: repo

#3957 [10.8] [PR 3951] Add doc guidelines
  README.md
  docs/doc-guidelines.md
Labels: backport

#3958 [10.7] [PR 3951] Add doc guidelines
  README.md
  docs/doc-guidelines.md
Labels: backport

#3960 [10.8] [PR 3959] Add warning around removal of external storage configuration
  modules/admin_manual/pages/configuration/files/external_storage/configuration.adoc
Labels: backport

#3961 [10.7] [PR 3959] Add warning around removal of external storage configuration
  modules/admin_manual/pages/configuration/files/external_storage/configuration.adoc
Labels: backport

#3966 ownCloud does currently not support Redis ACL´s
  modules/admin_manual/pages/configuration/server/caching_configuration.adoc
Labels: admin docs

#3968 [10.8] [PR 3966] ownCloud does currently not support Redis ACL´s
  modules/admin_manual/pages/configuration/server/caching_configuration.adoc
Labels: backport

#3967 [10.7] [PR 3966] ownCloud does currently not support Redis ACL´s
  modules/admin_manual/pages/configuration/server/caching_configuration.adoc
Labels: backport

#3972 added info on av_background_scan
  modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc
Labels: admin docs

#3973 recommendation to not locate the data directory in the webroot
  modules/admin_manual/pages/installation/installation_wizard.adoc
Labels: admin docs

#3974 [10.8] [PR 3972] added info on av_background_scan
  modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc
Labels: backport

#3975 [10.7] [PR 3972] added info on av_background_scan
  modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc
Labels: backport

#3977 [10.7] [PR 3973] recommendation to not locate the data directory in t…
  modules/admin_manual/pages/installation/installation_wizard.adoc
Labels: backport

#3976 [10.8] [PR 3973] recommendation to not locate the data directory in t…
  modules/admin_manual/pages/installation/installation_wizard.adoc
Labels: backport

#3978 gender neutral language
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
  modules/admin_manual/pages/configuration/server/language_configuration.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/file_commands.adoc
  modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
Labels: admin docs

#3979 [10.8] [PR 3978] gender neutral language
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
  modules/admin_manual/pages/configuration/server/language_configuration.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/file_commands.adoc
  modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
Labels: backport

#3980 [10.7] [PR 3978] gender neutral language
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
  modules/admin_manual/pages/configuration/server/language_configuration.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/file_commands.adoc
  modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
Labels: backport
