Repository owncloud/docs, pull requests merged in 2021-09, with the labels that each got.

#3983 Revised server hardening
  modules/admin_manual/pages/configuration/server/harden_server.adoc
Labels: admin docs

#3984 [10.8] [PR 3983] Revised server hardening
  modules/admin_manual/pages/configuration/server/harden_server.adoc
Labels: backport

#3985 [10.7] [PR 3983] Revised server hardening
  modules/admin_manual/pages/configuration/server/harden_server.adoc
Labels: backport

#3986 Use the latest stable PEAR release
  modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc
Labels: admin docs

#3988 [10.8] [PR 3986] Use the latest stable PEAR release
  modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc
Labels: backport

#3987 [10.7] [PR 3986] Use the latest stable PEAR release
  modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc
Labels: backport

#3999 Fix pdf link for 8.2 admin manual
  modules/ROOT/pages/releases.adoc
Labels: admin docs

#4000 [10.7] [PR 3999] Fix pdf link for 8.2 admin manual
  modules/ROOT/pages/releases.adoc
Labels: backport

#4001 [10.8] [PR 3999] Fix pdf link for 8.2 admin manual
  modules/ROOT/pages/releases.adoc
Labels: backport

#4009 [10.7] [PR 4008] fix: add favicon.ico to static files list
  overlay/ui.yml
Labels: backport

#4010 [10.8] [PR 4008] fix: add favicon.ico to static files list
  overlay/ui.yml
Labels: backport

#4012 Fix pdf link for desktop
  modules/ROOT/pages/releases.adoc
Labels: admin docs

#4014 [10.8] [PR 4012] Fix pdf link for desktop
  modules/ROOT/pages/releases.adoc
Labels: backport

#4013 [10.7] [PR 4012] Fix pdf link for desktop
  modules/ROOT/pages/releases.adoc
Labels: backport

#3792 Adding QNAP docs
  modules/admin_manual/assets/images/qnap/DDNS_qnap-cropped.png
  modules/admin_manual/assets/images/qnap/marketplace.png
  modules/admin_manual/assets/images/qnap/ownCloud_main_menu.png
  modules/admin_manual/assets/images/qnap/qnap-app_center.png
  modules/admin_manual/assets/images/qnap/qnap-controlpanel.png
  modules/admin_manual/assets/images/qnap/qnap_main_menu.png
  modules/admin_manual/assets/images/qnap/qulogcenter.png
  modules/admin_manual/assets/images/qnap/storage_pool.png
  modules/admin_manual/assets/images/qnap/users_on_qnap.png
  modules/admin_manual/nav.adoc
  modules/admin_manual/pages/qnap/index.adoc
Labels: admin docs

#4015 [10.8] [PR 3792] Adding QNAP docs
  modules/admin_manual/assets/images/qnap/DDNS_qnap-cropped.png
  modules/admin_manual/assets/images/qnap/marketplace.png
  modules/admin_manual/assets/images/qnap/ownCloud_main_menu.png
  modules/admin_manual/assets/images/qnap/qnap-app_center.png
  modules/admin_manual/assets/images/qnap/qnap-controlpanel.png
  modules/admin_manual/assets/images/qnap/qnap_main_menu.png
  modules/admin_manual/assets/images/qnap/qulogcenter.png
  modules/admin_manual/assets/images/qnap/storage_pool.png
  modules/admin_manual/assets/images/qnap/users_on_qnap.png
  modules/admin_manual/nav.adoc
  modules/admin_manual/pages/qnap/index.adoc
Labels: backport

#4023 [10.8] [PR 4018] Mailer sending modes
  modules/admin_manual/pages/configuration/server/email_configuration.adoc
Labels: backport

#4024 [10.7] [PR 4018] Mailer sending modes
  modules/admin_manual/pages/configuration/server/email_configuration.adoc
Labels: backport

#4026 [10.7] [PR 4017] add comment on initial user sync
  modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
Labels: backport

#4025 [10.8] [PR 4017] add comment on initial user sync
  modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
Labels: backport

#4022 Minor text fixes to the create version branch steps
  docs/new-version-branch.md
Labels: deployment

#4029 Set desktop to 2.9
  site.yml
Labels: deployment

#4030 [10.8] [PR 4029] Set desktop to 2.9
  site.yml
Labels: backport

#4031 [10.7] [PR 4029] Set desktop to 2.9
  site.yml
Labels: backport

#4038 Make all included occ files not being indexed by crawlers
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/2fa_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/activity_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/admin_audit_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/antivirus_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/brute_force_protection_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/calendar_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/contacts_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/data_explorer_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/files_lifecycle.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/ldap_integration_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/market_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/metrics_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/password_policy_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/ransomware_protection_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/richdocuments.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/s3objectstore_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/saml_sso_shibboleth_integration_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/wnd_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/app_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/background_jobs_selector.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/command_line_installation_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/command_line_upgrade_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/config_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/config_reports_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/database_conversion_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/dav_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/encryption_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/federation_sync_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/file_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/files_external_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/full_text_search_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/group_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/incoming_shares_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/integrity_check_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/localisation_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/logging_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/maintenance_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/managing_background_jobs.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/migration_steps_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/mimetype_update_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/notifications_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/security_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/sharing_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/trashbin_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/user_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/versions_commands.adoc
  modules/developer_manual/pages/webdav_api/groups/custom_groups_endpoints.adoc
  modules/developer_manual/pages/webdav_api/groups/group_membership_endpoints.adoc
  modules/developer_manual/pages/webdav_api/search/filter_files.adoc
  modules/developer_manual/pages/webdav_api/search/search_files.adoc
Labels: enhancement, developer docs, admin docs

#4039 [10.8] [PR 4038] Make all included occ files not being indexed by cra…
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/2fa_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/activity_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/admin_audit_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/antivirus_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/brute_force_protection_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/calendar_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/contacts_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/data_explorer_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/files_lifecycle.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/ldap_integration_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/market_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/metrics_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/password_policy_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/ransomware_protection_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/richdocuments.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/s3objectstore_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/saml_sso_shibboleth_integration_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/wnd_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/app_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/background_jobs_selector.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/command_line_installation_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/command_line_upgrade_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/config_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/config_reports_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/database_conversion_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/dav_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/encryption_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/federation_sync_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/file_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/files_external_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/full_text_search_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/group_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/incoming_shares_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/integrity_check_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/localisation_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/logging_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/maintenance_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/managing_background_jobs.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/migration_steps_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/mimetype_update_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/notifications_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/security_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/sharing_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/trashbin_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/user_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/versions_commands.adoc
  modules/developer_manual/pages/webdav_api/groups/custom_groups_endpoints.adoc
  modules/developer_manual/pages/webdav_api/groups/group_membership_endpoints.adoc
  modules/developer_manual/pages/webdav_api/search/filter_files.adoc
  modules/developer_manual/pages/webdav_api/search/search_files.adoc
Labels: backport

#4040 [10.7] [PR 4038] Make all included occ files not being indexed by crawlers
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/2fa_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/activity_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/admin_audit_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/antivirus_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/brute_force_protection_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/calendar_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/contacts_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/data_explorer_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/files_lifecycle.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/ldap_integration_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/market_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/metrics_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/password_policy_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/ransomware_protection_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/s3objectstore_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/saml_sso_shibboleth_integration_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/wnd_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/app_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/background_jobs_selector.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/command_line_installation_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/command_line_upgrade_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/config_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/config_reports_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/database_conversion_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/dav_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/encryption_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/federation_sync_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/file_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/files_external_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/full_text_search_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/group_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/incoming_shares_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/integrity_check_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/localisation_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/logging_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/maintenance_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/managing_background_jobs.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/migration_steps_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/mimetype_update_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/notifications_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/security_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/sharing_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/trashbin_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/user_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/versions_commands.adoc
  modules/developer_manual/pages/webdav_api/groups/custom_groups_endpoints.adoc
  modules/developer_manual/pages/webdav_api/groups/group_membership_endpoints.adoc
  modules/developer_manual/pages/webdav_api/search/filter_files.adoc
  modules/developer_manual/pages/webdav_api/search/search_files.adoc
Labels: backport

#4042 [10.8] [PR 4037] backtick removed from wnd examples
  modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
Labels: backport

#4043 [10.7] [PR 4037] backtick removed from wnd examples
  modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
Labels: backport

#4041 Config To Docs run for recent changes
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Labels: admin docs

#4051 [master] [PR 4045] replaced references of the generator app with the generator URL directly
  modules/admin_manual/pages/configuration/integration/ms-teams.adoc
Labels: backport

#4052 [10.8] [PR 4045] Backport of last commit to master
  modules/admin_manual/pages/configuration/integration/ms-teams.adoc
Labels: backport

#4047 Use the new docs ios repo
  modules/ROOT/pages/releases.adoc
  site.yml
Labels: deployment

#4053 [10.7] [PR 4047] Use the new docs ios repo
  modules/ROOT/pages/releases.adoc
  site.yml
Labels: backport

#4055 Improve robots and sitemap files automatically post building the docs
  .drone.star
  bin/optimize_crawl
Labels: deployment

#4059 [10.8] [PR 4055] Improve robots and sitemap files automatically post building the docs
  .drone.star
  bin/optimize_crawl
Labels: backport

#4060 [10.7] [PR 4055] Improve robots and sitemap files automatically post building the docs
  .drone.star
  bin/optimize_crawl
Labels: backport

#4061 Update of the makepdf script and configuration to be inline with the other repos
  bin/makepdf
  bin/manual_config
Labels: deployment

#4056 Add missing text line in releases file
  modules/ROOT/pages/releases.adoc
Labels: admin docs

#4062 [10.7] [PR 4061] Update of the makepdf script and configuration to be inline with the other repos
  bin/makepdf
  bin/manual_config
Labels: backport

#4063 [10.8] [PR 4061] Update of the makepdf script and configuration to be inline with the other repos
  bin/makepdf
  bin/manual_config
Labels: backport

#4065 [10.8] [PR 4056] Add missing text line in releases file
  modules/ROOT/pages/releases.adoc
Labels: backport

#4064 [10.7] [PR 4056] Add missing text line in releases file
  modules/ROOT/pages/releases.adoc
Labels: backport

#4066 New iOS App release
  modules/ROOT/pages/releases.adoc
  site.yml
Labels: deployment

#4067 [10.7] [PR 4066] New iOS App release
  modules/ROOT/pages/releases.adoc
  site.yml
Labels: backport

#4068 [10.8] [PR 4066] New iOS App release
  modules/ROOT/pages/releases.adoc
  site.yml
Labels: backport

#4069 Mini fix for using the correct release variable in releases file
  modules/ROOT/pages/releases.adoc
Labels: deployment

#4070 [10.7] [PR 4069] Mini fix for using the correct release variable in releases file
  modules/ROOT/pages/releases.adoc
Labels: backport

#4071 [10.8] [PR 4069] Mini fix for using the correct release variable in releases file
  modules/ROOT/pages/releases.adoc
Labels: backport

#4072 Takes back a minor iOS release
  modules/ROOT/pages/releases.adoc
  site.yml
Labels: deployment

#4073 [10.7] [PR 4072] Takes back a minor iOS release
  modules/ROOT/pages/releases.adoc
  site.yml
Labels: backport

#4074 [10.8] [PR 4072] Takes back a minor iOS release
  modules/ROOT/pages/releases.adoc
  site.yml
Labels: backport

#4077 [10.8] [PR 4075] Specify minor versions of MariaDb that are supported
  modules/admin_manual/pages/installation/system_requirements.adoc
Labels: backport

#4076 [10.7] [PR 4075] Specify minor versions of MariaDb that are supported
  modules/admin_manual/pages/installation/system_requirements.adoc
Labels: backport

#4084 Make the new docs-Android branch available for docs
  modules/ROOT/pages/releases.adoc
  site.yml
Labels: deployment

#4085 [10.8] [PR 4084] Make the new docs-Android branch available for docs
  modules/ROOT/pages/releases.adoc
  site.yml
Labels: backport

#4086 [10.7] [PR 4084] Make the new docs-Android branch available for docs
  modules/ROOT/pages/releases.adoc
  site.yml
Labels: backport

#4088 Add android to optimize_crawl script
  bin/optimize_crawl
Labels: deployment

#4090 [10.7] [PR 4088] Add android to optimize_crawl script
  bin/optimize_crawl
Labels: backport

#4089 [10.8] [PR 4088] Add android to optimize_crawl script
  bin/optimize_crawl
Labels: backport

#4094 config sample updates part two (no backports needed)
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Labels: admin docs

#4093 config sample updates part one (backports needed)
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Labels: admin docs

#4095 [10.8] [PR 4093] config sample updates part one (backports needed)
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Labels: backport

#4098 added OS requirements
  modules/admin_manual/pages/qnap/index.adoc
Labels: admin docs

#4099 [10.8] [PR 4098] added OS requirements
  modules/admin_manual/pages/qnap/index.adoc
Labels: backport
