Repository owncloud/docs, pull requests merged in 2021-04, with the labels that each got.

#3427 [10.6] [PR 3426] Switch Desktop branch to 2.8
  site.yml
Labels: backport

#3428 [10.7] [PR 3426] Switch Desktop branch to 2.8
  site.yml
Labels: backport

#3433 config.apps.sample core update
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
Labels: admin docs

#3432 Collabora Fixes
  modules/admin_manual/nav.adoc
  modules/admin_manual/pages/enterprise/collaboration/collabora_online_integration.adoc
Labels: admin docs

#3434 [10.7] [PR 3433] config.apps.sample core update
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
Labels: backport

#3435 [10.7] [PR 3432] Collabora Fixes
  modules/admin_manual/nav.adoc
  modules/admin_manual/pages/enterprise/collaboration/collabora_online_integration.adoc
Labels: backport

#3436 [10.6] [PR 3432] Collabora Fixes
  modules/admin_manual/nav.adoc
  modules/admin_manual/pages/enterprise/collaboration/collabora_online_integration.adoc
Labels: backport

#3438 Fix Collabora Secure View file naming
  modules/admin_manual/nav.adoc
  modules/admin_manual/pages/enterprise/collaboration/collabora_secure_view.adoc
Labels: admin docs

#3437 Typo and rendering fix in config.apps.sample
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
Labels: admin docs

#3441 [10.7][PR 3437] Typo and rendering fix in config.apps.sample
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
Labels: backport

#3440 [10.6][PR3438] Fix Collabora Secure View file naming
  modules/admin_manual/nav.adoc
  modules/admin_manual/pages/enterprise/collaboration/collabora_secure_view.adoc
Labels: backport

#3439 [10.7][PR3438] Fix Collabora Secure View file naming
  modules/admin_manual/nav.adoc
  modules/admin_manual/pages/enterprise/collaboration/collabora_secure_view.adoc
Labels: backport

#3442 document improvement
  modules/admin_manual/pages/maintenance/manual_upgrade.adoc
Labels: admin docs

#3446 Adding the occ commands for the Metrics app
  modules/admin_manual/pages/configuration/server/occ_command.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/2fa_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/activity_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/antivirus_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/brute_force_protection_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/calendar_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/contacts_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/data_explorer_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/ldap_integration_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/market_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/metrics_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/password_policy_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/ransomware_protection_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/s3objectstore_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/saml_sso_shibboleth_integration_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/wnd_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/app_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/background_jobs_selector.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/command_line_installation_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/command_line_upgrade_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/config_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/config_reports_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/database_conversion_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/dav_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/encryption_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/federation_sync_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/file_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/files_external_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/full_text_search_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/group_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/incoming_shares_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/integrity_check_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/localisation_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/logging_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/maintenance_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/managing_background_jobs.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/migration_steps_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/mimetype_update_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/notifications_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/security_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/sharing_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/trashbin_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/user_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/versions_commands.adoc
Labels: admin docs

#3447 [10.7] [PR 3446] Adding the occ commands for the Metrics app
  modules/admin_manual/pages/configuration/server/occ_command.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/2fa_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/activity_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/antivirus_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/brute_force_protection_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/calendar_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/contacts_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/data_explorer_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/ldap_integration_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/market_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/metrics_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/password_policy_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/ransomware_protection_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/s3objectstore_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/saml_sso_shibboleth_integration_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/wnd_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/app_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/background_jobs_selector.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/command_line_installation_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/command_line_upgrade_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/config_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/config_reports_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/database_conversion_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/dav_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/encryption_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/federation_sync_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/file_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/files_external_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/full_text_search_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/group_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/incoming_shares_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/integrity_check_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/localisation_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/logging_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/maintenance_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/managing_background_jobs.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/migration_steps_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/mimetype_update_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/notifications_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/security_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/sharing_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/trashbin_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/user_commands.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/versions_commands.adoc
Labels: backport

#3452 [10.6] [PR 3451] Update system_requirements.adoc
  modules/admin_manual/pages/installation/system_requirements.adoc
Labels: backport

#3453 [10.7] [PR 3451] Update system_requirements.adoc
  modules/admin_manual/pages/installation/system_requirements.adoc
Labels: backport

#3454 [10.7] [PR 3430] Update enterprise_logging_apps.adoc
  modules/admin_manual/assets/images/enterprise/logging/admin_auditing.png
  modules/admin_manual/nav.adoc
  modules/admin_manual/pages/configuration/server/occ_command.adoc
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/admin_audit_commands.adoc
  modules/admin_manual/pages/enterprise/logging/admin_audit.adoc
  modules/admin_manual/pages/enterprise/logging/enterprise_logging_apps.adoc
Labels: backport

#3455 [10.6] [PR 3449] Do not register ondrey repo twice
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
Labels: backport

#3456 [10.7] [PR 3449] Do not register ondrey repo twice
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
Labels: backport

#3458 Some WOPI fixes
  modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
Labels: admin docs

#3459 Fix page_alias attribute name
  modules/admin_manual/pages/enterprise/logging/admin_audit.adoc
Labels: admin docs

#3462 [10.7] [PR 3459] Fix page_alias attribute name
  modules/admin_manual/pages/enterprise/logging/admin_audit.adoc
Labels: backport

#3460 [10.6] [PR 3458] Some WOPI fixes
  modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
Labels: backport

#3461 [10.7] [PR 3458] Some WOPI fixes
  modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
Labels: backport

#3464 Fix build the docs guide
  docs/build-the-docs.md
Labels: dependencies

#3465 Update BPG using manually created anchors
  docs/best-practices.md
Labels: deployment

#3468 Update best-practices.md
  docs/best-practices.md
Labels: deployment

#3472 config.apps.sample changes from core
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
Labels: admin docs

#3473 [10.7] [PR 3472] config.apps.sample changes from core
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
Labels: backport

#3467 MS Teams Integration
  modules/admin_manual/assets/images/configuration/integration/ms-teams/add-a-tab-ms-teams.png
  modules/admin_manual/assets/images/configuration/integration/ms-teams/add-website-ms-teams.png
  modules/admin_manual/assets/images/configuration/integration/ms-teams/name-and-url-ms-teams.png
  modules/admin_manual/assets/images/configuration/user/oidc/ms-azure-ad/admin-consent-ms-azure-ad.png
  modules/admin_manual/assets/images/configuration/user/oidc/ms-azure-ad/app-id-uri-ms-azure-ad.png
  modules/admin_manual/assets/images/configuration/user/oidc/ms-azure-ad/graph-permission-ms-azure-ad.png
  modules/admin_manual/assets/images/configuration/user/oidc/ms-azure-ad/login-with-ms-azure.png
  modules/admin_manual/assets/images/configuration/user/oidc/ms-azure-ad/new-registration-ms-azure-ad.png
  modules/admin_manual/assets/images/configuration/user/oidc/ms-azure-ad/overview-screen-ms-azure.png
  modules/admin_manual/assets/images/configuration/user/oidc/ms-azure-ad/portal-tenant-id-ms-azure-ad.png
  modules/admin_manual/assets/images/configuration/user/oidc/ms-azure-ad/provide-required-information-ms-azure-ad.png
  modules/admin_manual/assets/images/configuration/user/oidc/ms-azure-ad/scope-consent-ms-azure-ad.png
  modules/admin_manual/assets/images/configuration/user/oidc/ms-azure-ad/select-manag-azure-ad.png
  modules/admin_manual/assets/images/configuration/user/oidc/ms-azure-ad/setup-claims-ms-azure-ad.png
  modules/admin_manual/assets/images/configuration/user/oidc/ms-azure-ad/setup-client-secret-ms-azure-ad.png
  modules/admin_manual/assets/images/configuration/user/oidc/ms-azure-ad/setup-redirect-url-ms-azure-ad.png
  modules/admin_manual/nav.adoc
  modules/admin_manual/pages/configuration/integration/index.adoc
  modules/admin_manual/pages/configuration/integration/ms-teams.adoc
  modules/admin_manual/pages/configuration/user/oidc/index.adoc
  modules/admin_manual/pages/configuration/user/oidc/kopano-setup.adoc
  modules/admin_manual/pages/configuration/user/oidc/ms-azure-setup.adoc
  modules/admin_manual/pages/configuration/user/oidc/oidc.adoc
  modules/user_manual/assets/images/integration/ms-teams/login-to-owncloud-with-azure-ad.png
  modules/user_manual/assets/images/integration/ms-teams/owncloud-teams-app.png
  modules/user_manual/nav.adoc
  modules/user_manual/pages/integration/index.adoc
  modules/user_manual/pages/integration/ms-teams.adoc
Labels: admin docs, user docs

#3474 [10.7] [PR 3467] MS Teams Integration
  modules/admin_manual/assets/images/configuration/integration/ms-teams/add-a-tab-ms-teams.png
  modules/admin_manual/assets/images/configuration/integration/ms-teams/add-website-ms-teams.png
  modules/admin_manual/assets/images/configuration/integration/ms-teams/name-and-url-ms-teams.png
  modules/admin_manual/assets/images/configuration/user/oidc/ms-azure-ad/admin-consent-ms-azure-ad.png
  modules/admin_manual/assets/images/configuration/user/oidc/ms-azure-ad/app-id-uri-ms-azure-ad.png
  modules/admin_manual/assets/images/configuration/user/oidc/ms-azure-ad/graph-permission-ms-azure-ad.png
  modules/admin_manual/assets/images/configuration/user/oidc/ms-azure-ad/login-with-ms-azure.png
  modules/admin_manual/assets/images/configuration/user/oidc/ms-azure-ad/new-registration-ms-azure-ad.png
  modules/admin_manual/assets/images/configuration/user/oidc/ms-azure-ad/overview-screen-ms-azure.png
  modules/admin_manual/assets/images/configuration/user/oidc/ms-azure-ad/portal-tenant-id-ms-azure-ad.png
  modules/admin_manual/assets/images/configuration/user/oidc/ms-azure-ad/provide-required-information-ms-azure-ad.png
  modules/admin_manual/assets/images/configuration/user/oidc/ms-azure-ad/scope-consent-ms-azure-ad.png
  modules/admin_manual/assets/images/configuration/user/oidc/ms-azure-ad/select-manag-azure-ad.png
  modules/admin_manual/assets/images/configuration/user/oidc/ms-azure-ad/setup-claims-ms-azure-ad.png
  modules/admin_manual/assets/images/configuration/user/oidc/ms-azure-ad/setup-client-secret-ms-azure-ad.png
  modules/admin_manual/assets/images/configuration/user/oidc/ms-azure-ad/setup-redirect-url-ms-azure-ad.png
  modules/admin_manual/nav.adoc
  modules/admin_manual/pages/configuration/integration/index.adoc
  modules/admin_manual/pages/configuration/integration/ms-teams.adoc
  modules/admin_manual/pages/configuration/user/oidc/index.adoc
  modules/admin_manual/pages/configuration/user/oidc/kopano-setup.adoc
  modules/admin_manual/pages/configuration/user/oidc/ms-azure-setup.adoc
  modules/admin_manual/pages/configuration/user/oidc/oidc.adoc
  modules/user_manual/assets/images/integration/ms-teams/login-to-owncloud-with-azure-ad.png
  modules/user_manual/assets/images/integration/ms-teams/owncloud-teams-app.png
  modules/user_manual/nav.adoc
  modules/user_manual/pages/integration/index.adoc
  modules/user_manual/pages/integration/ms-teams.adoc
Labels: backport

#3476 Fix link (typo) for MS Teams
  modules/admin_manual/pages/configuration/integration/ms-teams.adoc
Labels: admin docs

#3477 [10.7] [PR 3476] Fix link (typo) for MS Teams
  modules/admin_manual/pages/configuration/integration/ms-teams.adoc
Labels: backport

#3475 Add Microsoft Teams Bridge to config.apps.sample
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
Labels: admin docs

#3479 [10.7] [PR 3475] Add Microsoft Teams Bridge to config.apps.sample
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
Labels: backport

#3481 [10.7] [PR 3478] update docker compose file and instructions
  modules/admin_manual/assets/images/docker/owncloud-ui-login.png
  modules/admin_manual/examples/installation/docker/docker-compose.yml
  modules/admin_manual/pages/installation/docker/index.adoc
Labels: backport

#3480 [10.6] [PR 3478] update docker compose file and instructions
  modules/admin_manual/assets/images/docker/owncloud-ui-login.png
  modules/admin_manual/examples/installation/docker/docker-compose.yml
  modules/admin_manual/pages/installation/docker/index.adoc
Labels: backport

#3482 [10.6] [PR 3457] added listing instructions
  modules/admin_manual/pages/configuration/files/federated_cloud_sharing_configuration.adoc
Labels: backport

#3483 [10.7] [PR 3457] added listing instructions
  modules/admin_manual/pages/configuration/files/federated_cloud_sharing_configuration.adoc
Labels: backport

#3486 Add images to the description how to create a ms-teams app
  modules/admin_manual/assets/images/configuration/integration/ms-teams/app-description-msteamsgen.png
  modules/admin_manual/assets/images/configuration/integration/ms-teams/app-name-msteamsgen.png
  modules/admin_manual/assets/images/configuration/integration/ms-teams/define-app-version-msteamsgen.png
  modules/admin_manual/assets/images/configuration/integration/ms-teams/download-zip-msteamsgen.png
  modules/admin_manual/assets/images/configuration/integration/ms-teams/enter-app-id-msteamsgen.png
  modules/admin_manual/assets/images/configuration/integration/ms-teams/owncloud-url-msteamsgen.png
  modules/admin_manual/assets/images/configuration/integration/ms-teams/set-accent-color-msteamsgen.png
  modules/admin_manual/pages/configuration/integration/ms-teams.adoc
  modules/user_manual/pages/integration/ms-teams.adoc
Labels: admin docs

#3487 [10.7] [PR 3486] Add images to the description how to create a ms-teams app
  modules/admin_manual/assets/images/configuration/integration/ms-teams/app-description-msteamsgen.png
  modules/admin_manual/assets/images/configuration/integration/ms-teams/app-name-msteamsgen.png
  modules/admin_manual/assets/images/configuration/integration/ms-teams/define-app-version-msteamsgen.png
  modules/admin_manual/assets/images/configuration/integration/ms-teams/download-zip-msteamsgen.png
  modules/admin_manual/assets/images/configuration/integration/ms-teams/enter-app-id-msteamsgen.png
  modules/admin_manual/assets/images/configuration/integration/ms-teams/owncloud-url-msteamsgen.png
  modules/admin_manual/assets/images/configuration/integration/ms-teams/set-accent-color-msteamsgen.png
  modules/admin_manual/pages/configuration/integration/ms-teams.adoc
  modules/user_manual/pages/integration/ms-teams.adoc
Labels: backport

#3470 Adding icap
  modules/admin_manual/assets/images/configuration/server/anti-virus-panel.png
  modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc
Labels: admin docs

#3488 The share api endpoint does not end in `/pending`
  modules/developer_manual/pages/core/apis/ocs-share-api.adoc
Labels: bug

#3489 [10.7] [PR 3470] Adding icap
  modules/admin_manual/assets/images/configuration/server/anti-virus-panel.png
  modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc
Labels: backport

#3490 [10.6] [PR 3488] The share api endpoint does not end in `/pending`
  modules/developer_manual/pages/core/apis/ocs-share-api.adoc
Labels: backport

#3491 [10.7] [PR 3488] The share api endpoint does not end in `/pending`
  modules/developer_manual/pages/core/apis/ocs-share-api.adoc
Labels: backport

#3497 [10.7] [PR 3495] Document the ownCloud App for Splunk
  modules/admin_manual/nav.adoc
  modules/admin_manual/pages/configuration/integration/index.adoc
  modules/admin_manual/pages/configuration/integration/splunk.adoc
Labels: backport
