Repository owncloud/docs, pull requests merged in 2021-05, with the labels that each got.

#3510 [10.7] [PR 3509] Add 10.7 known issue to release notes
  modules/admin_manual/pages/release_notes.adoc
Labels: backport

#3511 User manual cleanup because of files on the wrong location
  modules/user_manual/nav.adoc
  modules/user_manual/pages/apps/calendar.adoc
  modules/user_manual/pages/apps/contacts.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/apps.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/auth.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/comments.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/config.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/console.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/custom_groups.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/file_lifecycle.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/files.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/holding_period.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/impersonate.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/sharing.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/smb_acl.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/tags.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/user_preference.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/users.adoc
  modules/user_manual/pages/apps/media_viewer_app.adoc
Labels: user docs

#3513 [10.7] [PR 3511] User manual cleanup because of files on the wrong location
  modules/user_manual/nav.adoc
  modules/user_manual/pages/apps/calendar.adoc
  modules/user_manual/pages/apps/contacts.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/apps.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/auth.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/comments.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/config.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/console.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/custom_groups.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/file_lifecycle.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/files.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/holding_period.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/impersonate.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/sharing.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/smb_acl.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/tags.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/user_preference.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/users.adoc
  modules/user_manual/pages/apps/media_viewer_app.adoc
Labels: backport

#3512 [10.6] [PR 3511] User manual cleanup because of files on the wrong location
  modules/user_manual/nav.adoc
  modules/user_manual/pages/apps/calendar.adoc
  modules/user_manual/pages/apps/contacts.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/apps.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/auth.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/comments.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/config.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/console.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/custom_groups.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/file_lifecycle.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/files.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/holding_period.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/impersonate.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/sharing.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/smb_acl.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/tags.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/user_preference.adoc
  modules/user_manual/pages/apps/enterprise/admin_audit/users.adoc
  modules/user_manual/pages/apps/media_viewer_app.adoc
Labels: backport

#3521 Added references to the new Splunk-App-Section
  modules/admin_manual/pages/enterprise/logging/admin_audit.adoc
  modules/admin_manual/pages/enterprise/reporting/metrics.adoc
Labels: admin docs

#3526 [10.6] Fixing release version plus adding -E to sudo command.
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
Labels: 10.6, admin docs

#3527 [10.7] [PR 3374] Fixing release version plus adding -E to sudo command
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
Labels: backport

#3529 Add Collaborative WND (CWND)
  modules/admin_manual/assets/images/enterprise/external_storage/windows_network_drive/acl-permissions-manager.png
  modules/admin_manual/assets/images/enterprise/external_storage/windows_network_drive/cwnd_add_storage.png
  modules/admin_manual/assets/images/enterprise/external_storage/windows_network_drive/cwnd_fields.png
  modules/admin_manual/assets/images/enterprise/external_storage/windows_network_drive/cwnd_login_possibilities.png
  modules/admin_manual/assets/images/enterprise/external_storage/windows_network_drive/cwnd_regain_mount_access.png
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/wnd_commands.adoc
  modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
Labels: admin docs

#3533 Replacing change log link with Server Packages link
  modules/admin_manual/pages/maintenance/package_upgrade.adoc
Labels: admin docs

#3543 Rename script cli to makepdf
  .drone.star
  bin/makepdf
  docs/build-the-docs.md
Labels: deployment

#3545 [10.6] [PR 3543] Rename script cli to makepdf
  .drone.star
  bin/makepdf
  docs/build-the-docs.md
Labels: deployment

#3546 [10.7] [PR 3543] Rename script cli to makepdf
  .drone.star
  bin/makepdf
  docs/build-the-docs.md
Labels: deployment

#3551 Added warnings to packagemanager upgrades
  modules/admin_manual/pages/maintenance/package_upgrade.adoc
  modules/admin_manual/pages/maintenance/upgrading/upgrade_php.adoc
Labels: admin docs

#3552 [10.7] [PR 3551] Added warnings to packagemanager upgrades
  modules/admin_manual/pages/maintenance/package_upgrade.adoc
  modules/admin_manual/pages/maintenance/upgrading/upgrade_php.adoc
Labels: backport

#3553 [10.6] [PR 3551] Added warnings to packagemanager upgrades
  modules/admin_manual/pages/maintenance/package_upgrade.adoc
  modules/admin_manual/pages/maintenance/upgrading/upgrade_php.adoc
Labels: backport

#3548 Fix makepdf (script which creates the pdf)
  bin/find-orphaned-files.sh
  bin/instructions_makepdf.md
  bin/makepdf
  modules/admin_manual/pages/configuration/server/security/oauth2.adoc
  site.yml
Labels: deployment

#3554 [10.6] [PR 3548] Fix makepdf (script which creates the pdf)
  bin/find-orphaned-files.sh
  bin/instructions_makepdf.md
  bin/makepdf
  modules/admin_manual/pages/configuration/server/security/oauth2.adoc
  site.yml
Labels: backport

#3555 [10.7] [PR 3548] Fix makepdf (script which creates the pdf)
  bin/find-orphaned-files.sh
  bin/instructions_makepdf.md
  bin/makepdf
  modules/admin_manual/pages/configuration/server/security/oauth2.adoc
  site.yml
Labels: backport

#3556 Find possible orphaned .adoc files
  bin/find-orphaned-adoc-files
  bin/find-orphaned-example-files
Labels: deployment

#3557 [10.6] [PR 3556] Find possible orphaned .adoc files
  bin/find-orphaned-adoc-files
  bin/find-orphaned-example-files
Labels: backport

#3558 [10.7] [PR 3556] Find possible orphaned .adoc files
  bin/find-orphaned-adoc-files
  bin/find-orphaned-example-files
Labels: backport

#3560 Upgrade revised
  modules/admin_manual/pages/maintenance/manual_upgrade.adoc
  modules/admin_manual/pages/maintenance/upgrade.adoc
Labels: admin docs

#3562 [10.6] [PR 3560] Upgrade revised
  modules/admin_manual/pages/maintenance/manual_upgrade.adoc
  modules/admin_manual/pages/maintenance/upgrade.adoc
Labels: backport

#3561 [10.7] [PR 3560] Upgrade revised
  modules/admin_manual/pages/maintenance/manual_upgrade.adoc
  modules/admin_manual/pages/maintenance/upgrade.adoc
Labels: backport

#3563 Pointer to script guided upgrade
  modules/admin_manual/pages/maintenance/manual_upgrade.adoc
  modules/admin_manual/pages/maintenance/package_upgrade.adoc
Labels: admin docs

#3564 [10.6] [PR 3563] Pointer to script guided upgrade
  modules/admin_manual/pages/maintenance/manual_upgrade.adoc
  modules/admin_manual/pages/maintenance/package_upgrade.adoc
Labels: backport

#3565 [10.7] [PR 3563] Pointer to script guided upgrade
  modules/admin_manual/pages/maintenance/manual_upgrade.adoc
  modules/admin_manual/pages/maintenance/package_upgrade.adoc
Labels: backport

#3566 Samba text improvement
  modules/admin_manual/pages/installation/manual_installation/compile_samba.adoc
Labels: admin docs

#3567 [10.6] [PR 3566] Samba text improvement
  modules/admin_manual/pages/installation/manual_installation/compile_samba.adoc
Labels: backport

#3568 [10.7] [PR 3566] Samba text improvement
  modules/admin_manual/pages/installation/manual_installation/compile_samba.adoc
Labels: backport

#3569 [Docs-Only] add docs for running tests with release tarballs in CI
  modules/developer_manual/pages/testing/acceptance-tests.adoc
Labels: QA-team

#3573 Improved find adoc files catching false-positive incudes
  bin/find-orphaned-adoc-files
Labels: deployment

#3575 [10.7] [PR 3573] Improved find adoc files catching false-positive incudes
  bin/find-orphaned-adoc-files
Labels: backport

#3574 [10.6] [PR 3573] Improved find adoc files catching false-positive incudes
  bin/find-orphaned-adoc-files
Labels: backport

#3576 Note that the Quick Install guide for Ubuntu 20.04 has its limits
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
Labels: admin docs

#3578 [10.7] [PR 3576] Note that the Quick Install guide for Ubuntu 20.04 has its limits
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
Labels: backport

#3577 [10.6] [PR 3576] Note that the Quick Install guide for Ubuntu 20.04 has its limits
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
Labels: backport

#3583 Do not suggest cron every minute
  modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc
Labels: admin docs

#3581 Add guest content for command occ user:report
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/user_commands.adoc
Labels: 10.8, admin docs

#3587 [10.6] [PR 3583] Do not suggest cron every minute
  modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc
Labels: backport

#3588 [10.7] [PR 3583] Do not suggest cron every minute
  modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc
Labels: backport

#3589 config.sample changes coming from core (config-to-docs run)
  modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
  modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Labels: admin docs

#3593 Fix of occ config commands
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/config_commands.adoc
Labels: admin docs

#3596 [10.7] [PR 3593] Fix of occ config commands
  modules/admin_manual/pages/configuration/server/occ_commands/core_commands/config_commands.adoc
Labels: backport

#3595 [10.6] [PR 3593] Fix of occ config commands
  modules/admin_manual/pages/configuration/server/occ_command/config_commands.adoc
Labels: backport

#3592 Update files_antivirus
  modules/admin_manual/assets/images/apps/files_antivirus/antivirus-executable.png
  modules/admin_manual/assets/images/apps/files_antivirus/antivirus-icap.png
  modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc
Labels: admin docs

#3597 [10.7] [PR 3592] Update files_antivirus
  modules/admin_manual/assets/images/apps/files_antivirus/antivirus-executable.png
  modules/admin_manual/assets/images/apps/files_antivirus/antivirus-icap.png
  modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc
Labels: backport

#3604 [10.6] [PR 3603] Update local.adoc
  modules/admin_manual/pages/configuration/files/external_storage/local.adoc
Labels: backport

#3605 [10.7] [PR 3603] Update local.adoc
  modules/admin_manual/pages/configuration/files/external_storage/local.adoc
Labels: backport
