Repository owncloud/docs, pull requests merged in 2022-01, with the labels that each got.

#4574 Fixes a bunch of helper scripts for improved usability
  bin/find-orphaned-adoc-files
  bin/find-orphaned-attachment-files
  bin/find-orphaned-base
  bin/find-orphaned-example-files
  bin/find-orphaned-image-files
  bin/instructions_makepdf.md
  bin/makepdf
  bin/manual_config_pdf
  modules/developer_manual/assets/images/app/fundamentals/controllers/debug-the-csrf-token.jpg
  modules/developer_manual/examples/core/scripts/php/user-sync.php
Labels: deployment

#4575 [10.9] [PR 4574] Fixes a bunch of helper scripts for improved usability
  bin/find-orphaned-adoc-files
  bin/find-orphaned-attachment-files
  bin/find-orphaned-base
  bin/find-orphaned-example-files
  bin/find-orphaned-image-files
  bin/instructions_makepdf.md
  bin/makepdf
  bin/manual_config_pdf
  modules/developer_manual/assets/images/app/fundamentals/controllers/debug-the-csrf-token.jpg
  modules/developer_manual/examples/core/scripts/php/user-sync.php
Labels: backport

#4576 [10.8] [PR 4574] Fixes a bunch of helper scripts for improved usability
  bin/find-orphaned-adoc-files
  bin/find-orphaned-attachment-files
  bin/find-orphaned-base
  bin/find-orphaned-example-files
  bin/find-orphaned-image-files
  bin/instructions_makepdf.md
  bin/makepdf
  bin/manual_config_pdf
  modules/developer_manual/assets/images/app/fundamentals/controllers/debug-the-csrf-token.jpg
  modules/developer_manual/examples/core/scripts/php/user-sync.php
Labels: backport

#4578 [10.9] [PR 4577] change the branding client url
  modules/ROOT/pages/client_releases.adoc
  site.yml
Labels: backport

#4579 [10.8] [PR 4577] change the branding client url
  modules/ROOT/pages/client_releases.adoc
  site.yml
Labels: backport

#4580 fix branded clients access link
  modules/ROOT/pages/client_releases.adoc
Labels: deployment

#4581 [10.9] [PR 4580] fix branded clients access link
  modules/ROOT/pages/client_releases.adoc
Labels: backport

#4582 [10.8] [PR 4580] fix branded clients access link
  modules/ROOT/pages/client_releases.adoc
Labels: backport

#4585 Update and fix big file upload
  modules/admin_manual/pages/configuration/files/big_file_upload_configuration.adoc
Labels: admin docs

#4586 [10.9] [PR 4585] Update and fix big file upload
  modules/admin_manual/pages/configuration/files/big_file_upload_configuration.adoc
Labels: backport

#4587 [10.8] [PR 4585] Update and fix big file upload
  modules/admin_manual/pages/configuration/files/big_file_upload_configuration.adoc
Labels: backport

#4588 Add page-aliases for removed U18.04 documents
  modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
Labels: admin docs

#4589 [10.9] [PR 4588] Add page-aliases for removed U18.04 documents
  modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc
  modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
Labels: backport

#4591 removing deprecated repo url
  modules/ROOT/pages/server_release_notes.adoc
  modules/admin_manual/pages/installation/linux_packetmanager_install.adoc
  modules/admin_manual/pages/maintenance/backup_and_restore/backup.adoc
  modules/admin_manual/pages/maintenance/upgrading/package_upgrade.adoc
Labels: admin docs

#4592 [10.9] [PR 4591] removing deprecated repo url
  modules/ROOT/pages/server_release_notes.adoc
  modules/admin_manual/pages/installation/linux_packetmanager_install.adoc
  modules/admin_manual/pages/maintenance/backup_and_restore/backup.adoc
  modules/admin_manual/pages/maintenance/upgrading/package_upgrade.adoc
Labels: backport

#4594 added link to installation repos
  modules/ROOT/pages/server_release_notes.adoc
  modules/admin_manual/pages/_partials/maintenance/major_release_note.adoc
  modules/admin_manual/pages/installation/linux_packetmanager_install.adoc
  modules/admin_manual/pages/maintenance/backup_and_restore/backup.adoc
  modules/admin_manual/pages/maintenance/upgrading/package_upgrade.adoc
  site.yml
Labels: admin docs

#4595 [10.9] [PR 4594] added link to installation repos
  modules/ROOT/pages/server_release_notes.adoc
  modules/admin_manual/pages/_partials/maintenance/major_release_note.adoc
  modules/admin_manual/pages/installation/linux_packetmanager_install.adoc
  modules/admin_manual/pages/maintenance/backup_and_restore/backup.adoc
  modules/admin_manual/pages/maintenance/upgrading/package_upgrade.adoc
  site.yml
Labels: backport

#4596 [10.8] [PR 4594] added link to installation repos
  modules/ROOT/pages/server_release_notes.adoc
  modules/admin_manual/pages/_partials/maintenance/major_release_note.adoc
  modules/admin_manual/pages/installation/linux_packetmanager_install.adoc
  modules/admin_manual/pages/maintenance/backup_and_restore/backup.adoc
  modules/admin_manual/pages/maintenance/upgrading/package_upgrade.adoc
  site.yml
Labels: backport

#4603 Move the attachments directory
  bin/find-orphaned-attachment-files
  bin/find-orphaned-example-files
  bin/find-orphaned-image-files
  modules/ROOT/attachments/.gitkeep
  modules/admin_manual/attachments/.gitkeep
  modules/admin_manual/attachments/configuration/user/oidc/OAuth-code-flow-sequence-diagram.png
  modules/admin_manual/attachments/installation/manual_installation/bootstrap.sh
  modules/admin_manual/attachments/installation/manual_installation/compile_samba.sh
  modules/admin_manual/attachments/installation/manual_installation/install_samba.sh
  modules/developer_manual/attachments/.gitkeep
  modules/developer_manual/attachments/core/Makefile.example
  modules/user_manual/attachments/.gitkeep
Labels: deployment

#4604 [10.9] [PR 4603] Move the attachments directory
  bin/find-orphaned-attachment-files
  bin/find-orphaned-example-files
  bin/find-orphaned-image-files
  modules/ROOT/attachments/.gitkeep
  modules/admin_manual/attachments/.gitkeep
  modules/admin_manual/attachments/configuration/user/oidc/OAuth-code-flow-sequence-diagram.png
  modules/admin_manual/attachments/installation/manual_installation/bootstrap.sh
  modules/admin_manual/attachments/installation/manual_installation/compile_samba.sh
  modules/admin_manual/attachments/installation/manual_installation/install_samba.sh
  modules/developer_manual/attachments/.gitkeep
  modules/developer_manual/attachments/core/Makefile.example
  modules/user_manual/attachments/.gitkeep
Labels: backport

#4605 [10.8] [PR 4603] Move the attachments directory
  bin/find-orphaned-attachment-files
  bin/find-orphaned-example-files
  bin/find-orphaned-image-files
  modules/ROOT/attachments/.gitkeep
  modules/admin_manual/attachments/.gitkeep
  modules/admin_manual/attachments/configuration/user/oidc/OAuth-code-flow-sequence-diagram.png
  modules/admin_manual/attachments/installation/manual_installation/bootstrap.sh
  modules/admin_manual/attachments/installation/manual_installation/compile_samba.sh
  modules/admin_manual/attachments/installation/manual_installation/install_samba.sh
  modules/developer_manual/attachments/.gitkeep
  modules/developer_manual/attachments/core/Makefile.example
  modules/user_manual/attachments/.gitkeep
Labels: backport

#4606 [10.9] [PR 4552] Added preliminary Releasenotes for 10.9.1
  modules/ROOT/pages/server_release_notes.adoc
  site.yml
Labels: backport

#4607 layout error fixed
  modules/user_manual/pages/personal_settings/security.adoc
Labels: admin docs

#4608 [10.9] [PR 4607] layout error fixed
  modules/user_manual/pages/personal_settings/security.adoc
Labels: backport

#4609 [10.8] [PR 4607] layout error fixed
  modules/user_manual/pages/personal_settings/security.adoc
Labels: backport

#4611 [10.9] [PR 4610] Add limitation about encryption to WOPI docs
  modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
Labels: backport

#4616 Add Antora Site Structure Description for Docs
  README.md
  docs/antora-site-structure.md
Labels: deployment

#4617 [10.9] [PR 4616] Add Antora Site Structure Description for Docs
  README.md
  docs/antora-site-structure.md
Labels: backport

#4618 [10.8] [PR 4616] Add Antora Site Structure Description for Docs
  README.md
  docs/antora-site-structure.md
Labels: backport

#4620 [10.9] Fix typos in antora-site-structure.md
  docs/antora-site-structure.md
Labels: backport

#4621 [10.8] Fix typos in antora-site-structure.md
  docs/antora-site-structure.md
Labels: backport

#4622 Update antora-site-structure.md
  docs/antora-site-structure.md
Labels: deployment

#4623 [10.9] Update antora-site-structure.md
  docs/antora-site-structure.md
Labels: backport

#4624 [10.8] Update antora-site-structure.md
  docs/antora-site-structure.md
Labels: backport

#4625 Add opengraph images to be accessed by the ui-template
  overlay/opengraph-android.png
  overlay/opengraph-default.png
  overlay/opengraph-desktop.png
  overlay/opengraph-docs.png
  overlay/opengraph-ios-app.png
  overlay/opengraph-ocis.png
  overlay/opengraph-server.png
  overlay/opengraph-user.png
  overlay/ui.yml
Labels: deployment

#4628 Update nodejs to v16 (lts)
  .drone.star
  docs/build-the-docs.md
Labels: deployment

#4626 [10.9] [PR 4625] Add opengraph images to be accessed by the ui-template
  overlay/opengraph-android.png
  overlay/opengraph-default.png
  overlay/opengraph-desktop.png
  overlay/opengraph-docs.png
  overlay/opengraph-ios-app.png
  overlay/opengraph-ocis.png
  overlay/opengraph-server.png
  overlay/opengraph-user.png
  overlay/ui.yml
Labels: backport

#4627 [10.8] [PR 4625] Add opengraph images to be accessed by the ui-template
  overlay/opengraph-android.png
  overlay/opengraph-default.png
  overlay/opengraph-desktop.png
  overlay/opengraph-docs.png
  overlay/opengraph-ios-app.png
  overlay/opengraph-ocis.png
  overlay/opengraph-server.png
  overlay/opengraph-user.png
  overlay/ui.yml
Labels: backport

#4629 [10.9] [PR 4628] Update nodejs to v16 (lts)
  .drone.star
  docs/build-the-docs.md
Labels: backport

#4630 [10.8] [PR 4628] Update nodejs to v16 (lts)
  .drone.star
  docs/build-the-docs.md
Labels: backport

#4520 Prepare for Desktop 2.10
  site.yml
Labels: deployment

#4631 [10.8] [PR 4520] Prepare for Desktop 2.10
  site.yml
Labels: backport

#4634 [10.9] [PR 4633] fix: fix elastic index handling
  .prettierrc
  generator/generate-site.js
  package.json
  yarn.lock
Labels: backport

#4635 [10.8] [PR 4633] fix: fix elastic index handling
  .prettierrc
  generator/generate-site.js
  package.json
  yarn.lock
Labels: backport

#4637 [10.9] [PR 4636] fix: fix elastic env vars in drone config
  .drone.star
Labels: backport

#4638 [10.8] [PR 4636] fix: fix elastic env vars in drone config
  .drone.star
Labels: backport

#4640 Update site.yml
  site.yml
Labels: deployment

#4641 [10.9] [PR 4640] Update site.yml
  site.yml
Labels: backport

#4642 [10.8] [PR 4640] Update site.yml
  site.yml
Labels: backport

#4639 Add attribute necessary for embedding opengraph images in docs-ui automatically
  site.yml
Labels: deployment

#4643 [10.9] [PR 4639] Add attribute necessary for embedding opengraph images in docs-ui automatically
  site.yml
Labels: backport

#4644 [10.8] [PR 4639] Add attribute necessary for embedding opengraph images in docs-ui automatically
  site.yml
Labels: backport

#4223 New metrics features
  modules/admin_manual/pages/enterprise/reporting/metrics.adoc
Labels: admin docs

#4645 [10.9] [PR 4223] New metrics features
  modules/admin_manual/pages/enterprise/reporting/metrics.adoc
Labels: backport

#4650 10.9 antora.yml attribute fix refs 4647
  antora.yml
Labels: deployment

#4647 Some fixes
  docs/antora-site-structure.md
  site.yml
Labels: deployment

#4648 master antora.yml attribute fix refs 4647
  antora.yml
Labels: deployment

#4651 [10.9] [PR 4647] Some fixes
  docs/antora-site-structure.md
  site.yml
Labels: backport

#4655 antora site structure documentation update
  docs/antora-site-structure.md
Labels: deployment

#4656 [10.9] [PR 4655] antora site structure documentation update
  docs/antora-site-structure.md
Labels: backport

#4657 [10.8] [PR 4655] antora site structure documentation update
  docs/antora-site-structure.md
Labels: backport

#4658 update of the new version branch documentation
  docs/new-version-branch.md
Labels: deployment

#4660 [10.9] [PR 4658] update of the new version branch documentation
  docs/new-version-branch.md
Labels: backport

#4661 [10.8] [PR 4658] update of the new version branch documentation
  docs/new-version-branch.md
Labels: backport

#4662 [10.9] [PR 4659] chore: replace s3 server in drone config by secret
  .drone.star
Labels: backport

#4663 [10.8] [PR 4659] chore: replace s3 server in drone config by secret
  .drone.star
Labels: backport

#4664 update the backport script
  modules/developer_manual/examples/scripts/backport.sh
  modules/developer_manual/pages/general/backporting.adoc
Labels: developer docs

#4665 [10.9] [PR 4664] update the backport script
  modules/developer_manual/examples/scripts/backport.sh
  modules/developer_manual/pages/general/backporting.adoc
Labels: backport

#4666 [10.8] [PR 4664] update the backport script
  modules/developer_manual/examples/scripts/backport.sh
  modules/developer_manual/pages/general/backporting.adoc
Labels: backport

#4667 Fix Richdocuments and the corrsponding occ comand set
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_richdocuments.adoc
  modules/admin_manual/pages/enterprise/collaboration/collabora_secure_view.adoc
Labels: admin docs

#4668 [10.9] [PR 4667] Fix Richdocuments and the corrsponding occ comand set
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_richdocuments.adoc
  modules/admin_manual/pages/enterprise/collaboration/collabora_secure_view.adoc
Labels: backport

#4669 [10.8] [PR 4667] Fix Richdocuments and the corrsponding occ comand set
  modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_richdocuments.adoc
  modules/admin_manual/pages/enterprise/collaboration/collabora_secure_view.adoc
Labels: backport

#4671 Update nfs to avoid boot stuck when nfs server is not available
  modules/admin_manual/pages/installation/deployment_recommendations/nfs.adoc
Labels: admin docs

#4672 [10.9] [PR 4671] Update nfs to avoid boot stuck when nfs server is not available
  modules/admin_manual/pages/installation/deployment_recommendations/nfs.adoc
Labels: backport

#4673 [10.8] [PR 4671] Update nfs to avoid boot stuck when nfs server is not available
  modules/admin_manual/pages/installation/deployment_recommendations/nfs.adoc
Labels: backport

#4674 Add how to remove non existent background jobs
  modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc
  modules/admin_manual/pages/troubleshooting/remove_non_existent_bg_jobs.adoc
  modules/admin_manual/partials/nav.adoc
Labels: admin docs

#4676 adding a build command for staging
  package.json
Labels: deployment

#4677 [10.9] [PR 4674] Add how to remove non existent background jobs
  modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc
  modules/admin_manual/pages/troubleshooting/remove_non_existent_bg_jobs.adoc
  modules/admin_manual/partials/nav.adoc
Labels: backport

#4678 [10.8] [PR 4674] Add how to remove non existent background jobs
  modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc
  modules/admin_manual/pages/troubleshooting/remove_non_existent_bg_jobs.adoc
  modules/admin_manual/partials/nav.adoc
Labels: backport
