Repository owncloud/docs, pull requests merged in 2022-08, with the labels that each got.

#4769 Update site.yml for ocis beta.6
  site.yml
Labels: deployment

#4767 Changes necessary for Desktop 2.11
  site.yml
Labels: deployment

#4770 Remove write-good from dependency.yml
  .github/dependabot.yml
Labels: dependencies

#4771 The occ command missed a ./ in the attribute
  site.yml
Labels: documentation

#4774 oCIS beta7 release notes
  modules/ROOT/pages/ocis_release_notes.adoc
Labels: documentation

#4775 Prepare for ocis beta.7
  site.yml
Labels: deployment
