Repository owncloud/docs, pull requests merged in 2023-03, with the labels that each got.

#4814 Enable ownCloud Server 10.12
  site.yml
Labels: deployment

#4804 Server 10.12 Release Notes
  modules/ROOT/pages/server_release_notes.adoc
Labels: documentation

#4821 some language improvements
  modules/ROOT/pages/server_release_notes.adoc
Labels: admin docs

#4823 Update server_release_notes.adoc for 10.12
  modules/ROOT/pages/server_release_notes.adoc
Labels: documentation
