Repository owncloud/docs, pull requests merged in 2023-08, with the labels that each got.

#4867 Update the optimize-crawl script
  bin/optimize_crawl
Labels: documentation

#4869 Changes necessary for Desktop 4.2
  site.yml
Labels: deployment

#4864 Server 10.13 Release Notes
  modules/ROOT/pages/server_release_notes.adoc
Labels: documentation

#4870 Changes necessary for Server 10.13
  site.yml
Labels: documentation

#4871 IE11 deprecation note
  modules/ROOT/pages/server_release_notes.adoc
Labels: admin docs

#4876 Update the intro page
  modules/ROOT/pages/index.adoc
Labels: documentation
